In [1]:
import os
import re
import time
from pathlib import Path
import pandas as pd
from tqdm import tqdm
from dotenv import load_dotenv


load_dotenv()

True

In [2]:
os.environ["HF_HOME"] = "/data/oussama/hf_cache"
os.environ["HUGGINGFACE_HUB_CACHE"] = "/data/oussama/hf_cache/hub"
os.environ["TRANSFORMERS_CACHE"] = "/data/oussama/hf_cache/transformers"

# Gemma 4 12B + LoRA adapter inference

This version keeps the same evaluation logic as your baseline Gemma notebook, but loads:

1. the original base model: `google/gemma-4-12B-it`
2. your LoRA adapter: e.g. `models/lora_r4_alpha8_lr2e-4`

Use the final adapter folder for inference, not the Trainer checkpoint folder, unless you specifically want to evaluate that checkpoint.

In [3]:
import gc
import torch
from transformers import AutoProcessor, BitsAndBytesConfig

try:
    from transformers import AutoModelForImageTextToText as GemmaModelClass
except Exception:
    try:
        from transformers import AutoModelForMultimodalLM as GemmaModelClass
    except Exception:
        from transformers import AutoModelForCausalLM as GemmaModelClass

from peft import PeftModel


def run_gemma4_lora_local_on_questions(
    input_csv,
    output_csv,
    prompt_col="Prompt",
    base_model_id="google/gemma-4-12B-it",
    adapter_path="lora_results/models/lora_r4_alpha8_lr2e-4",
    question_id_col=None,
    gold_col=None,
    level_col="level",
    medical_specialty_col="medical_specialty",
    max_retries=5,
    save_every=1,
    max_new_tokens=10,
    cache_dir="/data/oussama/hf_cache",
    offload_folder="/data/oussama/offload_gemma_lora_inference",
    use_4bit=True,
    gpu_memory="13GiB",
    cpu_memory="350GiB",
    local_files_only=False,
):
    """
    Run Gemma 4 12B locally with a saved LoRA adapter and save predictions.

    This uses the same output format as the baseline function:
    - question_id
    - gold
    - prediction
    - raw_output
    - correct
    - level
    - medical_specialty
    - model
    - stop_reason
    - refusal_category
    - refusal_type

    Important:
    adapter_path should point to the folder containing:
    - adapter_config.json
    - adapter_model.safetensors
    """

    input_csv = Path(input_csv)
    output_csv = Path(output_csv)
    output_csv.parent.mkdir(parents=True, exist_ok=True)
    Path(offload_folder).mkdir(parents=True, exist_ok=True)

    print(f"Loading base model: {base_model_id}")
    print(f"Loading LoRA adapter: {adapter_path}")

    # Load processor/tokenizer from the base model. The adapter only contains LoRA weights,
    # not the full Gemma processor.
    processor = AutoProcessor.from_pretrained(
        base_model_id,
        cache_dir=cache_dir,
        local_files_only=local_files_only,
        trust_remote_code=True,
    )

    if getattr(processor, "tokenizer", None) is not None:
        if processor.tokenizer.pad_token_id is None:
            processor.tokenizer.pad_token = processor.tokenizer.eos_token

    max_memory = None
    if torch.cuda.is_available():
        max_memory = {i: gpu_memory for i in range(torch.cuda.device_count())}
        max_memory["cpu"] = cpu_memory
        print("max_memory:", max_memory)

    load_kwargs = dict(
        cache_dir=cache_dir,
        device_map="auto",
        low_cpu_mem_usage=True,
        trust_remote_code=True,
        local_files_only=local_files_only,
        offload_folder=offload_folder,
    )

    if max_memory is not None:
        load_kwargs["max_memory"] = max_memory

    if use_4bit:
        load_kwargs["quantization_config"] = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_quant_type="nf4",
            bnb_4bit_compute_dtype=torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16,
            bnb_4bit_use_double_quant=True,
        )

    # Newer Transformers prefers dtype; older versions require torch_dtype.
    try:
        base_model = GemmaModelClass.from_pretrained(
            base_model_id,
            dtype=torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16,
            **load_kwargs,
        )
    except TypeError:
        base_model = GemmaModelClass.from_pretrained(
            base_model_id,
            torch_dtype=torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16,
            **load_kwargs,
        )

    # Attach the LoRA adapter to the base model.
    gemma_model = PeftModel.from_pretrained(
        base_model,
        adapter_path,
        is_trainable=False,
        local_files_only=local_files_only,
    )

    gemma_model.eval()
    gemma_model.config.use_cache = True

    if hasattr(gemma_model, "hf_device_map"):
        print("Device map:", gemma_model.hf_device_map)

    df = pd.read_csv(input_csv, encoding="utf-8-sig")

    if prompt_col not in df.columns:
        raise ValueError(f"Missing prompt column: {prompt_col}")

    if gold_col is None:
        raise ValueError(
            "Could not find the gold answer column. "
            "Please pass gold_col='your_column_name'."
        )

    output_columns = [
        "question_id",
        "gold",
        "prediction",
        "raw_output",
        "correct",
        "level",
        "medical_specialty",
        "model",
        "stop_reason",
        "refusal_category",
        "refusal_type",
    ]

    def clean_value(value):
        if pd.isna(value):
            return ""
        return str(value).strip()

    def normalize_gold(value):
        text = clean_value(value).upper()
        match = re.search(r"\b([A-F])\b", text)
        return match.group(1) if match else text[:1]

    def extract_prediction(raw_output, allowed_letters=None):
        raw_output = clean_value(raw_output).upper()

        if allowed_letters:
            allowed_letters = [x.upper() for x in allowed_letters]
        else:
            allowed_letters = ["A", "B", "C", "D", "E", "F"]

        if raw_output in allowed_letters:
            return raw_output

        pattern = r"\b(" + "|".join(map(re.escape, allowed_letters)) + r")\b"
        match = re.search(pattern, raw_output)
        if match:
            return match.group(1)

        if raw_output and raw_output[0] in allowed_letters:
            return raw_output[0]

        return ""

    def parse_gemma_output(decoded_text):
        text = decoded_text

        try:
            parsed = processor.parse_response(decoded_text)

            if isinstance(parsed, str):
                text = parsed
            elif isinstance(parsed, dict):
                text = (
                    parsed.get("content")
                    or parsed.get("answer")
                    or parsed.get("text")
                    or str(parsed)
                )
            elif isinstance(parsed, list) and len(parsed) > 0:
                first = parsed[0]
                if isinstance(first, dict):
                    text = first.get("content") or first.get("text") or str(first)
                else:
                    text = str(first)
            else:
                text = str(parsed)

        except Exception:
            text = decoded_text

        text = clean_value(text)

        # Remove common special tokens if they appear.
        text = text.replace("<turn|>", " ")
        text = text.replace("<end_of_turn>", " ")
        text = text.replace("<start_of_turn>", " ")
        text = text.strip()

        return text

    def get_input_device(model):
        """
        With device_map='auto', put input_ids on the same GPU as the input embeddings.
        This avoids cuda:0/cuda:3 mismatches on multi-GPU sharded Gemma.
        """
        try:
            return model.get_input_embeddings().weight.device
        except Exception:
            pass

        try:
            return next(model.parameters()).device
        except Exception:
            pass

        return torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

    def move_inputs_to_device(inputs, device):
        if hasattr(inputs, "to"):
            return inputs.to(device)
        return {
            k: v.to(device) if torch.is_tensor(v) else v
            for k, v in inputs.items()
        }

    input_device = get_input_device(gemma_model)
    print("Input device:", input_device)

    def call_model(prompt, allowed_letters=None, max_retries=5):
        """
        Calls adapted Gemma 4 locally.

        Returns:
        {
            "raw_output": str,
            "stop_reason": str,
            "refusal_category": None,
            "refusal_type": None,
        }
        """

        if allowed_letters is None:
            allowed_letters = ["A", "B", "C", "D", "E", "F"]

        allowed_text = ", ".join(allowed_letters)

        system_prompt = (
            "You are evaluating multiple-choice questions from a medical benchmark. "
            "Select the single best answer option. "
            "Return only one uppercase letter. "
            "Do not explain."
        )

        user_prompt = (
            f"{prompt}\n\n"
            f"Allowed options: {allowed_text}\n"
            "Return exactly one uppercase letter from the allowed options. "
            "No explanation."
        )

        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ]

        last_error = None

        for attempt in range(1, max_retries + 1):
            try:
                try:
                    inputs = processor.apply_chat_template(
                        messages,
                        tokenize=True,
                        return_dict=True,
                        return_tensors="pt",
                        add_generation_prompt=True,
                        enable_thinking=False,
                    )
                except TypeError:
                    inputs = processor.apply_chat_template(
                        messages,
                        tokenize=True,
                        return_dict=True,
                        return_tensors="pt",
                        add_generation_prompt=True,
                    )

                inputs = move_inputs_to_device(inputs, input_device)
                input_len = inputs["input_ids"].shape[-1]

                with torch.inference_mode():
                    outputs = gemma_model.generate(
                        **inputs,
                        max_new_tokens=max_new_tokens,
                        do_sample=False,
                        pad_token_id=processor.tokenizer.eos_token_id,
                    )

                generated_tokens = outputs[0][input_len:]

                decoded = processor.decode(
                    generated_tokens,
                    skip_special_tokens=False,
                )

                raw_output = parse_gemma_output(decoded)

                if raw_output:
                    return {
                        "raw_output": raw_output,
                        "stop_reason": "local_lora_generate",
                        "refusal_category": None,
                        "refusal_type": None,
                    }

                print("Empty adapted Gemma response:")
                print("decoded:", repr(decoded))

                raise RuntimeError("Adapted Gemma returned empty text output.")

            except Exception as e:
                last_error = e

                if attempt == max_retries:
                    break

                wait_time = min(2 ** attempt, 60)
                print(
                    f"Adapted local Gemma error attempt {attempt}/{max_retries}: {repr(e)}. "
                    f"Retrying in {wait_time}s..."
                )
                time.sleep(wait_time)

        raise RuntimeError(
            f"Failed after {max_retries} retries. Last error: {repr(last_error)}"
        )

    # Read already processed question IDs if results CSV exists.
    processed_ids = set()

    if output_csv.exists():
        old_results = pd.read_csv(output_csv, encoding="utf-8-sig")

        if "question_id" in old_results.columns:
            processed_ids = set(old_results["question_id"].astype(str))
        elif "Question_id" in old_results.columns:
            processed_ids = set(old_results["Question_id"].astype(str))

        for col in output_columns:
            if col not in old_results.columns:
                old_results[col] = ""

        old_results = old_results[output_columns]
        results = old_results.to_dict("records")
    else:
        old_results = pd.DataFrame(columns=output_columns)
        results = []

    print(f"Already processed: {len(processed_ids)} questions")

    newly_processed = 0
    model_label = f"{base_model_id}+LoRA:{adapter_path}"

    for idx, row in tqdm(df.iterrows(), total=len(df)):
        question_id = (
            clean_value(row[question_id_col])
            if question_id_col is not None
            else str(idx)
        )

        if str(question_id) in processed_ids:
            continue

        gold = normalize_gold(row[gold_col])

        group = clean_value(row["Group"]).upper() if "Group" in df.columns else "ABCDEF"

        allowed_letters = [
            letter for letter in group
            if letter in ["A", "B", "C", "D", "E", "F"]
        ]

        if not allowed_letters:
            allowed_letters = ["A", "B", "C", "D", "E", "F"]

        prompt = clean_value(row[prompt_col])

        call_result = call_model(
            prompt=prompt,
            allowed_letters=allowed_letters,
            max_retries=max_retries,
        )

        raw_output = call_result["raw_output"]
        stop_reason = call_result["stop_reason"]
        refusal_category = call_result["refusal_category"]
        refusal_type = call_result["refusal_type"]

        prediction = extract_prediction(raw_output, allowed_letters)
        correct = int(prediction == gold)

        result = {
            "question_id": question_id,
            "gold": gold,
            "prediction": prediction,
            "raw_output": raw_output,
            "correct": correct,
            "level": clean_value(row[level_col]) if level_col in df.columns else "",
            "medical_specialty": (
                clean_value(row[medical_specialty_col])
                if medical_specialty_col in df.columns
                else ""
            ),
            "model": model_label,
            "stop_reason": stop_reason,
            "refusal_category": refusal_category,
            "refusal_type": refusal_type,
        }

        results.append(result)
        processed_ids.add(str(question_id))
        newly_processed += 1

        if save_every and newly_processed % save_every == 0:
            pd.DataFrame(results, columns=output_columns).to_csv(
                output_csv,
                index=False,
                encoding="utf-8-sig",
            )

        if torch.cuda.is_available():
            torch.cuda.empty_cache()
        gc.collect()

    results_df = pd.DataFrame(results, columns=output_columns)

    results_df.to_csv(
        output_csv,
        index=False,
        encoding="utf-8-sig",
    )

    return results_df

In [4]:
# Run adapted Gemma 4 12B IT with your final LoRA adapter.
# Use the final adapter folder for inference:
ADAPTER_PATH = "lora_results/models/lora_r4_alpha8_lr2e-4"

# If you specifically want to evaluate the trainer checkpoint instead, use this:
# ADAPTER_PATH = "trainer_lora_r4_alpha8_lr2e-4/checkpoint-590"

results_lora = run_gemma4_lora_local_on_questions(
    input_csv="data/cleaned/medarabench_test_with_prompts.csv",
    output_csv="results/gemma-4-12B-it_lora_r4_alpha8_lr2e-4_results.csv",
    prompt_col="Prompt",
    base_model_id="google/gemma-4-12B-it",
    adapter_path=ADAPTER_PATH,
    question_id_col="Question Number",
    gold_col="Correct Answer",
    level_col="Level",
    medical_specialty_col="Medical Specialty",
    save_every=1,
    max_new_tokens=10,
    use_4bit=True,
    local_files_only=True,  # set True if the base model is already fully cached and you want offline mode
)

results_lora.head()

Loading base model: google/gemma-4-12B-it
Loading LoRA adapter: lora_results/models/lora_r4_alpha8_lr2e-4

max_memory: {0: '13GiB', 1: '13GiB', 2: '13GiB', 3: '13GiB', 'cpu': '350GiB'}

Loading weights:   0%|          | 0/677 [00:00<?, ?it/s]

Input device: cuda:3
Already processed: 427 questions

  0%|          | 0/4959 [00:00<?, ?it/s]

  9%|▊         | 428/4959 [00:02<00:31, 144.32it/s]

  9%|▊         | 428/4959 [00:13<00:31, 144.32it/s]

  9%|▉         | 434/4959 [00:13<03:11, 23.63it/s]

  9%|▉         | 435/4959 [00:15<03:45, 20.09it/s]

  9%|▉         | 441/4959 [00:27<09:10,  8.20it/s]

  9%|▉         | 442/4959 [00:28<10:13,  7.37it/s]

  9%|▉         | 446/4959 [00:35<16:26,  4.58it/s]

  9%|▉         | 449/4959 [00:41<22:13,  3.38it/s]

  9%|▉         | 451/4959 [00:44<27:27,  2.74it/s]

  9%|▉         | 452/4959 [00:46<30:32,  2.46it/s]

  9%|▉         | 453/4959 [00:48<34:33,  2.17it/s]

  9%|▉         | 454/4959 [00:49<39:52,  1.88it/s]

  9%|▉         | 455/4959 [00:51<46:14,  1.62it/s]

  9%|▉         | 456/4959 [00:53<53:56,  1.39it/s]

  9%|▉         | 457/4959 [00:55<1:05:53,  1.14it/s]

  9%|▉         | 458/4959 [00:57<1:18:19,  1.04s/it]

  9%|▉         | 459/4959 [00:58<1:26:21,  1.15s/it]

  9%|▉         | 460/4959 [01:00<1:39:16,  1.32s/it]

  9%|▉         | 461/4959 [01:02<1:50:13,  1.47s/it]

  9%|▉         | 462/4959 [01:04<1:53:05,  1.51s/it]

  9%|▉         | 463/4959 [01:06<2:02:57,  1.64s/it]

  9%|▉         | 464/4959 [01:08<2:10:43,  1.74s/it]

  9%|▉         | 465/4959 [01:10<2:09:01,  1.72s/it]

  9%|▉         | 466/4959 [01:12<2:15:06,  1.80s/it]

  9%|▉         | 467/4959 [01:13<2:12:00,  1.76s/it]

  9%|▉         | 468/4959 [01:15<2:09:16,  1.73s/it]

  9%|▉         | 469/4959 [01:17<2:15:59,  1.82s/it]

  9%|▉         | 470/4959 [01:19<2:19:31,  1.86s/it]

  9%|▉         | 471/4959 [01:21<2:14:58,  1.80s/it]

 10%|▉         | 472/4959 [01:22<2:11:39,  1.76s/it]

 10%|▉         | 473/4959 [01:24<2:17:13,  1.84s/it]

 10%|▉         | 474/4959 [01:26<2:12:43,  1.78s/it]

 10%|▉         | 475/4959 [01:28<2:09:59,  1.74s/it]

 10%|▉         | 476/4959 [01:29<2:07:33,  1.71s/it]

 10%|▉         | 477/4959 [01:31<2:05:48,  1.68s/it]

 10%|▉         | 478/4959 [01:33<2:12:50,  1.78s/it]

 10%|▉         | 479/4959 [01:35<2:10:09,  1.74s/it]

 10%|▉         | 480/4959 [01:36<2:07:39,  1.71s/it]

 10%|▉         | 481/4959 [01:38<2:06:51,  1.70s/it]

 10%|▉         | 482/4959 [01:40<2:05:28,  1.68s/it]

 10%|▉         | 483/4959 [01:42<2:12:36,  1.78s/it]

 10%|▉         | 484/4959 [01:43<2:09:11,  1.73s/it]

 10%|▉         | 485/4959 [01:45<2:15:28,  1.82s/it]

 10%|▉         | 486/4959 [01:47<2:11:17,  1.76s/it]

 10%|▉         | 487/4959 [01:49<2:09:55,  1.74s/it]

 10%|▉         | 488/4959 [01:50<2:07:45,  1.71s/it]

 10%|▉         | 489/4959 [01:52<2:05:48,  1.69s/it]

 10%|▉         | 490/4959 [01:54<2:13:37,  1.79s/it]

 10%|▉         | 491/4959 [01:56<2:19:00,  1.87s/it]

 10%|▉         | 492/4959 [01:58<2:22:11,  1.91s/it]

 10%|▉         | 493/4959 [02:00<2:17:06,  1.84s/it]

 10%|▉         | 494/4959 [02:02<2:20:46,  1.89s/it]

 10%|▉         | 495/4959 [02:03<2:15:54,  1.83s/it]

 10%|█         | 496/4959 [02:05<2:23:26,  1.93s/it]

 10%|█         | 497/4959 [02:07<2:18:39,  1.86s/it]

 10%|█         | 498/4959 [02:09<2:22:57,  1.92s/it]

 10%|█         | 499/4959 [02:11<2:17:25,  1.85s/it]

 10%|█         | 500/4959 [02:12<2:12:43,  1.79s/it]

 10%|█         | 501/4959 [02:15<2:18:19,  1.86s/it]

 10%|█         | 502/4959 [02:16<2:13:34,  1.80s/it]

 10%|█         | 503/4959 [02:18<2:18:48,  1.87s/it]

 10%|█         | 504/4959 [02:20<2:16:56,  1.84s/it]

 10%|█         | 505/4959 [02:22<2:11:58,  1.78s/it]

 10%|█         | 506/4959 [02:24<2:16:26,  1.84s/it]

 10%|█         | 507/4959 [02:25<2:11:28,  1.77s/it]

 10%|█         | 508/4959 [02:27<2:17:46,  1.86s/it]

 10%|█         | 509/4959 [02:29<2:13:58,  1.81s/it]

 10%|█         | 510/4959 [02:31<2:11:03,  1.77s/it]

 10%|█         | 511/4959 [02:33<2:15:47,  1.83s/it]

 10%|█         | 512/4959 [02:35<2:19:26,  1.88s/it]

 10%|█         | 513/4959 [02:37<2:22:25,  1.92s/it]

 10%|█         | 514/4959 [02:38<2:16:00,  1.84s/it]

 10%|█         | 515/4959 [02:40<2:11:39,  1.78s/it]

 10%|█         | 516/4959 [02:42<2:08:47,  1.74s/it]

 10%|█         | 517/4959 [02:43<2:06:32,  1.71s/it]

 10%|█         | 518/4959 [02:45<2:12:24,  1.79s/it]

 10%|█         | 519/4959 [02:47<2:17:17,  1.86s/it]

 10%|█         | 520/4959 [02:49<2:19:59,  1.89s/it]

 11%|█         | 521/4959 [02:51<2:14:29,  1.82s/it]

 11%|█         | 522/4959 [02:53<2:18:31,  1.87s/it]

 11%|█         | 523/4959 [02:54<2:13:45,  1.81s/it]

 11%|█         | 524/4959 [02:56<2:10:51,  1.77s/it]

 11%|█         | 525/4959 [02:58<2:08:08,  1.73s/it]

 11%|█         | 526/4959 [02:59<2:06:31,  1.71s/it]

 11%|█         | 527/4959 [03:01<2:06:35,  1.71s/it]

 11%|█         | 528/4959 [03:03<2:09:47,  1.76s/it]

 11%|█         | 529/4959 [03:05<2:09:04,  1.75s/it]

 11%|█         | 530/4959 [03:06<2:06:56,  1.72s/it]

 11%|█         | 531/4959 [03:08<2:12:40,  1.80s/it]

 11%|█         | 532/4959 [03:10<2:09:14,  1.75s/it]

 11%|█         | 533/4959 [03:12<2:06:58,  1.72s/it]

 11%|█         | 534/4959 [03:13<2:06:07,  1.71s/it]

 11%|█         | 535/4959 [03:15<2:12:23,  1.80s/it]

 11%|█         | 536/4959 [03:18<2:20:32,  1.91s/it]

 11%|█         | 537/4959 [03:19<2:15:02,  1.83s/it]

 11%|█         | 538/4959 [03:21<2:19:07,  1.89s/it]

 11%|█         | 539/4959 [03:23<2:14:55,  1.83s/it]

 11%|█         | 540/4959 [03:25<2:13:28,  1.81s/it]

 11%|█         | 541/4959 [03:27<2:18:30,  1.88s/it]

 11%|█         | 542/4959 [03:28<2:12:46,  1.80s/it]

 11%|█         | 543/4959 [03:30<2:09:09,  1.75s/it]

 11%|█         | 544/4959 [03:32<2:07:50,  1.74s/it]

 11%|█         | 545/4959 [03:33<2:06:50,  1.72s/it]

 11%|█         | 546/4959 [03:35<2:13:59,  1.82s/it]

 11%|█         | 547/4959 [03:37<2:10:19,  1.77s/it]

 11%|█         | 548/4959 [03:39<2:15:03,  1.84s/it]

 11%|█         | 549/4959 [03:41<2:20:39,  1.91s/it]

 11%|█         | 550/4959 [03:43<2:17:58,  1.88s/it]

 11%|█         | 551/4959 [03:45<2:20:45,  1.92s/it]

 11%|█         | 552/4959 [03:47<2:24:00,  1.96s/it]

 11%|█         | 553/4959 [03:49<2:17:05,  1.87s/it]

 11%|█         | 554/4959 [03:50<2:12:52,  1.81s/it]

 11%|█         | 555/4959 [03:52<2:16:52,  1.86s/it]

 11%|█         | 556/4959 [03:54<2:19:54,  1.91s/it]

 11%|█         | 557/4959 [03:56<2:22:28,  1.94s/it]

 11%|█▏        | 558/4959 [03:58<2:24:20,  1.97s/it]

 11%|█▏        | 559/4959 [04:00<2:16:58,  1.87s/it]

 11%|█▏        | 560/4959 [04:02<2:12:17,  1.80s/it]

 11%|█▏        | 561/4959 [04:03<2:08:51,  1.76s/it]

 11%|█▏        | 562/4959 [04:05<2:06:32,  1.73s/it]

 11%|█▏        | 563/4959 [04:07<2:06:23,  1.73s/it]

 11%|█▏        | 564/4959 [04:08<2:04:21,  1.70s/it]

 11%|█▏        | 565/4959 [04:10<2:11:59,  1.80s/it]

 11%|█▏        | 566/4959 [04:12<2:09:47,  1.77s/it]

 11%|█▏        | 567/4959 [04:14<2:07:26,  1.74s/it]

 11%|█▏        | 568/4959 [04:15<2:05:27,  1.71s/it]

 11%|█▏        | 569/4959 [04:17<2:03:50,  1.69s/it]

 11%|█▏        | 570/4959 [04:19<2:03:03,  1.68s/it]

 12%|█▏        | 571/4959 [04:21<2:12:17,  1.81s/it]

 12%|█▏        | 572/4959 [04:23<2:16:03,  1.86s/it]

 12%|█▏        | 573/4959 [04:25<2:13:16,  1.82s/it]

 12%|█▏        | 574/4959 [04:27<2:17:18,  1.88s/it]

 12%|█▏        | 575/4959 [04:29<2:19:10,  1.90s/it]

 12%|█▏        | 576/4959 [04:30<2:14:41,  1.84s/it]

 12%|█▏        | 577/4959 [04:33<2:26:10,  2.00s/it]

 12%|█▏        | 578/4959 [04:34<2:18:31,  1.90s/it]

 12%|█▏        | 579/4959 [04:37<2:28:03,  2.03s/it]

 12%|█▏        | 580/4959 [04:39<2:26:50,  2.01s/it]

 12%|█▏        | 581/4959 [04:40<2:20:01,  1.92s/it]

 12%|█▏        | 582/4959 [04:42<2:21:16,  1.94s/it]

 12%|█▏        | 583/4959 [04:44<2:23:31,  1.97s/it]

 12%|█▏        | 584/4959 [04:46<2:27:35,  2.02s/it]

 12%|█▏        | 585/4959 [04:48<2:19:04,  1.91s/it]

 12%|█▏        | 586/4959 [04:50<2:15:08,  1.85s/it]

 12%|█▏        | 587/4959 [04:51<2:11:18,  1.80s/it]

 12%|█▏        | 588/4959 [04:54<2:23:25,  1.97s/it]

 12%|█▏        | 589/4959 [04:56<2:26:53,  2.02s/it]

 12%|█▏        | 590/4959 [04:58<2:21:20,  1.94s/it]

 12%|█▏        | 591/4959 [05:00<2:19:27,  1.92s/it]

 12%|█▏        | 592/4959 [05:01<2:15:02,  1.86s/it]

 12%|█▏        | 593/4959 [05:03<2:11:31,  1.81s/it]

 12%|█▏        | 594/4959 [05:05<2:08:49,  1.77s/it]

 12%|█▏        | 595/4959 [05:07<2:11:16,  1.80s/it]

 12%|█▏        | 596/4959 [05:08<2:14:00,  1.84s/it]

 12%|█▏        | 597/4959 [05:10<2:10:36,  1.80s/it]

 12%|█▏        | 598/4959 [05:12<2:15:18,  1.86s/it]

 12%|█▏        | 599/4959 [05:14<2:12:16,  1.82s/it]

 12%|█▏        | 600/4959 [05:16<2:11:40,  1.81s/it]

 12%|█▏        | 601/4959 [05:18<2:20:14,  1.93s/it]

 12%|█▏        | 602/4959 [05:20<2:13:47,  1.84s/it]

 12%|█▏        | 603/4959 [05:21<2:09:47,  1.79s/it]

 12%|█▏        | 604/4959 [05:23<2:14:51,  1.86s/it]

 12%|█▏        | 605/4959 [05:25<2:18:13,  1.90s/it]

 12%|█▏        | 606/4959 [05:27<2:21:29,  1.95s/it]

 12%|█▏        | 607/4959 [05:29<2:14:28,  1.85s/it]

 12%|█▏        | 608/4959 [05:31<2:18:11,  1.91s/it]

 12%|█▏        | 609/4959 [05:33<2:12:56,  1.83s/it]

 12%|█▏        | 610/4959 [05:34<2:11:30,  1.81s/it]

 12%|█▏        | 611/4959 [05:36<2:08:06,  1.77s/it]

 12%|█▏        | 612/4959 [05:38<2:05:45,  1.74s/it]

 12%|█▏        | 613/4959 [05:40<2:12:43,  1.83s/it]

 12%|█▏        | 614/4959 [05:41<2:09:06,  1.78s/it]

 12%|█▏        | 615/4959 [05:43<2:09:33,  1.79s/it]

 12%|█▏        | 616/4959 [05:45<2:14:53,  1.86s/it]

 12%|█▏        | 617/4959 [05:47<2:11:19,  1.81s/it]

 12%|█▏        | 618/4959 [05:49<2:11:03,  1.81s/it]

 12%|█▏        | 619/4959 [05:50<2:08:13,  1.77s/it]

 13%|█▎        | 620/4959 [05:52<2:05:59,  1.74s/it]

 13%|█▎        | 621/4959 [05:54<2:11:35,  1.82s/it]

 13%|█▎        | 622/4959 [05:56<2:15:51,  1.88s/it]

 13%|█▎        | 623/4959 [05:58<2:18:45,  1.92s/it]

 13%|█▎        | 624/4959 [06:00<2:20:23,  1.94s/it]

 13%|█▎        | 625/4959 [06:02<2:19:10,  1.93s/it]

 13%|█▎        | 626/4959 [06:04<2:13:51,  1.85s/it]

 13%|█▎        | 627/4959 [06:05<2:09:42,  1.80s/it]

 13%|█▎        | 628/4959 [06:07<2:14:28,  1.86s/it]

 13%|█▎        | 629/4959 [06:09<2:11:37,  1.82s/it]

 13%|█▎        | 630/4959 [06:11<2:07:39,  1.77s/it]

 13%|█▎        | 631/4959 [06:13<2:13:54,  1.86s/it]

 13%|█▎        | 632/4959 [06:15<2:17:16,  1.90s/it]

 13%|█▎        | 633/4959 [06:17<2:12:47,  1.84s/it]

 13%|█▎        | 634/4959 [06:19<2:16:09,  1.89s/it]

 13%|█▎        | 635/4959 [06:20<2:11:18,  1.82s/it]

 13%|█▎        | 636/4959 [06:22<2:15:18,  1.88s/it]

 13%|█▎        | 637/4959 [06:24<2:10:18,  1.81s/it]

 13%|█▎        | 638/4959 [06:26<2:06:34,  1.76s/it]

 13%|█▎        | 639/4959 [06:27<2:04:42,  1.73s/it]

 13%|█▎        | 640/4959 [06:29<2:03:26,  1.71s/it]

 13%|█▎        | 641/4959 [06:31<2:02:32,  1.70s/it]

 13%|█▎        | 642/4959 [06:32<2:00:44,  1.68s/it]

 13%|█▎        | 643/4959 [06:34<2:00:18,  1.67s/it]

 13%|█▎        | 644/4959 [06:36<2:07:18,  1.77s/it]

 13%|█▎        | 645/4959 [06:37<2:04:58,  1.74s/it]

 13%|█▎        | 646/4959 [06:39<2:04:07,  1.73s/it]

 13%|█▎        | 647/4959 [06:41<2:12:14,  1.84s/it]

 13%|█▎        | 648/4959 [06:43<2:15:59,  1.89s/it]

 13%|█▎        | 649/4959 [06:45<2:10:53,  1.82s/it]

 13%|█▎        | 650/4959 [06:47<2:20:38,  1.96s/it]

 13%|█▎        | 651/4959 [06:49<2:13:29,  1.86s/it]

 13%|█▎        | 652/4959 [06:51<2:16:36,  1.90s/it]

 13%|█▎        | 653/4959 [06:53<2:12:09,  1.84s/it]

 13%|█▎        | 654/4959 [06:54<2:07:40,  1.78s/it]

 13%|█▎        | 655/4959 [06:57<2:18:53,  1.94s/it]

 13%|█▎        | 656/4959 [06:58<2:12:01,  1.84s/it]

 13%|█▎        | 657/4959 [07:00<2:17:24,  1.92s/it]

 13%|█▎        | 658/4959 [07:02<2:11:26,  1.83s/it]

 13%|█▎        | 659/4959 [07:04<2:07:37,  1.78s/it]

 13%|█▎        | 660/4959 [07:05<2:04:01,  1.73s/it]

 13%|█▎        | 661/4959 [07:07<2:10:12,  1.82s/it]

 13%|█▎        | 662/4959 [07:09<2:14:15,  1.87s/it]

 13%|█▎        | 663/4959 [07:11<2:11:04,  1.83s/it]

 13%|█▎        | 664/4959 [07:13<2:06:40,  1.77s/it]

 13%|█▎        | 665/4959 [07:14<2:03:33,  1.73s/it]

 13%|█▎        | 666/4959 [07:16<2:07:30,  1.78s/it]

 13%|█▎        | 667/4959 [07:18<2:04:59,  1.75s/it]

 13%|█▎        | 668/4959 [07:19<2:02:33,  1.71s/it]

 13%|█▎        | 669/4959 [07:21<2:10:19,  1.82s/it]

 14%|█▎        | 670/4959 [07:23<2:12:31,  1.85s/it]

 14%|█▎        | 671/4959 [07:25<2:10:02,  1.82s/it]

 14%|█▎        | 672/4959 [07:27<2:14:26,  1.88s/it]

 14%|█▎        | 673/4959 [07:29<2:20:57,  1.97s/it]

 14%|█▎        | 674/4959 [07:31<2:13:38,  1.87s/it]

 14%|█▎        | 675/4959 [07:33<2:09:05,  1.81s/it]

 14%|█▎        | 676/4959 [07:34<2:05:42,  1.76s/it]

 14%|█▎        | 677/4959 [07:36<2:13:33,  1.87s/it]

 14%|█▎        | 678/4959 [07:38<2:15:45,  1.90s/it]

 14%|█▎        | 679/4959 [07:40<2:10:07,  1.82s/it]

 14%|█▎        | 680/4959 [07:42<2:14:12,  1.88s/it]

 14%|█▎        | 681/4959 [07:44<2:17:54,  1.93s/it]

 14%|█▍        | 682/4959 [07:46<2:18:50,  1.95s/it]

 14%|█▍        | 683/4959 [07:48<2:16:58,  1.92s/it]

 14%|█▍        | 684/4959 [07:50<2:10:23,  1.83s/it]

 14%|█▍        | 685/4959 [07:52<2:13:40,  1.88s/it]

 14%|█▍        | 686/4959 [07:54<2:22:03,  1.99s/it]

 14%|█▍        | 687/4959 [07:56<2:21:32,  1.99s/it]

 14%|█▍        | 688/4959 [07:57<2:15:16,  1.90s/it]

 14%|█▍        | 689/4959 [07:59<2:10:25,  1.83s/it]

 14%|█▍        | 690/4959 [08:02<2:22:57,  2.01s/it]

 14%|█▍        | 691/4959 [08:03<2:15:23,  1.90s/it]

 14%|█▍        | 692/4959 [08:05<2:09:19,  1.82s/it]

 14%|█▍        | 693/4959 [08:07<2:13:47,  1.88s/it]

 14%|█▍        | 694/4959 [08:09<2:08:37,  1.81s/it]

 14%|█▍        | 695/4959 [08:10<2:04:51,  1.76s/it]

 14%|█▍        | 696/4959 [08:12<2:02:16,  1.72s/it]

 14%|█▍        | 697/4959 [08:13<2:00:01,  1.69s/it]

 14%|█▍        | 698/4959 [08:15<2:06:07,  1.78s/it]

 14%|█▍        | 699/4959 [08:17<2:03:31,  1.74s/it]

 14%|█▍        | 700/4959 [08:19<2:01:36,  1.71s/it]

 14%|█▍        | 701/4959 [08:20<2:00:45,  1.70s/it]

 14%|█▍        | 702/4959 [08:22<2:04:00,  1.75s/it]

 14%|█▍        | 703/4959 [08:24<2:02:50,  1.73s/it]

 14%|█▍        | 704/4959 [08:26<2:08:58,  1.82s/it]

 14%|█▍        | 705/4959 [08:28<2:04:48,  1.76s/it]

 14%|█▍        | 706/4959 [08:30<2:14:30,  1.90s/it]

 14%|█▍        | 707/4959 [08:32<2:16:59,  1.93s/it]

 14%|█▍        | 708/4959 [08:33<2:10:31,  1.84s/it]

 14%|█▍        | 709/4959 [08:35<2:07:24,  1.80s/it]

 14%|█▍        | 710/4959 [08:37<2:16:11,  1.92s/it]

 14%|█▍        | 711/4959 [08:39<2:17:21,  1.94s/it]

 14%|█▍        | 712/4959 [08:41<2:10:29,  1.84s/it]

 14%|█▍        | 713/4959 [08:43<2:14:18,  1.90s/it]

 14%|█▍        | 714/4959 [08:45<2:10:38,  1.85s/it]

 14%|█▍        | 715/4959 [08:46<2:07:30,  1.80s/it]

 14%|█▍        | 716/4959 [08:48<2:11:44,  1.86s/it]

 14%|█▍        | 717/4959 [08:50<2:06:23,  1.79s/it]

 14%|█▍        | 718/4959 [08:52<2:04:53,  1.77s/it]

 14%|█▍        | 719/4959 [08:53<2:02:37,  1.74s/it]

 15%|█▍        | 720/4959 [08:55<2:06:27,  1.79s/it]

 15%|█▍        | 721/4959 [08:57<2:02:31,  1.73s/it]

 15%|█▍        | 722/4959 [08:59<2:09:47,  1.84s/it]

 15%|█▍        | 723/4959 [09:01<2:05:39,  1.78s/it]

 15%|█▍        | 724/4959 [09:02<2:02:31,  1.74s/it]

 15%|█▍        | 725/4959 [09:04<2:00:03,  1.70s/it]

 15%|█▍        | 726/4959 [09:06<2:06:14,  1.79s/it]

 15%|█▍        | 727/4959 [09:08<2:07:25,  1.81s/it]

 15%|█▍        | 728/4959 [09:10<2:17:06,  1.94s/it]

 15%|█▍        | 729/4959 [09:12<2:19:33,  1.98s/it]

 15%|█▍        | 730/4959 [09:14<2:16:02,  1.93s/it]

 15%|█▍        | 731/4959 [09:16<2:17:38,  1.95s/it]

 15%|█▍        | 732/4959 [09:17<2:10:15,  1.85s/it]

 15%|█▍        | 733/4959 [09:19<2:08:01,  1.82s/it]

 15%|█▍        | 734/4959 [09:21<2:12:31,  1.88s/it]

 15%|█▍        | 735/4959 [09:23<2:08:24,  1.82s/it]

 15%|█▍        | 736/4959 [09:25<2:19:20,  1.98s/it]

 15%|█▍        | 737/4959 [09:27<2:19:22,  1.98s/it]

 15%|█▍        | 738/4959 [09:29<2:11:50,  1.87s/it]

 15%|█▍        | 739/4959 [09:31<2:14:33,  1.91s/it]

 15%|█▍        | 740/4959 [09:33<2:15:14,  1.92s/it]

 15%|█▍        | 741/4959 [09:34<2:08:36,  1.83s/it]

 15%|█▍        | 742/4959 [09:36<2:11:41,  1.87s/it]

 15%|█▍        | 743/4959 [09:38<2:15:15,  1.92s/it]

 15%|█▌        | 744/4959 [09:40<2:13:56,  1.91s/it]

 15%|█▌        | 745/4959 [09:42<2:07:42,  1.82s/it]

 15%|█▌        | 746/4959 [09:44<2:08:26,  1.83s/it]

 15%|█▌        | 747/4959 [09:46<2:07:08,  1.81s/it]

 15%|█▌        | 748/4959 [09:48<2:10:33,  1.86s/it]

 15%|█▌        | 749/4959 [09:50<2:19:29,  1.99s/it]

 15%|█▌        | 750/4959 [09:52<2:18:59,  1.98s/it]

 15%|█▌        | 751/4959 [09:54<2:18:44,  1.98s/it]

 15%|█▌        | 752/4959 [09:55<2:11:14,  1.87s/it]

 15%|█▌        | 753/4959 [09:57<2:12:59,  1.90s/it]

 15%|█▌        | 754/4959 [09:59<2:07:45,  1.82s/it]

 15%|█▌        | 755/4959 [10:01<2:03:47,  1.77s/it]

 15%|█▌        | 756/4959 [10:03<2:08:41,  1.84s/it]

 15%|█▌        | 757/4959 [10:04<2:05:20,  1.79s/it]

 15%|█▌        | 758/4959 [10:06<2:08:41,  1.84s/it]

 15%|█▌        | 759/4959 [10:08<2:05:03,  1.79s/it]

 15%|█▌        | 760/4959 [10:10<2:01:30,  1.74s/it]

 15%|█▌        | 761/4959 [10:12<2:07:03,  1.82s/it]

 15%|█▌        | 762/4959 [10:13<2:02:53,  1.76s/it]

 15%|█▌        | 763/4959 [10:15<2:07:34,  1.82s/it]

 15%|█▌        | 764/4959 [10:17<2:03:40,  1.77s/it]

 15%|█▌        | 765/4959 [10:19<2:03:13,  1.76s/it]

 15%|█▌        | 766/4959 [10:20<1:59:58,  1.72s/it]

 15%|█▌        | 767/4959 [10:22<1:58:11,  1.69s/it]

 15%|█▌        | 768/4959 [10:23<1:57:18,  1.68s/it]

 16%|█▌        | 769/4959 [10:25<1:56:33,  1.67s/it]

 16%|█▌        | 770/4959 [10:27<1:55:46,  1.66s/it]

 16%|█▌        | 771/4959 [10:29<2:02:56,  1.76s/it]

 16%|█▌        | 772/4959 [10:30<2:00:21,  1.72s/it]

 16%|█▌        | 773/4959 [10:32<2:06:03,  1.81s/it]

 16%|█▌        | 774/4959 [10:34<2:03:24,  1.77s/it]

 16%|█▌        | 775/4959 [10:36<2:00:16,  1.72s/it]

 16%|█▌        | 776/4959 [10:37<1:57:44,  1.69s/it]

 16%|█▌        | 777/4959 [10:39<2:03:14,  1.77s/it]

 16%|█▌        | 778/4959 [10:41<2:00:12,  1.73s/it]

 16%|█▌        | 779/4959 [10:43<2:05:22,  1.80s/it]

 16%|█▌        | 780/4959 [10:44<2:02:09,  1.75s/it]

 16%|█▌        | 781/4959 [10:46<2:06:55,  1.82s/it]

 16%|█▌        | 782/4959 [10:48<2:02:46,  1.76s/it]

 16%|█▌        | 783/4959 [10:50<2:00:40,  1.73s/it]

 16%|█▌        | 784/4959 [10:52<2:04:58,  1.80s/it]

 16%|█▌        | 785/4959 [10:53<2:00:55,  1.74s/it]

 16%|█▌        | 786/4959 [10:55<2:07:37,  1.84s/it]

 16%|█▌        | 787/4959 [10:57<2:03:09,  1.77s/it]

 16%|█▌        | 788/4959 [10:59<2:00:44,  1.74s/it]

 16%|█▌        | 789/4959 [11:01<2:06:07,  1.81s/it]

 16%|█▌        | 790/4959 [11:03<2:09:24,  1.86s/it]

 16%|█▌        | 791/4959 [11:04<2:04:40,  1.79s/it]

 16%|█▌        | 792/4959 [11:06<2:04:06,  1.79s/it]

 16%|█▌        | 793/4959 [11:08<2:08:13,  1.85s/it]

 16%|█▌        | 794/4959 [11:10<2:04:35,  1.79s/it]

 16%|█▌        | 795/4959 [11:12<2:09:22,  1.86s/it]

 16%|█▌        | 796/4959 [11:14<2:12:06,  1.90s/it]

 16%|█▌        | 797/4959 [11:16<2:13:32,  1.93s/it]

 16%|█▌        | 798/4959 [11:17<2:08:01,  1.85s/it]

 16%|█▌        | 799/4959 [11:19<2:09:11,  1.86s/it]

 16%|█▌        | 800/4959 [11:21<2:17:18,  1.98s/it]

 16%|█▌        | 801/4959 [11:23<2:10:36,  1.88s/it]

 16%|█▌        | 802/4959 [11:25<2:05:45,  1.82s/it]

 16%|█▌        | 803/4959 [11:26<2:01:46,  1.76s/it]

 16%|█▌        | 804/4959 [11:28<2:06:33,  1.83s/it]

 16%|█▌        | 805/4959 [11:30<2:09:09,  1.87s/it]

 16%|█▋        | 806/4959 [11:33<2:18:47,  2.01s/it]

 16%|█▋        | 807/4959 [11:35<2:19:27,  2.02s/it]

 16%|█▋        | 808/4959 [11:37<2:18:59,  2.01s/it]

 16%|█▋        | 809/4959 [11:38<2:11:09,  1.90s/it]

 16%|█▋        | 810/4959 [11:40<2:05:52,  1.82s/it]

 16%|█▋        | 811/4959 [11:42<2:08:51,  1.86s/it]

 16%|█▋        | 812/4959 [11:44<2:11:14,  1.90s/it]

 16%|█▋        | 813/4959 [11:46<2:06:10,  1.83s/it]

 16%|█▋        | 814/4959 [11:47<2:02:13,  1.77s/it]

 16%|█▋        | 815/4959 [11:49<1:59:17,  1.73s/it]

 16%|█▋        | 816/4959 [11:50<1:56:47,  1.69s/it]

 16%|█▋        | 817/4959 [11:52<1:55:34,  1.67s/it]

 16%|█▋        | 818/4959 [11:54<1:55:05,  1.67s/it]

 17%|█▋        | 819/4959 [11:55<1:54:27,  1.66s/it]

 17%|█▋        | 820/4959 [11:57<1:55:49,  1.68s/it]

 17%|█▋        | 821/4959 [11:59<1:57:45,  1.71s/it]

 17%|█▋        | 822/4959 [12:01<2:03:29,  1.79s/it]

 17%|█▋        | 823/4959 [12:03<2:02:39,  1.78s/it]

 17%|█▋        | 824/4959 [12:04<1:59:40,  1.74s/it]

 17%|█▋        | 825/4959 [12:06<2:03:53,  1.80s/it]

 17%|█▋        | 826/4959 [12:09<2:16:13,  1.98s/it]

 17%|█▋        | 827/4959 [12:11<2:16:35,  1.98s/it]

 17%|█▋        | 828/4959 [12:13<2:23:11,  2.08s/it]

 17%|█▋        | 829/4959 [12:15<2:17:03,  1.99s/it]

 17%|█▋        | 830/4959 [12:16<2:11:38,  1.91s/it]

 17%|█▋        | 831/4959 [12:18<2:11:37,  1.91s/it]

 17%|█▋        | 832/4959 [12:20<2:16:48,  1.99s/it]

 17%|█▋        | 833/4959 [12:22<2:14:38,  1.96s/it]

 17%|█▋        | 834/4959 [12:24<2:09:58,  1.89s/it]

 17%|█▋        | 835/4959 [12:26<2:09:32,  1.88s/it]

 17%|█▋        | 836/4959 [12:28<2:06:14,  1.84s/it]

 17%|█▋        | 837/4959 [12:30<2:11:16,  1.91s/it]

 17%|█▋        | 838/4959 [12:32<2:10:27,  1.90s/it]

 17%|█▋        | 839/4959 [12:34<2:15:27,  1.97s/it]

 17%|█▋        | 840/4959 [12:36<2:10:58,  1.91s/it]

 17%|█▋        | 841/4959 [12:38<2:14:27,  1.96s/it]

 17%|█▋        | 842/4959 [12:40<2:16:55,  2.00s/it]

 17%|█▋        | 843/4959 [12:42<2:18:39,  2.02s/it]

 17%|█▋        | 844/4959 [12:44<2:12:47,  1.94s/it]

 17%|█▋        | 845/4959 [12:46<2:15:43,  1.98s/it]

 17%|█▋        | 846/4959 [12:47<2:10:52,  1.91s/it]

 17%|█▋        | 847/4959 [12:49<2:13:47,  1.95s/it]

 17%|█▋        | 848/4959 [12:52<2:16:51,  2.00s/it]

 17%|█▋        | 849/4959 [12:53<2:12:54,  1.94s/it]

 17%|█▋        | 850/4959 [12:55<2:09:07,  1.89s/it]

 17%|█▋        | 851/4959 [12:57<2:12:52,  1.94s/it]

 17%|█▋        | 852/4959 [12:59<2:08:07,  1.87s/it]

 17%|█▋        | 853/4959 [13:01<2:05:37,  1.84s/it]

 17%|█▋        | 854/4959 [13:02<2:03:53,  1.81s/it]

 17%|█▋        | 855/4959 [13:04<2:02:06,  1.79s/it]

 17%|█▋        | 856/4959 [13:06<2:08:04,  1.87s/it]

 17%|█▋        | 857/4959 [13:08<2:04:57,  1.83s/it]

 17%|█▋        | 858/4959 [13:10<2:10:02,  1.90s/it]

 17%|█▋        | 859/4959 [13:12<2:15:08,  1.98s/it]

 17%|█▋        | 860/4959 [13:14<2:10:03,  1.90s/it]

 17%|█▋        | 861/4959 [13:16<2:07:05,  1.86s/it]

 17%|█▋        | 862/4959 [13:17<2:05:32,  1.84s/it]

 17%|█▋        | 863/4959 [13:19<2:04:18,  1.82s/it]

 17%|█▋        | 864/4959 [13:21<2:02:32,  1.80s/it]

 17%|█▋        | 865/4959 [13:23<2:04:15,  1.82s/it]

 17%|█▋        | 866/4959 [13:25<2:03:55,  1.82s/it]

 17%|█▋        | 867/4959 [13:27<2:09:53,  1.90s/it]

 18%|█▊        | 868/4959 [13:28<2:06:11,  1.85s/it]

 18%|█▊        | 869/4959 [13:30<2:02:50,  1.80s/it]

 18%|█▊        | 870/4959 [13:32<2:08:16,  1.88s/it]

 18%|█▊        | 871/4959 [13:34<2:05:18,  1.84s/it]

 18%|█▊        | 872/4959 [13:36<2:02:47,  1.80s/it]

 18%|█▊        | 873/4959 [13:38<2:04:53,  1.83s/it]

 18%|█▊        | 874/4959 [13:39<2:03:12,  1.81s/it]

 18%|█▊        | 875/4959 [13:41<2:02:08,  1.79s/it]

 18%|█▊        | 876/4959 [13:43<2:12:11,  1.94s/it]

 18%|█▊        | 877/4959 [13:45<2:09:46,  1.91s/it]

 18%|█▊        | 878/4959 [13:47<2:05:17,  1.84s/it]

 18%|█▊        | 879/4959 [13:49<2:03:10,  1.81s/it]

 18%|█▊        | 880/4959 [13:50<2:01:32,  1.79s/it]

 18%|█▊        | 881/4959 [13:52<2:00:13,  1.77s/it]

 18%|█▊        | 882/4959 [13:54<2:06:21,  1.86s/it]

 18%|█▊        | 883/4959 [13:56<2:03:31,  1.82s/it]

 18%|█▊        | 884/4959 [13:58<2:08:55,  1.90s/it]

 18%|█▊        | 885/4959 [14:00<2:11:47,  1.94s/it]

 18%|█▊        | 886/4959 [14:02<2:07:11,  1.87s/it]

 18%|█▊        | 887/4959 [14:03<2:03:11,  1.82s/it]

 18%|█▊        | 888/4959 [14:05<2:02:12,  1.80s/it]

 18%|█▊        | 889/4959 [14:07<2:07:49,  1.88s/it]

 18%|█▊        | 890/4959 [14:09<2:03:57,  1.83s/it]

 18%|█▊        | 891/4959 [14:11<2:01:36,  1.79s/it]

 18%|█▊        | 892/4959 [14:13<2:08:38,  1.90s/it]

 18%|█▊        | 893/4959 [14:14<2:04:22,  1.84s/it]

 18%|█▊        | 894/4959 [14:16<2:01:25,  1.79s/it]

 18%|█▊        | 895/4959 [14:18<2:06:02,  1.86s/it]

 18%|█▊        | 896/4959 [14:20<2:02:51,  1.81s/it]

 18%|█▊        | 897/4959 [14:22<2:00:13,  1.78s/it]

 18%|█▊        | 898/4959 [14:23<1:58:31,  1.75s/it]

 18%|█▊        | 899/4959 [14:25<2:03:54,  1.83s/it]

 18%|█▊        | 900/4959 [14:27<2:01:11,  1.79s/it]

 18%|█▊        | 901/4959 [14:29<1:58:49,  1.76s/it]

 18%|█▊        | 902/4959 [14:31<2:04:33,  1.84s/it]

 18%|█▊        | 903/4959 [14:32<2:01:13,  1.79s/it]

 18%|█▊        | 904/4959 [14:34<2:06:17,  1.87s/it]

 18%|█▊        | 905/4959 [14:36<2:09:24,  1.92s/it]

 18%|█▊        | 906/4959 [14:38<2:11:45,  1.95s/it]

 18%|█▊        | 907/4959 [14:41<2:13:15,  1.97s/it]

 18%|█▊        | 908/4959 [14:42<2:07:15,  1.88s/it]

 18%|█▊        | 909/4959 [14:44<2:03:06,  1.82s/it]

 18%|█▊        | 910/4959 [14:46<2:00:10,  1.78s/it]

 18%|█▊        | 911/4959 [14:48<2:04:56,  1.85s/it]

 18%|█▊        | 912/4959 [14:49<2:01:27,  1.80s/it]

 18%|█▊        | 913/4959 [14:51<1:59:00,  1.76s/it]

 18%|█▊        | 914/4959 [14:53<1:57:16,  1.74s/it]

 18%|█▊        | 915/4959 [14:55<2:03:04,  1.83s/it]

 18%|█▊        | 916/4959 [14:56<1:59:59,  1.78s/it]

 18%|█▊        | 917/4959 [14:58<1:57:42,  1.75s/it]

 19%|█▊        | 918/4959 [15:00<1:57:15,  1.74s/it]

 19%|█▊        | 919/4959 [15:01<1:56:10,  1.73s/it]

 19%|█▊        | 920/4959 [15:03<1:55:10,  1.71s/it]

 19%|█▊        | 921/4959 [15:05<1:54:26,  1.70s/it]

 19%|█▊        | 922/4959 [15:06<1:53:51,  1.69s/it]

 19%|█▊        | 923/4959 [15:08<1:53:30,  1.69s/it]

 19%|█▊        | 924/4959 [15:10<2:00:08,  1.79s/it]

 19%|█▊        | 925/4959 [15:12<1:57:42,  1.75s/it]

 19%|█▊        | 926/4959 [15:13<1:56:07,  1.73s/it]

 19%|█▊        | 927/4959 [15:15<1:55:10,  1.71s/it]

 19%|█▊        | 928/4959 [15:17<2:01:42,  1.81s/it]

 19%|█▊        | 929/4959 [15:19<1:59:06,  1.77s/it]

 19%|█▉        | 930/4959 [15:20<1:55:53,  1.73s/it]

 19%|█▉        | 931/4959 [15:22<1:54:02,  1.70s/it]

 19%|█▉        | 932/4959 [15:24<1:53:09,  1.69s/it]

 19%|█▉        | 933/4959 [15:25<1:52:18,  1.67s/it]

 19%|█▉        | 934/4959 [15:27<1:58:03,  1.76s/it]

 19%|█▉        | 935/4959 [15:29<1:55:25,  1.72s/it]

 19%|█▉        | 936/4959 [15:31<1:53:14,  1.69s/it]

 19%|█▉        | 937/4959 [15:32<1:54:21,  1.71s/it]

 19%|█▉        | 938/4959 [15:35<2:06:48,  1.89s/it]

 19%|█▉        | 939/4959 [15:37<2:06:42,  1.89s/it]

 19%|█▉        | 940/4959 [15:39<2:10:30,  1.95s/it]

 19%|█▉        | 941/4959 [15:41<2:18:18,  2.07s/it]

 19%|█▉        | 942/4959 [15:43<2:23:56,  2.15s/it]

 19%|█▉        | 943/4959 [15:46<2:25:24,  2.17s/it]

 19%|█▉        | 944/4959 [15:48<2:26:31,  2.19s/it]

 19%|█▉        | 945/4959 [15:50<2:30:08,  2.24s/it]

 19%|█▉        | 946/4959 [15:52<2:28:15,  2.22s/it]

 19%|█▉        | 947/4959 [15:54<2:21:18,  2.11s/it]

 19%|█▉        | 948/4959 [15:56<2:12:14,  1.98s/it]

 19%|█▉        | 949/4959 [15:58<2:10:06,  1.95s/it]

 19%|█▉        | 950/4959 [16:00<2:13:33,  2.00s/it]

 19%|█▉        | 951/4959 [16:02<2:10:47,  1.96s/it]

 19%|█▉        | 952/4959 [16:03<2:06:00,  1.89s/it]

 19%|█▉        | 953/4959 [16:05<2:04:03,  1.86s/it]

 19%|█▉        | 954/4959 [16:07<2:11:11,  1.97s/it]

 19%|█▉        | 955/4959 [16:10<2:16:14,  2.04s/it]

 19%|█▉        | 956/4959 [16:12<2:12:15,  1.98s/it]

 19%|█▉        | 957/4959 [16:13<2:09:46,  1.95s/it]

 19%|█▉        | 958/4959 [16:15<2:13:08,  2.00s/it]

 19%|█▉        | 959/4959 [16:17<2:11:42,  1.98s/it]

 19%|█▉        | 960/4959 [16:19<2:08:13,  1.92s/it]

 19%|█▉        | 961/4959 [16:21<2:09:39,  1.95s/it]

 19%|█▉        | 962/4959 [16:23<2:08:05,  1.92s/it]

 19%|█▉        | 963/4959 [16:26<2:20:33,  2.11s/it]

 19%|█▉        | 964/4959 [16:27<2:15:25,  2.03s/it]

 19%|█▉        | 965/4959 [16:29<2:08:39,  1.93s/it]

 19%|█▉        | 966/4959 [16:31<2:08:59,  1.94s/it]

 19%|█▉        | 967/4959 [16:33<2:07:05,  1.91s/it]

 20%|█▉        | 968/4959 [16:35<2:11:22,  1.98s/it]

 20%|█▉        | 969/4959 [16:37<2:13:12,  2.00s/it]

 20%|█▉        | 970/4959 [16:39<2:08:06,  1.93s/it]

 20%|█▉        | 971/4959 [16:41<2:11:38,  1.98s/it]

 20%|█▉        | 972/4959 [16:43<2:13:13,  2.00s/it]

 20%|█▉        | 973/4959 [16:45<2:14:56,  2.03s/it]

 20%|█▉        | 974/4959 [16:47<2:20:07,  2.11s/it]

 20%|█▉        | 975/4959 [16:50<2:19:28,  2.10s/it]

 20%|█▉        | 976/4959 [16:51<2:12:35,  2.00s/it]

 20%|█▉        | 977/4959 [16:53<2:08:53,  1.94s/it]

 20%|█▉        | 978/4959 [16:55<2:05:57,  1.90s/it]

 20%|█▉        | 979/4959 [16:57<2:13:59,  2.02s/it]

 20%|█▉        | 980/4959 [16:59<2:09:29,  1.95s/it]

 20%|█▉        | 981/4959 [17:01<2:12:12,  1.99s/it]

 20%|█▉        | 982/4959 [17:03<2:16:26,  2.06s/it]

 20%|█▉        | 983/4959 [17:05<2:09:05,  1.95s/it]

 20%|█▉        | 984/4959 [17:07<2:04:45,  1.88s/it]

 20%|█▉        | 985/4959 [17:09<2:03:03,  1.86s/it]

 20%|█▉        | 986/4959 [17:10<2:03:12,  1.86s/it]

 20%|█▉        | 987/4959 [17:13<2:09:36,  1.96s/it]

 20%|█▉        | 988/4959 [17:14<2:04:44,  1.88s/it]

 20%|█▉        | 989/4959 [17:17<2:11:07,  1.98s/it]

 20%|█▉        | 990/4959 [17:19<2:16:20,  2.06s/it]

 20%|█▉        | 991/4959 [17:21<2:09:46,  1.96s/it]

 20%|██        | 992/4959 [17:22<2:06:29,  1.91s/it]

 20%|██        | 993/4959 [17:24<2:03:31,  1.87s/it]

 20%|██        | 994/4959 [17:26<2:02:42,  1.86s/it]

 20%|██        | 995/4959 [17:28<2:00:25,  1.82s/it]

 20%|██        | 996/4959 [17:30<2:04:51,  1.89s/it]

 20%|██        | 997/4959 [17:32<2:08:06,  1.94s/it]

 20%|██        | 998/4959 [17:34<2:12:33,  2.01s/it]

 20%|██        | 999/4959 [17:36<2:16:52,  2.07s/it]

 20%|██        | 1000/4959 [17:38<2:13:18,  2.02s/it]

 20%|██        | 1001/4959 [17:40<2:20:37,  2.13s/it]

 20%|██        | 1002/4959 [17:42<2:16:12,  2.07s/it]

 20%|██        | 1003/4959 [17:44<2:17:34,  2.09s/it]

 20%|██        | 1004/4959 [17:46<2:15:04,  2.05s/it]

 20%|██        | 1005/4959 [17:48<2:10:00,  1.97s/it]

 20%|██        | 1006/4959 [17:50<2:11:54,  2.00s/it]

 20%|██        | 1007/4959 [17:52<2:14:33,  2.04s/it]

 20%|██        | 1008/4959 [17:54<2:08:29,  1.95s/it]

 20%|██        | 1009/4959 [17:56<2:10:59,  1.99s/it]

 20%|██        | 1010/4959 [17:58<2:06:49,  1.93s/it]

 20%|██        | 1011/4959 [18:00<2:07:48,  1.94s/it]

 20%|██        | 1012/4959 [18:02<2:02:26,  1.86s/it]

 20%|██        | 1013/4959 [18:03<2:00:40,  1.83s/it]

 20%|██        | 1014/4959 [18:05<2:03:23,  1.88s/it]

 20%|██        | 1015/4959 [18:07<2:04:50,  1.90s/it]

 20%|██        | 1016/4959 [18:09<2:06:42,  1.93s/it]

 21%|██        | 1017/4959 [18:11<2:08:18,  1.95s/it]

 21%|██        | 1018/4959 [18:13<2:08:00,  1.95s/it]

 21%|██        | 1019/4959 [18:15<2:12:10,  2.01s/it]

 21%|██        | 1020/4959 [18:18<2:13:19,  2.03s/it]

 21%|██        | 1021/4959 [18:20<2:11:33,  2.00s/it]

 21%|██        | 1022/4959 [18:21<2:05:45,  1.92s/it]

 21%|██        | 1023/4959 [18:23<2:02:45,  1.87s/it]

 21%|██        | 1024/4959 [18:25<2:11:37,  2.01s/it]

 21%|██        | 1025/4959 [18:27<2:05:55,  1.92s/it]

 21%|██        | 1026/4959 [18:29<2:03:53,  1.89s/it]

 21%|██        | 1027/4959 [18:31<2:02:32,  1.87s/it]

 21%|██        | 1028/4959 [18:33<2:06:33,  1.93s/it]

 21%|██        | 1029/4959 [18:35<2:09:10,  1.97s/it]

 21%|██        | 1030/4959 [18:37<2:10:10,  1.99s/it]

 21%|██        | 1031/4959 [18:39<2:07:13,  1.94s/it]

 21%|██        | 1032/4959 [18:41<2:05:52,  1.92s/it]

 21%|██        | 1033/4959 [18:43<2:11:33,  2.01s/it]

 21%|██        | 1034/4959 [18:45<2:07:37,  1.95s/it]

 21%|██        | 1035/4959 [18:46<2:05:03,  1.91s/it]

 21%|██        | 1036/4959 [18:49<2:12:41,  2.03s/it]

 21%|██        | 1037/4959 [18:51<2:16:30,  2.09s/it]

 21%|██        | 1038/4959 [18:53<2:10:42,  2.00s/it]

 21%|██        | 1039/4959 [18:55<2:06:49,  1.94s/it]

 21%|██        | 1040/4959 [18:56<2:06:22,  1.93s/it]

 21%|██        | 1041/4959 [18:58<2:03:22,  1.89s/it]

 21%|██        | 1042/4959 [19:00<2:06:19,  1.93s/it]

 21%|██        | 1043/4959 [19:02<2:07:00,  1.95s/it]

 21%|██        | 1044/4959 [19:04<2:03:28,  1.89s/it]

 21%|██        | 1045/4959 [19:06<2:06:56,  1.95s/it]

 21%|██        | 1046/4959 [19:08<2:04:21,  1.91s/it]

 21%|██        | 1047/4959 [19:10<2:07:56,  1.96s/it]

 21%|██        | 1048/4959 [19:12<2:03:22,  1.89s/it]

 21%|██        | 1049/4959 [19:14<2:06:43,  1.94s/it]

 21%|██        | 1050/4959 [19:15<2:02:00,  1.87s/it]

 21%|██        | 1051/4959 [19:17<1:59:15,  1.83s/it]

 21%|██        | 1052/4959 [19:19<1:57:38,  1.81s/it]

 21%|██        | 1053/4959 [19:21<2:03:55,  1.90s/it]

 21%|██▏       | 1054/4959 [19:23<2:03:53,  1.90s/it]

 21%|██▏       | 1055/4959 [19:25<2:00:56,  1.86s/it]

 21%|██▏       | 1056/4959 [19:27<2:06:41,  1.95s/it]

 21%|██▏       | 1057/4959 [19:29<2:11:08,  2.02s/it]

 21%|██▏       | 1058/4959 [19:31<2:07:10,  1.96s/it]

 21%|██▏       | 1059/4959 [19:33<2:03:11,  1.90s/it]

 21%|██▏       | 1060/4959 [19:35<2:10:05,  2.00s/it]

 21%|██▏       | 1061/4959 [19:37<2:09:04,  1.99s/it]

 21%|██▏       | 1062/4959 [19:39<2:07:16,  1.96s/it]

 21%|██▏       | 1063/4959 [19:41<2:13:19,  2.05s/it]

 21%|██▏       | 1064/4959 [19:43<2:10:59,  2.02s/it]

 21%|██▏       | 1065/4959 [19:45<2:07:00,  1.96s/it]

 21%|██▏       | 1066/4959 [19:47<2:11:36,  2.03s/it]

 22%|██▏       | 1067/4959 [19:49<2:05:29,  1.93s/it]

 22%|██▏       | 1068/4959 [19:51<2:05:54,  1.94s/it]

 22%|██▏       | 1069/4959 [19:52<2:01:54,  1.88s/it]

 22%|██▏       | 1070/4959 [19:54<2:03:32,  1.91s/it]

 22%|██▏       | 1071/4959 [19:56<2:02:24,  1.89s/it]

 22%|██▏       | 1072/4959 [19:58<2:01:38,  1.88s/it]

 22%|██▏       | 1073/4959 [20:00<2:01:42,  1.88s/it]

 22%|██▏       | 1074/4959 [20:02<2:06:12,  1.95s/it]

 22%|██▏       | 1075/4959 [20:04<2:09:16,  2.00s/it]

 22%|██▏       | 1076/4959 [20:06<2:04:02,  1.92s/it]

 22%|██▏       | 1077/4959 [20:08<2:02:16,  1.89s/it]

 22%|██▏       | 1078/4959 [20:09<1:57:43,  1.82s/it]

 22%|██▏       | 1079/4959 [20:11<1:57:13,  1.81s/it]

 22%|██▏       | 1080/4959 [20:13<2:04:39,  1.93s/it]

 22%|██▏       | 1081/4959 [20:16<2:10:10,  2.01s/it]

 22%|██▏       | 1082/4959 [20:18<2:08:29,  1.99s/it]

 22%|██▏       | 1083/4959 [20:19<2:04:58,  1.93s/it]

 22%|██▏       | 1084/4959 [20:21<2:01:07,  1.88s/it]

 22%|██▏       | 1085/4959 [20:23<1:58:41,  1.84s/it]

 22%|██▏       | 1086/4959 [20:25<2:03:37,  1.92s/it]

 22%|██▏       | 1087/4959 [20:27<2:01:21,  1.88s/it]

 22%|██▏       | 1088/4959 [20:29<2:07:15,  1.97s/it]

 22%|██▏       | 1089/4959 [20:31<2:00:59,  1.88s/it]

 22%|██▏       | 1090/4959 [20:32<2:00:04,  1.86s/it]

 22%|██▏       | 1091/4959 [20:34<1:55:15,  1.79s/it]

 22%|██▏       | 1092/4959 [20:36<1:58:50,  1.84s/it]

 22%|██▏       | 1093/4959 [20:38<2:01:32,  1.89s/it]

 22%|██▏       | 1094/4959 [20:40<2:03:25,  1.92s/it]

 22%|██▏       | 1095/4959 [20:42<2:04:22,  1.93s/it]

 22%|██▏       | 1096/4959 [20:44<1:58:13,  1.84s/it]

 22%|██▏       | 1097/4959 [20:45<2:00:45,  1.88s/it]

 22%|██▏       | 1098/4959 [20:47<1:55:59,  1.80s/it]

 22%|██▏       | 1099/4959 [20:49<1:59:15,  1.85s/it]

 22%|██▏       | 1100/4959 [20:51<1:54:54,  1.79s/it]

 22%|██▏       | 1101/4959 [20:53<1:58:52,  1.85s/it]

 22%|██▏       | 1102/4959 [20:55<2:01:10,  1.89s/it]

 22%|██▏       | 1103/4959 [20:57<2:03:02,  1.91s/it]

 22%|██▏       | 1104/4959 [20:59<2:04:46,  1.94s/it]

 22%|██▏       | 1105/4959 [21:00<1:58:24,  1.84s/it]

 22%|██▏       | 1106/4959 [21:02<2:00:44,  1.88s/it]

 22%|██▏       | 1107/4959 [21:04<2:02:54,  1.91s/it]

 22%|██▏       | 1108/4959 [21:06<2:03:50,  1.93s/it]

 22%|██▏       | 1109/4959 [21:08<1:58:05,  1.84s/it]

 22%|██▏       | 1110/4959 [21:09<1:53:47,  1.77s/it]

 22%|██▏       | 1111/4959 [21:11<1:57:45,  1.84s/it]

 22%|██▏       | 1112/4959 [21:13<2:00:52,  1.89s/it]

 22%|██▏       | 1113/4959 [21:15<1:55:44,  1.81s/it]

 22%|██▏       | 1114/4959 [21:17<1:52:13,  1.75s/it]

 22%|██▏       | 1115/4959 [21:18<1:49:34,  1.71s/it]

 23%|██▎       | 1116/4959 [21:20<1:47:38,  1.68s/it]

 23%|██▎       | 1117/4959 [21:22<1:46:42,  1.67s/it]

 23%|██▎       | 1118/4959 [21:23<1:46:00,  1.66s/it]

 23%|██▎       | 1119/4959 [21:25<1:52:33,  1.76s/it]

 23%|██▎       | 1120/4959 [21:27<1:49:59,  1.72s/it]

 23%|██▎       | 1121/4959 [21:29<1:55:38,  1.81s/it]

 23%|██▎       | 1122/4959 [21:30<1:52:21,  1.76s/it]

 23%|██▎       | 1123/4959 [21:32<1:56:36,  1.82s/it]

 23%|██▎       | 1124/4959 [21:34<1:52:47,  1.76s/it]

 23%|██▎       | 1125/4959 [21:36<1:49:55,  1.72s/it]

 23%|██▎       | 1126/4959 [21:37<1:47:46,  1.69s/it]

 23%|██▎       | 1127/4959 [21:39<1:56:48,  1.83s/it]

 23%|██▎       | 1128/4959 [21:41<1:59:54,  1.88s/it]

 23%|██▎       | 1129/4959 [21:43<1:54:50,  1.80s/it]

 23%|██▎       | 1130/4959 [21:45<1:51:41,  1.75s/it]

 23%|██▎       | 1131/4959 [21:46<1:49:41,  1.72s/it]

 23%|██▎       | 1132/4959 [21:48<1:48:09,  1.70s/it]

 23%|██▎       | 1133/4959 [21:50<1:53:30,  1.78s/it]

 23%|██▎       | 1134/4959 [21:52<1:56:57,  1.83s/it]

 23%|██▎       | 1135/4959 [21:54<1:59:35,  1.88s/it]

 23%|██▎       | 1136/4959 [21:56<1:54:55,  1.80s/it]

 23%|██▎       | 1137/4959 [21:58<1:59:12,  1.87s/it]

 23%|██▎       | 1138/4959 [21:59<1:54:35,  1.80s/it]

 23%|██▎       | 1139/4959 [22:01<1:51:11,  1.75s/it]

 23%|██▎       | 1140/4959 [22:02<1:48:57,  1.71s/it]

 23%|██▎       | 1141/4959 [22:04<1:53:49,  1.79s/it]

 23%|██▎       | 1142/4959 [22:06<1:50:45,  1.74s/it]

 23%|██▎       | 1143/4959 [22:08<1:48:27,  1.71s/it]

 23%|██▎       | 1144/4959 [22:09<1:47:00,  1.68s/it]

 23%|██▎       | 1145/4959 [22:11<1:52:54,  1.78s/it]

 23%|██▎       | 1146/4959 [22:13<1:49:52,  1.73s/it]

 23%|██▎       | 1147/4959 [22:15<1:54:43,  1.81s/it]

 23%|██▎       | 1148/4959 [22:17<1:51:11,  1.75s/it]

 23%|██▎       | 1149/4959 [22:18<1:55:13,  1.81s/it]

 23%|██▎       | 1150/4959 [22:20<1:58:13,  1.86s/it]

 23%|██▎       | 1151/4959 [22:22<1:53:40,  1.79s/it]

 23%|██▎       | 1152/4959 [22:24<1:50:34,  1.74s/it]

 23%|██▎       | 1153/4959 [22:26<1:55:30,  1.82s/it]

 23%|██▎       | 1154/4959 [22:27<1:52:21,  1.77s/it]

 23%|██▎       | 1155/4959 [22:29<1:49:28,  1.73s/it]

 23%|██▎       | 1156/4959 [22:31<1:47:20,  1.69s/it]

 23%|██▎       | 1157/4959 [22:33<1:53:22,  1.79s/it]

 23%|██▎       | 1158/4959 [22:35<1:57:50,  1.86s/it]

 23%|██▎       | 1159/4959 [22:36<1:53:28,  1.79s/it]

 23%|██▎       | 1160/4959 [22:38<1:50:29,  1.74s/it]

 23%|██▎       | 1161/4959 [22:40<1:54:54,  1.82s/it]

 23%|██▎       | 1162/4959 [22:42<1:57:44,  1.86s/it]

 23%|██▎       | 1163/4959 [22:44<1:59:45,  1.89s/it]

 23%|██▎       | 1164/4959 [22:46<2:01:52,  1.93s/it]

 23%|██▎       | 1165/4959 [22:48<2:02:38,  1.94s/it]

 24%|██▎       | 1166/4959 [22:50<2:03:52,  1.96s/it]

 24%|██▎       | 1167/4959 [22:52<2:04:36,  1.97s/it]

 24%|██▎       | 1168/4959 [22:54<2:05:03,  1.98s/it]

 24%|██▎       | 1169/4959 [22:56<2:05:28,  1.99s/it]

 24%|██▎       | 1170/4959 [22:58<2:06:01,  2.00s/it]

 24%|██▎       | 1171/4959 [22:59<1:59:39,  1.90s/it]

 24%|██▎       | 1172/4959 [23:01<1:54:29,  1.81s/it]

 24%|██▎       | 1173/4959 [23:03<1:50:53,  1.76s/it]

 24%|██▎       | 1174/4959 [23:04<1:48:57,  1.73s/it]

 24%|██▎       | 1175/4959 [23:06<1:53:43,  1.80s/it]

 24%|██▎       | 1176/4959 [23:08<1:57:43,  1.87s/it]

 24%|██▎       | 1177/4959 [23:10<1:53:00,  1.79s/it]

 24%|██▍       | 1178/4959 [23:12<1:50:07,  1.75s/it]

 24%|██▍       | 1179/4959 [23:13<1:47:48,  1.71s/it]

 24%|██▍       | 1180/4959 [23:15<1:46:32,  1.69s/it]

 24%|██▍       | 1181/4959 [23:17<1:51:59,  1.78s/it]

 24%|██▍       | 1182/4959 [23:19<1:49:04,  1.73s/it]

 24%|██▍       | 1183/4959 [23:20<1:53:26,  1.80s/it]

 24%|██▍       | 1184/4959 [23:23<1:57:37,  1.87s/it]

 24%|██▍       | 1185/4959 [23:24<1:59:36,  1.90s/it]

 24%|██▍       | 1186/4959 [23:26<1:54:14,  1.82s/it]

 24%|██▍       | 1187/4959 [23:28<1:50:41,  1.76s/it]

 24%|██▍       | 1188/4959 [23:29<1:48:12,  1.72s/it]

 24%|██▍       | 1189/4959 [23:31<1:53:15,  1.80s/it]

 24%|██▍       | 1190/4959 [23:33<1:56:35,  1.86s/it]

 24%|██▍       | 1191/4959 [23:35<1:59:22,  1.90s/it]

 24%|██▍       | 1192/4959 [23:37<2:00:58,  1.93s/it]

 24%|██▍       | 1193/4959 [23:39<2:01:42,  1.94s/it]

 24%|██▍       | 1194/4959 [23:41<2:02:28,  1.95s/it]

 24%|██▍       | 1195/4959 [23:43<1:56:14,  1.85s/it]

 24%|██▍       | 1196/4959 [23:45<1:59:41,  1.91s/it]

 24%|██▍       | 1197/4959 [23:47<2:00:53,  1.93s/it]

 24%|██▍       | 1198/4959 [23:49<1:55:08,  1.84s/it]

 24%|██▍       | 1199/4959 [23:51<1:57:34,  1.88s/it]

 24%|██▍       | 1200/4959 [23:52<1:59:39,  1.91s/it]

 24%|██▍       | 1201/4959 [23:54<2:01:14,  1.94s/it]

 24%|██▍       | 1202/4959 [23:57<2:05:40,  2.01s/it]

 24%|██▍       | 1203/4959 [23:59<2:04:55,  2.00s/it]

 24%|██▍       | 1204/4959 [24:00<1:58:46,  1.90s/it]

 24%|██▍       | 1205/4959 [24:02<2:00:57,  1.93s/it]

 24%|██▍       | 1206/4959 [24:04<2:02:09,  1.95s/it]

 24%|██▍       | 1207/4959 [24:06<2:05:55,  2.01s/it]

 24%|██▍       | 1208/4959 [24:08<2:05:16,  2.00s/it]

 24%|██▍       | 1209/4959 [24:10<2:04:23,  1.99s/it]

 24%|██▍       | 1210/4959 [24:12<2:04:11,  1.99s/it]

 24%|██▍       | 1211/4959 [24:14<2:04:18,  1.99s/it]

 24%|██▍       | 1212/4959 [24:16<2:03:59,  1.99s/it]

 24%|██▍       | 1213/4959 [24:18<2:04:02,  1.99s/it]

 24%|██▍       | 1214/4959 [24:21<2:07:25,  2.04s/it]

 25%|██▍       | 1215/4959 [24:23<2:06:56,  2.03s/it]

 25%|██▍       | 1216/4959 [24:25<2:05:41,  2.01s/it]

 25%|██▍       | 1217/4959 [24:26<2:04:43,  2.00s/it]

 25%|██▍       | 1218/4959 [24:28<2:04:17,  1.99s/it]

 25%|██▍       | 1219/4959 [24:30<2:03:56,  1.99s/it]

 25%|██▍       | 1220/4959 [24:32<2:03:38,  1.98s/it]

 25%|██▍       | 1221/4959 [24:34<2:03:22,  1.98s/it]

 25%|██▍       | 1222/4959 [24:36<2:03:41,  1.99s/it]

 25%|██▍       | 1223/4959 [24:38<2:03:45,  1.99s/it]

 25%|██▍       | 1224/4959 [24:40<2:03:30,  1.98s/it]

 25%|██▍       | 1225/4959 [24:42<2:03:09,  1.98s/it]

 25%|██▍       | 1226/4959 [24:44<2:03:25,  1.98s/it]

 25%|██▍       | 1227/4959 [24:46<2:06:37,  2.04s/it]

 25%|██▍       | 1228/4959 [24:48<2:05:42,  2.02s/it]

 25%|██▍       | 1229/4959 [24:50<2:05:29,  2.02s/it]

 25%|██▍       | 1230/4959 [24:52<2:04:44,  2.01s/it]

 25%|██▍       | 1231/4959 [24:55<2:07:43,  2.06s/it]

 25%|██▍       | 1232/4959 [24:57<2:06:22,  2.03s/it]

 25%|██▍       | 1233/4959 [24:59<2:05:19,  2.02s/it]

 25%|██▍       | 1234/4959 [25:01<2:04:38,  2.01s/it]

 25%|██▍       | 1235/4959 [25:03<2:03:51,  2.00s/it]

 25%|██▍       | 1236/4959 [25:05<2:03:35,  1.99s/it]

 25%|██▍       | 1237/4959 [25:06<2:03:17,  1.99s/it]

 25%|██▍       | 1238/4959 [25:09<2:06:21,  2.04s/it]

 25%|██▍       | 1239/4959 [25:11<2:05:23,  2.02s/it]

 25%|██▌       | 1240/4959 [25:13<2:05:06,  2.02s/it]

 25%|██▌       | 1241/4959 [25:15<2:04:27,  2.01s/it]

 25%|██▌       | 1242/4959 [25:17<2:03:58,  2.00s/it]

 25%|██▌       | 1243/4959 [25:19<2:02:55,  1.98s/it]

 25%|██▌       | 1244/4959 [25:21<2:03:26,  1.99s/it]

 25%|██▌       | 1245/4959 [25:23<2:03:19,  1.99s/it]

 25%|██▌       | 1246/4959 [25:25<2:03:09,  1.99s/it]

 25%|██▌       | 1247/4959 [25:27<2:03:38,  2.00s/it]

 25%|██▌       | 1248/4959 [25:29<2:03:24,  2.00s/it]

 25%|██▌       | 1249/4959 [25:31<2:02:45,  1.99s/it]

 25%|██▌       | 1250/4959 [25:33<2:03:03,  1.99s/it]

 25%|██▌       | 1251/4959 [25:34<2:02:40,  1.99s/it]

 25%|██▌       | 1252/4959 [25:36<2:02:29,  1.98s/it]

 25%|██▌       | 1253/4959 [25:39<2:06:16,  2.04s/it]

 25%|██▌       | 1254/4959 [25:41<2:05:11,  2.03s/it]

 25%|██▌       | 1255/4959 [25:43<2:04:38,  2.02s/it]

 25%|██▌       | 1256/4959 [25:45<2:03:56,  2.01s/it]

 25%|██▌       | 1257/4959 [25:47<2:06:49,  2.06s/it]

 25%|██▌       | 1258/4959 [25:49<2:05:31,  2.03s/it]

 25%|██▌       | 1259/4959 [25:51<2:04:18,  2.02s/it]

 25%|██▌       | 1260/4959 [25:53<2:03:31,  2.00s/it]

 25%|██▌       | 1261/4959 [25:55<2:03:04,  2.00s/it]

 25%|██▌       | 1262/4959 [25:57<2:02:32,  1.99s/it]

 25%|██▌       | 1263/4959 [25:59<2:02:38,  1.99s/it]

 25%|██▌       | 1264/4959 [26:01<2:02:45,  1.99s/it]

 26%|██▌       | 1265/4959 [26:03<2:03:04,  2.00s/it]

 26%|██▌       | 1266/4959 [26:05<2:03:43,  2.01s/it]

 26%|██▌       | 1267/4959 [26:07<2:03:15,  2.00s/it]

 26%|██▌       | 1268/4959 [26:09<2:02:37,  1.99s/it]

 26%|██▌       | 1269/4959 [26:11<2:03:01,  2.00s/it]

 26%|██▌       | 1270/4959 [26:13<2:03:02,  2.00s/it]

 26%|██▌       | 1271/4959 [26:15<2:02:45,  2.00s/it]

 26%|██▌       | 1272/4959 [26:17<2:02:36,  2.00s/it]

 26%|██▌       | 1273/4959 [26:19<2:06:10,  2.05s/it]

 26%|██▌       | 1274/4959 [26:21<2:05:05,  2.04s/it]

 26%|██▌       | 1275/4959 [26:23<2:04:25,  2.03s/it]

 26%|██▌       | 1276/4959 [26:25<2:03:36,  2.01s/it]

 26%|██▌       | 1277/4959 [26:27<2:06:36,  2.06s/it]

 26%|██▌       | 1278/4959 [26:29<2:04:53,  2.04s/it]

 26%|██▌       | 1279/4959 [26:31<2:03:51,  2.02s/it]

 26%|██▌       | 1280/4959 [26:33<1:56:46,  1.90s/it]

 26%|██▌       | 1281/4959 [26:35<1:57:53,  1.92s/it]

 26%|██▌       | 1282/4959 [26:36<1:52:30,  1.84s/it]

 26%|██▌       | 1283/4959 [26:38<1:54:56,  1.88s/it]

 26%|██▌       | 1284/4959 [26:40<1:56:32,  1.90s/it]

 26%|██▌       | 1285/4959 [26:42<1:57:56,  1.93s/it]

 26%|██▌       | 1286/4959 [26:44<1:58:55,  1.94s/it]

 26%|██▌       | 1287/4959 [26:46<1:53:45,  1.86s/it]

 26%|██▌       | 1288/4959 [26:48<1:55:56,  1.90s/it]

 26%|██▌       | 1289/4959 [26:50<1:58:30,  1.94s/it]

 26%|██▌       | 1290/4959 [26:51<1:52:54,  1.85s/it]

 26%|██▌       | 1291/4959 [26:53<1:48:41,  1.78s/it]

 26%|██▌       | 1292/4959 [26:55<1:52:24,  1.84s/it]

 26%|██▌       | 1293/4959 [26:57<1:54:57,  1.88s/it]

 26%|██▌       | 1294/4959 [26:59<1:50:39,  1.81s/it]

 26%|██▌       | 1295/4959 [27:00<1:46:58,  1.75s/it]

 26%|██▌       | 1296/4959 [27:02<1:44:34,  1.71s/it]

 26%|██▌       | 1297/4959 [27:04<1:42:54,  1.69s/it]

 26%|██▌       | 1298/4959 [27:06<1:48:26,  1.78s/it]

 26%|██▌       | 1299/4959 [27:08<1:56:16,  1.91s/it]

 26%|██▌       | 1300/4959 [27:09<1:51:09,  1.82s/it]

 26%|██▌       | 1301/4959 [27:11<1:47:36,  1.77s/it]

 26%|██▋       | 1302/4959 [27:13<1:51:27,  1.83s/it]

 26%|██▋       | 1303/4959 [27:15<1:48:32,  1.78s/it]

 26%|██▋       | 1304/4959 [27:16<1:45:30,  1.73s/it]

 26%|██▋       | 1305/4959 [27:18<1:51:27,  1.83s/it]

 26%|██▋       | 1306/4959 [27:20<1:54:05,  1.87s/it]

 26%|██▋       | 1307/4959 [27:22<1:49:44,  1.80s/it]

 26%|██▋       | 1308/4959 [27:24<1:52:53,  1.86s/it]

 26%|██▋       | 1309/4959 [27:26<1:49:04,  1.79s/it]

 26%|██▋       | 1310/4959 [27:28<1:52:30,  1.85s/it]

 26%|██▋       | 1311/4959 [27:29<1:54:57,  1.89s/it]

 26%|██▋       | 1312/4959 [27:31<1:49:53,  1.81s/it]

 26%|██▋       | 1313/4959 [27:33<1:46:28,  1.75s/it]

 26%|██▋       | 1314/4959 [27:35<1:50:57,  1.83s/it]

 27%|██▋       | 1315/4959 [27:37<1:54:05,  1.88s/it]

 27%|██▋       | 1316/4959 [27:38<1:49:36,  1.81s/it]

 27%|██▋       | 1317/4959 [27:40<1:46:26,  1.75s/it]

 27%|██▋       | 1318/4959 [27:42<1:50:30,  1.82s/it]

 27%|██▋       | 1319/4959 [27:44<1:53:03,  1.86s/it]

 27%|██▋       | 1320/4959 [27:46<1:55:11,  1.90s/it]

 27%|██▋       | 1321/4959 [27:48<1:50:00,  1.81s/it]

 27%|██▋       | 1322/4959 [27:50<1:52:36,  1.86s/it]

 27%|██▋       | 1323/4959 [27:52<1:55:35,  1.91s/it]

 27%|██▋       | 1324/4959 [27:54<1:56:53,  1.93s/it]

 27%|██▋       | 1325/4959 [27:55<1:57:55,  1.95s/it]

 27%|██▋       | 1326/4959 [27:57<1:52:29,  1.86s/it]

 27%|██▋       | 1327/4959 [27:59<1:54:45,  1.90s/it]

 27%|██▋       | 1328/4959 [28:01<1:50:12,  1.82s/it]

 27%|██▋       | 1329/4959 [28:03<1:53:39,  1.88s/it]

 27%|██▋       | 1330/4959 [28:04<1:49:09,  1.80s/it]

 27%|██▋       | 1331/4959 [28:06<1:45:54,  1.75s/it]

 27%|██▋       | 1332/4959 [28:08<1:43:31,  1.71s/it]

 27%|██▋       | 1333/4959 [28:09<1:42:21,  1.69s/it]

 27%|██▋       | 1334/4959 [28:11<1:47:59,  1.79s/it]

 27%|██▋       | 1335/4959 [28:13<1:44:56,  1.74s/it]

 27%|██▋       | 1336/4959 [28:15<1:49:19,  1.81s/it]

 27%|██▋       | 1337/4959 [28:17<1:52:34,  1.86s/it]

 27%|██▋       | 1338/4959 [28:19<1:48:58,  1.81s/it]

 27%|██▋       | 1339/4959 [28:20<1:47:07,  1.78s/it]

 27%|██▋       | 1340/4959 [28:22<1:44:40,  1.74s/it]

 27%|██▋       | 1341/4959 [28:24<1:51:18,  1.85s/it]

 27%|██▋       | 1342/4959 [28:26<1:53:43,  1.89s/it]

 27%|██▋       | 1343/4959 [28:28<1:55:27,  1.92s/it]

 27%|██▋       | 1344/4959 [28:30<1:56:41,  1.94s/it]

 27%|██▋       | 1345/4959 [28:32<1:57:27,  1.95s/it]

 27%|██▋       | 1346/4959 [28:34<1:51:49,  1.86s/it]

 27%|██▋       | 1347/4959 [28:36<1:53:51,  1.89s/it]

 27%|██▋       | 1348/4959 [28:38<1:55:48,  1.92s/it]

 27%|██▋       | 1349/4959 [28:40<1:57:06,  1.95s/it]

 27%|██▋       | 1350/4959 [28:41<1:52:03,  1.86s/it]

 27%|██▋       | 1351/4959 [28:43<1:56:17,  1.93s/it]

 27%|██▋       | 1352/4959 [28:45<1:52:44,  1.88s/it]

 27%|██▋       | 1353/4959 [28:47<1:54:10,  1.90s/it]

 27%|██▋       | 1354/4959 [28:49<1:49:14,  1.82s/it]

 27%|██▋       | 1355/4959 [28:50<1:45:27,  1.76s/it]

 27%|██▋       | 1356/4959 [28:52<1:42:58,  1.71s/it]

 27%|██▋       | 1357/4959 [28:54<1:41:38,  1.69s/it]

 27%|██▋       | 1358/4959 [28:55<1:40:15,  1.67s/it]

 27%|██▋       | 1359/4959 [28:57<1:45:46,  1.76s/it]

 27%|██▋       | 1360/4959 [28:59<1:44:07,  1.74s/it]

 27%|██▋       | 1361/4959 [29:00<1:42:15,  1.71s/it]

 27%|██▋       | 1362/4959 [29:02<1:46:46,  1.78s/it]

 27%|██▋       | 1363/4959 [29:04<1:50:16,  1.84s/it]

 28%|██▊       | 1364/4959 [29:06<1:52:16,  1.87s/it]

 28%|██▊       | 1365/4959 [29:08<1:53:54,  1.90s/it]

 28%|██▊       | 1366/4959 [29:10<1:56:30,  1.95s/it]

 28%|██▊       | 1367/4959 [29:12<1:51:00,  1.85s/it]

 28%|██▊       | 1368/4959 [29:14<1:53:30,  1.90s/it]

 28%|██▊       | 1369/4959 [29:16<1:55:10,  1.93s/it]

 28%|██▊       | 1370/4959 [29:18<1:56:24,  1.95s/it]

 28%|██▊       | 1371/4959 [29:20<1:56:50,  1.95s/it]

 28%|██▊       | 1372/4959 [29:22<1:51:05,  1.86s/it]

 28%|██▊       | 1373/4959 [29:24<1:52:50,  1.89s/it]

 28%|██▊       | 1374/4959 [29:26<1:54:42,  1.92s/it]

 28%|██▊       | 1375/4959 [29:27<1:49:26,  1.83s/it]

 28%|██▊       | 1376/4959 [29:29<1:46:05,  1.78s/it]

 28%|██▊       | 1377/4959 [29:31<1:49:59,  1.84s/it]

 28%|██▊       | 1378/4959 [29:32<1:46:14,  1.78s/it]

 28%|██▊       | 1379/4959 [29:34<1:43:30,  1.73s/it]

 28%|██▊       | 1380/4959 [29:36<1:48:25,  1.82s/it]

 28%|██▊       | 1381/4959 [29:38<1:51:46,  1.87s/it]

 28%|██▊       | 1382/4959 [29:40<1:47:20,  1.80s/it]

 28%|██▊       | 1383/4959 [29:42<1:50:12,  1.85s/it]

 28%|██▊       | 1384/4959 [29:44<1:52:48,  1.89s/it]

 28%|██▊       | 1385/4959 [29:46<1:54:00,  1.91s/it]

 28%|██▊       | 1386/4959 [29:48<1:57:11,  1.97s/it]

 28%|██▊       | 1387/4959 [29:49<1:52:27,  1.89s/it]

 28%|██▊       | 1388/4959 [29:51<1:55:29,  1.94s/it]

 28%|██▊       | 1389/4959 [29:53<1:50:30,  1.86s/it]

 28%|██▊       | 1390/4959 [29:55<1:53:49,  1.91s/it]

 28%|██▊       | 1391/4959 [29:57<1:56:06,  1.95s/it]

 28%|██▊       | 1392/4959 [29:59<1:52:01,  1.88s/it]

 28%|██▊       | 1393/4959 [30:01<1:48:56,  1.83s/it]

 28%|██▊       | 1394/4959 [30:03<1:52:47,  1.90s/it]

 28%|██▊       | 1395/4959 [30:05<1:55:50,  1.95s/it]

 28%|██▊       | 1396/4959 [30:07<1:51:51,  1.88s/it]

 28%|██▊       | 1397/4959 [30:08<1:49:28,  1.84s/it]

 28%|██▊       | 1398/4959 [30:10<1:54:26,  1.93s/it]

 28%|██▊       | 1399/4959 [30:12<1:51:33,  1.88s/it]

 28%|██▊       | 1400/4959 [30:14<1:50:35,  1.86s/it]

 28%|██▊       | 1401/4959 [30:16<1:55:17,  1.94s/it]

 28%|██▊       | 1402/4959 [30:18<1:58:23,  2.00s/it]

 28%|██▊       | 1403/4959 [30:20<1:54:02,  1.92s/it]

 28%|██▊       | 1404/4959 [30:22<1:50:28,  1.86s/it]

 28%|██▊       | 1405/4959 [30:24<1:54:06,  1.93s/it]

 28%|██▊       | 1406/4959 [30:26<1:50:15,  1.86s/it]

 28%|██▊       | 1407/4959 [30:28<1:54:50,  1.94s/it]

 28%|██▊       | 1408/4959 [30:30<1:56:31,  1.97s/it]

 28%|██▊       | 1409/4959 [30:31<1:52:20,  1.90s/it]

 28%|██▊       | 1410/4959 [30:33<1:51:54,  1.89s/it]

 28%|██▊       | 1411/4959 [30:35<1:48:42,  1.84s/it]

 28%|██▊       | 1412/4959 [30:37<1:48:01,  1.83s/it]

 28%|██▊       | 1413/4959 [30:38<1:45:09,  1.78s/it]

 29%|██▊       | 1414/4959 [30:41<1:50:19,  1.87s/it]

 29%|██▊       | 1415/4959 [30:43<1:53:52,  1.93s/it]

 29%|██▊       | 1416/4959 [30:45<1:57:02,  1.98s/it]

 29%|██▊       | 1417/4959 [30:46<1:52:21,  1.90s/it]

 29%|██▊       | 1418/4959 [30:49<1:55:34,  1.96s/it]

 29%|██▊       | 1419/4959 [30:50<1:50:45,  1.88s/it]

 29%|██▊       | 1420/4959 [30:52<1:48:03,  1.83s/it]

 29%|██▊       | 1421/4959 [30:54<1:52:10,  1.90s/it]

 29%|██▊       | 1422/4959 [30:56<1:48:57,  1.85s/it]

 29%|██▊       | 1423/4959 [30:58<1:52:45,  1.91s/it]

 29%|██▊       | 1424/4959 [31:00<1:49:12,  1.85s/it]

 29%|██▊       | 1425/4959 [31:02<1:52:23,  1.91s/it]

 29%|██▉       | 1426/4959 [31:04<1:55:46,  1.97s/it]

 29%|██▉       | 1427/4959 [31:06<1:56:40,  1.98s/it]

 29%|██▉       | 1428/4959 [31:07<1:52:10,  1.91s/it]

 29%|██▉       | 1429/4959 [31:09<1:55:37,  1.97s/it]

 29%|██▉       | 1430/4959 [31:11<1:50:29,  1.88s/it]

 29%|██▉       | 1431/4959 [31:13<1:53:33,  1.93s/it]

 29%|██▉       | 1432/4959 [31:15<1:48:45,  1.85s/it]

 29%|██▉       | 1433/4959 [31:17<1:45:54,  1.80s/it]

 29%|██▉       | 1434/4959 [31:18<1:43:07,  1.76s/it]

 29%|██▉       | 1435/4959 [31:20<1:47:57,  1.84s/it]

 29%|██▉       | 1436/4959 [31:22<1:45:39,  1.80s/it]

 29%|██▉       | 1437/4959 [31:24<1:43:25,  1.76s/it]

 29%|██▉       | 1438/4959 [31:26<1:47:45,  1.84s/it]

 29%|██▉       | 1439/4959 [31:27<1:44:57,  1.79s/it]

 29%|██▉       | 1440/4959 [31:29<1:43:54,  1.77s/it]

 29%|██▉       | 1441/4959 [31:31<1:48:27,  1.85s/it]

 29%|██▉       | 1442/4959 [31:33<1:45:24,  1.80s/it]

 29%|██▉       | 1443/4959 [31:34<1:43:16,  1.76s/it]

 29%|██▉       | 1444/4959 [31:36<1:41:38,  1.74s/it]

 29%|██▉       | 1445/4959 [31:38<1:41:16,  1.73s/it]

 29%|██▉       | 1446/4959 [31:40<1:46:52,  1.83s/it]

 29%|██▉       | 1447/4959 [31:42<1:50:46,  1.89s/it]

 29%|██▉       | 1448/4959 [31:44<1:49:11,  1.87s/it]

 29%|██▉       | 1449/4959 [31:46<1:47:30,  1.84s/it]

 29%|██▉       | 1450/4959 [31:47<1:45:52,  1.81s/it]

 29%|██▉       | 1451/4959 [31:49<1:44:41,  1.79s/it]

 29%|██▉       | 1452/4959 [31:51<1:48:58,  1.86s/it]

 29%|██▉       | 1453/4959 [31:53<1:46:10,  1.82s/it]

 29%|██▉       | 1454/4959 [31:55<1:49:53,  1.88s/it]

 29%|██▉       | 1455/4959 [31:57<1:52:30,  1.93s/it]

 29%|██▉       | 1456/4959 [31:59<1:54:44,  1.97s/it]

 29%|██▉       | 1457/4959 [32:01<1:49:39,  1.88s/it]

 29%|██▉       | 1458/4959 [32:02<1:46:06,  1.82s/it]

 29%|██▉       | 1459/4959 [32:04<1:43:43,  1.78s/it]

 29%|██▉       | 1460/4959 [32:06<1:41:58,  1.75s/it]

 29%|██▉       | 1461/4959 [32:08<1:47:29,  1.84s/it]

 29%|██▉       | 1462/4959 [32:09<1:45:04,  1.80s/it]

 30%|██▉       | 1463/4959 [32:11<1:43:56,  1.78s/it]

 30%|██▉       | 1464/4959 [32:13<1:43:37,  1.78s/it]

 30%|██▉       | 1465/4959 [32:15<1:42:56,  1.77s/it]

 30%|██▉       | 1466/4959 [32:16<1:41:30,  1.74s/it]

 30%|██▉       | 1467/4959 [32:18<1:45:53,  1.82s/it]

 30%|██▉       | 1468/4959 [32:20<1:49:50,  1.89s/it]

 30%|██▉       | 1469/4959 [32:22<1:52:33,  1.94s/it]

 30%|██▉       | 1470/4959 [32:24<1:54:50,  1.97s/it]

 30%|██▉       | 1471/4959 [32:26<1:49:52,  1.89s/it]

 30%|██▉       | 1472/4959 [32:28<1:46:21,  1.83s/it]

 30%|██▉       | 1473/4959 [32:29<1:43:11,  1.78s/it]

 30%|██▉       | 1474/4959 [32:32<1:47:40,  1.85s/it]

 30%|██▉       | 1475/4959 [32:33<1:44:34,  1.80s/it]

 30%|██▉       | 1476/4959 [32:35<1:48:54,  1.88s/it]

 30%|██▉       | 1477/4959 [32:37<1:46:01,  1.83s/it]

 30%|██▉       | 1478/4959 [32:39<1:50:05,  1.90s/it]

 30%|██▉       | 1479/4959 [32:41<1:52:30,  1.94s/it]

 30%|██▉       | 1480/4959 [32:43<1:47:26,  1.85s/it]

 30%|██▉       | 1481/4959 [32:44<1:44:52,  1.81s/it]

 30%|██▉       | 1482/4959 [32:46<1:48:50,  1.88s/it]

 30%|██▉       | 1483/4959 [32:48<1:45:38,  1.82s/it]

 30%|██▉       | 1484/4959 [32:50<1:49:09,  1.88s/it]

 30%|██▉       | 1485/4959 [32:52<1:52:57,  1.95s/it]

 30%|██▉       | 1486/4959 [32:54<1:53:40,  1.96s/it]

 30%|██▉       | 1487/4959 [32:56<1:55:16,  1.99s/it]

 30%|███       | 1488/4959 [32:58<1:49:24,  1.89s/it]

 30%|███       | 1489/4959 [33:00<1:51:56,  1.94s/it]

 30%|███       | 1490/4959 [33:02<1:47:31,  1.86s/it]

 30%|███       | 1491/4959 [33:04<1:50:54,  1.92s/it]

 30%|███       | 1492/4959 [33:05<1:46:32,  1.84s/it]

 30%|███       | 1493/4959 [33:08<1:52:34,  1.95s/it]

 30%|███       | 1494/4959 [33:09<1:47:30,  1.86s/it]

 30%|███       | 1495/4959 [33:11<1:50:19,  1.91s/it]

 30%|███       | 1496/4959 [33:13<1:52:16,  1.95s/it]

 30%|███       | 1497/4959 [33:15<1:48:00,  1.87s/it]

 30%|███       | 1498/4959 [33:17<1:45:03,  1.82s/it]

 30%|███       | 1499/4959 [33:19<1:48:58,  1.89s/it]

 30%|███       | 1500/4959 [33:20<1:45:42,  1.83s/it]

 30%|███       | 1501/4959 [33:23<1:49:13,  1.90s/it]

 30%|███       | 1502/4959 [33:24<1:46:09,  1.84s/it]

 30%|███       | 1503/4959 [33:26<1:43:37,  1.80s/it]

 30%|███       | 1504/4959 [33:28<1:41:34,  1.76s/it]

 30%|███       | 1505/4959 [33:29<1:39:58,  1.74s/it]

 30%|███       | 1506/4959 [33:31<1:39:20,  1.73s/it]

 30%|███       | 1507/4959 [33:33<1:38:28,  1.71s/it]

 30%|███       | 1508/4959 [33:35<1:44:59,  1.83s/it]

 30%|███       | 1509/4959 [33:37<1:45:39,  1.84s/it]

 30%|███       | 1510/4959 [33:39<1:49:58,  1.91s/it]

 30%|███       | 1511/4959 [33:41<1:52:43,  1.96s/it]

 30%|███       | 1512/4959 [33:42<1:47:49,  1.88s/it]

 31%|███       | 1513/4959 [33:45<1:50:38,  1.93s/it]

 31%|███       | 1514/4959 [33:47<1:52:46,  1.96s/it]

 31%|███       | 1515/4959 [33:48<1:49:35,  1.91s/it]

 31%|███       | 1516/4959 [33:50<1:46:12,  1.85s/it]

 31%|███       | 1517/4959 [33:52<1:44:07,  1.81s/it]

 31%|███       | 1518/4959 [33:53<1:41:47,  1.77s/it]

 31%|███       | 1519/4959 [33:56<1:45:53,  1.85s/it]

 31%|███       | 1520/4959 [33:57<1:46:56,  1.87s/it]

 31%|███       | 1521/4959 [34:00<1:50:49,  1.93s/it]

 31%|███       | 1522/4959 [34:01<1:46:47,  1.86s/it]

 31%|███       | 1523/4959 [34:03<1:43:36,  1.81s/it]

 31%|███       | 1524/4959 [34:05<1:41:03,  1.77s/it]

 31%|███       | 1525/4959 [34:07<1:45:45,  1.85s/it]

 31%|███       | 1526/4959 [34:09<1:49:50,  1.92s/it]

 31%|███       | 1527/4959 [34:11<1:51:48,  1.95s/it]

 31%|███       | 1528/4959 [34:12<1:47:05,  1.87s/it]

 31%|███       | 1529/4959 [34:14<1:49:49,  1.92s/it]

 31%|███       | 1530/4959 [34:17<1:52:46,  1.97s/it]

 31%|███       | 1531/4959 [34:19<1:53:15,  1.98s/it]

 31%|███       | 1532/4959 [34:21<1:53:46,  1.99s/it]

 31%|███       | 1533/4959 [34:22<1:48:06,  1.89s/it]

 31%|███       | 1534/4959 [34:24<1:44:21,  1.83s/it]

 31%|███       | 1535/4959 [34:26<1:47:50,  1.89s/it]

 31%|███       | 1536/4959 [34:28<1:44:12,  1.83s/it]

 31%|███       | 1537/4959 [34:30<1:46:56,  1.87s/it]

 31%|███       | 1538/4959 [34:32<1:48:48,  1.91s/it]

 31%|███       | 1539/4959 [34:33<1:44:16,  1.83s/it]

 31%|███       | 1540/4959 [34:35<1:47:20,  1.88s/it]

 31%|███       | 1541/4959 [34:37<1:43:52,  1.82s/it]

 31%|███       | 1542/4959 [34:39<1:40:53,  1.77s/it]

 31%|███       | 1543/4959 [34:41<1:44:38,  1.84s/it]

 31%|███       | 1544/4959 [34:43<1:47:04,  1.88s/it]

 31%|███       | 1545/4959 [34:44<1:43:36,  1.82s/it]

 31%|███       | 1546/4959 [34:46<1:47:03,  1.88s/it]

 31%|███       | 1547/4959 [34:48<1:42:50,  1.81s/it]

 31%|███       | 1548/4959 [34:50<1:47:04,  1.88s/it]

 31%|███       | 1549/4959 [34:52<1:49:34,  1.93s/it]

 31%|███▏      | 1550/4959 [34:54<1:51:14,  1.96s/it]

 31%|███▏      | 1551/4959 [34:56<1:46:16,  1.87s/it]

 31%|███▏      | 1552/4959 [34:57<1:42:20,  1.80s/it]

 31%|███▏      | 1553/4959 [34:59<1:39:32,  1.75s/it]

 31%|███▏      | 1554/4959 [35:01<1:43:30,  1.82s/it]

 31%|███▏      | 1555/4959 [35:03<1:40:15,  1.77s/it]

 31%|███▏      | 1556/4959 [35:05<1:44:36,  1.84s/it]

 31%|███▏      | 1557/4959 [35:06<1:41:05,  1.78s/it]

 31%|███▏      | 1558/4959 [35:08<1:45:16,  1.86s/it]

 31%|███▏      | 1559/4959 [35:10<1:47:20,  1.89s/it]

 31%|███▏      | 1560/4959 [35:12<1:49:14,  1.93s/it]

 31%|███▏      | 1561/4959 [35:14<1:44:19,  1.84s/it]

 31%|███▏      | 1562/4959 [35:16<1:46:45,  1.89s/it]

 32%|███▏      | 1563/4959 [35:18<1:49:17,  1.93s/it]

 32%|███▏      | 1564/4959 [35:20<1:45:01,  1.86s/it]

 32%|███▏      | 1565/4959 [35:21<1:41:18,  1.79s/it]

 32%|███▏      | 1566/4959 [35:23<1:45:18,  1.86s/it]

 32%|███▏      | 1567/4959 [35:25<1:41:37,  1.80s/it]

 32%|███▏      | 1568/4959 [35:27<1:45:34,  1.87s/it]

 32%|███▏      | 1569/4959 [35:29<1:48:14,  1.92s/it]

 32%|███▏      | 1570/4959 [35:31<1:50:19,  1.95s/it]

 32%|███▏      | 1571/4959 [35:33<1:51:33,  1.98s/it]

 32%|███▏      | 1572/4959 [35:35<1:52:52,  2.00s/it]

 32%|███▏      | 1573/4959 [35:37<1:53:30,  2.01s/it]

 32%|███▏      | 1574/4959 [35:39<1:53:51,  2.02s/it]

 32%|███▏      | 1575/4959 [35:41<1:54:50,  2.04s/it]

 32%|███▏      | 1576/4959 [35:43<1:49:10,  1.94s/it]

 32%|███▏      | 1577/4959 [35:45<1:50:09,  1.95s/it]

 32%|███▏      | 1578/4959 [35:47<1:45:16,  1.87s/it]

 32%|███▏      | 1579/4959 [35:48<1:42:43,  1.82s/it]

 32%|███▏      | 1580/4959 [35:50<1:40:26,  1.78s/it]

 32%|███▏      | 1581/4959 [35:52<1:39:24,  1.77s/it]

 32%|███▏      | 1582/4959 [35:53<1:37:55,  1.74s/it]

 32%|███▏      | 1583/4959 [35:55<1:42:52,  1.83s/it]

 32%|███▏      | 1584/4959 [35:57<1:46:12,  1.89s/it]

 32%|███▏      | 1585/4959 [36:00<1:48:37,  1.93s/it]

 32%|███▏      | 1586/4959 [36:02<1:50:01,  1.96s/it]

 32%|███▏      | 1587/4959 [36:03<1:45:21,  1.87s/it]

 32%|███▏      | 1588/4959 [36:05<1:42:15,  1.82s/it]

 32%|███▏      | 1589/4959 [36:07<1:39:40,  1.77s/it]

 32%|███▏      | 1590/4959 [36:08<1:38:11,  1.75s/it]

 32%|███▏      | 1591/4959 [36:10<1:42:43,  1.83s/it]

 32%|███▏      | 1592/4959 [36:12<1:45:49,  1.89s/it]

 32%|███▏      | 1593/4959 [36:14<1:48:01,  1.93s/it]

 32%|███▏      | 1594/4959 [36:16<1:49:48,  1.96s/it]

 32%|███▏      | 1595/4959 [36:18<1:51:52,  2.00s/it]

 32%|███▏      | 1596/4959 [36:20<1:52:14,  2.00s/it]

 32%|███▏      | 1597/4959 [36:22<1:46:25,  1.90s/it]

 32%|███▏      | 1598/4959 [36:24<1:48:40,  1.94s/it]

 32%|███▏      | 1599/4959 [36:26<1:44:16,  1.86s/it]

 32%|███▏      | 1600/4959 [36:27<1:40:19,  1.79s/it]

 32%|███▏      | 1601/4959 [36:29<1:43:43,  1.85s/it]

 32%|███▏      | 1602/4959 [36:31<1:39:54,  1.79s/it]

 32%|███▏      | 1603/4959 [36:33<1:38:09,  1.75s/it]

 32%|███▏      | 1604/4959 [36:35<1:42:53,  1.84s/it]

 32%|███▏      | 1605/4959 [36:36<1:39:58,  1.79s/it]

 32%|███▏      | 1606/4959 [36:39<1:44:00,  1.86s/it]

 32%|███▏      | 1607/4959 [36:40<1:40:40,  1.80s/it]

 32%|███▏      | 1608/4959 [36:42<1:38:51,  1.77s/it]

 32%|███▏      | 1609/4959 [36:44<1:43:31,  1.85s/it]

 32%|███▏      | 1610/4959 [36:46<1:45:43,  1.89s/it]

 32%|███▏      | 1611/4959 [36:48<1:47:11,  1.92s/it]

 33%|███▎      | 1612/4959 [36:50<1:48:31,  1.95s/it]

 33%|███▎      | 1613/4959 [36:52<1:50:28,  1.98s/it]

 33%|███▎      | 1614/4959 [36:54<1:51:03,  1.99s/it]

 33%|███▎      | 1615/4959 [36:56<1:45:10,  1.89s/it]

 33%|███▎      | 1616/4959 [36:58<1:46:38,  1.91s/it]

 33%|███▎      | 1617/4959 [36:59<1:41:48,  1.83s/it]

 33%|███▎      | 1618/4959 [37:01<1:38:25,  1.77s/it]

 33%|███▎      | 1619/4959 [37:03<1:42:00,  1.83s/it]

 33%|███▎      | 1620/4959 [37:05<1:44:36,  1.88s/it]

 33%|███▎      | 1621/4959 [37:07<1:46:20,  1.91s/it]

 33%|███▎      | 1622/4959 [37:08<1:41:32,  1.83s/it]

 33%|███▎      | 1623/4959 [37:10<1:44:04,  1.87s/it]

 33%|███▎      | 1624/4959 [37:12<1:46:01,  1.91s/it]

 33%|███▎      | 1625/4959 [37:14<1:41:25,  1.83s/it]

 33%|███▎      | 1626/4959 [37:16<1:38:03,  1.77s/it]

 33%|███▎      | 1627/4959 [37:17<1:35:45,  1.72s/it]

 33%|███▎      | 1628/4959 [37:19<1:34:19,  1.70s/it]

 33%|███▎      | 1629/4959 [37:21<1:39:09,  1.79s/it]

 33%|███▎      | 1630/4959 [37:23<1:42:20,  1.84s/it]

 33%|███▎      | 1631/4959 [37:25<1:45:01,  1.89s/it]

 33%|███▎      | 1632/4959 [37:27<1:50:20,  1.99s/it]

 33%|███▎      | 1633/4959 [37:29<1:54:06,  2.06s/it]

 33%|███▎      | 1634/4959 [37:32<1:56:06,  2.10s/it]

 33%|███▎      | 1635/4959 [37:34<1:54:20,  2.06s/it]

 33%|███▎      | 1636/4959 [37:36<1:53:12,  2.04s/it]

 33%|███▎      | 1637/4959 [37:38<1:52:29,  2.03s/it]

 33%|███▎      | 1638/4959 [37:40<1:52:08,  2.03s/it]

 33%|███▎      | 1639/4959 [37:42<1:54:35,  2.07s/it]

 33%|███▎      | 1640/4959 [37:44<1:53:39,  2.05s/it]

 33%|███▎      | 1641/4959 [37:46<1:53:22,  2.05s/it]

 33%|███▎      | 1642/4959 [37:48<1:53:02,  2.04s/it]

 33%|███▎      | 1643/4959 [37:50<1:52:31,  2.04s/it]

 33%|███▎      | 1644/4959 [37:52<1:52:41,  2.04s/it]

 33%|███▎      | 1645/4959 [37:53<1:46:07,  1.92s/it]

 33%|███▎      | 1646/4959 [37:55<1:47:00,  1.94s/it]

 33%|███▎      | 1647/4959 [37:57<1:47:53,  1.95s/it]

 33%|███▎      | 1648/4959 [37:59<1:48:58,  1.97s/it]

 33%|███▎      | 1649/4959 [38:01<1:49:15,  1.98s/it]

 33%|███▎      | 1650/4959 [38:04<1:50:14,  2.00s/it]

 33%|███▎      | 1651/4959 [38:05<1:44:42,  1.90s/it]

 33%|███▎      | 1652/4959 [38:07<1:46:25,  1.93s/it]

 33%|███▎      | 1653/4959 [38:09<1:41:35,  1.84s/it]

 33%|███▎      | 1654/4959 [38:11<1:38:46,  1.79s/it]

 33%|███▎      | 1655/4959 [38:12<1:35:59,  1.74s/it]

 33%|███▎      | 1656/4959 [38:14<1:34:31,  1.72s/it]

 33%|███▎      | 1657/4959 [38:16<1:39:36,  1.81s/it]

 33%|███▎      | 1658/4959 [38:17<1:36:49,  1.76s/it]

 33%|███▎      | 1659/4959 [38:19<1:40:48,  1.83s/it]

 33%|███▎      | 1660/4959 [38:21<1:43:16,  1.88s/it]

 33%|███▎      | 1661/4959 [38:23<1:39:34,  1.81s/it]

 34%|███▎      | 1662/4959 [38:25<1:37:11,  1.77s/it]

 34%|███▎      | 1663/4959 [38:27<1:41:35,  1.85s/it]

 34%|███▎      | 1664/4959 [38:28<1:38:05,  1.79s/it]

 34%|███▎      | 1665/4959 [38:30<1:41:11,  1.84s/it]

 34%|███▎      | 1666/4959 [38:32<1:43:14,  1.88s/it]

 34%|███▎      | 1667/4959 [38:34<1:45:16,  1.92s/it]

 34%|███▎      | 1668/4959 [38:36<1:40:30,  1.83s/it]

 34%|███▎      | 1669/4959 [38:38<1:37:09,  1.77s/it]

 34%|███▎      | 1670/4959 [38:39<1:35:26,  1.74s/it]

 34%|███▎      | 1671/4959 [38:41<1:34:09,  1.72s/it]

 34%|███▎      | 1672/4959 [38:43<1:32:40,  1.69s/it]

 34%|███▎      | 1673/4959 [38:44<1:32:49,  1.70s/it]

 34%|███▍      | 1674/4959 [38:46<1:38:23,  1.80s/it]

 34%|███▍      | 1675/4959 [38:48<1:36:14,  1.76s/it]

 34%|███▍      | 1676/4959 [38:50<1:34:03,  1.72s/it]

 34%|███▍      | 1677/4959 [38:51<1:33:12,  1.70s/it]

 34%|███▍      | 1678/4959 [38:53<1:39:08,  1.81s/it]

 34%|███▍      | 1679/4959 [38:55<1:36:08,  1.76s/it]

 34%|███▍      | 1680/4959 [38:57<1:39:45,  1.83s/it]

 34%|███▍      | 1681/4959 [38:59<1:37:11,  1.78s/it]

 34%|███▍      | 1682/4959 [39:01<1:41:10,  1.85s/it]

 34%|███▍      | 1683/4959 [39:02<1:37:36,  1.79s/it]

 34%|███▍      | 1684/4959 [39:04<1:41:26,  1.86s/it]

 34%|███▍      | 1685/4959 [39:06<1:44:06,  1.91s/it]

 34%|███▍      | 1686/4959 [39:08<1:47:04,  1.96s/it]

 34%|███▍      | 1687/4959 [39:10<1:47:43,  1.98s/it]

 34%|███▍      | 1688/4959 [39:12<1:42:33,  1.88s/it]

 34%|███▍      | 1689/4959 [39:14<1:39:03,  1.82s/it]

 34%|███▍      | 1690/4959 [39:16<1:44:49,  1.92s/it]

 34%|███▍      | 1691/4959 [39:18<1:40:33,  1.85s/it]

 34%|███▍      | 1692/4959 [39:19<1:36:58,  1.78s/it]

 34%|███▍      | 1693/4959 [39:21<1:35:01,  1.75s/it]

 34%|███▍      | 1694/4959 [39:23<1:34:51,  1.74s/it]

 34%|███▍      | 1695/4959 [39:24<1:33:37,  1.72s/it]

 34%|███▍      | 1696/4959 [39:26<1:38:34,  1.81s/it]

 34%|███▍      | 1697/4959 [39:28<1:41:50,  1.87s/it]

 34%|███▍      | 1698/4959 [39:30<1:39:01,  1.82s/it]

 34%|███▍      | 1699/4959 [39:32<1:36:49,  1.78s/it]

 34%|███▍      | 1700/4959 [39:34<1:40:24,  1.85s/it]

 34%|███▍      | 1701/4959 [39:35<1:36:53,  1.78s/it]

 34%|███▍      | 1702/4959 [39:37<1:40:14,  1.85s/it]

 34%|███▍      | 1703/4959 [39:39<1:43:20,  1.90s/it]

 34%|███▍      | 1704/4959 [39:41<1:39:27,  1.83s/it]

 34%|███▍      | 1705/4959 [39:43<1:42:51,  1.90s/it]

 34%|███▍      | 1706/4959 [39:45<1:44:09,  1.92s/it]

 34%|███▍      | 1707/4959 [39:47<1:40:29,  1.85s/it]

 34%|███▍      | 1708/4959 [39:49<1:44:28,  1.93s/it]

 34%|███▍      | 1709/4959 [39:51<1:45:40,  1.95s/it]

 34%|███▍      | 1710/4959 [39:53<1:46:42,  1.97s/it]

 35%|███▍      | 1711/4959 [39:55<1:49:10,  2.02s/it]

 35%|███▍      | 1712/4959 [39:57<1:43:39,  1.92s/it]

 35%|███▍      | 1713/4959 [39:59<1:45:20,  1.95s/it]

 35%|███▍      | 1714/4959 [40:00<1:40:41,  1.86s/it]

 35%|███▍      | 1715/4959 [40:02<1:39:38,  1.84s/it]

 35%|███▍      | 1716/4959 [40:04<1:36:06,  1.78s/it]

 35%|███▍      | 1717/4959 [40:06<1:39:35,  1.84s/it]

 35%|███▍      | 1718/4959 [40:08<1:38:04,  1.82s/it]

 35%|███▍      | 1719/4959 [40:09<1:35:39,  1.77s/it]

 35%|███▍      | 1720/4959 [40:11<1:39:40,  1.85s/it]

 35%|███▍      | 1721/4959 [40:13<1:42:10,  1.89s/it]

 35%|███▍      | 1722/4959 [40:15<1:38:00,  1.82s/it]

 35%|███▍      | 1723/4959 [40:17<1:41:17,  1.88s/it]

 35%|███▍      | 1724/4959 [40:19<1:43:28,  1.92s/it]

 35%|███▍      | 1725/4959 [40:21<1:38:58,  1.84s/it]

 35%|███▍      | 1726/4959 [40:23<1:41:31,  1.88s/it]

 35%|███▍      | 1727/4959 [40:24<1:37:58,  1.82s/it]

 35%|███▍      | 1728/4959 [40:26<1:41:12,  1.88s/it]

 35%|███▍      | 1729/4959 [40:28<1:37:18,  1.81s/it]

 35%|███▍      | 1730/4959 [40:30<1:35:14,  1.77s/it]

 35%|███▍      | 1731/4959 [40:31<1:32:55,  1.73s/it]

 35%|███▍      | 1732/4959 [40:33<1:31:36,  1.70s/it]

 35%|███▍      | 1733/4959 [40:35<1:30:33,  1.68s/it]

 35%|███▍      | 1734/4959 [40:36<1:29:44,  1.67s/it]

 35%|███▍      | 1735/4959 [40:38<1:30:32,  1.68s/it]

 35%|███▌      | 1736/4959 [40:40<1:30:13,  1.68s/it]

 35%|███▌      | 1737/4959 [40:41<1:30:10,  1.68s/it]

 35%|███▌      | 1738/4959 [40:43<1:30:09,  1.68s/it]

 35%|███▌      | 1739/4959 [40:45<1:29:49,  1.67s/it]

 35%|███▌      | 1740/4959 [40:47<1:35:11,  1.77s/it]

 35%|███▌      | 1741/4959 [40:49<1:38:42,  1.84s/it]

 35%|███▌      | 1742/4959 [40:50<1:35:31,  1.78s/it]

 35%|███▌      | 1743/4959 [40:52<1:39:16,  1.85s/it]

 35%|███▌      | 1744/4959 [40:54<1:41:25,  1.89s/it]

 35%|███▌      | 1745/4959 [40:56<1:44:50,  1.96s/it]

 35%|███▌      | 1746/4959 [40:58<1:39:57,  1.87s/it]

 35%|███▌      | 1747/4959 [41:00<1:36:41,  1.81s/it]

 35%|███▌      | 1748/4959 [41:02<1:39:18,  1.86s/it]

 35%|███▌      | 1749/4959 [41:03<1:36:45,  1.81s/it]

 35%|███▌      | 1750/4959 [41:05<1:34:30,  1.77s/it]

 35%|███▌      | 1751/4959 [41:07<1:38:55,  1.85s/it]

 35%|███▌      | 1752/4959 [41:09<1:35:29,  1.79s/it]

 35%|███▌      | 1753/4959 [41:10<1:33:27,  1.75s/it]

 35%|███▌      | 1754/4959 [41:12<1:32:25,  1.73s/it]

 35%|███▌      | 1755/4959 [41:14<1:31:36,  1.72s/it]

 35%|███▌      | 1756/4959 [41:15<1:30:47,  1.70s/it]

 35%|███▌      | 1757/4959 [41:17<1:30:39,  1.70s/it]

 35%|███▌      | 1758/4959 [41:19<1:29:32,  1.68s/it]

 35%|███▌      | 1759/4959 [41:20<1:29:25,  1.68s/it]

 35%|███▌      | 1760/4959 [41:22<1:35:48,  1.80s/it]

 36%|███▌      | 1761/4959 [41:24<1:33:47,  1.76s/it]

 36%|███▌      | 1762/4959 [41:26<1:32:26,  1.73s/it]

 36%|███▌      | 1763/4959 [41:28<1:36:53,  1.82s/it]

 36%|███▌      | 1764/4959 [41:29<1:34:08,  1.77s/it]

 36%|███▌      | 1765/4959 [41:31<1:32:32,  1.74s/it]

 36%|███▌      | 1766/4959 [41:33<1:31:35,  1.72s/it]

 36%|███▌      | 1767/4959 [41:35<1:36:51,  1.82s/it]

 36%|███▌      | 1768/4959 [41:37<1:35:51,  1.80s/it]

 36%|███▌      | 1769/4959 [41:38<1:33:51,  1.77s/it]

 36%|███▌      | 1770/4959 [41:40<1:38:02,  1.84s/it]

 36%|███▌      | 1771/4959 [41:43<1:43:21,  1.95s/it]

 36%|███▌      | 1772/4959 [41:45<1:44:20,  1.96s/it]

 36%|███▌      | 1773/4959 [41:47<1:45:04,  1.98s/it]

 36%|███▌      | 1774/4959 [41:48<1:40:06,  1.89s/it]

 36%|███▌      | 1775/4959 [41:50<1:36:37,  1.82s/it]

 36%|███▌      | 1776/4959 [41:52<1:39:49,  1.88s/it]

 36%|███▌      | 1777/4959 [41:54<1:36:50,  1.83s/it]

 36%|███▌      | 1778/4959 [41:56<1:40:04,  1.89s/it]

 36%|███▌      | 1779/4959 [41:58<1:42:55,  1.94s/it]

 36%|███▌      | 1780/4959 [42:00<1:43:33,  1.95s/it]

 36%|███▌      | 1781/4959 [42:01<1:38:31,  1.86s/it]

 36%|███▌      | 1782/4959 [42:03<1:40:36,  1.90s/it]

 36%|███▌      | 1783/4959 [42:05<1:41:52,  1.92s/it]

 36%|███▌      | 1784/4959 [42:07<1:37:44,  1.85s/it]

 36%|███▌      | 1785/4959 [42:09<1:40:25,  1.90s/it]

 36%|███▌      | 1786/4959 [42:11<1:41:31,  1.92s/it]

 36%|███▌      | 1787/4959 [42:13<1:43:00,  1.95s/it]

 36%|███▌      | 1788/4959 [42:15<1:44:10,  1.97s/it]

 36%|███▌      | 1789/4959 [42:17<1:45:09,  1.99s/it]

 36%|███▌      | 1790/4959 [42:19<1:40:01,  1.89s/it]

 36%|███▌      | 1791/4959 [42:21<1:41:35,  1.92s/it]

 36%|███▌      | 1792/4959 [42:22<1:37:33,  1.85s/it]

 36%|███▌      | 1793/4959 [42:24<1:40:14,  1.90s/it]

 36%|███▌      | 1794/4959 [42:26<1:36:32,  1.83s/it]

 36%|███▌      | 1795/4959 [42:28<1:39:32,  1.89s/it]

 36%|███▌      | 1796/4959 [42:30<1:43:30,  1.96s/it]

 36%|███▌      | 1797/4959 [42:32<1:44:28,  1.98s/it]

 36%|███▋      | 1798/4959 [42:34<1:44:29,  1.98s/it]

 36%|███▋      | 1799/4959 [42:36<1:44:57,  1.99s/it]

 36%|███▋      | 1800/4959 [42:38<1:39:42,  1.89s/it]

 36%|███▋      | 1801/4959 [42:40<1:36:18,  1.83s/it]

 36%|███▋      | 1802/4959 [42:41<1:33:13,  1.77s/it]

 36%|███▋      | 1803/4959 [42:43<1:31:46,  1.74s/it]

 36%|███▋      | 1804/4959 [42:45<1:30:29,  1.72s/it]

 36%|███▋      | 1805/4959 [42:46<1:29:16,  1.70s/it]

 36%|███▋      | 1806/4959 [42:48<1:34:39,  1.80s/it]

 36%|███▋      | 1807/4959 [42:50<1:32:37,  1.76s/it]

 36%|███▋      | 1808/4959 [42:52<1:31:59,  1.75s/it]

 36%|███▋      | 1809/4959 [42:53<1:30:36,  1.73s/it]

 36%|███▋      | 1810/4959 [42:55<1:35:39,  1.82s/it]

 37%|███▋      | 1811/4959 [42:57<1:38:27,  1.88s/it]

 37%|███▋      | 1812/4959 [42:59<1:35:10,  1.81s/it]

 37%|███▋      | 1813/4959 [43:01<1:38:23,  1.88s/it]

 37%|███▋      | 1814/4959 [43:03<1:39:54,  1.91s/it]

 37%|███▋      | 1815/4959 [43:05<1:35:43,  1.83s/it]

 37%|███▋      | 1816/4959 [43:06<1:33:00,  1.78s/it]

 37%|███▋      | 1817/4959 [43:08<1:31:14,  1.74s/it]

 37%|███▋      | 1818/4959 [43:10<1:29:24,  1.71s/it]

 37%|███▋      | 1819/4959 [43:11<1:28:01,  1.68s/it]

 37%|███▋      | 1820/4959 [43:13<1:27:43,  1.68s/it]

 37%|███▋      | 1821/4959 [43:15<1:27:19,  1.67s/it]

 37%|███▋      | 1822/4959 [43:17<1:32:28,  1.77s/it]

 37%|███▋      | 1823/4959 [43:18<1:30:14,  1.73s/it]

 37%|███▋      | 1824/4959 [43:20<1:29:20,  1.71s/it]

 37%|███▋      | 1825/4959 [43:22<1:34:21,  1.81s/it]

 37%|███▋      | 1826/4959 [43:24<1:32:05,  1.76s/it]

 37%|███▋      | 1827/4959 [43:25<1:31:06,  1.75s/it]

 37%|███▋      | 1828/4959 [43:27<1:35:20,  1.83s/it]

 37%|███▋      | 1829/4959 [43:29<1:32:56,  1.78s/it]

 37%|███▋      | 1830/4959 [43:31<1:30:50,  1.74s/it]

 37%|███▋      | 1831/4959 [43:32<1:29:28,  1.72s/it]

 37%|███▋      | 1832/4959 [43:34<1:33:23,  1.79s/it]

 37%|███▋      | 1833/4959 [43:36<1:36:48,  1.86s/it]

 37%|███▋      | 1834/4959 [43:38<1:38:35,  1.89s/it]

 37%|███▋      | 1835/4959 [43:40<1:41:00,  1.94s/it]

 37%|███▋      | 1836/4959 [43:42<1:41:28,  1.95s/it]

 37%|███▋      | 1837/4959 [43:44<1:37:19,  1.87s/it]

 37%|███▋      | 1838/4959 [43:46<1:33:38,  1.80s/it]

 37%|███▋      | 1839/4959 [43:47<1:31:53,  1.77s/it]

 37%|███▋      | 1840/4959 [43:49<1:30:13,  1.74s/it]

 37%|███▋      | 1841/4959 [43:51<1:28:54,  1.71s/it]

 37%|███▋      | 1842/4959 [43:52<1:28:09,  1.70s/it]

 37%|███▋      | 1843/4959 [43:54<1:28:02,  1.70s/it]

 37%|███▋      | 1844/4959 [43:56<1:28:08,  1.70s/it]

 37%|███▋      | 1845/4959 [43:58<1:33:35,  1.80s/it]

 37%|███▋      | 1846/4959 [43:59<1:32:00,  1.77s/it]

 37%|███▋      | 1847/4959 [44:01<1:30:53,  1.75s/it]

 37%|███▋      | 1848/4959 [44:03<1:35:31,  1.84s/it]

 37%|███▋      | 1849/4959 [44:05<1:32:30,  1.78s/it]

 37%|███▋      | 1850/4959 [44:06<1:31:06,  1.76s/it]

 37%|███▋      | 1851/4959 [44:09<1:35:31,  1.84s/it]

 37%|███▋      | 1852/4959 [44:10<1:32:55,  1.79s/it]

 37%|███▋      | 1853/4959 [44:12<1:36:36,  1.87s/it]

 37%|███▋      | 1854/4959 [44:14<1:34:07,  1.82s/it]

 37%|███▋      | 1855/4959 [44:16<1:32:09,  1.78s/it]

 37%|███▋      | 1856/4959 [44:17<1:31:05,  1.76s/it]

 37%|███▋      | 1857/4959 [44:19<1:30:08,  1.74s/it]

 37%|███▋      | 1858/4959 [44:21<1:28:53,  1.72s/it]

 37%|███▋      | 1859/4959 [44:23<1:32:57,  1.80s/it]

 38%|███▊      | 1860/4959 [44:24<1:30:56,  1.76s/it]

 38%|███▊      | 1861/4959 [44:26<1:34:49,  1.84s/it]

 38%|███▊      | 1862/4959 [44:28<1:32:08,  1.79s/it]

 38%|███▊      | 1863/4959 [44:30<1:30:58,  1.76s/it]

 38%|███▊      | 1864/4959 [44:31<1:29:34,  1.74s/it]

 38%|███▊      | 1865/4959 [44:33<1:33:40,  1.82s/it]

 38%|███▊      | 1866/4959 [44:35<1:31:39,  1.78s/it]

 38%|███▊      | 1867/4959 [44:37<1:29:16,  1.73s/it]

 38%|███▊      | 1868/4959 [44:39<1:33:13,  1.81s/it]

 38%|███▊      | 1869/4959 [44:41<1:36:08,  1.87s/it]

 38%|███▊      | 1870/4959 [44:43<1:38:18,  1.91s/it]

 38%|███▊      | 1871/4959 [44:44<1:34:07,  1.83s/it]

 38%|███▊      | 1872/4959 [44:46<1:31:22,  1.78s/it]

 38%|███▊      | 1873/4959 [44:48<1:34:55,  1.85s/it]

 38%|███▊      | 1874/4959 [44:50<1:32:11,  1.79s/it]

 38%|███▊      | 1875/4959 [44:51<1:30:11,  1.75s/it]

 38%|███▊      | 1876/4959 [44:53<1:29:07,  1.73s/it]

 38%|███▊      | 1877/4959 [44:55<1:27:36,  1.71s/it]

 38%|███▊      | 1878/4959 [44:57<1:32:02,  1.79s/it]

 38%|███▊      | 1879/4959 [44:58<1:29:56,  1.75s/it]

 38%|███▊      | 1880/4959 [45:00<1:28:26,  1.72s/it]

 38%|███▊      | 1881/4959 [45:02<1:32:06,  1.80s/it]

 38%|███▊      | 1882/4959 [45:04<1:29:19,  1.74s/it]

 38%|███▊      | 1883/4959 [45:05<1:27:45,  1.71s/it]

 38%|███▊      | 1884/4959 [45:07<1:26:27,  1.69s/it]

 38%|███▊      | 1885/4959 [45:09<1:25:28,  1.67s/it]

 38%|███▊      | 1886/4959 [45:10<1:24:50,  1.66s/it]

 38%|███▊      | 1887/4959 [45:12<1:29:42,  1.75s/it]

 38%|███▊      | 1888/4959 [45:14<1:33:10,  1.82s/it]

 38%|███▊      | 1889/4959 [45:16<1:30:12,  1.76s/it]

 38%|███▊      | 1890/4959 [45:17<1:28:15,  1.73s/it]

 38%|███▊      | 1891/4959 [45:19<1:32:15,  1.80s/it]

 38%|███▊      | 1892/4959 [45:21<1:29:30,  1.75s/it]

 38%|███▊      | 1893/4959 [45:23<1:27:50,  1.72s/it]

 38%|███▊      | 1894/4959 [45:25<1:31:48,  1.80s/it]

 38%|███▊      | 1895/4959 [45:27<1:34:29,  1.85s/it]

 38%|███▊      | 1896/4959 [45:28<1:31:02,  1.78s/it]

 38%|███▊      | 1897/4959 [45:30<1:30:15,  1.77s/it]

 38%|███▊      | 1898/4959 [45:32<1:28:54,  1.74s/it]

 38%|███▊      | 1899/4959 [45:33<1:27:47,  1.72s/it]

 38%|███▊      | 1900/4959 [45:35<1:32:24,  1.81s/it]

 38%|███▊      | 1901/4959 [45:37<1:35:35,  1.88s/it]

 38%|███▊      | 1902/4959 [45:39<1:32:29,  1.82s/it]

 38%|███▊      | 1903/4959 [45:41<1:30:08,  1.77s/it]

 38%|███▊      | 1904/4959 [45:42<1:28:37,  1.74s/it]

 38%|███▊      | 1905/4959 [45:44<1:32:55,  1.83s/it]

 38%|███▊      | 1906/4959 [45:46<1:30:30,  1.78s/it]

 38%|███▊      | 1907/4959 [45:48<1:34:10,  1.85s/it]

 38%|███▊      | 1908/4959 [45:50<1:36:33,  1.90s/it]

 38%|███▊      | 1909/4959 [45:52<1:33:04,  1.83s/it]

 39%|███▊      | 1910/4959 [45:54<1:35:24,  1.88s/it]

 39%|███▊      | 1911/4959 [45:56<1:37:55,  1.93s/it]

 39%|███▊      | 1912/4959 [45:58<1:39:15,  1.95s/it]

 39%|███▊      | 1913/4959 [46:00<1:40:37,  1.98s/it]

 39%|███▊      | 1914/4959 [46:02<1:41:43,  2.00s/it]

 39%|███▊      | 1915/4959 [46:04<1:42:07,  2.01s/it]

 39%|███▊      | 1916/4959 [46:06<1:42:21,  2.02s/it]

 39%|███▊      | 1917/4959 [46:08<1:42:17,  2.02s/it]

 39%|███▊      | 1918/4959 [46:10<1:42:16,  2.02s/it]

 39%|███▊      | 1919/4959 [46:12<1:37:02,  1.92s/it]

 39%|███▊      | 1920/4959 [46:13<1:33:16,  1.84s/it]

 39%|███▊      | 1921/4959 [46:15<1:35:56,  1.89s/it]

 39%|███▉      | 1922/4959 [46:17<1:37:30,  1.93s/it]

 39%|███▉      | 1923/4959 [46:19<1:33:41,  1.85s/it]

 39%|███▉      | 1924/4959 [46:21<1:31:25,  1.81s/it]

 39%|███▉      | 1925/4959 [46:23<1:34:51,  1.88s/it]

 39%|███▉      | 1926/4959 [46:24<1:31:19,  1.81s/it]

 39%|███▉      | 1927/4959 [46:27<1:36:06,  1.90s/it]

 39%|███▉      | 1928/4959 [46:28<1:32:34,  1.83s/it]

 39%|███▉      | 1929/4959 [46:30<1:30:19,  1.79s/it]

 39%|███▉      | 1930/4959 [46:32<1:28:31,  1.75s/it]

 39%|███▉      | 1931/4959 [46:34<1:32:23,  1.83s/it]

 39%|███▉      | 1932/4959 [46:36<1:35:26,  1.89s/it]

 39%|███▉      | 1933/4959 [46:38<1:36:44,  1.92s/it]

 39%|███▉      | 1934/4959 [46:39<1:32:58,  1.84s/it]

 39%|███▉      | 1935/4959 [46:41<1:30:19,  1.79s/it]

 39%|███▉      | 1936/4959 [46:43<1:28:26,  1.76s/it]

 39%|███▉      | 1937/4959 [46:44<1:27:26,  1.74s/it]

 39%|███▉      | 1938/4959 [46:46<1:31:24,  1.82s/it]

 39%|███▉      | 1939/4959 [46:48<1:34:30,  1.88s/it]

 39%|███▉      | 1940/4959 [46:50<1:36:47,  1.92s/it]

 39%|███▉      | 1941/4959 [46:52<1:32:59,  1.85s/it]

 39%|███▉      | 1942/4959 [46:54<1:30:33,  1.80s/it]

 39%|███▉      | 1943/4959 [46:55<1:28:41,  1.76s/it]

 39%|███▉      | 1944/4959 [46:57<1:27:23,  1.74s/it]

 39%|███▉      | 1945/4959 [46:59<1:26:37,  1.72s/it]

 39%|███▉      | 1946/4959 [47:00<1:25:40,  1.71s/it]

 39%|███▉      | 1947/4959 [47:02<1:25:00,  1.69s/it]

 39%|███▉      | 1948/4959 [47:04<1:29:58,  1.79s/it]

 39%|███▉      | 1949/4959 [47:06<1:33:05,  1.86s/it]

 39%|███▉      | 1950/4959 [47:08<1:30:14,  1.80s/it]

 39%|███▉      | 1951/4959 [47:09<1:28:04,  1.76s/it]

 39%|███▉      | 1952/4959 [47:11<1:26:50,  1.73s/it]

 39%|███▉      | 1953/4959 [47:13<1:30:55,  1.81s/it]

 39%|███▉      | 1954/4959 [47:15<1:28:16,  1.76s/it]

 39%|███▉      | 1955/4959 [47:16<1:26:51,  1.73s/it]

 39%|███▉      | 1956/4959 [47:18<1:25:39,  1.71s/it]

 39%|███▉      | 1957/4959 [47:20<1:26:01,  1.72s/it]

 39%|███▉      | 1958/4959 [47:22<1:30:20,  1.81s/it]

 40%|███▉      | 1959/4959 [47:24<1:28:16,  1.77s/it]

 40%|███▉      | 1960/4959 [47:26<1:31:42,  1.83s/it]

 40%|███▉      | 1961/4959 [47:28<1:35:03,  1.90s/it]

 40%|███▉      | 1962/4959 [47:29<1:31:30,  1.83s/it]

 40%|███▉      | 1963/4959 [47:31<1:34:21,  1.89s/it]

 40%|███▉      | 1964/4959 [47:33<1:36:26,  1.93s/it]

 40%|███▉      | 1965/4959 [47:35<1:37:22,  1.95s/it]

 40%|███▉      | 1966/4959 [47:37<1:37:57,  1.96s/it]

 40%|███▉      | 1967/4959 [47:39<1:39:02,  1.99s/it]

 40%|███▉      | 1968/4959 [47:41<1:39:10,  1.99s/it]

 40%|███▉      | 1969/4959 [47:43<1:34:09,  1.89s/it]

 40%|███▉      | 1970/4959 [47:45<1:35:28,  1.92s/it]

 40%|███▉      | 1971/4959 [47:47<1:31:19,  1.83s/it]

 40%|███▉      | 1972/4959 [47:48<1:28:21,  1.77s/it]

 40%|███▉      | 1973/4959 [47:50<1:31:15,  1.83s/it]

 40%|███▉      | 1974/4959 [47:52<1:33:20,  1.88s/it]

 40%|███▉      | 1975/4959 [47:54<1:29:46,  1.81s/it]

 40%|███▉      | 1976/4959 [47:56<1:33:09,  1.87s/it]

 40%|███▉      | 1977/4959 [47:58<1:29:51,  1.81s/it]

 40%|███▉      | 1978/4959 [48:00<1:32:36,  1.86s/it]

 40%|███▉      | 1979/4959 [48:01<1:29:15,  1.80s/it]

 40%|███▉      | 1980/4959 [48:03<1:32:28,  1.86s/it]

 40%|███▉      | 1981/4959 [48:05<1:34:38,  1.91s/it]

 40%|███▉      | 1982/4959 [48:07<1:31:04,  1.84s/it]

 40%|███▉      | 1983/4959 [48:09<1:33:47,  1.89s/it]

 40%|████      | 1984/4959 [48:11<1:35:46,  1.93s/it]

 40%|████      | 1985/4959 [48:13<1:36:52,  1.95s/it]

 40%|████      | 1986/4959 [48:15<1:37:18,  1.96s/it]

 40%|████      | 1987/4959 [48:17<1:33:49,  1.89s/it]

 40%|████      | 1988/4959 [48:18<1:30:00,  1.82s/it]

 40%|████      | 1989/4959 [48:20<1:27:17,  1.76s/it]

 40%|████      | 1990/4959 [48:22<1:30:46,  1.83s/it]

 40%|████      | 1991/4959 [48:24<1:27:45,  1.77s/it]

 40%|████      | 1992/4959 [48:25<1:25:36,  1.73s/it]

 40%|████      | 1993/4959 [48:27<1:24:05,  1.70s/it]

 40%|████      | 1994/4959 [48:29<1:28:15,  1.79s/it]

 40%|████      | 1995/4959 [48:30<1:25:58,  1.74s/it]

 40%|████      | 1996/4959 [48:32<1:24:56,  1.72s/it]

 40%|████      | 1997/4959 [48:34<1:23:55,  1.70s/it]

 40%|████      | 1998/4959 [48:36<1:27:58,  1.78s/it]

 40%|████      | 1999/4959 [48:37<1:26:32,  1.75s/it]

 40%|████      | 2000/4959 [48:39<1:24:47,  1.72s/it]

 40%|████      | 2001/4959 [48:41<1:29:06,  1.81s/it]

 40%|████      | 2002/4959 [48:43<1:26:45,  1.76s/it]

 40%|████      | 2003/4959 [48:44<1:25:44,  1.74s/it]

 40%|████      | 2004/4959 [48:46<1:29:30,  1.82s/it]

 40%|████      | 2005/4959 [48:48<1:32:31,  1.88s/it]

 40%|████      | 2006/4959 [48:50<1:34:42,  1.92s/it]

 40%|████      | 2007/4959 [48:52<1:31:04,  1.85s/it]

 40%|████      | 2008/4959 [48:54<1:28:19,  1.80s/it]

 41%|████      | 2009/4959 [48:55<1:26:32,  1.76s/it]

 41%|████      | 2010/4959 [48:57<1:25:36,  1.74s/it]

 41%|████      | 2011/4959 [48:59<1:23:54,  1.71s/it]

 41%|████      | 2012/4959 [49:01<1:27:55,  1.79s/it]

 41%|████      | 2013/4959 [49:02<1:26:12,  1.76s/it]

 41%|████      | 2014/4959 [49:04<1:26:23,  1.76s/it]

 41%|████      | 2015/4959 [49:06<1:25:18,  1.74s/it]

 41%|████      | 2016/4959 [49:08<1:24:18,  1.72s/it]

 41%|████      | 2017/4959 [49:10<1:28:10,  1.80s/it]

 41%|████      | 2018/4959 [49:12<1:31:17,  1.86s/it]

 41%|████      | 2019/4959 [49:13<1:29:22,  1.82s/it]

 41%|████      | 2020/4959 [49:15<1:27:11,  1.78s/it]

 41%|████      | 2021/4959 [49:17<1:25:29,  1.75s/it]

 41%|████      | 2022/4959 [49:19<1:29:10,  1.82s/it]

 41%|████      | 2023/4959 [49:20<1:27:11,  1.78s/it]

 41%|████      | 2024/4959 [49:22<1:30:48,  1.86s/it]

 41%|████      | 2025/4959 [49:24<1:28:06,  1.80s/it]

 41%|████      | 2026/4959 [49:26<1:26:08,  1.76s/it]

 41%|████      | 2027/4959 [49:27<1:24:47,  1.74s/it]

 41%|████      | 2028/4959 [49:29<1:23:49,  1.72s/it]

 41%|████      | 2029/4959 [49:31<1:26:09,  1.76s/it]

 41%|████      | 2030/4959 [49:33<1:24:41,  1.73s/it]

 41%|████      | 2031/4959 [49:35<1:29:25,  1.83s/it]

 41%|████      | 2032/4959 [49:36<1:27:13,  1.79s/it]

 41%|████      | 2033/4959 [49:38<1:25:21,  1.75s/it]

 41%|████      | 2034/4959 [49:40<1:29:18,  1.83s/it]

 41%|████      | 2035/4959 [49:42<1:31:51,  1.88s/it]

 41%|████      | 2036/4959 [49:44<1:28:25,  1.82s/it]

 41%|████      | 2037/4959 [49:45<1:26:42,  1.78s/it]

 41%|████      | 2038/4959 [49:47<1:30:06,  1.85s/it]

 41%|████      | 2039/4959 [49:49<1:32:46,  1.91s/it]

 41%|████      | 2040/4959 [49:51<1:29:24,  1.84s/it]

 41%|████      | 2041/4959 [49:53<1:26:33,  1.78s/it]

 41%|████      | 2042/4959 [49:55<1:29:35,  1.84s/it]

 41%|████      | 2043/4959 [49:56<1:27:30,  1.80s/it]

 41%|████      | 2044/4959 [49:59<1:33:40,  1.93s/it]

 41%|████      | 2045/4959 [50:01<1:34:45,  1.95s/it]

 41%|████▏     | 2046/4959 [50:03<1:35:29,  1.97s/it]

 41%|████▏     | 2047/4959 [50:05<1:38:42,  2.03s/it]

 41%|████▏     | 2048/4959 [50:07<1:32:56,  1.92s/it]

 41%|████▏     | 2049/4959 [50:09<1:34:30,  1.95s/it]

 41%|████▏     | 2050/4959 [50:10<1:30:07,  1.86s/it]

 41%|████▏     | 2051/4959 [50:12<1:32:43,  1.91s/it]

 41%|████▏     | 2052/4959 [50:14<1:33:40,  1.93s/it]

 41%|████▏     | 2053/4959 [50:16<1:34:52,  1.96s/it]

 41%|████▏     | 2054/4959 [50:18<1:30:35,  1.87s/it]

 41%|████▏     | 2055/4959 [50:20<1:27:48,  1.81s/it]

 41%|████▏     | 2056/4959 [50:21<1:26:29,  1.79s/it]

 41%|████▏     | 2057/4959 [50:23<1:29:54,  1.86s/it]

 42%|████▏     | 2058/4959 [50:25<1:27:10,  1.80s/it]

 42%|████▏     | 2059/4959 [50:27<1:24:59,  1.76s/it]

 42%|████▏     | 2060/4959 [50:28<1:23:47,  1.73s/it]

 42%|████▏     | 2061/4959 [50:30<1:22:54,  1.72s/it]

 42%|████▏     | 2062/4959 [50:32<1:27:20,  1.81s/it]

 42%|████▏     | 2063/4959 [50:34<1:24:47,  1.76s/it]

 42%|████▏     | 2064/4959 [50:36<1:28:05,  1.83s/it]

 42%|████▏     | 2065/4959 [50:37<1:25:46,  1.78s/it]

 42%|████▏     | 2066/4959 [50:39<1:23:46,  1.74s/it]

 42%|████▏     | 2067/4959 [50:41<1:22:35,  1.71s/it]

 42%|████▏     | 2068/4959 [50:42<1:22:04,  1.70s/it]

 42%|████▏     | 2069/4959 [50:44<1:21:50,  1.70s/it]

 42%|████▏     | 2070/4959 [50:46<1:26:26,  1.80s/it]

 42%|████▏     | 2071/4959 [50:48<1:24:22,  1.75s/it]

 42%|████▏     | 2072/4959 [50:50<1:27:42,  1.82s/it]

 42%|████▏     | 2073/4959 [50:52<1:32:05,  1.91s/it]

 42%|████▏     | 2074/4959 [50:54<1:33:59,  1.95s/it]

 42%|████▏     | 2075/4959 [50:56<1:35:30,  1.99s/it]

 42%|████▏     | 2076/4959 [50:58<1:36:37,  2.01s/it]

 42%|████▏     | 2077/4959 [51:00<1:31:21,  1.90s/it]

 42%|████▏     | 2078/4959 [51:01<1:28:04,  1.83s/it]

 42%|████▏     | 2079/4959 [51:03<1:25:19,  1.78s/it]

 42%|████▏     | 2080/4959 [51:05<1:24:41,  1.76s/it]

 42%|████▏     | 2081/4959 [51:06<1:23:21,  1.74s/it]

 42%|████▏     | 2082/4959 [51:08<1:27:31,  1.83s/it]

 42%|████▏     | 2083/4959 [51:10<1:30:31,  1.89s/it]

 42%|████▏     | 2084/4959 [51:12<1:32:33,  1.93s/it]

 42%|████▏     | 2085/4959 [51:14<1:33:40,  1.96s/it]

 42%|████▏     | 2086/4959 [51:16<1:29:32,  1.87s/it]

 42%|████▏     | 2087/4959 [51:18<1:26:26,  1.81s/it]

 42%|████▏     | 2088/4959 [51:20<1:28:54,  1.86s/it]

 42%|████▏     | 2089/4959 [51:22<1:31:22,  1.91s/it]

 42%|████▏     | 2090/4959 [51:23<1:27:57,  1.84s/it]

 42%|████▏     | 2091/4959 [51:25<1:30:25,  1.89s/it]

 42%|████▏     | 2092/4959 [51:27<1:31:55,  1.92s/it]

 42%|████▏     | 2093/4959 [51:29<1:28:32,  1.85s/it]

 42%|████▏     | 2094/4959 [51:31<1:30:54,  1.90s/it]

 42%|████▏     | 2095/4959 [51:33<1:32:35,  1.94s/it]

 42%|████▏     | 2096/4959 [51:35<1:28:35,  1.86s/it]

 42%|████▏     | 2097/4959 [51:37<1:25:58,  1.80s/it]

 42%|████▏     | 2098/4959 [51:39<1:29:15,  1.87s/it]

 42%|████▏     | 2099/4959 [51:40<1:26:27,  1.81s/it]

 42%|████▏     | 2100/4959 [51:42<1:24:24,  1.77s/it]

 42%|████▏     | 2101/4959 [51:44<1:23:07,  1.75s/it]

 42%|████▏     | 2102/4959 [51:45<1:22:06,  1.72s/it]

 42%|████▏     | 2103/4959 [51:47<1:22:13,  1.73s/it]

 42%|████▏     | 2104/4959 [51:49<1:26:23,  1.82s/it]

 42%|████▏     | 2105/4959 [51:51<1:23:57,  1.76s/it]

 42%|████▏     | 2106/4959 [51:53<1:27:26,  1.84s/it]

 42%|████▏     | 2107/4959 [51:55<1:29:37,  1.89s/it]

 43%|████▎     | 2108/4959 [51:57<1:31:33,  1.93s/it]

 43%|████▎     | 2109/4959 [51:58<1:28:08,  1.86s/it]

 43%|████▎     | 2110/4959 [52:00<1:31:06,  1.92s/it]

 43%|████▎     | 2111/4959 [52:02<1:27:13,  1.84s/it]

 43%|████▎     | 2112/4959 [52:04<1:29:58,  1.90s/it]

 43%|████▎     | 2113/4959 [52:06<1:27:36,  1.85s/it]

 43%|████▎     | 2114/4959 [52:08<1:30:08,  1.90s/it]

 43%|████▎     | 2115/4959 [52:10<1:26:51,  1.83s/it]

 43%|████▎     | 2116/4959 [52:11<1:24:51,  1.79s/it]

 43%|████▎     | 2117/4959 [52:13<1:23:16,  1.76s/it]

 43%|████▎     | 2118/4959 [52:15<1:27:12,  1.84s/it]

 43%|████▎     | 2119/4959 [52:17<1:24:53,  1.79s/it]

 43%|████▎     | 2120/4959 [52:19<1:28:30,  1.87s/it]

 43%|████▎     | 2121/4959 [52:20<1:25:13,  1.80s/it]

 43%|████▎     | 2122/4959 [52:22<1:23:22,  1.76s/it]

 43%|████▎     | 2123/4959 [52:24<1:27:19,  1.85s/it]

 43%|████▎     | 2124/4959 [52:26<1:25:14,  1.80s/it]

 43%|████▎     | 2125/4959 [52:27<1:23:16,  1.76s/it]

 43%|████▎     | 2126/4959 [52:29<1:22:01,  1.74s/it]

 43%|████▎     | 2127/4959 [52:31<1:21:22,  1.72s/it]

 43%|████▎     | 2128/4959 [52:33<1:20:40,  1.71s/it]

 43%|████▎     | 2129/4959 [52:35<1:25:06,  1.80s/it]

 43%|████▎     | 2130/4959 [52:36<1:23:14,  1.77s/it]

 43%|████▎     | 2131/4959 [52:38<1:22:03,  1.74s/it]

 43%|████▎     | 2132/4959 [52:40<1:21:30,  1.73s/it]

 43%|████▎     | 2133/4959 [52:41<1:20:43,  1.71s/it]

 43%|████▎     | 2134/4959 [52:43<1:20:12,  1.70s/it]

 43%|████▎     | 2135/4959 [52:45<1:19:27,  1.69s/it]

 43%|████▎     | 2136/4959 [52:47<1:24:21,  1.79s/it]

 43%|████▎     | 2137/4959 [52:48<1:22:52,  1.76s/it]

 43%|████▎     | 2138/4959 [52:50<1:26:36,  1.84s/it]

 43%|████▎     | 2139/4959 [52:52<1:29:13,  1.90s/it]

 43%|████▎     | 2140/4959 [52:54<1:31:20,  1.94s/it]

 43%|████▎     | 2141/4959 [52:56<1:28:55,  1.89s/it]

 43%|████▎     | 2142/4959 [52:58<1:30:27,  1.93s/it]

 43%|████▎     | 2143/4959 [53:00<1:26:56,  1.85s/it]

 43%|████▎     | 2144/4959 [53:02<1:29:17,  1.90s/it]

 43%|████▎     | 2145/4959 [53:04<1:31:03,  1.94s/it]

 43%|████▎     | 2146/4959 [53:06<1:32:00,  1.96s/it]

 43%|████▎     | 2147/4959 [53:08<1:32:43,  1.98s/it]

 43%|████▎     | 2148/4959 [53:10<1:28:58,  1.90s/it]

 43%|████▎     | 2149/4959 [53:12<1:31:12,  1.95s/it]

 43%|████▎     | 2150/4959 [53:14<1:32:30,  1.98s/it]

 43%|████▎     | 2151/4959 [53:16<1:33:30,  2.00s/it]

 43%|████▎     | 2152/4959 [53:18<1:29:05,  1.90s/it]

 43%|████▎     | 2153/4959 [53:20<1:30:45,  1.94s/it]

 43%|████▎     | 2154/4959 [53:21<1:27:10,  1.86s/it]

 43%|████▎     | 2155/4959 [53:23<1:24:34,  1.81s/it]

 43%|████▎     | 2156/4959 [53:25<1:23:23,  1.79s/it]

 43%|████▎     | 2157/4959 [53:27<1:26:38,  1.86s/it]

 44%|████▎     | 2158/4959 [53:29<1:29:12,  1.91s/it]

 44%|████▎     | 2159/4959 [53:31<1:30:52,  1.95s/it]

 44%|████▎     | 2160/4959 [53:33<1:31:59,  1.97s/it]

 44%|████▎     | 2161/4959 [53:34<1:27:51,  1.88s/it]

 44%|████▎     | 2162/4959 [53:36<1:25:02,  1.82s/it]

 44%|████▎     | 2163/4959 [53:38<1:22:58,  1.78s/it]

 44%|████▎     | 2164/4959 [53:40<1:21:41,  1.75s/it]

 44%|████▎     | 2165/4959 [53:42<1:25:27,  1.84s/it]

 44%|████▎     | 2166/4959 [53:43<1:23:11,  1.79s/it]

 44%|████▎     | 2167/4959 [53:45<1:26:42,  1.86s/it]

 44%|████▎     | 2168/4959 [53:47<1:24:25,  1.81s/it]

 44%|████▎     | 2169/4959 [53:49<1:27:27,  1.88s/it]

 44%|████▍     | 2170/4959 [53:51<1:29:44,  1.93s/it]

 44%|████▍     | 2171/4959 [53:53<1:26:17,  1.86s/it]

 44%|████▍     | 2172/4959 [53:54<1:23:52,  1.81s/it]

 44%|████▍     | 2173/4959 [53:57<1:29:00,  1.92s/it]

 44%|████▍     | 2174/4959 [53:58<1:26:13,  1.86s/it]

 44%|████▍     | 2175/4959 [54:00<1:23:49,  1.81s/it]

 44%|████▍     | 2176/4959 [54:02<1:21:19,  1.75s/it]

 44%|████▍     | 2177/4959 [54:03<1:20:37,  1.74s/it]

 44%|████▍     | 2178/4959 [54:05<1:25:20,  1.84s/it]

 44%|████▍     | 2179/4959 [54:07<1:23:36,  1.80s/it]

 44%|████▍     | 2180/4959 [54:09<1:27:18,  1.88s/it]

 44%|████▍     | 2181/4959 [54:11<1:24:48,  1.83s/it]

 44%|████▍     | 2182/4959 [54:13<1:23:01,  1.79s/it]

 44%|████▍     | 2183/4959 [54:14<1:21:52,  1.77s/it]

 44%|████▍     | 2184/4959 [54:16<1:25:47,  1.86s/it]

 44%|████▍     | 2185/4959 [54:18<1:28:37,  1.92s/it]

 44%|████▍     | 2186/4959 [54:20<1:26:05,  1.86s/it]

 44%|████▍     | 2187/4959 [54:22<1:23:58,  1.82s/it]

 44%|████▍     | 2188/4959 [54:24<1:22:26,  1.79s/it]

 44%|████▍     | 2189/4959 [54:25<1:21:27,  1.76s/it]

 44%|████▍     | 2190/4959 [54:27<1:20:28,  1.74s/it]

 44%|████▍     | 2191/4959 [54:29<1:24:39,  1.84s/it]

 44%|████▍     | 2192/4959 [54:31<1:22:50,  1.80s/it]

 44%|████▍     | 2193/4959 [54:32<1:21:36,  1.77s/it]

 44%|████▍     | 2194/4959 [54:35<1:25:36,  1.86s/it]

 44%|████▍     | 2195/4959 [54:37<1:28:32,  1.92s/it]

 44%|████▍     | 2196/4959 [54:38<1:25:37,  1.86s/it]

 44%|████▍     | 2197/4959 [54:40<1:28:17,  1.92s/it]

 44%|████▍     | 2198/4959 [54:42<1:25:35,  1.86s/it]

 44%|████▍     | 2199/4959 [54:44<1:23:29,  1.82s/it]

 44%|████▍     | 2200/4959 [54:46<1:22:16,  1.79s/it]

 44%|████▍     | 2201/4959 [54:47<1:21:13,  1.77s/it]

 44%|████▍     | 2202/4959 [54:49<1:20:21,  1.75s/it]

 44%|████▍     | 2203/4959 [54:51<1:20:11,  1.75s/it]

 44%|████▍     | 2204/4959 [54:53<1:25:09,  1.85s/it]

 44%|████▍     | 2205/4959 [54:55<1:27:51,  1.91s/it]

 44%|████▍     | 2206/4959 [54:57<1:29:35,  1.95s/it]

 45%|████▍     | 2207/4959 [54:59<1:30:58,  1.98s/it]

 45%|████▍     | 2208/4959 [55:01<1:32:09,  2.01s/it]

 45%|████▍     | 2209/4959 [55:03<1:32:48,  2.02s/it]

 45%|████▍     | 2210/4959 [55:05<1:33:14,  2.03s/it]

 45%|████▍     | 2211/4959 [55:07<1:33:26,  2.04s/it]

 45%|████▍     | 2212/4959 [55:09<1:33:29,  2.04s/it]

 45%|████▍     | 2213/4959 [55:11<1:34:04,  2.06s/it]

 45%|████▍     | 2214/4959 [55:13<1:29:17,  1.95s/it]

 45%|████▍     | 2215/4959 [55:15<1:31:00,  1.99s/it]

 45%|████▍     | 2216/4959 [55:17<1:27:35,  1.92s/it]

 45%|████▍     | 2217/4959 [55:19<1:24:36,  1.85s/it]

 45%|████▍     | 2218/4959 [55:20<1:22:38,  1.81s/it]

 45%|████▍     | 2219/4959 [55:22<1:21:22,  1.78s/it]

 45%|████▍     | 2220/4959 [55:24<1:20:33,  1.76s/it]

 45%|████▍     | 2221/4959 [55:26<1:24:49,  1.86s/it]

 45%|████▍     | 2222/4959 [55:28<1:28:39,  1.94s/it]

 45%|████▍     | 2223/4959 [55:30<1:30:33,  1.99s/it]

 45%|████▍     | 2224/4959 [55:32<1:32:15,  2.02s/it]

 45%|████▍     | 2225/4959 [55:34<1:32:45,  2.04s/it]

 45%|████▍     | 2226/4959 [55:36<1:28:51,  1.95s/it]

 45%|████▍     | 2227/4959 [55:38<1:25:33,  1.88s/it]

 45%|████▍     | 2228/4959 [55:40<1:28:34,  1.95s/it]

 45%|████▍     | 2229/4959 [55:42<1:30:47,  2.00s/it]

 45%|████▍     | 2230/4959 [55:44<1:26:51,  1.91s/it]

 45%|████▍     | 2231/4959 [55:45<1:24:53,  1.87s/it]

 45%|████▌     | 2232/4959 [55:47<1:24:01,  1.85s/it]

 45%|████▌     | 2233/4959 [55:49<1:27:11,  1.92s/it]

 45%|████▌     | 2234/4959 [55:51<1:30:47,  2.00s/it]

 45%|████▌     | 2235/4959 [55:53<1:26:45,  1.91s/it]

 45%|████▌     | 2236/4959 [55:55<1:28:55,  1.96s/it]

 45%|████▌     | 2237/4959 [55:57<1:30:23,  1.99s/it]

 45%|████▌     | 2238/4959 [55:59<1:32:45,  2.05s/it]

 45%|████▌     | 2239/4959 [56:02<1:32:48,  2.05s/it]

 45%|████▌     | 2240/4959 [56:03<1:28:05,  1.94s/it]

 45%|████▌     | 2241/4959 [56:05<1:30:19,  1.99s/it]

 45%|████▌     | 2242/4959 [56:08<1:32:58,  2.05s/it]

 45%|████▌     | 2243/4959 [56:10<1:33:38,  2.07s/it]

 45%|████▌     | 2244/4959 [56:12<1:33:27,  2.07s/it]

 45%|████▌     | 2245/4959 [56:13<1:28:36,  1.96s/it]

 45%|████▌     | 2246/4959 [56:16<1:30:51,  2.01s/it]

 45%|████▌     | 2247/4959 [56:17<1:26:29,  1.91s/it]

 45%|████▌     | 2248/4959 [56:19<1:23:38,  1.85s/it]

 45%|████▌     | 2249/4959 [56:21<1:26:08,  1.91s/it]

 45%|████▌     | 2250/4959 [56:23<1:28:17,  1.96s/it]

 45%|████▌     | 2251/4959 [56:25<1:30:06,  2.00s/it]

 45%|████▌     | 2252/4959 [56:27<1:33:29,  2.07s/it]

 45%|████▌     | 2253/4959 [56:29<1:32:57,  2.06s/it]

 45%|████▌     | 2254/4959 [56:31<1:33:30,  2.07s/it]

 45%|████▌     | 2255/4959 [56:34<1:33:04,  2.07s/it]

 45%|████▌     | 2256/4959 [56:36<1:32:30,  2.05s/it]

 46%|████▌     | 2257/4959 [56:38<1:33:39,  2.08s/it]

 46%|████▌     | 2258/4959 [56:39<1:29:09,  1.98s/it]

 46%|████▌     | 2259/4959 [56:41<1:30:00,  2.00s/it]

 46%|████▌     | 2260/4959 [56:43<1:25:49,  1.91s/it]

 46%|████▌     | 2261/4959 [56:45<1:28:23,  1.97s/it]

 46%|████▌     | 2262/4959 [56:47<1:30:13,  2.01s/it]

 46%|████▌     | 2263/4959 [56:49<1:30:44,  2.02s/it]

 46%|████▌     | 2264/4959 [56:51<1:30:53,  2.02s/it]

 46%|████▌     | 2265/4959 [56:54<1:32:33,  2.06s/it]

 46%|████▌     | 2266/4959 [56:56<1:33:20,  2.08s/it]

 46%|████▌     | 2267/4959 [56:58<1:33:14,  2.08s/it]

 46%|████▌     | 2268/4959 [57:00<1:35:13,  2.12s/it]

 46%|████▌     | 2269/4959 [57:02<1:34:52,  2.12s/it]

 46%|████▌     | 2270/4959 [57:04<1:34:01,  2.10s/it]

 46%|████▌     | 2271/4959 [57:06<1:32:59,  2.08s/it]

 46%|████▌     | 2272/4959 [57:08<1:33:17,  2.08s/it]

 46%|████▌     | 2273/4959 [57:10<1:33:06,  2.08s/it]

 46%|████▌     | 2274/4959 [57:13<1:33:26,  2.09s/it]

 46%|████▌     | 2275/4959 [57:14<1:28:11,  1.97s/it]

 46%|████▌     | 2276/4959 [57:16<1:25:31,  1.91s/it]

 46%|████▌     | 2277/4959 [57:18<1:22:30,  1.85s/it]

 46%|████▌     | 2278/4959 [57:20<1:26:11,  1.93s/it]

 46%|████▌     | 2279/4959 [57:22<1:27:35,  1.96s/it]

 46%|████▌     | 2280/4959 [57:24<1:29:52,  2.01s/it]

 46%|████▌     | 2281/4959 [57:26<1:29:51,  2.01s/it]

 46%|████▌     | 2282/4959 [57:28<1:31:26,  2.05s/it]

 46%|████▌     | 2283/4959 [57:30<1:27:47,  1.97s/it]

 46%|████▌     | 2284/4959 [57:32<1:24:56,  1.91s/it]

 46%|████▌     | 2285/4959 [57:34<1:27:25,  1.96s/it]

 46%|████▌     | 2286/4959 [57:36<1:29:48,  2.02s/it]

 46%|████▌     | 2287/4959 [57:38<1:25:31,  1.92s/it]

 46%|████▌     | 2288/4959 [57:40<1:28:18,  1.98s/it]

 46%|████▌     | 2289/4959 [57:41<1:24:24,  1.90s/it]

 46%|████▌     | 2290/4959 [57:44<1:28:51,  2.00s/it]

 46%|████▌     | 2291/4959 [57:45<1:24:37,  1.90s/it]

 46%|████▌     | 2292/4959 [57:47<1:21:40,  1.84s/it]

 46%|████▌     | 2293/4959 [57:49<1:21:22,  1.83s/it]

 46%|████▋     | 2294/4959 [57:51<1:19:20,  1.79s/it]

 46%|████▋     | 2295/4959 [57:53<1:23:54,  1.89s/it]

 46%|████▋     | 2296/4959 [57:55<1:25:55,  1.94s/it]

 46%|████▋     | 2297/4959 [57:57<1:24:28,  1.90s/it]

 46%|████▋     | 2298/4959 [57:58<1:22:43,  1.87s/it]

 46%|████▋     | 2299/4959 [58:00<1:25:59,  1.94s/it]

 46%|████▋     | 2300/4959 [58:02<1:26:32,  1.95s/it]

 46%|████▋     | 2301/4959 [58:04<1:22:11,  1.86s/it]

 46%|████▋     | 2302/4959 [58:06<1:18:51,  1.78s/it]

 46%|████▋     | 2303/4959 [58:07<1:17:31,  1.75s/it]

 46%|████▋     | 2304/4959 [58:09<1:21:25,  1.84s/it]

 46%|████▋     | 2305/4959 [58:11<1:23:15,  1.88s/it]

 47%|████▋     | 2306/4959 [58:13<1:24:21,  1.91s/it]

 47%|████▋     | 2307/4959 [58:15<1:21:57,  1.85s/it]

 47%|████▋     | 2308/4959 [58:17<1:18:39,  1.78s/it]

 47%|████▋     | 2309/4959 [58:18<1:17:46,  1.76s/it]

 47%|████▋     | 2310/4959 [58:20<1:16:25,  1.73s/it]

 47%|████▋     | 2311/4959 [58:22<1:15:56,  1.72s/it]

 47%|████▋     | 2312/4959 [58:24<1:16:53,  1.74s/it]

 47%|████▋     | 2313/4959 [58:25<1:19:47,  1.81s/it]

 47%|████▋     | 2314/4959 [58:27<1:18:10,  1.77s/it]

 47%|████▋     | 2315/4959 [58:29<1:16:06,  1.73s/it]

 47%|████▋     | 2316/4959 [58:30<1:14:34,  1.69s/it]

 47%|████▋     | 2317/4959 [58:32<1:14:35,  1.69s/it]

 47%|████▋     | 2318/4959 [58:34<1:13:40,  1.67s/it]

 47%|████▋     | 2319/4959 [58:35<1:12:55,  1.66s/it]

 47%|████▋     | 2320/4959 [58:37<1:17:00,  1.75s/it]

 47%|████▋     | 2321/4959 [58:39<1:20:16,  1.83s/it]

 47%|████▋     | 2322/4959 [58:41<1:18:10,  1.78s/it]

 47%|████▋     | 2323/4959 [58:43<1:16:32,  1.74s/it]

 47%|████▋     | 2324/4959 [58:45<1:20:04,  1.82s/it]

 47%|████▋     | 2325/4959 [58:47<1:26:11,  1.96s/it]

 47%|████▋     | 2326/4959 [58:49<1:22:37,  1.88s/it]

 47%|████▋     | 2327/4959 [58:51<1:23:51,  1.91s/it]

 47%|████▋     | 2328/4959 [58:52<1:20:59,  1.85s/it]

 47%|████▋     | 2329/4959 [58:54<1:18:14,  1.78s/it]

 47%|████▋     | 2330/4959 [58:56<1:16:51,  1.75s/it]

 47%|████▋     | 2331/4959 [58:58<1:19:55,  1.82s/it]

 47%|████▋     | 2332/4959 [59:00<1:23:27,  1.91s/it]

 47%|████▋     | 2333/4959 [59:02<1:25:28,  1.95s/it]

 47%|████▋     | 2334/4959 [59:04<1:26:50,  1.99s/it]

 47%|████▋     | 2335/4959 [59:06<1:27:05,  1.99s/it]

 47%|████▋     | 2336/4959 [59:07<1:22:27,  1.89s/it]

 47%|████▋     | 2337/4959 [59:09<1:23:42,  1.92s/it]

 47%|████▋     | 2338/4959 [59:12<1:25:17,  1.95s/it]

 47%|████▋     | 2339/4959 [59:13<1:21:02,  1.86s/it]

 47%|████▋     | 2340/4959 [59:15<1:18:09,  1.79s/it]

 47%|████▋     | 2341/4959 [59:16<1:15:55,  1.74s/it]

 47%|████▋     | 2342/4959 [59:18<1:14:21,  1.70s/it]

 47%|████▋     | 2343/4959 [59:20<1:18:15,  1.79s/it]

 47%|████▋     | 2344/4959 [59:22<1:15:56,  1.74s/it]

 47%|████▋     | 2345/4959 [59:24<1:19:11,  1.82s/it]

 47%|████▋     | 2346/4959 [59:25<1:16:41,  1.76s/it]

 47%|████▋     | 2347/4959 [59:27<1:19:29,  1.83s/it]

 47%|████▋     | 2348/4959 [59:29<1:21:56,  1.88s/it]

 47%|████▋     | 2349/4959 [59:31<1:23:01,  1.91s/it]

 47%|████▋     | 2350/4959 [59:33<1:19:26,  1.83s/it]

 47%|████▋     | 2351/4959 [59:34<1:16:50,  1.77s/it]

 47%|████▋     | 2352/4959 [59:36<1:14:55,  1.72s/it]

 47%|████▋     | 2353/4959 [59:38<1:18:05,  1.80s/it]

 47%|████▋     | 2354/4959 [59:40<1:15:47,  1.75s/it]

 47%|████▋     | 2355/4959 [59:41<1:14:17,  1.71s/it]

 48%|████▊     | 2356/4959 [59:43<1:13:02,  1.68s/it]

 48%|████▊     | 2357/4959 [59:45<1:17:20,  1.78s/it]

 48%|████▊     | 2358/4959 [59:47<1:15:12,  1.73s/it]

 48%|████▊     | 2359/4959 [59:49<1:18:10,  1.80s/it]

 48%|████▊     | 2360/4959 [59:50<1:15:51,  1.75s/it]

 48%|████▊     | 2361/4959 [59:52<1:14:40,  1.72s/it]

 48%|████▊     | 2362/4959 [59:54<1:18:02,  1.80s/it]

 48%|████▊     | 2363/4959 [59:56<1:20:05,  1.85s/it]

 48%|████▊     | 2364/4959 [59:57<1:17:08,  1.78s/it]

 48%|████▊     | 2365/4959 [59:59<1:20:00,  1.85s/it]

 48%|████▊     | 2366/4959 [1:00:01<1:22:17,  1.90s/it]

 48%|████▊     | 2367/4959 [1:00:03<1:23:11,  1.93s/it]

 48%|████▊     | 2368/4959 [1:00:05<1:19:06,  1.83s/it]

 48%|████▊     | 2369/4959 [1:00:07<1:16:15,  1.77s/it]

 48%|████▊     | 2370/4959 [1:00:08<1:14:28,  1.73s/it]

 48%|████▊     | 2371/4959 [1:00:10<1:13:07,  1.70s/it]

 48%|████▊     | 2372/4959 [1:00:12<1:12:14,  1.68s/it]

 48%|████▊     | 2373/4959 [1:00:13<1:11:27,  1.66s/it]

 48%|████▊     | 2374/4959 [1:00:15<1:10:51,  1.64s/it]

 48%|████▊     | 2375/4959 [1:00:17<1:14:58,  1.74s/it]

 48%|████▊     | 2376/4959 [1:00:18<1:13:26,  1.71s/it]

 48%|████▊     | 2377/4959 [1:00:20<1:16:54,  1.79s/it]

 48%|████▊     | 2378/4959 [1:00:22<1:19:14,  1.84s/it]

 48%|████▊     | 2379/4959 [1:00:24<1:16:21,  1.78s/it]

 48%|████▊     | 2380/4959 [1:00:26<1:14:19,  1.73s/it]

 48%|████▊     | 2381/4959 [1:00:28<1:20:02,  1.86s/it]

 48%|████▊     | 2382/4959 [1:00:29<1:17:08,  1.80s/it]

 48%|████▊     | 2383/4959 [1:00:31<1:19:52,  1.86s/it]

 48%|████▊     | 2384/4959 [1:00:33<1:16:57,  1.79s/it]

 48%|████▊     | 2385/4959 [1:00:35<1:19:25,  1.85s/it]

 48%|████▊     | 2386/4959 [1:00:37<1:16:21,  1.78s/it]

 48%|████▊     | 2387/4959 [1:00:39<1:18:34,  1.83s/it]

 48%|████▊     | 2388/4959 [1:00:41<1:20:23,  1.88s/it]

 48%|████▊     | 2389/4959 [1:00:42<1:17:02,  1.80s/it]

 48%|████▊     | 2390/4959 [1:00:44<1:19:41,  1.86s/it]

 48%|████▊     | 2391/4959 [1:00:46<1:21:22,  1.90s/it]

 48%|████▊     | 2392/4959 [1:00:48<1:17:52,  1.82s/it]

 48%|████▊     | 2393/4959 [1:00:50<1:19:48,  1.87s/it]

 48%|████▊     | 2394/4959 [1:00:51<1:17:24,  1.81s/it]

 48%|████▊     | 2395/4959 [1:00:53<1:14:54,  1.75s/it]

 48%|████▊     | 2396/4959 [1:00:55<1:17:43,  1.82s/it]

 48%|████▊     | 2397/4959 [1:00:57<1:15:26,  1.77s/it]

 48%|████▊     | 2398/4959 [1:00:58<1:13:58,  1.73s/it]

 48%|████▊     | 2399/4959 [1:01:00<1:17:09,  1.81s/it]

 48%|████▊     | 2400/4959 [1:01:02<1:15:03,  1.76s/it]

 48%|████▊     | 2401/4959 [1:01:04<1:17:59,  1.83s/it]

 48%|████▊     | 2402/4959 [1:01:06<1:15:38,  1.78s/it]

 48%|████▊     | 2403/4959 [1:01:08<1:18:12,  1.84s/it]

 48%|████▊     | 2404/4959 [1:01:10<1:19:55,  1.88s/it]

 48%|████▊     | 2405/4959 [1:01:11<1:16:41,  1.80s/it]

 49%|████▊     | 2406/4959 [1:01:13<1:14:22,  1.75s/it]

 49%|████▊     | 2407/4959 [1:01:15<1:17:47,  1.83s/it]

 49%|████▊     | 2408/4959 [1:01:17<1:19:32,  1.87s/it]

 49%|████▊     | 2409/4959 [1:01:19<1:20:50,  1.90s/it]

 49%|████▊     | 2410/4959 [1:01:20<1:17:28,  1.82s/it]

 49%|████▊     | 2411/4959 [1:01:22<1:14:51,  1.76s/it]

 49%|████▊     | 2412/4959 [1:01:24<1:17:27,  1.82s/it]

 49%|████▊     | 2413/4959 [1:01:26<1:19:26,  1.87s/it]

 49%|████▊     | 2414/4959 [1:01:28<1:20:55,  1.91s/it]

 49%|████▊     | 2415/4959 [1:01:30<1:17:17,  1.82s/it]

 49%|████▊     | 2416/4959 [1:01:32<1:19:11,  1.87s/it]

 49%|████▊     | 2417/4959 [1:01:34<1:21:17,  1.92s/it]

 49%|████▉     | 2418/4959 [1:01:35<1:18:04,  1.84s/it]

 49%|████▉     | 2419/4959 [1:01:37<1:22:07,  1.94s/it]

 49%|████▉     | 2420/4959 [1:01:40<1:24:02,  1.99s/it]

 49%|████▉     | 2421/4959 [1:01:41<1:19:23,  1.88s/it]

 49%|████▉     | 2422/4959 [1:01:43<1:16:01,  1.80s/it]

 49%|████▉     | 2423/4959 [1:01:45<1:18:17,  1.85s/it]

 49%|████▉     | 2424/4959 [1:01:46<1:15:28,  1.79s/it]

 49%|████▉     | 2425/4959 [1:01:48<1:17:57,  1.85s/it]

 49%|████▉     | 2426/4959 [1:01:50<1:19:35,  1.89s/it]

 49%|████▉     | 2427/4959 [1:01:52<1:16:41,  1.82s/it]

 49%|████▉     | 2428/4959 [1:01:54<1:18:34,  1.86s/it]

 49%|████▉     | 2429/4959 [1:01:56<1:15:23,  1.79s/it]

 49%|████▉     | 2430/4959 [1:01:57<1:13:39,  1.75s/it]

 49%|████▉     | 2431/4959 [1:01:59<1:16:40,  1.82s/it]

 49%|████▉     | 2432/4959 [1:02:01<1:14:12,  1.76s/it]

 49%|████▉     | 2433/4959 [1:02:03<1:13:48,  1.75s/it]

 49%|████▉     | 2434/4959 [1:02:04<1:12:37,  1.73s/it]

 49%|████▉     | 2435/4959 [1:02:06<1:16:01,  1.81s/it]

 49%|████▉     | 2436/4959 [1:02:08<1:13:58,  1.76s/it]

 49%|████▉     | 2437/4959 [1:02:10<1:12:33,  1.73s/it]

 49%|████▉     | 2438/4959 [1:02:12<1:15:22,  1.79s/it]

 49%|████▉     | 2439/4959 [1:02:13<1:17:37,  1.85s/it]

 49%|████▉     | 2440/4959 [1:02:15<1:15:04,  1.79s/it]

 49%|████▉     | 2441/4959 [1:02:17<1:13:13,  1.74s/it]

 49%|████▉     | 2442/4959 [1:02:18<1:12:05,  1.72s/it]

 49%|████▉     | 2443/4959 [1:02:20<1:15:28,  1.80s/it]

 49%|████▉     | 2444/4959 [1:02:22<1:13:12,  1.75s/it]

 49%|████▉     | 2445/4959 [1:02:24<1:18:30,  1.87s/it]

 49%|████▉     | 2446/4959 [1:02:26<1:20:19,  1.92s/it]

 49%|████▉     | 2447/4959 [1:02:28<1:21:10,  1.94s/it]

 49%|████▉     | 2448/4959 [1:02:30<1:24:33,  2.02s/it]

 49%|████▉     | 2449/4959 [1:02:32<1:19:30,  1.90s/it]

 49%|████▉     | 2450/4959 [1:02:34<1:16:10,  1.82s/it]

 49%|████▉     | 2451/4959 [1:02:35<1:13:47,  1.77s/it]

 49%|████▉     | 2452/4959 [1:02:37<1:12:03,  1.72s/it]

 49%|████▉     | 2453/4959 [1:02:39<1:11:04,  1.70s/it]

 49%|████▉     | 2454/4959 [1:02:41<1:15:06,  1.80s/it]

 50%|████▉     | 2455/4959 [1:02:42<1:12:55,  1.75s/it]

 50%|████▉     | 2456/4959 [1:02:44<1:15:58,  1.82s/it]

 50%|████▉     | 2457/4959 [1:02:46<1:17:48,  1.87s/it]

 50%|████▉     | 2458/4959 [1:02:48<1:14:45,  1.79s/it]

 50%|████▉     | 2459/4959 [1:02:49<1:12:40,  1.74s/it]

 50%|████▉     | 2460/4959 [1:02:51<1:11:07,  1.71s/it]

 50%|████▉     | 2461/4959 [1:02:53<1:14:08,  1.78s/it]

 50%|████▉     | 2462/4959 [1:02:55<1:16:38,  1.84s/it]

 50%|████▉     | 2463/4959 [1:02:57<1:20:44,  1.94s/it]

 50%|████▉     | 2464/4959 [1:02:59<1:23:27,  2.01s/it]

 50%|████▉     | 2465/4959 [1:03:01<1:18:36,  1.89s/it]

 50%|████▉     | 2466/4959 [1:03:03<1:15:15,  1.81s/it]

 50%|████▉     | 2467/4959 [1:03:04<1:12:48,  1.75s/it]

 50%|████▉     | 2468/4959 [1:03:06<1:11:09,  1.71s/it]

 50%|████▉     | 2469/4959 [1:03:08<1:10:20,  1.69s/it]

 50%|████▉     | 2470/4959 [1:03:09<1:13:47,  1.78s/it]

 50%|████▉     | 2471/4959 [1:03:11<1:11:51,  1.73s/it]

 50%|████▉     | 2472/4959 [1:03:13<1:14:53,  1.81s/it]

 50%|████▉     | 2473/4959 [1:03:15<1:17:06,  1.86s/it]

 50%|████▉     | 2474/4959 [1:03:17<1:14:12,  1.79s/it]

 50%|████▉     | 2475/4959 [1:03:19<1:16:23,  1.85s/it]

 50%|████▉     | 2476/4959 [1:03:20<1:13:53,  1.79s/it]

 50%|████▉     | 2477/4959 [1:03:22<1:16:31,  1.85s/it]

 50%|████▉     | 2478/4959 [1:03:24<1:17:54,  1.88s/it]

 50%|████▉     | 2479/4959 [1:03:26<1:14:46,  1.81s/it]

 50%|█████     | 2480/4959 [1:03:28<1:12:26,  1.75s/it]

 50%|█████     | 2481/4959 [1:03:29<1:10:46,  1.71s/it]

 50%|█████     | 2482/4959 [1:03:31<1:10:03,  1.70s/it]

 50%|█████     | 2483/4959 [1:03:32<1:09:18,  1.68s/it]

 50%|█████     | 2484/4959 [1:03:35<1:18:01,  1.89s/it]

 50%|█████     | 2485/4959 [1:03:37<1:21:26,  1.98s/it]

 50%|█████     | 2486/4959 [1:03:39<1:17:16,  1.87s/it]

 50%|█████     | 2487/4959 [1:03:40<1:14:36,  1.81s/it]

 50%|█████     | 2488/4959 [1:03:42<1:17:06,  1.87s/it]

 50%|█████     | 2489/4959 [1:03:44<1:18:49,  1.91s/it]

 50%|█████     | 2490/4959 [1:03:46<1:19:37,  1.94s/it]

 50%|█████     | 2491/4959 [1:03:48<1:16:08,  1.85s/it]

 50%|█████     | 2492/4959 [1:03:50<1:17:37,  1.89s/it]

 50%|█████     | 2493/4959 [1:03:52<1:18:41,  1.91s/it]

 50%|█████     | 2494/4959 [1:03:54<1:15:02,  1.83s/it]

 50%|█████     | 2495/4959 [1:03:55<1:12:32,  1.77s/it]

 50%|█████     | 2496/4959 [1:03:57<1:14:55,  1.83s/it]

 50%|█████     | 2497/4959 [1:03:59<1:16:29,  1.86s/it]

 50%|█████     | 2498/4959 [1:04:01<1:17:46,  1.90s/it]

 50%|█████     | 2499/4959 [1:04:03<1:14:35,  1.82s/it]

 50%|█████     | 2500/4959 [1:04:04<1:12:16,  1.76s/it]

 50%|█████     | 2501/4959 [1:04:06<1:14:38,  1.82s/it]

 50%|█████     | 2502/4959 [1:04:08<1:12:13,  1.76s/it]

 50%|█████     | 2503/4959 [1:04:10<1:10:35,  1.72s/it]

 50%|█████     | 2504/4959 [1:04:11<1:09:32,  1.70s/it]

 51%|█████     | 2505/4959 [1:04:13<1:08:31,  1.68s/it]

 51%|█████     | 2506/4959 [1:04:15<1:12:13,  1.77s/it]

 51%|█████     | 2507/4959 [1:04:17<1:17:07,  1.89s/it]

 51%|█████     | 2508/4959 [1:04:19<1:18:06,  1.91s/it]

 51%|█████     | 2509/4959 [1:04:21<1:18:53,  1.93s/it]

 51%|█████     | 2510/4959 [1:04:23<1:15:08,  1.84s/it]

 51%|█████     | 2511/4959 [1:04:24<1:12:50,  1.79s/it]

 51%|█████     | 2512/4959 [1:04:26<1:15:12,  1.84s/it]

 51%|█████     | 2513/4959 [1:04:28<1:12:38,  1.78s/it]

 51%|█████     | 2514/4959 [1:04:30<1:15:03,  1.84s/it]

 51%|█████     | 2515/4959 [1:04:32<1:19:09,  1.94s/it]

 51%|█████     | 2516/4959 [1:04:34<1:19:23,  1.95s/it]

 51%|█████     | 2517/4959 [1:04:36<1:20:11,  1.97s/it]

 51%|█████     | 2518/4959 [1:04:38<1:22:34,  2.03s/it]

 51%|█████     | 2519/4959 [1:04:40<1:17:40,  1.91s/it]

 51%|█████     | 2520/4959 [1:04:42<1:18:12,  1.92s/it]

 51%|█████     | 2521/4959 [1:04:43<1:14:28,  1.83s/it]

 51%|█████     | 2522/4959 [1:04:45<1:12:00,  1.77s/it]

 51%|█████     | 2523/4959 [1:04:47<1:10:14,  1.73s/it]

 51%|█████     | 2524/4959 [1:04:49<1:13:21,  1.81s/it]

 51%|█████     | 2525/4959 [1:04:51<1:15:47,  1.87s/it]

 51%|█████     | 2526/4959 [1:04:52<1:12:46,  1.79s/it]

 51%|█████     | 2527/4959 [1:04:54<1:10:48,  1.75s/it]

 51%|█████     | 2528/4959 [1:04:56<1:13:36,  1.82s/it]

 51%|█████     | 2529/4959 [1:04:58<1:15:34,  1.87s/it]

 51%|█████     | 2530/4959 [1:04:59<1:12:33,  1.79s/it]

 51%|█████     | 2531/4959 [1:05:01<1:14:53,  1.85s/it]

 51%|█████     | 2532/4959 [1:05:03<1:16:29,  1.89s/it]

 51%|█████     | 2533/4959 [1:05:05<1:13:21,  1.81s/it]

 51%|█████     | 2534/4959 [1:05:07<1:11:19,  1.76s/it]

 51%|█████     | 2535/4959 [1:05:09<1:14:02,  1.83s/it]

 51%|█████     | 2536/4959 [1:05:11<1:15:43,  1.88s/it]

 51%|█████     | 2537/4959 [1:05:12<1:12:42,  1.80s/it]

 51%|█████     | 2538/4959 [1:05:14<1:14:52,  1.86s/it]

 51%|█████     | 2539/4959 [1:05:16<1:16:11,  1.89s/it]

 51%|█████     | 2540/4959 [1:05:18<1:17:25,  1.92s/it]

 51%|█████     | 2541/4959 [1:05:20<1:18:01,  1.94s/it]

 51%|█████▏    | 2542/4959 [1:05:22<1:18:38,  1.95s/it]

 51%|█████▏    | 2543/4959 [1:05:24<1:14:42,  1.86s/it]

 51%|█████▏    | 2544/4959 [1:05:25<1:11:48,  1.78s/it]

 51%|█████▏    | 2545/4959 [1:05:27<1:13:58,  1.84s/it]

 51%|█████▏    | 2546/4959 [1:05:29<1:16:17,  1.90s/it]

 51%|█████▏    | 2547/4959 [1:05:31<1:14:38,  1.86s/it]

 51%|█████▏    | 2548/4959 [1:05:33<1:11:58,  1.79s/it]

 51%|█████▏    | 2549/4959 [1:05:34<1:09:58,  1.74s/it]

 51%|█████▏    | 2550/4959 [1:05:37<1:15:10,  1.87s/it]

 51%|█████▏    | 2551/4959 [1:05:39<1:16:52,  1.92s/it]

 51%|█████▏    | 2552/4959 [1:05:41<1:17:49,  1.94s/it]

 51%|█████▏    | 2553/4959 [1:05:42<1:14:03,  1.85s/it]

 52%|█████▏    | 2554/4959 [1:05:44<1:11:14,  1.78s/it]

 52%|█████▏    | 2555/4959 [1:05:46<1:13:22,  1.83s/it]

 52%|█████▏    | 2556/4959 [1:05:47<1:10:56,  1.77s/it]

 52%|█████▏    | 2557/4959 [1:05:50<1:14:10,  1.85s/it]

 52%|█████▏    | 2558/4959 [1:05:52<1:16:00,  1.90s/it]

 52%|█████▏    | 2559/4959 [1:05:54<1:17:01,  1.93s/it]

 52%|█████▏    | 2560/4959 [1:05:55<1:13:41,  1.84s/it]

 52%|█████▏    | 2561/4959 [1:05:57<1:15:51,  1.90s/it]

 52%|█████▏    | 2562/4959 [1:05:59<1:16:40,  1.92s/it]

 52%|█████▏    | 2563/4959 [1:06:01<1:17:12,  1.93s/it]

 52%|█████▏    | 2564/4959 [1:06:03<1:13:28,  1.84s/it]

 52%|█████▏    | 2565/4959 [1:06:04<1:11:18,  1.79s/it]

 52%|█████▏    | 2566/4959 [1:06:06<1:13:25,  1.84s/it]

 52%|█████▏    | 2567/4959 [1:06:08<1:15:09,  1.89s/it]

 52%|█████▏    | 2568/4959 [1:06:10<1:12:11,  1.81s/it]

 52%|█████▏    | 2569/4959 [1:06:12<1:09:58,  1.76s/it]

 52%|█████▏    | 2570/4959 [1:06:13<1:08:25,  1.72s/it]

 52%|█████▏    | 2571/4959 [1:06:15<1:11:42,  1.80s/it]

 52%|█████▏    | 2572/4959 [1:06:17<1:09:33,  1.75s/it]

 52%|█████▏    | 2573/4959 [1:06:19<1:12:08,  1.81s/it]

 52%|█████▏    | 2574/4959 [1:06:21<1:10:01,  1.76s/it]

 52%|█████▏    | 2575/4959 [1:06:23<1:14:56,  1.89s/it]

 52%|█████▏    | 2576/4959 [1:06:24<1:11:56,  1.81s/it]

 52%|█████▏    | 2577/4959 [1:06:26<1:09:45,  1.76s/it]

 52%|█████▏    | 2578/4959 [1:06:28<1:08:08,  1.72s/it]

 52%|█████▏    | 2579/4959 [1:06:30<1:11:21,  1.80s/it]

 52%|█████▏    | 2580/4959 [1:06:31<1:09:04,  1.74s/it]

 52%|█████▏    | 2581/4959 [1:06:33<1:07:32,  1.70s/it]

 52%|█████▏    | 2582/4959 [1:06:35<1:10:42,  1.78s/it]

 52%|█████▏    | 2583/4959 [1:06:36<1:08:59,  1.74s/it]

 52%|█████▏    | 2584/4959 [1:06:38<1:07:25,  1.70s/it]

 52%|█████▏    | 2585/4959 [1:06:40<1:10:38,  1.79s/it]

 52%|█████▏    | 2586/4959 [1:06:42<1:13:01,  1.85s/it]

 52%|█████▏    | 2587/4959 [1:06:44<1:10:32,  1.78s/it]

 52%|█████▏    | 2588/4959 [1:06:46<1:12:25,  1.83s/it]

 52%|█████▏    | 2589/4959 [1:06:47<1:10:03,  1.77s/it]

 52%|█████▏    | 2590/4959 [1:06:49<1:12:25,  1.83s/it]

 52%|█████▏    | 2591/4959 [1:06:51<1:09:52,  1.77s/it]

 52%|█████▏    | 2592/4959 [1:06:52<1:08:31,  1.74s/it]

 52%|█████▏    | 2593/4959 [1:06:54<1:07:14,  1.71s/it]

 52%|█████▏    | 2594/4959 [1:06:56<1:06:16,  1.68s/it]

 52%|█████▏    | 2595/4959 [1:06:58<1:09:33,  1.77s/it]

 52%|█████▏    | 2596/4959 [1:06:59<1:07:40,  1.72s/it]

 52%|█████▏    | 2597/4959 [1:07:01<1:11:31,  1.82s/it]

 52%|█████▏    | 2598/4959 [1:07:03<1:09:06,  1.76s/it]

 52%|█████▏    | 2599/4959 [1:07:05<1:07:35,  1.72s/it]

 52%|█████▏    | 2600/4959 [1:07:07<1:10:42,  1.80s/it]

 52%|█████▏    | 2601/4959 [1:07:09<1:15:06,  1.91s/it]

 52%|█████▏    | 2602/4959 [1:07:11<1:15:46,  1.93s/it]

 52%|█████▏    | 2603/4959 [1:07:13<1:16:08,  1.94s/it]

 53%|█████▎    | 2604/4959 [1:07:15<1:16:28,  1.95s/it]

 53%|█████▎    | 2605/4959 [1:07:16<1:12:36,  1.85s/it]

 53%|█████▎    | 2606/4959 [1:07:18<1:13:44,  1.88s/it]

 53%|█████▎    | 2607/4959 [1:07:20<1:10:28,  1.80s/it]

 53%|█████▎    | 2608/4959 [1:07:22<1:12:25,  1.85s/it]

 53%|█████▎    | 2609/4959 [1:07:23<1:09:44,  1.78s/it]

 53%|█████▎    | 2610/4959 [1:07:25<1:12:13,  1.84s/it]

 53%|█████▎    | 2611/4959 [1:07:27<1:13:56,  1.89s/it]

 53%|█████▎    | 2612/4959 [1:07:29<1:15:15,  1.92s/it]

 53%|█████▎    | 2613/4959 [1:07:31<1:16:41,  1.96s/it]

 53%|█████▎    | 2614/4959 [1:07:33<1:16:45,  1.96s/it]

 53%|█████▎    | 2615/4959 [1:07:35<1:12:49,  1.86s/it]

 53%|█████▎    | 2616/4959 [1:07:37<1:10:05,  1.80s/it]

 53%|█████▎    | 2617/4959 [1:07:38<1:08:16,  1.75s/it]

 53%|█████▎    | 2618/4959 [1:07:40<1:06:40,  1.71s/it]

 53%|█████▎    | 2619/4959 [1:07:42<1:09:49,  1.79s/it]

 53%|█████▎    | 2620/4959 [1:07:44<1:07:48,  1.74s/it]

 53%|█████▎    | 2621/4959 [1:07:46<1:10:28,  1.81s/it]

 53%|█████▎    | 2622/4959 [1:07:47<1:12:20,  1.86s/it]

 53%|█████▎    | 2623/4959 [1:07:50<1:14:44,  1.92s/it]

 53%|█████▎    | 2624/4959 [1:07:51<1:11:29,  1.84s/it]

 53%|█████▎    | 2625/4959 [1:07:53<1:10:34,  1.81s/it]

 53%|█████▎    | 2626/4959 [1:07:55<1:12:27,  1.86s/it]

 53%|█████▎    | 2627/4959 [1:07:57<1:10:03,  1.80s/it]

 53%|█████▎    | 2628/4959 [1:07:58<1:08:06,  1.75s/it]

 53%|█████▎    | 2629/4959 [1:08:00<1:06:32,  1.71s/it]

 53%|█████▎    | 2630/4959 [1:08:01<1:05:16,  1.68s/it]

 53%|█████▎    | 2631/4959 [1:08:03<1:04:36,  1.67s/it]

 53%|█████▎    | 2632/4959 [1:08:05<1:08:26,  1.76s/it]

 53%|█████▎    | 2633/4959 [1:08:07<1:10:45,  1.83s/it]

 53%|█████▎    | 2634/4959 [1:08:09<1:08:37,  1.77s/it]

 53%|█████▎    | 2635/4959 [1:08:11<1:11:16,  1.84s/it]

 53%|█████▎    | 2636/4959 [1:08:13<1:12:45,  1.88s/it]

 53%|█████▎    | 2637/4959 [1:08:14<1:09:50,  1.80s/it]

 53%|█████▎    | 2638/4959 [1:08:16<1:11:52,  1.86s/it]

 53%|█████▎    | 2639/4959 [1:08:18<1:09:15,  1.79s/it]

 53%|█████▎    | 2640/4959 [1:08:20<1:07:26,  1.75s/it]

 53%|█████▎    | 2641/4959 [1:08:22<1:12:15,  1.87s/it]

 53%|█████▎    | 2642/4959 [1:08:23<1:09:31,  1.80s/it]

 53%|█████▎    | 2643/4959 [1:08:25<1:07:21,  1.75s/it]

 53%|█████▎    | 2644/4959 [1:08:27<1:06:11,  1.72s/it]

 53%|█████▎    | 2645/4959 [1:08:28<1:05:27,  1.70s/it]

 53%|█████▎    | 2646/4959 [1:08:30<1:04:46,  1.68s/it]

 53%|█████▎    | 2647/4959 [1:08:32<1:04:01,  1.66s/it]

 53%|█████▎    | 2648/4959 [1:08:33<1:03:25,  1.65s/it]

 53%|█████▎    | 2649/4959 [1:08:35<1:03:09,  1.64s/it]

 53%|█████▎    | 2650/4959 [1:08:37<1:06:51,  1.74s/it]

 53%|█████▎    | 2651/4959 [1:08:38<1:05:30,  1.70s/it]

 53%|█████▎    | 2652/4959 [1:08:40<1:04:39,  1.68s/it]

 53%|█████▎    | 2653/4959 [1:08:42<1:04:04,  1.67s/it]

 54%|█████▎    | 2654/4959 [1:08:43<1:03:42,  1.66s/it]

 54%|█████▎    | 2655/4959 [1:08:45<1:07:18,  1.75s/it]

 54%|█████▎    | 2656/4959 [1:08:47<1:09:51,  1.82s/it]

 54%|█████▎    | 2657/4959 [1:08:49<1:11:42,  1.87s/it]

 54%|█████▎    | 2658/4959 [1:08:51<1:12:55,  1.90s/it]

 54%|█████▎    | 2659/4959 [1:08:53<1:09:37,  1.82s/it]

 54%|█████▎    | 2660/4959 [1:08:55<1:11:27,  1.86s/it]

 54%|█████▎    | 2661/4959 [1:08:56<1:09:02,  1.80s/it]

 54%|█████▎    | 2662/4959 [1:08:58<1:07:12,  1.76s/it]

 54%|█████▎    | 2663/4959 [1:09:00<1:09:45,  1.82s/it]

 54%|█████▎    | 2664/4959 [1:09:02<1:11:28,  1.87s/it]

 54%|█████▎    | 2665/4959 [1:09:04<1:12:32,  1.90s/it]

 54%|█████▍    | 2666/4959 [1:09:06<1:10:19,  1.84s/it]

 54%|█████▍    | 2667/4959 [1:09:07<1:07:45,  1.77s/it]

 54%|█████▍    | 2668/4959 [1:09:09<1:06:58,  1.75s/it]

 54%|█████▍    | 2669/4959 [1:09:11<1:09:43,  1.83s/it]

 54%|█████▍    | 2670/4959 [1:09:13<1:07:26,  1.77s/it]

 54%|█████▍    | 2671/4959 [1:09:14<1:05:55,  1.73s/it]

 54%|█████▍    | 2672/4959 [1:09:16<1:05:01,  1.71s/it]

 54%|█████▍    | 2673/4959 [1:09:18<1:08:15,  1.79s/it]

 54%|█████▍    | 2674/4959 [1:09:20<1:06:14,  1.74s/it]

 54%|█████▍    | 2675/4959 [1:09:21<1:05:03,  1.71s/it]

 54%|█████▍    | 2676/4959 [1:09:23<1:04:02,  1.68s/it]

 54%|█████▍    | 2677/4959 [1:09:24<1:03:25,  1.67s/it]

 54%|█████▍    | 2678/4959 [1:09:26<1:07:10,  1.77s/it]

 54%|█████▍    | 2679/4959 [1:09:28<1:05:41,  1.73s/it]

 54%|█████▍    | 2680/4959 [1:09:30<1:04:28,  1.70s/it]

 54%|█████▍    | 2681/4959 [1:09:32<1:07:27,  1.78s/it]

 54%|█████▍    | 2682/4959 [1:09:33<1:05:42,  1.73s/it]

 54%|█████▍    | 2683/4959 [1:09:35<1:08:37,  1.81s/it]

 54%|█████▍    | 2684/4959 [1:09:37<1:10:33,  1.86s/it]

 54%|█████▍    | 2685/4959 [1:09:39<1:07:59,  1.79s/it]

 54%|█████▍    | 2686/4959 [1:09:41<1:06:17,  1.75s/it]

 54%|█████▍    | 2687/4959 [1:09:42<1:04:59,  1.72s/it]

 54%|█████▍    | 2688/4959 [1:09:44<1:08:20,  1.81s/it]

 54%|█████▍    | 2689/4959 [1:09:46<1:06:19,  1.75s/it]

 54%|█████▍    | 2690/4959 [1:09:48<1:08:50,  1.82s/it]

 54%|█████▍    | 2691/4959 [1:09:49<1:07:09,  1.78s/it]

 54%|█████▍    | 2692/4959 [1:09:51<1:05:32,  1.73s/it]

 54%|█████▍    | 2693/4959 [1:09:53<1:04:27,  1.71s/it]

 54%|█████▍    | 2694/4959 [1:09:55<1:07:40,  1.79s/it]

 54%|█████▍    | 2695/4959 [1:09:56<1:05:56,  1.75s/it]

 54%|█████▍    | 2696/4959 [1:09:58<1:08:41,  1.82s/it]

 54%|█████▍    | 2697/4959 [1:10:00<1:10:38,  1.87s/it]

 54%|█████▍    | 2698/4959 [1:10:02<1:07:54,  1.80s/it]

 54%|█████▍    | 2699/4959 [1:10:04<1:05:55,  1.75s/it]

 54%|█████▍    | 2700/4959 [1:10:05<1:04:26,  1.71s/it]

 54%|█████▍    | 2701/4959 [1:10:07<1:03:41,  1.69s/it]

 54%|█████▍    | 2702/4959 [1:10:09<1:06:54,  1.78s/it]

 55%|█████▍    | 2703/4959 [1:10:11<1:05:15,  1.74s/it]

 55%|█████▍    | 2704/4959 [1:10:12<1:07:49,  1.80s/it]

 55%|█████▍    | 2705/4959 [1:10:14<1:09:46,  1.86s/it]

 55%|█████▍    | 2706/4959 [1:10:16<1:11:16,  1.90s/it]

 55%|█████▍    | 2707/4959 [1:10:18<1:08:19,  1.82s/it]

 55%|█████▍    | 2708/4959 [1:10:20<1:10:30,  1.88s/it]

 55%|█████▍    | 2709/4959 [1:10:22<1:10:27,  1.88s/it]

 55%|█████▍    | 2710/4959 [1:10:24<1:11:33,  1.91s/it]

 55%|█████▍    | 2711/4959 [1:10:26<1:12:18,  1.93s/it]

 55%|█████▍    | 2712/4959 [1:10:28<1:12:53,  1.95s/it]

 55%|█████▍    | 2713/4959 [1:10:30<1:09:16,  1.85s/it]

 55%|█████▍    | 2714/4959 [1:10:32<1:13:07,  1.95s/it]

 55%|█████▍    | 2715/4959 [1:10:33<1:09:17,  1.85s/it]

 55%|█████▍    | 2716/4959 [1:10:35<1:06:38,  1.78s/it]

 55%|█████▍    | 2717/4959 [1:10:37<1:04:56,  1.74s/it]

 55%|█████▍    | 2718/4959 [1:10:39<1:07:39,  1.81s/it]

 55%|█████▍    | 2719/4959 [1:10:40<1:05:27,  1.75s/it]

 55%|█████▍    | 2720/4959 [1:10:42<1:04:01,  1.72s/it]

 55%|█████▍    | 2721/4959 [1:10:43<1:02:56,  1.69s/it]

 55%|█████▍    | 2722/4959 [1:10:45<1:06:16,  1.78s/it]

 55%|█████▍    | 2723/4959 [1:10:47<1:04:47,  1.74s/it]

 55%|█████▍    | 2724/4959 [1:10:49<1:03:41,  1.71s/it]

 55%|█████▍    | 2725/4959 [1:10:51<1:06:46,  1.79s/it]

 55%|█████▍    | 2726/4959 [1:10:52<1:04:55,  1.74s/it]

 55%|█████▍    | 2727/4959 [1:10:54<1:07:33,  1.82s/it]

 55%|█████▌    | 2728/4959 [1:10:56<1:05:42,  1.77s/it]

 55%|█████▌    | 2729/4959 [1:10:58<1:08:02,  1.83s/it]

 55%|█████▌    | 2730/4959 [1:11:00<1:05:41,  1.77s/it]

 55%|█████▌    | 2731/4959 [1:11:02<1:10:12,  1.89s/it]

 55%|█████▌    | 2732/4959 [1:11:03<1:07:49,  1.83s/it]

 55%|█████▌    | 2733/4959 [1:11:05<1:09:37,  1.88s/it]

 55%|█████▌    | 2734/4959 [1:11:07<1:07:01,  1.81s/it]

 55%|█████▌    | 2735/4959 [1:11:09<1:09:01,  1.86s/it]

 55%|█████▌    | 2736/4959 [1:11:11<1:11:03,  1.92s/it]

 55%|█████▌    | 2737/4959 [1:11:13<1:07:52,  1.83s/it]

 55%|█████▌    | 2738/4959 [1:11:15<1:09:34,  1.88s/it]

 55%|█████▌    | 2739/4959 [1:11:17<1:10:52,  1.92s/it]

 55%|█████▌    | 2740/4959 [1:11:19<1:11:35,  1.94s/it]

 55%|█████▌    | 2741/4959 [1:11:21<1:11:53,  1.94s/it]

 55%|█████▌    | 2742/4959 [1:11:22<1:08:21,  1.85s/it]

 55%|█████▌    | 2743/4959 [1:11:24<1:09:42,  1.89s/it]

 55%|█████▌    | 2744/4959 [1:11:27<1:13:04,  1.98s/it]

 55%|█████▌    | 2745/4959 [1:11:28<1:09:12,  1.88s/it]

 55%|█████▌    | 2746/4959 [1:11:30<1:06:24,  1.80s/it]

 55%|█████▌    | 2747/4959 [1:11:31<1:04:42,  1.76s/it]

 55%|█████▌    | 2748/4959 [1:11:33<1:07:07,  1.82s/it]

 55%|█████▌    | 2749/4959 [1:11:35<1:09:03,  1.87s/it]

 55%|█████▌    | 2750/4959 [1:11:37<1:06:20,  1.80s/it]

 55%|█████▌    | 2751/4959 [1:11:39<1:04:50,  1.76s/it]

 55%|█████▌    | 2752/4959 [1:11:40<1:03:26,  1.72s/it]

 56%|█████▌    | 2753/4959 [1:11:42<1:06:17,  1.80s/it]

 56%|█████▌    | 2754/4959 [1:11:44<1:09:11,  1.88s/it]

 56%|█████▌    | 2755/4959 [1:11:46<1:06:35,  1.81s/it]

 56%|█████▌    | 2756/4959 [1:11:48<1:04:28,  1.76s/it]

 56%|█████▌    | 2757/4959 [1:11:49<1:03:14,  1.72s/it]

 56%|█████▌    | 2758/4959 [1:11:51<1:02:19,  1.70s/it]

 56%|█████▌    | 2759/4959 [1:11:53<1:01:50,  1.69s/it]

 56%|█████▌    | 2760/4959 [1:11:54<1:01:14,  1.67s/it]

 56%|█████▌    | 2761/4959 [1:11:56<1:04:44,  1.77s/it]

 56%|█████▌    | 2762/4959 [1:11:58<1:03:26,  1.73s/it]

 56%|█████▌    | 2763/4959 [1:12:00<1:06:55,  1.83s/it]

 56%|█████▌    | 2764/4959 [1:12:02<1:04:36,  1.77s/it]

 56%|█████▌    | 2765/4959 [1:12:03<1:02:59,  1.72s/it]

 56%|█████▌    | 2766/4959 [1:12:05<1:01:47,  1.69s/it]

 56%|█████▌    | 2767/4959 [1:12:07<1:02:08,  1.70s/it]

 56%|█████▌    | 2768/4959 [1:12:09<1:05:09,  1.78s/it]

 56%|█████▌    | 2769/4959 [1:12:10<1:03:31,  1.74s/it]

 56%|█████▌    | 2770/4959 [1:12:12<1:02:25,  1.71s/it]

 56%|█████▌    | 2771/4959 [1:12:14<1:05:29,  1.80s/it]

 56%|█████▌    | 2772/4959 [1:12:15<1:03:50,  1.75s/it]

 56%|█████▌    | 2773/4959 [1:12:17<1:06:10,  1.82s/it]

 56%|█████▌    | 2774/4959 [1:12:19<1:08:02,  1.87s/it]

 56%|█████▌    | 2775/4959 [1:12:21<1:09:02,  1.90s/it]

 56%|█████▌    | 2776/4959 [1:12:23<1:06:11,  1.82s/it]

 56%|█████▌    | 2777/4959 [1:12:25<1:04:02,  1.76s/it]

 56%|█████▌    | 2778/4959 [1:12:26<1:02:36,  1.72s/it]

 56%|█████▌    | 2779/4959 [1:12:28<1:01:53,  1.70s/it]

 56%|█████▌    | 2780/4959 [1:12:30<1:01:05,  1.68s/it]

 56%|█████▌    | 2781/4959 [1:12:31<1:00:47,  1.67s/it]

 56%|█████▌    | 2782/4959 [1:12:33<1:04:19,  1.77s/it]

 56%|█████▌    | 2783/4959 [1:12:35<1:06:39,  1.84s/it]

 56%|█████▌    | 2784/4959 [1:12:37<1:08:05,  1.88s/it]

 56%|█████▌    | 2785/4959 [1:12:39<1:09:19,  1.91s/it]

 56%|█████▌    | 2786/4959 [1:12:41<1:09:59,  1.93s/it]

 56%|█████▌    | 2787/4959 [1:12:43<1:10:33,  1.95s/it]

 56%|█████▌    | 2788/4959 [1:12:45<1:07:03,  1.85s/it]

 56%|█████▌    | 2789/4959 [1:12:47<1:08:27,  1.89s/it]

 56%|█████▋    | 2790/4959 [1:12:48<1:05:40,  1.82s/it]

 56%|█████▋    | 2791/4959 [1:12:50<1:03:35,  1.76s/it]

 56%|█████▋    | 2792/4959 [1:12:52<1:02:10,  1.72s/it]

 56%|█████▋    | 2793/4959 [1:12:53<1:01:23,  1.70s/it]

 56%|█████▋    | 2794/4959 [1:12:55<1:04:15,  1.78s/it]

 56%|█████▋    | 2795/4959 [1:12:57<1:06:49,  1.85s/it]

 56%|█████▋    | 2796/4959 [1:12:59<1:04:23,  1.79s/it]

 56%|█████▋    | 2797/4959 [1:13:01<1:06:28,  1.84s/it]

 56%|█████▋    | 2798/4959 [1:13:03<1:07:53,  1.88s/it]

 56%|█████▋    | 2799/4959 [1:13:05<1:05:08,  1.81s/it]

 56%|█████▋    | 2800/4959 [1:13:06<1:03:15,  1.76s/it]

 56%|█████▋    | 2801/4959 [1:13:08<1:05:31,  1.82s/it]

 57%|█████▋    | 2802/4959 [1:13:10<1:03:39,  1.77s/it]

 57%|█████▋    | 2803/4959 [1:13:11<1:02:01,  1.73s/it]

 57%|█████▋    | 2804/4959 [1:13:13<1:04:35,  1.80s/it]

 57%|█████▋    | 2805/4959 [1:13:15<1:07:04,  1.87s/it]

 57%|█████▋    | 2806/4959 [1:13:17<1:04:36,  1.80s/it]

 57%|█████▋    | 2807/4959 [1:13:19<1:04:05,  1.79s/it]

 57%|█████▋    | 2808/4959 [1:13:21<1:06:19,  1.85s/it]

 57%|█████▋    | 2809/4959 [1:13:22<1:03:58,  1.79s/it]

 57%|█████▋    | 2810/4959 [1:13:24<1:02:26,  1.74s/it]

 57%|█████▋    | 2811/4959 [1:13:26<1:01:13,  1.71s/it]

 57%|█████▋    | 2812/4959 [1:13:27<1:00:40,  1.70s/it]

 57%|█████▋    | 2813/4959 [1:13:29<1:03:44,  1.78s/it]

 57%|█████▋    | 2814/4959 [1:13:31<1:02:27,  1.75s/it]

 57%|█████▋    | 2815/4959 [1:13:33<1:01:11,  1.71s/it]

 57%|█████▋    | 2816/4959 [1:13:35<1:03:50,  1.79s/it]

 57%|█████▋    | 2817/4959 [1:13:37<1:08:21,  1.91s/it]

 57%|█████▋    | 2818/4959 [1:13:39<1:08:58,  1.93s/it]

 57%|█████▋    | 2819/4959 [1:13:41<1:09:33,  1.95s/it]

 57%|█████▋    | 2820/4959 [1:13:42<1:06:21,  1.86s/it]

 57%|█████▋    | 2821/4959 [1:13:44<1:03:49,  1.79s/it]

 57%|█████▋    | 2822/4959 [1:13:46<1:05:59,  1.85s/it]

 57%|█████▋    | 2823/4959 [1:13:48<1:03:42,  1.79s/it]

 57%|█████▋    | 2824/4959 [1:13:50<1:05:42,  1.85s/it]

 57%|█████▋    | 2825/4959 [1:13:52<1:07:08,  1.89s/it]

 57%|█████▋    | 2826/4959 [1:13:54<1:08:02,  1.91s/it]

 57%|█████▋    | 2827/4959 [1:13:55<1:04:57,  1.83s/it]

 57%|█████▋    | 2828/4959 [1:13:57<1:02:49,  1.77s/it]

 57%|█████▋    | 2829/4959 [1:13:59<1:01:20,  1.73s/it]

 57%|█████▋    | 2830/4959 [1:14:00<1:00:33,  1.71s/it]

 57%|█████▋    | 2831/4959 [1:14:02<59:47,  1.69s/it]

 57%|█████▋    | 2832/4959 [1:14:04<1:02:58,  1.78s/it]

 57%|█████▋    | 2833/4959 [1:14:05<1:01:29,  1.74s/it]

 57%|█████▋    | 2834/4959 [1:14:07<1:04:12,  1.81s/it]

 57%|█████▋    | 2835/4959 [1:14:09<1:05:58,  1.86s/it]

 57%|█████▋    | 2836/4959 [1:14:11<1:07:19,  1.90s/it]

 57%|█████▋    | 2837/4959 [1:14:13<1:08:24,  1.93s/it]

 57%|█████▋    | 2838/4959 [1:14:15<1:08:47,  1.95s/it]

 57%|█████▋    | 2839/4959 [1:14:17<1:05:29,  1.85s/it]

 57%|█████▋    | 2840/4959 [1:14:19<1:03:12,  1.79s/it]

 57%|█████▋    | 2841/4959 [1:14:20<1:01:34,  1.74s/it]

 57%|█████▋    | 2842/4959 [1:14:22<1:00:12,  1.71s/it]

 57%|█████▋    | 2843/4959 [1:14:24<59:27,  1.69s/it]

 57%|█████▋    | 2844/4959 [1:14:25<58:49,  1.67s/it]

 57%|█████▋    | 2845/4959 [1:14:27<1:02:09,  1.76s/it]

 57%|█████▋    | 2846/4959 [1:14:29<1:05:18,  1.85s/it]

 57%|█████▋    | 2847/4959 [1:14:31<1:06:37,  1.89s/it]

 57%|█████▋    | 2848/4959 [1:14:33<1:04:01,  1.82s/it]

 57%|█████▋    | 2849/4959 [1:14:35<1:05:52,  1.87s/it]

 57%|█████▋    | 2850/4959 [1:14:37<1:03:14,  1.80s/it]

 57%|█████▋    | 2851/4959 [1:14:39<1:05:15,  1.86s/it]

 58%|█████▊    | 2852/4959 [1:14:40<1:02:46,  1.79s/it]

 58%|█████▊    | 2853/4959 [1:14:42<1:01:12,  1.74s/it]

 58%|█████▊    | 2854/4959 [1:14:44<1:03:38,  1.81s/it]

 58%|█████▊    | 2855/4959 [1:14:45<1:01:48,  1.76s/it]

 58%|█████▊    | 2856/4959 [1:14:47<1:03:59,  1.83s/it]

 58%|█████▊    | 2857/4959 [1:14:49<1:01:57,  1.77s/it]

 58%|█████▊    | 2858/4959 [1:14:51<1:04:10,  1.83s/it]

 58%|█████▊    | 2859/4959 [1:14:53<1:01:55,  1.77s/it]

 58%|█████▊    | 2860/4959 [1:14:54<1:00:29,  1.73s/it]

 58%|█████▊    | 2861/4959 [1:14:56<59:27,  1.70s/it]

 58%|█████▊    | 2862/4959 [1:14:58<1:02:18,  1.78s/it]

 58%|█████▊    | 2863/4959 [1:15:00<1:04:22,  1.84s/it]

 58%|█████▊    | 2864/4959 [1:15:02<1:05:42,  1.88s/it]

 58%|█████▊    | 2865/4959 [1:15:04<1:06:53,  1.92s/it]

 58%|█████▊    | 2866/4959 [1:15:06<1:07:24,  1.93s/it]

 58%|█████▊    | 2867/4959 [1:15:08<1:07:57,  1.95s/it]

 58%|█████▊    | 2868/4959 [1:15:09<1:04:49,  1.86s/it]

 58%|█████▊    | 2869/4959 [1:15:11<1:02:37,  1.80s/it]

 58%|█████▊    | 2870/4959 [1:15:13<1:04:29,  1.85s/it]

 58%|█████▊    | 2871/4959 [1:15:15<1:02:12,  1.79s/it]

 58%|█████▊    | 2872/4959 [1:15:17<1:04:18,  1.85s/it]

 58%|█████▊    | 2873/4959 [1:15:19<1:05:29,  1.88s/it]

 58%|█████▊    | 2874/4959 [1:15:21<1:06:32,  1.91s/it]

 58%|█████▊    | 2875/4959 [1:15:22<1:03:47,  1.84s/it]

 58%|█████▊    | 2876/4959 [1:15:24<1:05:25,  1.88s/it]

 58%|█████▊    | 2877/4959 [1:15:26<1:02:47,  1.81s/it]

 58%|█████▊    | 2878/4959 [1:15:28<1:00:51,  1.75s/it]

 58%|█████▊    | 2879/4959 [1:15:30<1:03:06,  1.82s/it]

 58%|█████▊    | 2880/4959 [1:15:32<1:04:57,  1.87s/it]

 58%|█████▊    | 2881/4959 [1:15:33<1:02:30,  1.80s/it]

 58%|█████▊    | 2882/4959 [1:15:35<1:04:24,  1.86s/it]

 58%|█████▊    | 2883/4959 [1:15:37<1:01:55,  1.79s/it]

 58%|█████▊    | 2884/4959 [1:15:38<1:00:40,  1.75s/it]

 58%|█████▊    | 2885/4959 [1:15:40<1:03:04,  1.82s/it]

 58%|█████▊    | 2886/4959 [1:15:42<1:04:40,  1.87s/it]

 58%|█████▊    | 2887/4959 [1:15:44<1:02:08,  1.80s/it]

 58%|█████▊    | 2888/4959 [1:15:46<1:00:23,  1.75s/it]

 58%|█████▊    | 2889/4959 [1:15:47<59:25,  1.72s/it]

 58%|█████▊    | 2890/4959 [1:15:49<1:02:17,  1.81s/it]

 58%|█████▊    | 2891/4959 [1:15:51<1:04:04,  1.86s/it]

 58%|█████▊    | 2892/4959 [1:15:53<1:05:22,  1.90s/it]

 58%|█████▊    | 2893/4959 [1:15:55<1:02:45,  1.82s/it]

 58%|█████▊    | 2894/4959 [1:15:57<1:00:36,  1.76s/it]

 58%|█████▊    | 2895/4959 [1:15:58<59:04,  1.72s/it]

 58%|█████▊    | 2896/4959 [1:16:00<58:03,  1.69s/it]

 58%|█████▊    | 2897/4959 [1:16:01<57:22,  1.67s/it]

 58%|█████▊    | 2898/4959 [1:16:04<1:02:29,  1.82s/it]

 58%|█████▊    | 2899/4959 [1:16:06<1:04:07,  1.87s/it]

 58%|█████▊    | 2900/4959 [1:16:07<1:01:40,  1.80s/it]

 58%|█████▊    | 2901/4959 [1:16:09<1:04:49,  1.89s/it]

 59%|█████▊    | 2902/4959 [1:16:11<1:05:33,  1.91s/it]

 59%|█████▊    | 2903/4959 [1:16:13<1:06:01,  1.93s/it]

 59%|█████▊    | 2904/4959 [1:16:15<1:02:55,  1.84s/it]

 59%|█████▊    | 2905/4959 [1:16:17<1:04:17,  1.88s/it]

 59%|█████▊    | 2906/4959 [1:16:18<1:01:36,  1.80s/it]

 59%|█████▊    | 2907/4959 [1:16:20<59:52,  1.75s/it]

 59%|█████▊    | 2908/4959 [1:16:22<1:02:29,  1.83s/it]

 59%|█████▊    | 2909/4959 [1:16:24<1:03:55,  1.87s/it]

 59%|█████▊    | 2910/4959 [1:16:26<1:01:29,  1.80s/it]

 59%|█████▊    | 2911/4959 [1:16:27<59:38,  1.75s/it]

 59%|█████▊    | 2912/4959 [1:16:29<58:50,  1.72s/it]

 59%|█████▊    | 2913/4959 [1:16:31<1:01:39,  1.81s/it]

 59%|█████▉    | 2914/4959 [1:16:33<1:03:39,  1.87s/it]

 59%|█████▉    | 2915/4959 [1:16:35<1:04:45,  1.90s/it]

 59%|█████▉    | 2916/4959 [1:16:37<1:01:52,  1.82s/it]

 59%|█████▉    | 2917/4959 [1:16:39<1:03:24,  1.86s/it]

 59%|█████▉    | 2918/4959 [1:16:40<1:00:51,  1.79s/it]

 59%|█████▉    | 2919/4959 [1:16:42<1:02:55,  1.85s/it]

 59%|█████▉    | 2920/4959 [1:16:44<1:02:00,  1.82s/it]

 59%|█████▉    | 2921/4959 [1:16:46<1:00:00,  1.77s/it]

 59%|█████▉    | 2922/4959 [1:16:48<1:02:11,  1.83s/it]

 59%|█████▉    | 2923/4959 [1:16:49<1:00:07,  1.77s/it]

 59%|█████▉    | 2924/4959 [1:16:51<58:31,  1.73s/it]

 59%|█████▉    | 2925/4959 [1:16:52<57:19,  1.69s/it]

 59%|█████▉    | 2926/4959 [1:16:54<56:49,  1.68s/it]

 59%|█████▉    | 2927/4959 [1:16:56<56:14,  1.66s/it]

 59%|█████▉    | 2928/4959 [1:16:57<55:49,  1.65s/it]

 59%|█████▉    | 2929/4959 [1:16:59<55:48,  1.65s/it]

 59%|█████▉    | 2930/4959 [1:17:01<59:17,  1.75s/it]

 59%|█████▉    | 2931/4959 [1:17:03<57:55,  1.71s/it]

 59%|█████▉    | 2932/4959 [1:17:05<1:00:34,  1.79s/it]

 59%|█████▉    | 2933/4959 [1:17:07<1:02:21,  1.85s/it]

 59%|█████▉    | 2934/4959 [1:17:08<1:00:03,  1.78s/it]

 59%|█████▉    | 2935/4959 [1:17:10<58:26,  1.73s/it]

 59%|█████▉    | 2936/4959 [1:17:12<1:00:53,  1.81s/it]

 59%|█████▉    | 2937/4959 [1:17:13<59:05,  1.75s/it]

 59%|█████▉    | 2938/4959 [1:17:15<1:01:18,  1.82s/it]

 59%|█████▉    | 2939/4959 [1:17:17<1:02:54,  1.87s/it]

 59%|█████▉    | 2940/4959 [1:17:19<1:00:28,  1.80s/it]

 59%|█████▉    | 2941/4959 [1:17:21<1:02:29,  1.86s/it]

 59%|█████▉    | 2942/4959 [1:17:23<1:03:35,  1.89s/it]

 59%|█████▉    | 2943/4959 [1:17:25<1:05:00,  1.93s/it]

 59%|█████▉    | 2944/4959 [1:17:27<1:05:36,  1.95s/it]

 59%|█████▉    | 2945/4959 [1:17:29<1:06:00,  1.97s/it]

 59%|█████▉    | 2946/4959 [1:17:31<1:08:12,  2.03s/it]

 59%|█████▉    | 2947/4959 [1:17:33<1:07:35,  2.02s/it]

 59%|█████▉    | 2948/4959 [1:17:35<1:03:43,  1.90s/it]

 59%|█████▉    | 2949/4959 [1:17:36<1:00:54,  1.82s/it]

 59%|█████▉    | 2950/4959 [1:17:38<59:03,  1.76s/it]

 60%|█████▉    | 2951/4959 [1:17:40<58:52,  1.76s/it]

 60%|█████▉    | 2952/4959 [1:17:42<1:00:54,  1.82s/it]

 60%|█████▉    | 2953/4959 [1:17:43<58:52,  1.76s/it]

 60%|█████▉    | 2954/4959 [1:17:45<57:47,  1.73s/it]

 60%|█████▉    | 2955/4959 [1:17:47<1:00:16,  1.80s/it]

 60%|█████▉    | 2956/4959 [1:17:49<58:32,  1.75s/it]

 60%|█████▉    | 2957/4959 [1:17:50<57:11,  1.71s/it]

 60%|█████▉    | 2958/4959 [1:17:52<56:14,  1.69s/it]

 60%|█████▉    | 2959/4959 [1:17:54<59:16,  1.78s/it]

 60%|█████▉    | 2960/4959 [1:17:56<57:46,  1.73s/it]

 60%|█████▉    | 2961/4959 [1:17:57<56:41,  1.70s/it]

 60%|█████▉    | 2962/4959 [1:17:59<56:00,  1.68s/it]

 60%|█████▉    | 2963/4959 [1:18:00<56:08,  1.69s/it]

 60%|█████▉    | 2964/4959 [1:18:02<58:50,  1.77s/it]

 60%|█████▉    | 2965/4959 [1:18:04<1:00:48,  1.83s/it]

 60%|█████▉    | 2966/4959 [1:18:06<58:49,  1.77s/it]

 60%|█████▉    | 2967/4959 [1:18:08<1:00:43,  1.83s/it]

 60%|█████▉    | 2968/4959 [1:18:10<1:02:33,  1.89s/it]

 60%|█████▉    | 2969/4959 [1:18:12<1:03:24,  1.91s/it]

 60%|█████▉    | 2970/4959 [1:18:14<1:00:43,  1.83s/it]

 60%|█████▉    | 2971/4959 [1:18:16<1:02:14,  1.88s/it]

 60%|█████▉    | 2972/4959 [1:18:17<59:42,  1.80s/it]

 60%|█████▉    | 2973/4959 [1:18:19<58:00,  1.75s/it]

 60%|█████▉    | 2974/4959 [1:18:21<1:00:06,  1.82s/it]

 60%|█████▉    | 2975/4959 [1:18:22<58:05,  1.76s/it]

 60%|██████    | 2976/4959 [1:18:24<57:04,  1.73s/it]

 60%|██████    | 2977/4959 [1:18:26<56:01,  1.70s/it]

 60%|██████    | 2978/4959 [1:18:27<55:12,  1.67s/it]

 60%|██████    | 2979/4959 [1:18:29<58:16,  1.77s/it]

 60%|██████    | 2980/4959 [1:18:31<57:03,  1.73s/it]

 60%|██████    | 2981/4959 [1:18:33<56:03,  1.70s/it]

 60%|██████    | 2982/4959 [1:18:34<56:52,  1.73s/it]

 60%|██████    | 2983/4959 [1:18:36<55:59,  1.70s/it]

 60%|██████    | 2984/4959 [1:18:38<55:15,  1.68s/it]

 60%|██████    | 2985/4959 [1:18:40<57:58,  1.76s/it]

 60%|██████    | 2986/4959 [1:18:42<1:00:04,  1.83s/it]

 60%|██████    | 2987/4959 [1:18:43<58:06,  1.77s/it]

 60%|██████    | 2988/4959 [1:18:45<56:46,  1.73s/it]

 60%|██████    | 2989/4959 [1:18:47<55:47,  1.70s/it]

 60%|██████    | 2990/4959 [1:18:49<58:34,  1.78s/it]

 60%|██████    | 2991/4959 [1:18:51<1:00:31,  1.85s/it]

 60%|██████    | 2992/4959 [1:18:52<1:01:47,  1.89s/it]

 60%|██████    | 2993/4959 [1:18:54<1:02:51,  1.92s/it]

 60%|██████    | 2994/4959 [1:18:56<1:00:02,  1.83s/it]

 60%|██████    | 2995/4959 [1:18:58<58:07,  1.78s/it]

 60%|██████    | 2996/4959 [1:18:59<56:31,  1.73s/it]

 60%|██████    | 2997/4959 [1:19:01<59:06,  1.81s/it]

 60%|██████    | 2998/4959 [1:19:03<57:13,  1.75s/it]

 60%|██████    | 2999/4959 [1:19:05<55:52,  1.71s/it]

 60%|██████    | 3000/4959 [1:19:07<58:26,  1.79s/it]

 61%|██████    | 3001/4959 [1:19:08<56:52,  1.74s/it]

 61%|██████    | 3002/4959 [1:19:10<55:40,  1.71s/it]

 61%|██████    | 3003/4959 [1:19:11<54:51,  1.68s/it]

 61%|██████    | 3004/4959 [1:19:13<57:39,  1.77s/it]

 61%|██████    | 3005/4959 [1:19:15<59:44,  1.83s/it]

 61%|██████    | 3006/4959 [1:19:17<1:01:21,  1.88s/it]

 61%|██████    | 3007/4959 [1:19:19<58:48,  1.81s/it]

 61%|██████    | 3008/4959 [1:19:21<1:00:25,  1.86s/it]

 61%|██████    | 3009/4959 [1:19:23<58:07,  1.79s/it]

 61%|██████    | 3010/4959 [1:19:24<56:34,  1.74s/it]

 61%|██████    | 3011/4959 [1:19:26<55:27,  1.71s/it]

 61%|██████    | 3012/4959 [1:19:28<58:07,  1.79s/it]

 61%|██████    | 3013/4959 [1:19:30<59:52,  1.85s/it]

 61%|██████    | 3014/4959 [1:19:32<1:01:13,  1.89s/it]

 61%|██████    | 3015/4959 [1:19:33<58:45,  1.81s/it]

 61%|██████    | 3016/4959 [1:19:35<56:54,  1.76s/it]

 61%|██████    | 3017/4959 [1:19:37<55:37,  1.72s/it]

 61%|██████    | 3018/4959 [1:19:39<58:08,  1.80s/it]

 61%|██████    | 3019/4959 [1:19:41<59:51,  1.85s/it]

 61%|██████    | 3020/4959 [1:19:42<57:38,  1.78s/it]

 61%|██████    | 3021/4959 [1:19:44<56:07,  1.74s/it]

 61%|██████    | 3022/4959 [1:19:46<55:03,  1.71s/it]

 61%|██████    | 3023/4959 [1:19:47<54:25,  1.69s/it]

 61%|██████    | 3024/4959 [1:19:49<57:20,  1.78s/it]

 61%|██████    | 3025/4959 [1:19:51<59:06,  1.83s/it]

 61%|██████    | 3026/4959 [1:19:53<57:24,  1.78s/it]

 61%|██████    | 3027/4959 [1:19:54<55:57,  1.74s/it]

 61%|██████    | 3028/4959 [1:19:56<55:48,  1.73s/it]

 61%|██████    | 3029/4959 [1:19:58<58:16,  1.81s/it]

 61%|██████    | 3030/4959 [1:20:00<56:33,  1.76s/it]

 61%|██████    | 3031/4959 [1:20:02<58:33,  1.82s/it]

 61%|██████    | 3032/4959 [1:20:04<1:00:08,  1.87s/it]

 61%|██████    | 3033/4959 [1:20:05<57:42,  1.80s/it]

 61%|██████    | 3034/4959 [1:20:07<59:22,  1.85s/it]

 61%|██████    | 3035/4959 [1:20:09<1:00:45,  1.89s/it]

 61%|██████    | 3036/4959 [1:20:11<58:35,  1.83s/it]

 61%|██████    | 3037/4959 [1:20:13<56:38,  1.77s/it]

 61%|██████▏   | 3038/4959 [1:20:14<55:17,  1.73s/it]

 61%|██████▏   | 3039/4959 [1:20:16<54:23,  1.70s/it]

 61%|██████▏   | 3040/4959 [1:20:18<53:47,  1.68s/it]

 61%|██████▏   | 3041/4959 [1:20:19<53:31,  1.67s/it]

 61%|██████▏   | 3042/4959 [1:20:21<53:12,  1.67s/it]

 61%|██████▏   | 3043/4959 [1:20:23<52:54,  1.66s/it]

 61%|██████▏   | 3044/4959 [1:20:25<56:00,  1.75s/it]

 61%|██████▏   | 3045/4959 [1:20:26<54:48,  1.72s/it]

 61%|██████▏   | 3046/4959 [1:20:28<53:57,  1.69s/it]

 61%|██████▏   | 3047/4959 [1:20:30<56:48,  1.78s/it]

 61%|██████▏   | 3048/4959 [1:20:31<55:24,  1.74s/it]

 61%|██████▏   | 3049/4959 [1:20:33<54:22,  1.71s/it]

 62%|██████▏   | 3050/4959 [1:20:35<53:34,  1.68s/it]

 62%|██████▏   | 3051/4959 [1:20:37<56:20,  1.77s/it]

 62%|██████▏   | 3052/4959 [1:20:38<55:01,  1.73s/it]

 62%|██████▏   | 3053/4959 [1:20:40<57:38,  1.81s/it]

 62%|██████▏   | 3054/4959 [1:20:42<58:59,  1.86s/it]

 62%|██████▏   | 3055/4959 [1:20:44<1:00:13,  1.90s/it]

 62%|██████▏   | 3056/4959 [1:20:46<1:01:00,  1.92s/it]

 62%|██████▏   | 3057/4959 [1:20:48<1:01:43,  1.95s/it]

 62%|██████▏   | 3058/4959 [1:20:50<1:01:56,  1.96s/it]

 62%|██████▏   | 3059/4959 [1:20:52<1:02:10,  1.96s/it]

 62%|██████▏   | 3060/4959 [1:20:54<1:04:03,  2.02s/it]

 62%|██████▏   | 3061/4959 [1:20:57<1:05:25,  2.07s/it]

 62%|██████▏   | 3062/4959 [1:20:58<1:01:12,  1.94s/it]

 62%|██████▏   | 3063/4959 [1:21:00<1:01:44,  1.95s/it]

 62%|██████▏   | 3064/4959 [1:21:02<1:02:05,  1.97s/it]

 62%|██████▏   | 3065/4959 [1:21:04<58:58,  1.87s/it]

 62%|██████▏   | 3066/4959 [1:21:06<1:00:07,  1.91s/it]

 62%|██████▏   | 3067/4959 [1:21:08<1:00:48,  1.93s/it]

 62%|██████▏   | 3068/4959 [1:21:10<1:01:23,  1.95s/it]

 62%|██████▏   | 3069/4959 [1:21:12<1:01:46,  1.96s/it]

 62%|██████▏   | 3070/4959 [1:21:14<1:02:09,  1.97s/it]

 62%|██████▏   | 3071/4959 [1:21:15<58:55,  1.87s/it]

 62%|██████▏   | 3072/4959 [1:21:18<1:01:45,  1.96s/it]

 62%|██████▏   | 3073/4959 [1:21:20<1:02:02,  1.97s/it]

 62%|██████▏   | 3074/4959 [1:21:22<1:02:25,  1.99s/it]

 62%|██████▏   | 3075/4959 [1:21:24<1:02:27,  1.99s/it]

 62%|██████▏   | 3076/4959 [1:21:26<1:02:49,  2.00s/it]

 62%|██████▏   | 3077/4959 [1:21:28<1:02:47,  2.00s/it]

 62%|██████▏   | 3078/4959 [1:21:30<1:02:50,  2.00s/it]

 62%|██████▏   | 3079/4959 [1:21:32<1:02:42,  2.00s/it]

 62%|██████▏   | 3080/4959 [1:21:34<1:02:34,  2.00s/it]

 62%|██████▏   | 3081/4959 [1:21:36<1:02:28,  2.00s/it]

 62%|██████▏   | 3082/4959 [1:21:38<1:04:12,  2.05s/it]

 62%|██████▏   | 3083/4959 [1:21:40<1:03:33,  2.03s/it]

 62%|██████▏   | 3084/4959 [1:21:42<1:05:00,  2.08s/it]

 62%|██████▏   | 3085/4959 [1:21:44<1:04:32,  2.07s/it]

 62%|██████▏   | 3086/4959 [1:21:46<1:03:45,  2.04s/it]

 62%|██████▏   | 3087/4959 [1:21:48<1:03:17,  2.03s/it]

 62%|██████▏   | 3088/4959 [1:21:50<1:03:00,  2.02s/it]

 62%|██████▏   | 3089/4959 [1:21:52<1:02:40,  2.01s/it]

 62%|██████▏   | 3090/4959 [1:21:54<1:02:22,  2.00s/it]

 62%|██████▏   | 3091/4959 [1:21:56<1:04:10,  2.06s/it]

 62%|██████▏   | 3092/4959 [1:21:58<1:03:18,  2.03s/it]

 62%|██████▏   | 3093/4959 [1:22:00<1:02:47,  2.02s/it]

 62%|██████▏   | 3094/4959 [1:22:02<59:25,  1.91s/it]

 62%|██████▏   | 3095/4959 [1:22:03<56:48,  1.83s/it]

 62%|██████▏   | 3096/4959 [1:22:05<58:16,  1.88s/it]

 62%|██████▏   | 3097/4959 [1:22:07<56:03,  1.81s/it]

 62%|██████▏   | 3098/4959 [1:22:09<57:38,  1.86s/it]

 62%|██████▏   | 3099/4959 [1:22:11<58:41,  1.89s/it]

 63%|██████▎   | 3100/4959 [1:22:13<56:26,  1.82s/it]

 63%|██████▎   | 3101/4959 [1:22:14<55:22,  1.79s/it]

 63%|██████▎   | 3102/4959 [1:22:16<57:15,  1.85s/it]

 63%|██████▎   | 3103/4959 [1:22:18<58:27,  1.89s/it]

 63%|██████▎   | 3104/4959 [1:22:20<59:08,  1.91s/it]

 63%|██████▎   | 3105/4959 [1:22:22<59:36,  1.93s/it]

 63%|██████▎   | 3106/4959 [1:22:24<1:00:00,  1.94s/it]

 63%|██████▎   | 3107/4959 [1:22:26<57:07,  1.85s/it]

 63%|██████▎   | 3108/4959 [1:22:28<58:30,  1.90s/it]

 63%|██████▎   | 3109/4959 [1:22:30<59:17,  1.92s/it]

 63%|██████▎   | 3110/4959 [1:22:32<56:43,  1.84s/it]

 63%|██████▎   | 3111/4959 [1:22:33<54:48,  1.78s/it]

 63%|██████▎   | 3112/4959 [1:22:35<53:34,  1.74s/it]

 63%|██████▎   | 3113/4959 [1:22:37<55:48,  1.81s/it]

 63%|██████▎   | 3114/4959 [1:22:38<54:11,  1.76s/it]

 63%|██████▎   | 3115/4959 [1:22:40<56:03,  1.82s/it]

 63%|██████▎   | 3116/4959 [1:22:42<54:19,  1.77s/it]

 63%|██████▎   | 3117/4959 [1:22:44<56:32,  1.84s/it]

 63%|██████▎   | 3118/4959 [1:22:46<57:43,  1.88s/it]

 63%|██████▎   | 3119/4959 [1:22:48<58:34,  1.91s/it]

 63%|██████▎   | 3120/4959 [1:22:50<59:42,  1.95s/it]

 63%|██████▎   | 3121/4959 [1:22:52<59:58,  1.96s/it]

 63%|██████▎   | 3122/4959 [1:22:54<56:57,  1.86s/it]

 63%|██████▎   | 3123/4959 [1:22:55<54:51,  1.79s/it]

 63%|██████▎   | 3124/4959 [1:22:57<56:31,  1.85s/it]

 63%|██████▎   | 3125/4959 [1:22:59<57:36,  1.88s/it]

 63%|██████▎   | 3126/4959 [1:23:01<55:13,  1.81s/it]

 63%|██████▎   | 3127/4959 [1:23:03<56:37,  1.85s/it]

 63%|██████▎   | 3128/4959 [1:23:04<54:27,  1.78s/it]

 63%|██████▎   | 3129/4959 [1:23:06<56:17,  1.85s/it]

 63%|██████▎   | 3130/4959 [1:23:08<57:26,  1.88s/it]

 63%|██████▎   | 3131/4959 [1:23:10<55:10,  1.81s/it]

 63%|██████▎   | 3132/4959 [1:23:12<53:30,  1.76s/it]

 63%|██████▎   | 3133/4959 [1:23:14<55:29,  1.82s/it]

 63%|██████▎   | 3134/4959 [1:23:15<53:46,  1.77s/it]

 63%|██████▎   | 3135/4959 [1:23:17<52:28,  1.73s/it]

 63%|██████▎   | 3136/4959 [1:23:19<51:37,  1.70s/it]

 63%|██████▎   | 3137/4959 [1:23:21<54:14,  1.79s/it]

 63%|██████▎   | 3138/4959 [1:23:23<56:25,  1.86s/it]

 63%|██████▎   | 3139/4959 [1:23:25<57:36,  1.90s/it]

 63%|██████▎   | 3140/4959 [1:23:26<55:07,  1.82s/it]

 63%|██████▎   | 3141/4959 [1:23:28<53:24,  1.76s/it]

 63%|██████▎   | 3142/4959 [1:23:30<55:19,  1.83s/it]

 63%|██████▎   | 3143/4959 [1:23:32<56:49,  1.88s/it]

 63%|██████▎   | 3144/4959 [1:23:34<57:47,  1.91s/it]

 63%|██████▎   | 3145/4959 [1:23:35<55:13,  1.83s/it]

 63%|██████▎   | 3146/4959 [1:23:37<56:42,  1.88s/it]

 63%|██████▎   | 3147/4959 [1:23:39<57:27,  1.90s/it]

 63%|██████▎   | 3148/4959 [1:23:41<54:56,  1.82s/it]

 64%|██████▎   | 3149/4959 [1:23:43<53:33,  1.78s/it]

 64%|██████▎   | 3150/4959 [1:23:44<52:19,  1.74s/it]

 64%|██████▎   | 3151/4959 [1:23:46<51:24,  1.71s/it]

 64%|██████▎   | 3152/4959 [1:23:48<50:37,  1.68s/it]

 64%|██████▎   | 3153/4959 [1:23:49<50:15,  1.67s/it]

 64%|██████▎   | 3154/4959 [1:23:51<53:03,  1.76s/it]

 64%|██████▎   | 3155/4959 [1:23:53<55:03,  1.83s/it]

 64%|██████▎   | 3156/4959 [1:23:55<56:25,  1.88s/it]

 64%|██████▎   | 3157/4959 [1:23:57<57:29,  1.91s/it]

 64%|██████▎   | 3158/4959 [1:23:59<58:17,  1.94s/it]

 64%|██████▎   | 3159/4959 [1:24:01<58:39,  1.96s/it]

 64%|██████▎   | 3160/4959 [1:24:03<59:02,  1.97s/it]

 64%|██████▎   | 3161/4959 [1:24:05<1:01:05,  2.04s/it]

 64%|██████▍   | 3162/4959 [1:24:07<1:00:26,  2.02s/it]

 64%|██████▍   | 3163/4959 [1:24:09<59:57,  2.00s/it]

 64%|██████▍   | 3164/4959 [1:24:11<59:47,  2.00s/it]

 64%|██████▍   | 3165/4959 [1:24:13<1:00:15,  2.02s/it]

 64%|██████▍   | 3166/4959 [1:24:15<1:00:00,  2.01s/it]

 64%|██████▍   | 3167/4959 [1:24:17<59:47,  2.00s/it]

 64%|██████▍   | 3168/4959 [1:24:19<59:36,  2.00s/it]

 64%|██████▍   | 3169/4959 [1:24:21<59:24,  1.99s/it]

 64%|██████▍   | 3170/4959 [1:24:23<59:14,  1.99s/it]

 64%|██████▍   | 3171/4959 [1:24:25<59:04,  1.98s/it]

 64%|██████▍   | 3172/4959 [1:24:27<58:48,  1.97s/it]

 64%|██████▍   | 3173/4959 [1:24:29<59:01,  1.98s/it]

 64%|██████▍   | 3174/4959 [1:24:31<58:57,  1.98s/it]

 64%|██████▍   | 3175/4959 [1:24:33<1:00:35,  2.04s/it]

 64%|██████▍   | 3176/4959 [1:24:35<59:57,  2.02s/it]

 64%|██████▍   | 3177/4959 [1:24:37<59:39,  2.01s/it]

 64%|██████▍   | 3178/4959 [1:24:39<59:17,  2.00s/it]

 64%|██████▍   | 3179/4959 [1:24:41<59:07,  1.99s/it]

 64%|██████▍   | 3180/4959 [1:24:43<58:55,  1.99s/it]

 64%|██████▍   | 3181/4959 [1:24:45<58:59,  1.99s/it]

 64%|██████▍   | 3182/4959 [1:24:47<58:44,  1.98s/it]

 64%|██████▍   | 3183/4959 [1:24:49<58:32,  1.98s/it]

 64%|██████▍   | 3184/4959 [1:24:51<58:24,  1.97s/it]

 64%|██████▍   | 3185/4959 [1:24:53<58:11,  1.97s/it]

 64%|██████▍   | 3186/4959 [1:24:55<58:07,  1.97s/it]

 64%|██████▍   | 3187/4959 [1:24:57<58:08,  1.97s/it]

 64%|██████▍   | 3188/4959 [1:24:59<58:07,  1.97s/it]

 64%|██████▍   | 3189/4959 [1:25:01<58:11,  1.97s/it]

 64%|██████▍   | 3190/4959 [1:25:03<58:07,  1.97s/it]

 64%|██████▍   | 3191/4959 [1:25:05<58:04,  1.97s/it]

 64%|██████▍   | 3192/4959 [1:25:07<58:03,  1.97s/it]

 64%|██████▍   | 3193/4959 [1:25:09<57:58,  1.97s/it]

 64%|██████▍   | 3194/4959 [1:25:11<57:49,  1.97s/it]

 64%|██████▍   | 3195/4959 [1:25:13<57:45,  1.96s/it]

 64%|██████▍   | 3196/4959 [1:25:15<57:46,  1.97s/it]

 64%|██████▍   | 3197/4959 [1:25:17<57:48,  1.97s/it]

 64%|██████▍   | 3198/4959 [1:25:18<54:44,  1.86s/it]

 65%|██████▍   | 3199/4959 [1:25:20<55:39,  1.90s/it]

 65%|██████▍   | 3200/4959 [1:25:22<56:08,  1.92s/it]

 65%|██████▍   | 3201/4959 [1:25:24<56:46,  1.94s/it]

 65%|██████▍   | 3202/4959 [1:25:26<58:36,  2.00s/it]

 65%|██████▍   | 3203/4959 [1:25:28<58:38,  2.00s/it]

 65%|██████▍   | 3204/4959 [1:25:30<58:21,  2.00s/it]

 65%|██████▍   | 3205/4959 [1:25:32<55:07,  1.89s/it]

 65%|██████▍   | 3206/4959 [1:25:34<56:21,  1.93s/it]

 65%|██████▍   | 3207/4959 [1:25:36<56:44,  1.94s/it]

 65%|██████▍   | 3208/4959 [1:25:38<54:04,  1.85s/it]

 65%|██████▍   | 3209/4959 [1:25:40<55:06,  1.89s/it]

 65%|██████▍   | 3210/4959 [1:25:42<55:37,  1.91s/it]

 65%|██████▍   | 3211/4959 [1:25:44<56:07,  1.93s/it]

 65%|██████▍   | 3212/4959 [1:25:46<56:27,  1.94s/it]

 65%|██████▍   | 3213/4959 [1:25:48<57:01,  1.96s/it]

 65%|██████▍   | 3214/4959 [1:25:50<57:05,  1.96s/it]

 65%|██████▍   | 3215/4959 [1:25:51<57:04,  1.96s/it]

 65%|██████▍   | 3216/4959 [1:25:53<56:54,  1.96s/it]

 65%|██████▍   | 3217/4959 [1:25:55<56:51,  1.96s/it]

 65%|██████▍   | 3218/4959 [1:25:57<56:53,  1.96s/it]

 65%|██████▍   | 3219/4959 [1:25:59<56:50,  1.96s/it]

 65%|██████▍   | 3220/4959 [1:26:01<56:48,  1.96s/it]

 65%|██████▍   | 3221/4959 [1:26:03<56:52,  1.96s/it]

 65%|██████▍   | 3222/4959 [1:26:05<56:58,  1.97s/it]

 65%|██████▍   | 3223/4959 [1:26:07<56:49,  1.96s/it]

 65%|██████▌   | 3224/4959 [1:26:09<56:49,  1.97s/it]

 65%|██████▌   | 3225/4959 [1:26:11<56:52,  1.97s/it]

 65%|██████▌   | 3226/4959 [1:26:13<56:59,  1.97s/it]

 65%|██████▌   | 3227/4959 [1:26:15<56:53,  1.97s/it]

 65%|██████▌   | 3228/4959 [1:26:17<56:53,  1.97s/it]

 65%|██████▌   | 3229/4959 [1:26:19<56:51,  1.97s/it]

 65%|██████▌   | 3230/4959 [1:26:21<56:56,  1.98s/it]

 65%|██████▌   | 3231/4959 [1:26:23<56:51,  1.97s/it]

 65%|██████▌   | 3232/4959 [1:26:25<56:48,  1.97s/it]

 65%|██████▌   | 3233/4959 [1:26:27<56:45,  1.97s/it]

 65%|██████▌   | 3234/4959 [1:26:29<56:40,  1.97s/it]

 65%|██████▌   | 3235/4959 [1:26:31<56:46,  1.98s/it]

 65%|██████▌   | 3236/4959 [1:26:33<56:36,  1.97s/it]

 65%|██████▌   | 3237/4959 [1:26:35<56:21,  1.96s/it]

 65%|██████▌   | 3238/4959 [1:26:37<56:15,  1.96s/it]

 65%|██████▌   | 3239/4959 [1:26:39<56:26,  1.97s/it]

 65%|██████▌   | 3240/4959 [1:26:41<56:28,  1.97s/it]

 65%|██████▌   | 3241/4959 [1:26:43<56:45,  1.98s/it]

 65%|██████▌   | 3242/4959 [1:26:45<56:39,  1.98s/it]

 65%|██████▌   | 3243/4959 [1:26:47<56:36,  1.98s/it]

 65%|██████▌   | 3244/4959 [1:26:49<56:29,  1.98s/it]

 65%|██████▌   | 3245/4959 [1:26:50<53:39,  1.88s/it]

 65%|██████▌   | 3246/4959 [1:26:52<54:29,  1.91s/it]

 65%|██████▌   | 3247/4959 [1:26:54<55:02,  1.93s/it]

 65%|██████▌   | 3248/4959 [1:26:56<55:18,  1.94s/it]

 66%|██████▌   | 3249/4959 [1:26:58<55:32,  1.95s/it]

 66%|██████▌   | 3250/4959 [1:27:00<55:41,  1.96s/it]

 66%|██████▌   | 3251/4959 [1:27:02<55:54,  1.96s/it]

 66%|██████▌   | 3252/4959 [1:27:04<57:27,  2.02s/it]

 66%|██████▌   | 3253/4959 [1:27:06<56:55,  2.00s/it]

 66%|██████▌   | 3254/4959 [1:27:08<58:13,  2.05s/it]

 66%|██████▌   | 3255/4959 [1:27:11<59:10,  2.08s/it]

 66%|██████▌   | 3256/4959 [1:27:13<58:13,  2.05s/it]

 66%|██████▌   | 3257/4959 [1:27:15<57:36,  2.03s/it]

 66%|██████▌   | 3258/4959 [1:27:17<58:44,  2.07s/it]

 66%|██████▌   | 3259/4959 [1:27:19<57:53,  2.04s/it]

 66%|██████▌   | 3260/4959 [1:27:21<57:14,  2.02s/it]

 66%|██████▌   | 3261/4959 [1:27:23<56:47,  2.01s/it]

 66%|██████▌   | 3262/4959 [1:27:25<56:19,  1.99s/it]

 66%|██████▌   | 3263/4959 [1:27:27<56:07,  1.99s/it]

 66%|██████▌   | 3264/4959 [1:27:29<56:27,  2.00s/it]

 66%|██████▌   | 3265/4959 [1:27:31<56:12,  1.99s/it]

 66%|██████▌   | 3266/4959 [1:27:33<56:08,  1.99s/it]

 66%|██████▌   | 3267/4959 [1:27:35<57:45,  2.05s/it]

 66%|██████▌   | 3268/4959 [1:27:37<57:06,  2.03s/it]

 66%|██████▌   | 3269/4959 [1:27:39<56:31,  2.01s/it]

 66%|██████▌   | 3270/4959 [1:27:41<57:47,  2.05s/it]

 66%|██████▌   | 3271/4959 [1:27:43<57:10,  2.03s/it]

 66%|██████▌   | 3272/4959 [1:27:45<56:37,  2.01s/it]

 66%|██████▌   | 3273/4959 [1:27:47<56:12,  2.00s/it]

 66%|██████▌   | 3274/4959 [1:27:49<56:00,  1.99s/it]

 66%|██████▌   | 3275/4959 [1:27:51<55:49,  1.99s/it]

 66%|██████▌   | 3276/4959 [1:27:52<52:52,  1.89s/it]

 66%|██████▌   | 3277/4959 [1:27:54<53:45,  1.92s/it]

 66%|██████▌   | 3278/4959 [1:27:56<54:03,  1.93s/it]

 66%|██████▌   | 3279/4959 [1:27:58<54:35,  1.95s/it]

 66%|██████▌   | 3280/4959 [1:28:00<51:46,  1.85s/it]

 66%|██████▌   | 3281/4959 [1:28:02<52:46,  1.89s/it]

 66%|██████▌   | 3282/4959 [1:28:03<50:29,  1.81s/it]

 66%|██████▌   | 3283/4959 [1:28:05<51:52,  1.86s/it]

 66%|██████▌   | 3284/4959 [1:28:07<49:54,  1.79s/it]

 66%|██████▌   | 3285/4959 [1:28:09<51:20,  1.84s/it]

 66%|██████▋   | 3286/4959 [1:28:11<52:18,  1.88s/it]

 66%|██████▋   | 3287/4959 [1:28:13<53:00,  1.90s/it]

 66%|██████▋   | 3288/4959 [1:28:15<53:59,  1.94s/it]

 66%|██████▋   | 3289/4959 [1:28:17<54:08,  1.95s/it]

 66%|██████▋   | 3290/4959 [1:28:19<54:42,  1.97s/it]

 66%|██████▋   | 3291/4959 [1:28:21<54:40,  1.97s/it]

 66%|██████▋   | 3292/4959 [1:28:23<54:56,  1.98s/it]

 66%|██████▋   | 3293/4959 [1:28:25<52:08,  1.88s/it]

 66%|██████▋   | 3294/4959 [1:28:27<53:08,  1.92s/it]

 66%|██████▋   | 3295/4959 [1:28:29<53:41,  1.94s/it]

 66%|██████▋   | 3296/4959 [1:28:31<54:07,  1.95s/it]

 66%|██████▋   | 3297/4959 [1:28:33<54:15,  1.96s/it]

 67%|██████▋   | 3298/4959 [1:28:35<54:39,  1.97s/it]

 67%|██████▋   | 3299/4959 [1:28:36<54:25,  1.97s/it]

 67%|██████▋   | 3300/4959 [1:28:38<51:40,  1.87s/it]

 67%|██████▋   | 3301/4959 [1:28:40<52:50,  1.91s/it]

 67%|██████▋   | 3302/4959 [1:28:42<53:26,  1.94s/it]

 67%|██████▋   | 3303/4959 [1:28:44<50:51,  1.84s/it]

 67%|██████▋   | 3304/4959 [1:28:45<49:03,  1.78s/it]

 67%|██████▋   | 3305/4959 [1:28:47<50:33,  1.83s/it]

 67%|██████▋   | 3306/4959 [1:28:49<51:41,  1.88s/it]

 67%|██████▋   | 3307/4959 [1:28:51<49:42,  1.81s/it]

 67%|██████▋   | 3308/4959 [1:28:53<48:18,  1.76s/it]

 67%|██████▋   | 3309/4959 [1:28:54<47:05,  1.71s/it]

 67%|██████▋   | 3310/4959 [1:28:56<49:12,  1.79s/it]

 67%|██████▋   | 3311/4959 [1:28:58<47:44,  1.74s/it]

 67%|██████▋   | 3312/4959 [1:29:00<49:36,  1.81s/it]

 67%|██████▋   | 3313/4959 [1:29:01<48:01,  1.75s/it]

 67%|██████▋   | 3314/4959 [1:29:03<49:46,  1.82s/it]

 67%|██████▋   | 3315/4959 [1:29:05<48:04,  1.75s/it]

 67%|██████▋   | 3316/4959 [1:29:07<49:51,  1.82s/it]

 67%|██████▋   | 3317/4959 [1:29:09<51:04,  1.87s/it]

 67%|██████▋   | 3318/4959 [1:29:11<51:56,  1.90s/it]

 67%|██████▋   | 3319/4959 [1:29:13<52:31,  1.92s/it]

 67%|██████▋   | 3320/4959 [1:29:15<52:51,  1.94s/it]

 67%|██████▋   | 3321/4959 [1:29:17<53:05,  1.94s/it]

 67%|██████▋   | 3322/4959 [1:29:19<53:10,  1.95s/it]

 67%|██████▋   | 3323/4959 [1:29:21<53:23,  1.96s/it]

 67%|██████▋   | 3324/4959 [1:29:23<53:29,  1.96s/it]

 67%|██████▋   | 3325/4959 [1:29:25<53:28,  1.96s/it]

 67%|██████▋   | 3326/4959 [1:29:27<53:25,  1.96s/it]

 67%|██████▋   | 3327/4959 [1:29:29<55:04,  2.02s/it]

 67%|██████▋   | 3328/4959 [1:29:31<54:39,  2.01s/it]

 67%|██████▋   | 3329/4959 [1:29:33<54:10,  1.99s/it]

 67%|██████▋   | 3330/4959 [1:29:35<53:56,  1.99s/it]

 67%|██████▋   | 3331/4959 [1:29:37<53:42,  1.98s/it]

 67%|██████▋   | 3332/4959 [1:29:38<50:42,  1.87s/it]

 67%|██████▋   | 3333/4959 [1:29:40<51:30,  1.90s/it]

 67%|██████▋   | 3334/4959 [1:29:42<51:51,  1.91s/it]

 67%|██████▋   | 3335/4959 [1:29:44<52:10,  1.93s/it]

 67%|██████▋   | 3336/4959 [1:29:46<52:27,  1.94s/it]

 67%|██████▋   | 3337/4959 [1:29:48<52:40,  1.95s/it]

 67%|██████▋   | 3338/4959 [1:29:50<52:45,  1.95s/it]

 67%|██████▋   | 3339/4959 [1:29:52<50:57,  1.89s/it]

 67%|██████▋   | 3340/4959 [1:29:54<52:32,  1.95s/it]

 67%|██████▋   | 3341/4959 [1:29:56<53:19,  1.98s/it]

 67%|██████▋   | 3342/4959 [1:29:58<53:46,  2.00s/it]

 67%|██████▋   | 3343/4959 [1:30:00<54:04,  2.01s/it]

 67%|██████▋   | 3344/4959 [1:30:02<54:25,  2.02s/it]

 67%|██████▋   | 3345/4959 [1:30:04<51:47,  1.93s/it]

 67%|██████▋   | 3346/4959 [1:30:06<54:14,  2.02s/it]

 67%|██████▋   | 3347/4959 [1:30:08<54:21,  2.02s/it]

 68%|██████▊   | 3348/4959 [1:30:10<54:44,  2.04s/it]

 68%|██████▊   | 3349/4959 [1:30:12<51:57,  1.94s/it]

 68%|██████▊   | 3350/4959 [1:30:14<50:01,  1.87s/it]

 68%|██████▊   | 3351/4959 [1:30:16<52:50,  1.97s/it]

 68%|██████▊   | 3352/4959 [1:30:18<52:49,  1.97s/it]

 68%|██████▊   | 3353/4959 [1:30:20<52:55,  1.98s/it]

 68%|██████▊   | 3354/4959 [1:30:21<50:00,  1.87s/it]

 68%|██████▊   | 3355/4959 [1:30:23<50:49,  1.90s/it]

 68%|██████▊   | 3356/4959 [1:30:25<51:17,  1.92s/it]

 68%|██████▊   | 3357/4959 [1:30:27<51:30,  1.93s/it]

 68%|██████▊   | 3358/4959 [1:30:29<51:51,  1.94s/it]

 68%|██████▊   | 3359/4959 [1:30:31<52:01,  1.95s/it]

 68%|██████▊   | 3360/4959 [1:30:33<49:22,  1.85s/it]

 68%|██████▊   | 3361/4959 [1:30:35<50:23,  1.89s/it]

 68%|██████▊   | 3362/4959 [1:30:37<51:02,  1.92s/it]

 68%|██████▊   | 3363/4959 [1:30:38<48:35,  1.83s/it]

 68%|██████▊   | 3364/4959 [1:30:40<46:53,  1.76s/it]

 68%|██████▊   | 3365/4959 [1:30:42<48:26,  1.82s/it]

 68%|██████▊   | 3366/4959 [1:30:44<51:09,  1.93s/it]

 68%|██████▊   | 3367/4959 [1:30:46<51:28,  1.94s/it]

 68%|██████▊   | 3368/4959 [1:30:48<52:14,  1.97s/it]

 68%|██████▊   | 3369/4959 [1:30:50<52:36,  1.99s/it]

 68%|██████▊   | 3370/4959 [1:30:52<52:59,  2.00s/it]

 68%|██████▊   | 3371/4959 [1:30:54<53:22,  2.02s/it]

 68%|██████▊   | 3372/4959 [1:30:56<53:31,  2.02s/it]

 68%|██████▊   | 3373/4959 [1:30:58<53:38,  2.03s/it]

 68%|██████▊   | 3374/4959 [1:31:00<53:34,  2.03s/it]

 68%|██████▊   | 3375/4959 [1:31:02<53:33,  2.03s/it]

 68%|██████▊   | 3376/4959 [1:31:04<53:41,  2.04s/it]

 68%|██████▊   | 3377/4959 [1:31:06<53:36,  2.03s/it]

 68%|██████▊   | 3378/4959 [1:31:08<50:55,  1.93s/it]

 68%|██████▊   | 3379/4959 [1:31:10<51:40,  1.96s/it]

 68%|██████▊   | 3380/4959 [1:31:12<49:32,  1.88s/it]

 68%|██████▊   | 3381/4959 [1:31:14<50:48,  1.93s/it]

 68%|██████▊   | 3382/4959 [1:31:16<51:35,  1.96s/it]

 68%|██████▊   | 3383/4959 [1:31:18<49:21,  1.88s/it]

 68%|██████▊   | 3384/4959 [1:31:19<47:49,  1.82s/it]

 68%|██████▊   | 3385/4959 [1:31:21<49:28,  1.89s/it]

 68%|██████▊   | 3386/4959 [1:31:23<50:06,  1.91s/it]

 68%|██████▊   | 3387/4959 [1:31:25<50:39,  1.93s/it]

 68%|██████▊   | 3388/4959 [1:31:27<51:01,  1.95s/it]

 68%|██████▊   | 3389/4959 [1:31:29<51:06,  1.95s/it]

 68%|██████▊   | 3390/4959 [1:31:31<52:38,  2.01s/it]

 68%|██████▊   | 3391/4959 [1:31:33<49:33,  1.90s/it]

 68%|██████▊   | 3392/4959 [1:31:35<50:19,  1.93s/it]

 68%|██████▊   | 3393/4959 [1:31:37<51:04,  1.96s/it]

 68%|██████▊   | 3394/4959 [1:31:39<51:14,  1.96s/it]

 68%|██████▊   | 3395/4959 [1:31:41<48:37,  1.87s/it]

 68%|██████▊   | 3396/4959 [1:31:43<49:52,  1.91s/it]

 69%|██████▊   | 3397/4959 [1:31:45<50:20,  1.93s/it]

 69%|██████▊   | 3398/4959 [1:31:47<51:03,  1.96s/it]

 69%|██████▊   | 3399/4959 [1:31:48<48:32,  1.87s/it]

 69%|██████▊   | 3400/4959 [1:31:50<49:40,  1.91s/it]

 69%|██████▊   | 3401/4959 [1:31:52<50:05,  1.93s/it]

 69%|██████▊   | 3402/4959 [1:31:54<47:54,  1.85s/it]

 69%|██████▊   | 3403/4959 [1:31:56<49:20,  1.90s/it]

 69%|██████▊   | 3404/4959 [1:31:58<50:05,  1.93s/it]

 69%|██████▊   | 3405/4959 [1:32:00<50:20,  1.94s/it]

 69%|██████▊   | 3406/4959 [1:32:02<47:54,  1.85s/it]

 69%|██████▊   | 3407/4959 [1:32:04<48:49,  1.89s/it]

 69%|██████▊   | 3408/4959 [1:32:05<46:54,  1.81s/it]

 69%|██████▊   | 3409/4959 [1:32:07<48:13,  1.87s/it]

 69%|██████▉   | 3410/4959 [1:32:09<49:26,  1.91s/it]

 69%|██████▉   | 3411/4959 [1:32:11<50:06,  1.94s/it]

 69%|██████▉   | 3412/4959 [1:32:13<50:29,  1.96s/it]

 69%|██████▉   | 3413/4959 [1:32:15<50:40,  1.97s/it]

 69%|██████▉   | 3414/4959 [1:32:17<50:46,  1.97s/it]

 69%|██████▉   | 3415/4959 [1:32:19<50:52,  1.98s/it]

 69%|██████▉   | 3416/4959 [1:32:21<52:24,  2.04s/it]

 69%|██████▉   | 3417/4959 [1:32:23<49:32,  1.93s/it]

 69%|██████▉   | 3418/4959 [1:32:25<50:10,  1.95s/it]

 69%|██████▉   | 3419/4959 [1:32:27<50:16,  1.96s/it]

 69%|██████▉   | 3420/4959 [1:32:29<50:37,  1.97s/it]

 69%|██████▉   | 3421/4959 [1:32:31<50:43,  1.98s/it]

 69%|██████▉   | 3422/4959 [1:32:33<50:44,  1.98s/it]

 69%|██████▉   | 3423/4959 [1:32:35<52:02,  2.03s/it]

 69%|██████▉   | 3424/4959 [1:32:37<48:49,  1.91s/it]

 69%|██████▉   | 3425/4959 [1:32:39<49:22,  1.93s/it]

 69%|██████▉   | 3426/4959 [1:32:41<49:43,  1.95s/it]

 69%|██████▉   | 3427/4959 [1:32:43<50:04,  1.96s/it]

 69%|██████▉   | 3428/4959 [1:32:45<50:12,  1.97s/it]

 69%|██████▉   | 3429/4959 [1:32:47<50:26,  1.98s/it]

 69%|██████▉   | 3430/4959 [1:32:48<47:58,  1.88s/it]

 69%|██████▉   | 3431/4959 [1:32:50<49:11,  1.93s/it]

 69%|██████▉   | 3432/4959 [1:32:53<50:06,  1.97s/it]

 69%|██████▉   | 3433/4959 [1:32:54<50:00,  1.97s/it]

 69%|██████▉   | 3434/4959 [1:32:56<50:22,  1.98s/it]

 69%|██████▉   | 3435/4959 [1:32:58<50:08,  1.97s/it]

 69%|██████▉   | 3436/4959 [1:33:00<50:15,  1.98s/it]

 69%|██████▉   | 3437/4959 [1:33:02<50:28,  1.99s/it]

 69%|██████▉   | 3438/4959 [1:33:04<50:43,  2.00s/it]

 69%|██████▉   | 3439/4959 [1:33:06<50:43,  2.00s/it]

 69%|██████▉   | 3440/4959 [1:33:09<50:45,  2.01s/it]

 69%|██████▉   | 3441/4959 [1:33:11<50:40,  2.00s/it]

 69%|██████▉   | 3442/4959 [1:33:13<50:38,  2.00s/it]

 69%|██████▉   | 3443/4959 [1:33:15<50:35,  2.00s/it]

 69%|██████▉   | 3444/4959 [1:33:17<50:37,  2.00s/it]

 69%|██████▉   | 3445/4959 [1:33:19<50:41,  2.01s/it]

 69%|██████▉   | 3446/4959 [1:33:21<50:30,  2.00s/it]

 70%|██████▉   | 3447/4959 [1:33:23<50:16,  2.00s/it]

 70%|██████▉   | 3448/4959 [1:33:24<50:13,  1.99s/it]

 70%|██████▉   | 3449/4959 [1:33:27<50:20,  2.00s/it]

 70%|██████▉   | 3450/4959 [1:33:28<50:05,  1.99s/it]

 70%|██████▉   | 3451/4959 [1:33:30<50:07,  1.99s/it]

 70%|██████▉   | 3452/4959 [1:33:32<50:00,  1.99s/it]

 70%|██████▉   | 3453/4959 [1:33:34<50:03,  1.99s/it]

 70%|██████▉   | 3454/4959 [1:33:36<50:04,  2.00s/it]

 70%|██████▉   | 3455/4959 [1:33:38<47:19,  1.89s/it]

 70%|██████▉   | 3456/4959 [1:33:40<47:56,  1.91s/it]

 70%|██████▉   | 3457/4959 [1:33:42<48:30,  1.94s/it]

 70%|██████▉   | 3458/4959 [1:33:44<48:35,  1.94s/it]

 70%|██████▉   | 3459/4959 [1:33:46<50:14,  2.01s/it]

 70%|██████▉   | 3460/4959 [1:33:48<47:30,  1.90s/it]

 70%|██████▉   | 3461/4959 [1:33:50<49:43,  1.99s/it]

 70%|██████▉   | 3462/4959 [1:33:52<49:51,  2.00s/it]

 70%|██████▉   | 3463/4959 [1:33:54<47:40,  1.91s/it]

 70%|██████▉   | 3464/4959 [1:33:56<48:05,  1.93s/it]

 70%|██████▉   | 3465/4959 [1:33:58<48:32,  1.95s/it]

 70%|██████▉   | 3466/4959 [1:34:00<48:49,  1.96s/it]

 70%|██████▉   | 3467/4959 [1:34:02<48:59,  1.97s/it]

 70%|██████▉   | 3468/4959 [1:34:04<48:50,  1.97s/it]

 70%|██████▉   | 3469/4959 [1:34:06<49:06,  1.98s/it]

 70%|██████▉   | 3470/4959 [1:34:08<48:54,  1.97s/it]

 70%|██████▉   | 3471/4959 [1:34:10<50:33,  2.04s/it]

 70%|███████   | 3472/4959 [1:34:12<50:14,  2.03s/it]

 70%|███████   | 3473/4959 [1:34:14<50:02,  2.02s/it]

 70%|███████   | 3474/4959 [1:34:16<49:46,  2.01s/it]

 70%|███████   | 3475/4959 [1:34:18<49:39,  2.01s/it]

 70%|███████   | 3476/4959 [1:34:20<49:23,  2.00s/it]

 70%|███████   | 3477/4959 [1:34:22<49:17,  2.00s/it]

 70%|███████   | 3478/4959 [1:34:24<49:22,  2.00s/it]

 70%|███████   | 3479/4959 [1:34:26<49:25,  2.00s/it]

 70%|███████   | 3480/4959 [1:34:28<49:17,  2.00s/it]

 70%|███████   | 3481/4959 [1:34:30<49:15,  2.00s/it]

 70%|███████   | 3482/4959 [1:34:31<46:40,  1.90s/it]

 70%|███████   | 3483/4959 [1:34:34<48:39,  1.98s/it]

 70%|███████   | 3484/4959 [1:34:35<46:01,  1.87s/it]

 70%|███████   | 3485/4959 [1:34:37<46:55,  1.91s/it]

 70%|███████   | 3486/4959 [1:34:39<44:58,  1.83s/it]

 70%|███████   | 3487/4959 [1:34:41<46:02,  1.88s/it]

 70%|███████   | 3488/4959 [1:34:43<46:56,  1.91s/it]

 70%|███████   | 3489/4959 [1:34:45<47:25,  1.94s/it]

 70%|███████   | 3490/4959 [1:34:47<47:41,  1.95s/it]

 70%|███████   | 3491/4959 [1:34:49<49:13,  2.01s/it]

 70%|███████   | 3492/4959 [1:34:51<49:24,  2.02s/it]

 70%|███████   | 3493/4959 [1:34:53<49:12,  2.01s/it]

 70%|███████   | 3494/4959 [1:34:55<49:01,  2.01s/it]

 70%|███████   | 3495/4959 [1:34:57<48:43,  2.00s/it]

 70%|███████   | 3496/4959 [1:34:59<48:36,  1.99s/it]

 71%|███████   | 3497/4959 [1:35:01<50:03,  2.05s/it]

 71%|███████   | 3498/4959 [1:35:03<49:35,  2.04s/it]

 71%|███████   | 3499/4959 [1:35:05<49:06,  2.02s/it]

 71%|███████   | 3500/4959 [1:35:07<48:48,  2.01s/it]

 71%|███████   | 3501/4959 [1:35:09<48:33,  2.00s/it]

 71%|███████   | 3502/4959 [1:35:11<48:15,  1.99s/it]

 71%|███████   | 3503/4959 [1:35:13<48:09,  1.98s/it]

 71%|███████   | 3504/4959 [1:35:15<48:06,  1.98s/it]

 71%|███████   | 3505/4959 [1:35:17<47:58,  1.98s/it]

 71%|███████   | 3506/4959 [1:35:19<45:20,  1.87s/it]

 71%|███████   | 3507/4959 [1:35:21<47:25,  1.96s/it]

 71%|███████   | 3508/4959 [1:35:23<47:41,  1.97s/it]

 71%|███████   | 3509/4959 [1:35:25<47:47,  1.98s/it]

 71%|███████   | 3510/4959 [1:35:27<47:49,  1.98s/it]

 71%|███████   | 3511/4959 [1:35:29<47:53,  1.98s/it]

 71%|███████   | 3512/4959 [1:35:31<47:43,  1.98s/it]

 71%|███████   | 3513/4959 [1:35:33<47:35,  1.98s/it]

 71%|███████   | 3514/4959 [1:35:35<47:37,  1.98s/it]

 71%|███████   | 3515/4959 [1:35:37<47:50,  1.99s/it]

 71%|███████   | 3516/4959 [1:35:39<47:44,  1.99s/it]

 71%|███████   | 3517/4959 [1:35:41<47:39,  1.98s/it]

 71%|███████   | 3518/4959 [1:35:43<47:39,  1.98s/it]

 71%|███████   | 3519/4959 [1:35:44<45:10,  1.88s/it]

 71%|███████   | 3520/4959 [1:35:46<45:44,  1.91s/it]

 71%|███████   | 3521/4959 [1:35:48<46:12,  1.93s/it]

 71%|███████   | 3522/4959 [1:35:50<46:33,  1.94s/it]

 71%|███████   | 3523/4959 [1:35:52<46:44,  1.95s/it]

 71%|███████   | 3524/4959 [1:35:54<46:52,  1.96s/it]

 71%|███████   | 3525/4959 [1:35:56<46:58,  1.97s/it]

 71%|███████   | 3526/4959 [1:35:58<47:02,  1.97s/it]

 71%|███████   | 3527/4959 [1:36:00<47:09,  1.98s/it]

 71%|███████   | 3528/4959 [1:36:02<47:21,  1.99s/it]

 71%|███████   | 3529/4959 [1:36:04<44:56,  1.89s/it]

 71%|███████   | 3530/4959 [1:36:06<45:31,  1.91s/it]

 71%|███████   | 3531/4959 [1:36:08<46:00,  1.93s/it]

 71%|███████   | 3532/4959 [1:36:10<46:14,  1.94s/it]

 71%|███████   | 3533/4959 [1:36:12<46:19,  1.95s/it]

 71%|███████▏  | 3534/4959 [1:36:14<46:40,  1.97s/it]

 71%|███████▏  | 3535/4959 [1:36:16<46:39,  1.97s/it]

 71%|███████▏  | 3536/4959 [1:36:18<46:46,  1.97s/it]

 71%|███████▏  | 3537/4959 [1:36:20<47:00,  1.98s/it]

 71%|███████▏  | 3538/4959 [1:36:22<46:58,  1.98s/it]

 71%|███████▏  | 3539/4959 [1:36:24<46:52,  1.98s/it]

 71%|███████▏  | 3540/4959 [1:36:25<44:21,  1.88s/it]

 71%|███████▏  | 3541/4959 [1:36:27<45:07,  1.91s/it]

 71%|███████▏  | 3542/4959 [1:36:29<45:30,  1.93s/it]

 71%|███████▏  | 3543/4959 [1:36:31<43:16,  1.83s/it]

 71%|███████▏  | 3544/4959 [1:36:33<44:26,  1.88s/it]

 71%|███████▏  | 3545/4959 [1:36:35<45:07,  1.92s/it]

 72%|███████▏  | 3546/4959 [1:36:37<45:28,  1.93s/it]

 72%|███████▏  | 3547/4959 [1:36:39<45:56,  1.95s/it]

 72%|███████▏  | 3548/4959 [1:36:41<47:24,  2.02s/it]

 72%|███████▏  | 3549/4959 [1:36:43<44:34,  1.90s/it]

 72%|███████▏  | 3550/4959 [1:36:44<42:46,  1.82s/it]

 72%|███████▏  | 3551/4959 [1:36:46<43:53,  1.87s/it]

 72%|███████▏  | 3552/4959 [1:36:48<44:31,  1.90s/it]

 72%|███████▏  | 3553/4959 [1:36:50<45:03,  1.92s/it]

 72%|███████▏  | 3554/4959 [1:36:52<45:31,  1.94s/it]

 72%|███████▏  | 3555/4959 [1:36:54<43:15,  1.85s/it]

 72%|███████▏  | 3556/4959 [1:36:55<41:48,  1.79s/it]

 72%|███████▏  | 3557/4959 [1:36:57<43:02,  1.84s/it]

 72%|███████▏  | 3558/4959 [1:36:59<44:05,  1.89s/it]

 72%|███████▏  | 3559/4959 [1:37:01<44:36,  1.91s/it]

 72%|███████▏  | 3560/4959 [1:37:03<45:03,  1.93s/it]

 72%|███████▏  | 3561/4959 [1:37:05<45:29,  1.95s/it]

 72%|███████▏  | 3562/4959 [1:37:07<45:34,  1.96s/it]

 72%|███████▏  | 3563/4959 [1:37:09<45:44,  1.97s/it]

 72%|███████▏  | 3564/4959 [1:37:11<45:53,  1.97s/it]

 72%|███████▏  | 3565/4959 [1:37:13<43:19,  1.86s/it]

 72%|███████▏  | 3566/4959 [1:37:15<44:03,  1.90s/it]

 72%|███████▏  | 3567/4959 [1:37:17<44:41,  1.93s/it]

 72%|███████▏  | 3568/4959 [1:37:19<44:59,  1.94s/it]

 72%|███████▏  | 3569/4959 [1:37:21<45:14,  1.95s/it]

 72%|███████▏  | 3570/4959 [1:37:23<45:20,  1.96s/it]

 72%|███████▏  | 3571/4959 [1:37:25<45:25,  1.96s/it]

 72%|███████▏  | 3572/4959 [1:37:27<45:31,  1.97s/it]

 72%|███████▏  | 3573/4959 [1:37:29<45:35,  1.97s/it]

 72%|███████▏  | 3574/4959 [1:37:31<45:50,  1.99s/it]

 72%|███████▏  | 3575/4959 [1:37:33<45:50,  1.99s/it]

 72%|███████▏  | 3576/4959 [1:37:35<45:56,  1.99s/it]

 72%|███████▏  | 3577/4959 [1:37:37<45:48,  1.99s/it]

 72%|███████▏  | 3578/4959 [1:37:39<45:44,  1.99s/it]

 72%|███████▏  | 3579/4959 [1:37:41<45:37,  1.98s/it]

 72%|███████▏  | 3580/4959 [1:37:43<45:32,  1.98s/it]

 72%|███████▏  | 3581/4959 [1:37:45<45:29,  1.98s/it]

 72%|███████▏  | 3582/4959 [1:37:47<45:31,  1.98s/it]

 72%|███████▏  | 3583/4959 [1:37:49<46:56,  2.05s/it]

 72%|███████▏  | 3584/4959 [1:37:51<46:52,  2.05s/it]

 72%|███████▏  | 3585/4959 [1:37:53<46:32,  2.03s/it]

 72%|███████▏  | 3586/4959 [1:37:55<46:16,  2.02s/it]

 72%|███████▏  | 3587/4959 [1:37:57<46:01,  2.01s/it]

 72%|███████▏  | 3588/4959 [1:37:59<45:42,  2.00s/it]

 72%|███████▏  | 3589/4959 [1:38:01<45:35,  2.00s/it]

 72%|███████▏  | 3590/4959 [1:38:03<45:29,  1.99s/it]

 72%|███████▏  | 3591/4959 [1:38:04<42:54,  1.88s/it]

 72%|███████▏  | 3592/4959 [1:38:06<43:40,  1.92s/it]

 72%|███████▏  | 3593/4959 [1:38:08<41:55,  1.84s/it]

 72%|███████▏  | 3594/4959 [1:38:10<40:38,  1.79s/it]

 72%|███████▏  | 3595/4959 [1:38:12<41:59,  1.85s/it]

 73%|███████▎  | 3596/4959 [1:38:14<43:00,  1.89s/it]

 73%|███████▎  | 3597/4959 [1:38:16<43:38,  1.92s/it]

 73%|███████▎  | 3598/4959 [1:38:18<43:56,  1.94s/it]

 73%|███████▎  | 3599/4959 [1:38:20<44:25,  1.96s/it]

 73%|███████▎  | 3600/4959 [1:38:22<44:30,  1.97s/it]

 73%|███████▎  | 3601/4959 [1:38:24<44:42,  1.98s/it]

 73%|███████▎  | 3602/4959 [1:38:26<44:34,  1.97s/it]

 73%|███████▎  | 3603/4959 [1:38:28<44:42,  1.98s/it]

 73%|███████▎  | 3604/4959 [1:38:30<44:38,  1.98s/it]

 73%|███████▎  | 3605/4959 [1:38:32<44:27,  1.97s/it]

 73%|███████▎  | 3606/4959 [1:38:34<44:42,  1.98s/it]

 73%|███████▎  | 3607/4959 [1:38:36<44:57,  2.00s/it]

 73%|███████▎  | 3608/4959 [1:38:38<44:57,  2.00s/it]

 73%|███████▎  | 3609/4959 [1:38:40<45:37,  2.03s/it]

 73%|███████▎  | 3610/4959 [1:38:42<45:24,  2.02s/it]

 73%|███████▎  | 3611/4959 [1:38:44<45:11,  2.01s/it]

 73%|███████▎  | 3612/4959 [1:38:46<45:02,  2.01s/it]

 73%|███████▎  | 3613/4959 [1:38:48<44:56,  2.00s/it]

 73%|███████▎  | 3614/4959 [1:38:50<44:54,  2.00s/it]

 73%|███████▎  | 3615/4959 [1:38:52<44:49,  2.00s/it]

 73%|███████▎  | 3616/4959 [1:38:54<44:50,  2.00s/it]

 73%|███████▎  | 3617/4959 [1:38:56<44:49,  2.00s/it]

 73%|███████▎  | 3618/4959 [1:38:58<44:59,  2.01s/it]

 73%|███████▎  | 3619/4959 [1:39:00<44:59,  2.01s/it]

 73%|███████▎  | 3620/4959 [1:39:02<45:00,  2.02s/it]

 73%|███████▎  | 3621/4959 [1:39:04<46:11,  2.07s/it]

 73%|███████▎  | 3622/4959 [1:39:06<45:37,  2.05s/it]

 73%|███████▎  | 3623/4959 [1:39:08<45:21,  2.04s/it]

 73%|███████▎  | 3624/4959 [1:39:10<44:53,  2.02s/it]

 73%|███████▎  | 3625/4959 [1:39:12<44:34,  2.00s/it]

 73%|███████▎  | 3626/4959 [1:39:14<44:27,  2.00s/it]

 73%|███████▎  | 3627/4959 [1:39:16<44:17,  2.00s/it]

 73%|███████▎  | 3628/4959 [1:39:18<44:11,  1.99s/it]

 73%|███████▎  | 3629/4959 [1:39:20<44:11,  1.99s/it]

 73%|███████▎  | 3630/4959 [1:39:21<41:40,  1.88s/it]

 73%|███████▎  | 3631/4959 [1:39:23<42:22,  1.91s/it]

 73%|███████▎  | 3632/4959 [1:39:25<42:47,  1.94s/it]

 73%|███████▎  | 3633/4959 [1:39:27<43:13,  1.96s/it]

 73%|███████▎  | 3634/4959 [1:39:29<43:23,  1.97s/it]

 73%|███████▎  | 3635/4959 [1:39:31<41:08,  1.86s/it]

 73%|███████▎  | 3636/4959 [1:39:33<39:32,  1.79s/it]

 73%|███████▎  | 3637/4959 [1:39:34<38:22,  1.74s/it]

 73%|███████▎  | 3638/4959 [1:39:36<39:52,  1.81s/it]

 73%|███████▎  | 3639/4959 [1:39:38<40:52,  1.86s/it]

 73%|███████▎  | 3640/4959 [1:39:40<41:41,  1.90s/it]

 73%|███████▎  | 3641/4959 [1:39:42<43:25,  1.98s/it]

 73%|███████▎  | 3642/4959 [1:39:44<43:31,  1.98s/it]

 73%|███████▎  | 3643/4959 [1:39:46<43:21,  1.98s/it]

 73%|███████▎  | 3644/4959 [1:39:48<43:14,  1.97s/it]

 74%|███████▎  | 3645/4959 [1:39:50<43:12,  1.97s/it]

 74%|███████▎  | 3646/4959 [1:39:52<43:05,  1.97s/it]

 74%|███████▎  | 3647/4959 [1:39:54<43:06,  1.97s/it]

 74%|███████▎  | 3648/4959 [1:39:56<43:15,  1.98s/it]

 74%|███████▎  | 3649/4959 [1:39:58<43:11,  1.98s/it]

 74%|███████▎  | 3650/4959 [1:40:00<43:13,  1.98s/it]

 74%|███████▎  | 3651/4959 [1:40:02<43:19,  1.99s/it]

 74%|███████▎  | 3652/4959 [1:40:04<43:24,  1.99s/it]

 74%|███████▎  | 3653/4959 [1:40:06<43:23,  1.99s/it]

 74%|███████▎  | 3654/4959 [1:40:08<43:22,  1.99s/it]

 74%|███████▎  | 3655/4959 [1:40:10<43:47,  2.01s/it]

 74%|███████▎  | 3656/4959 [1:40:12<43:50,  2.02s/it]

 74%|███████▎  | 3657/4959 [1:40:14<43:47,  2.02s/it]

 74%|███████▍  | 3658/4959 [1:40:16<43:35,  2.01s/it]

 74%|███████▍  | 3659/4959 [1:40:18<44:39,  2.06s/it]

 74%|███████▍  | 3660/4959 [1:40:21<44:40,  2.06s/it]

 74%|███████▍  | 3661/4959 [1:40:23<44:07,  2.04s/it]

 74%|███████▍  | 3662/4959 [1:40:24<43:39,  2.02s/it]

 74%|███████▍  | 3663/4959 [1:40:26<43:21,  2.01s/it]

 74%|███████▍  | 3664/4959 [1:40:28<43:11,  2.00s/it]

 74%|███████▍  | 3665/4959 [1:40:30<43:09,  2.00s/it]

 74%|███████▍  | 3666/4959 [1:40:33<44:12,  2.05s/it]

 74%|███████▍  | 3667/4959 [1:40:35<43:45,  2.03s/it]

 74%|███████▍  | 3668/4959 [1:40:37<43:21,  2.02s/it]

 74%|███████▍  | 3669/4959 [1:40:39<43:08,  2.01s/it]

 74%|███████▍  | 3670/4959 [1:40:41<42:46,  1.99s/it]

 74%|███████▍  | 3671/4959 [1:40:43<42:43,  1.99s/it]

 74%|███████▍  | 3672/4959 [1:40:44<42:41,  1.99s/it]

 74%|███████▍  | 3673/4959 [1:40:47<43:22,  2.02s/it]

 74%|███████▍  | 3674/4959 [1:40:49<43:15,  2.02s/it]

 74%|███████▍  | 3675/4959 [1:40:51<43:03,  2.01s/it]

 74%|███████▍  | 3676/4959 [1:40:53<42:53,  2.01s/it]

 74%|███████▍  | 3677/4959 [1:40:55<42:42,  2.00s/it]

 74%|███████▍  | 3678/4959 [1:40:57<42:39,  2.00s/it]

 74%|███████▍  | 3679/4959 [1:40:59<42:31,  1.99s/it]

 74%|███████▍  | 3680/4959 [1:41:01<42:24,  1.99s/it]

 74%|███████▍  | 3681/4959 [1:41:03<42:16,  1.99s/it]

 74%|███████▍  | 3682/4959 [1:41:04<40:12,  1.89s/it]

 74%|███████▍  | 3683/4959 [1:41:06<38:37,  1.82s/it]

 74%|███████▍  | 3684/4959 [1:41:07<37:24,  1.76s/it]

 74%|███████▍  | 3685/4959 [1:41:09<36:41,  1.73s/it]

 74%|███████▍  | 3686/4959 [1:41:11<36:27,  1.72s/it]

 74%|███████▍  | 3687/4959 [1:41:13<38:17,  1.81s/it]

 74%|███████▍  | 3688/4959 [1:41:14<37:23,  1.77s/it]

 74%|███████▍  | 3689/4959 [1:41:16<36:31,  1.73s/it]

 74%|███████▍  | 3690/4959 [1:41:18<35:53,  1.70s/it]

 74%|███████▍  | 3691/4959 [1:41:19<35:41,  1.69s/it]

 74%|███████▍  | 3692/4959 [1:41:21<37:30,  1.78s/it]

 74%|███████▍  | 3693/4959 [1:41:23<36:38,  1.74s/it]

 74%|███████▍  | 3694/4959 [1:41:25<36:17,  1.72s/it]

 75%|███████▍  | 3695/4959 [1:41:26<35:56,  1.71s/it]

 75%|███████▍  | 3696/4959 [1:41:28<37:49,  1.80s/it]

 75%|███████▍  | 3697/4959 [1:41:30<36:46,  1.75s/it]

 75%|███████▍  | 3698/4959 [1:41:32<36:06,  1.72s/it]

 75%|███████▍  | 3699/4959 [1:41:33<35:45,  1.70s/it]

 75%|███████▍  | 3700/4959 [1:41:35<35:18,  1.68s/it]

 75%|███████▍  | 3701/4959 [1:41:37<35:12,  1.68s/it]

 75%|███████▍  | 3702/4959 [1:41:38<35:01,  1.67s/it]

 75%|███████▍  | 3703/4959 [1:41:40<35:00,  1.67s/it]

 75%|███████▍  | 3704/4959 [1:41:42<34:56,  1.67s/it]

 75%|███████▍  | 3705/4959 [1:41:43<34:50,  1.67s/it]

 75%|███████▍  | 3706/4959 [1:41:45<36:46,  1.76s/it]

 75%|███████▍  | 3707/4959 [1:41:47<36:10,  1.73s/it]

 75%|███████▍  | 3708/4959 [1:41:49<35:42,  1.71s/it]

 75%|███████▍  | 3709/4959 [1:41:50<35:26,  1.70s/it]

 75%|███████▍  | 3710/4959 [1:41:52<34:59,  1.68s/it]

 75%|███████▍  | 3711/4959 [1:41:54<36:53,  1.77s/it]

 75%|███████▍  | 3712/4959 [1:41:56<35:57,  1.73s/it]

 75%|███████▍  | 3713/4959 [1:41:57<35:19,  1.70s/it]

 75%|███████▍  | 3714/4959 [1:41:59<35:05,  1.69s/it]

 75%|███████▍  | 3715/4959 [1:42:01<34:55,  1.68s/it]

 75%|███████▍  | 3716/4959 [1:42:02<34:36,  1.67s/it]

 75%|███████▍  | 3717/4959 [1:42:04<36:41,  1.77s/it]

 75%|███████▍  | 3718/4959 [1:42:06<35:58,  1.74s/it]

 75%|███████▍  | 3719/4959 [1:42:08<35:35,  1.72s/it]

 75%|███████▌  | 3720/4959 [1:42:09<35:12,  1.70s/it]

 75%|███████▌  | 3721/4959 [1:42:11<34:55,  1.69s/it]

 75%|███████▌  | 3722/4959 [1:42:13<34:53,  1.69s/it]

 75%|███████▌  | 3723/4959 [1:42:14<34:28,  1.67s/it]

 75%|███████▌  | 3724/4959 [1:42:16<36:26,  1.77s/it]

 75%|███████▌  | 3725/4959 [1:42:18<35:53,  1.74s/it]

 75%|███████▌  | 3726/4959 [1:42:19<35:13,  1.71s/it]

 75%|███████▌  | 3727/4959 [1:42:21<35:11,  1.71s/it]

 75%|███████▌  | 3728/4959 [1:42:23<34:40,  1.69s/it]

 75%|███████▌  | 3729/4959 [1:42:25<37:42,  1.84s/it]

 75%|███████▌  | 3730/4959 [1:42:27<39:58,  1.95s/it]

 75%|███████▌  | 3731/4959 [1:42:29<38:38,  1.89s/it]

 75%|███████▌  | 3732/4959 [1:42:31<37:14,  1.82s/it]

 75%|███████▌  | 3733/4959 [1:42:33<38:23,  1.88s/it]

 75%|███████▌  | 3734/4959 [1:42:34<36:52,  1.81s/it]

 75%|███████▌  | 3735/4959 [1:42:36<38:02,  1.86s/it]

 75%|███████▌  | 3736/4959 [1:42:38<36:47,  1.80s/it]

 75%|███████▌  | 3737/4959 [1:42:40<35:58,  1.77s/it]

 75%|███████▌  | 3738/4959 [1:42:41<35:26,  1.74s/it]

 75%|███████▌  | 3739/4959 [1:42:43<37:04,  1.82s/it]

 75%|███████▌  | 3740/4959 [1:42:45<35:53,  1.77s/it]

 75%|███████▌  | 3741/4959 [1:42:47<37:11,  1.83s/it]

 75%|███████▌  | 3742/4959 [1:42:49<39:29,  1.95s/it]

 75%|███████▌  | 3743/4959 [1:42:51<39:45,  1.96s/it]

 75%|███████▌  | 3744/4959 [1:42:53<39:46,  1.96s/it]

 76%|███████▌  | 3745/4959 [1:42:55<40:01,  1.98s/it]

 76%|███████▌  | 3746/4959 [1:42:57<40:06,  1.98s/it]

 76%|███████▌  | 3747/4959 [1:42:59<40:17,  1.99s/it]

 76%|███████▌  | 3748/4959 [1:43:01<40:26,  2.00s/it]

 76%|███████▌  | 3749/4959 [1:43:03<40:25,  2.00s/it]

 76%|███████▌  | 3750/4959 [1:43:05<41:04,  2.04s/it]

 76%|███████▌  | 3751/4959 [1:43:07<40:50,  2.03s/it]

 76%|███████▌  | 3752/4959 [1:43:09<40:42,  2.02s/it]

 76%|███████▌  | 3753/4959 [1:43:11<38:34,  1.92s/it]

 76%|███████▌  | 3754/4959 [1:43:13<37:01,  1.84s/it]

 76%|███████▌  | 3755/4959 [1:43:15<37:54,  1.89s/it]

 76%|███████▌  | 3756/4959 [1:43:17<38:19,  1.91s/it]

 76%|███████▌  | 3757/4959 [1:43:19<38:55,  1.94s/it]

 76%|███████▌  | 3758/4959 [1:43:21<39:19,  1.96s/it]

 76%|███████▌  | 3759/4959 [1:43:23<39:30,  1.98s/it]

 76%|███████▌  | 3760/4959 [1:43:25<39:39,  1.98s/it]

 76%|███████▌  | 3761/4959 [1:43:27<39:32,  1.98s/it]

 76%|███████▌  | 3762/4959 [1:43:29<39:44,  1.99s/it]

 76%|███████▌  | 3763/4959 [1:43:31<39:48,  2.00s/it]

 76%|███████▌  | 3764/4959 [1:43:33<39:51,  2.00s/it]

 76%|███████▌  | 3765/4959 [1:43:35<39:45,  2.00s/it]

 76%|███████▌  | 3766/4959 [1:43:37<39:46,  2.00s/it]

 76%|███████▌  | 3767/4959 [1:43:39<39:45,  2.00s/it]

 76%|███████▌  | 3768/4959 [1:43:41<39:49,  2.01s/it]

 76%|███████▌  | 3769/4959 [1:43:43<39:41,  2.00s/it]

 76%|███████▌  | 3770/4959 [1:43:45<39:42,  2.00s/it]

 76%|███████▌  | 3771/4959 [1:43:47<40:01,  2.02s/it]

 76%|███████▌  | 3772/4959 [1:43:49<39:57,  2.02s/it]

 76%|███████▌  | 3773/4959 [1:43:51<40:01,  2.02s/it]

 76%|███████▌  | 3774/4959 [1:43:53<40:00,  2.03s/it]

 76%|███████▌  | 3775/4959 [1:43:55<39:51,  2.02s/it]

 76%|███████▌  | 3776/4959 [1:43:57<39:39,  2.01s/it]

 76%|███████▌  | 3777/4959 [1:43:59<39:35,  2.01s/it]

 76%|███████▌  | 3778/4959 [1:44:01<39:29,  2.01s/it]

 76%|███████▌  | 3779/4959 [1:44:03<39:33,  2.01s/it]

 76%|███████▌  | 3780/4959 [1:44:05<39:22,  2.00s/it]

 76%|███████▌  | 3781/4959 [1:44:07<39:33,  2.01s/it]

 76%|███████▋  | 3782/4959 [1:44:09<39:31,  2.01s/it]

 76%|███████▋  | 3783/4959 [1:44:11<39:32,  2.02s/it]

 76%|███████▋  | 3784/4959 [1:44:13<39:32,  2.02s/it]

 76%|███████▋  | 3785/4959 [1:44:15<39:49,  2.04s/it]

 76%|███████▋  | 3786/4959 [1:44:17<39:55,  2.04s/it]

 76%|███████▋  | 3787/4959 [1:44:19<40:02,  2.05s/it]

 76%|███████▋  | 3788/4959 [1:44:21<40:11,  2.06s/it]

 76%|███████▋  | 3789/4959 [1:44:23<39:59,  2.05s/it]

 76%|███████▋  | 3790/4959 [1:44:25<39:55,  2.05s/it]

 76%|███████▋  | 3791/4959 [1:44:27<39:45,  2.04s/it]

 76%|███████▋  | 3792/4959 [1:44:29<39:42,  2.04s/it]

 76%|███████▋  | 3793/4959 [1:44:31<39:29,  2.03s/it]

 77%|███████▋  | 3794/4959 [1:44:33<39:31,  2.04s/it]

 77%|███████▋  | 3795/4959 [1:44:35<37:16,  1.92s/it]

 77%|███████▋  | 3796/4959 [1:44:37<37:58,  1.96s/it]

 77%|███████▋  | 3797/4959 [1:44:40<40:53,  2.11s/it]

 77%|███████▋  | 3798/4959 [1:44:42<40:21,  2.09s/it]

 77%|███████▋  | 3799/4959 [1:44:44<42:27,  2.20s/it]

 77%|███████▋  | 3800/4959 [1:44:46<39:23,  2.04s/it]

 77%|███████▋  | 3801/4959 [1:44:48<39:16,  2.04s/it]

 77%|███████▋  | 3802/4959 [1:44:50<39:09,  2.03s/it]

 77%|███████▋  | 3803/4959 [1:44:52<39:02,  2.03s/it]

 77%|███████▋  | 3804/4959 [1:44:53<36:58,  1.92s/it]

 77%|███████▋  | 3805/4959 [1:44:56<37:55,  1.97s/it]

 77%|███████▋  | 3806/4959 [1:44:57<36:06,  1.88s/it]

 77%|███████▋  | 3807/4959 [1:44:59<34:57,  1.82s/it]

 77%|███████▋  | 3808/4959 [1:45:01<34:02,  1.77s/it]

 77%|███████▋  | 3809/4959 [1:45:03<35:38,  1.86s/it]

 77%|███████▋  | 3810/4959 [1:45:04<34:31,  1.80s/it]

 77%|███████▋  | 3811/4959 [1:45:06<33:32,  1.75s/it]

 77%|███████▋  | 3812/4959 [1:45:08<33:05,  1.73s/it]

 77%|███████▋  | 3813/4959 [1:45:10<34:33,  1.81s/it]

 77%|███████▋  | 3814/4959 [1:45:12<35:45,  1.87s/it]

 77%|███████▋  | 3815/4959 [1:45:14<36:45,  1.93s/it]

 77%|███████▋  | 3816/4959 [1:45:15<35:19,  1.85s/it]

 77%|███████▋  | 3817/4959 [1:45:17<34:17,  1.80s/it]

 77%|███████▋  | 3818/4959 [1:45:19<33:33,  1.76s/it]

 77%|███████▋  | 3819/4959 [1:45:21<35:04,  1.85s/it]

 77%|███████▋  | 3820/4959 [1:45:22<33:58,  1.79s/it]

 77%|███████▋  | 3821/4959 [1:45:24<35:18,  1.86s/it]

 77%|███████▋  | 3822/4959 [1:45:26<34:07,  1.80s/it]

 77%|███████▋  | 3823/4959 [1:45:28<33:23,  1.76s/it]

 77%|███████▋  | 3824/4959 [1:45:30<34:49,  1.84s/it]

 77%|███████▋  | 3825/4959 [1:45:31<33:50,  1.79s/it]

 77%|███████▋  | 3826/4959 [1:45:34<35:03,  1.86s/it]

 77%|███████▋  | 3827/4959 [1:45:36<36:05,  1.91s/it]

 77%|███████▋  | 3828/4959 [1:45:37<34:50,  1.85s/it]

 77%|███████▋  | 3829/4959 [1:45:39<35:44,  1.90s/it]

 77%|███████▋  | 3830/4959 [1:45:41<34:30,  1.83s/it]

 77%|███████▋  | 3831/4959 [1:45:43<35:36,  1.89s/it]

 77%|███████▋  | 3832/4959 [1:45:45<36:18,  1.93s/it]

 77%|███████▋  | 3833/4959 [1:45:47<34:50,  1.86s/it]

 77%|███████▋  | 3834/4959 [1:45:48<33:34,  1.79s/it]

 77%|███████▋  | 3835/4959 [1:45:50<32:52,  1.76s/it]

 77%|███████▋  | 3836/4959 [1:45:52<34:20,  1.83s/it]

 77%|███████▋  | 3837/4959 [1:45:54<35:23,  1.89s/it]

 77%|███████▋  | 3838/4959 [1:45:56<34:09,  1.83s/it]

 77%|███████▋  | 3839/4959 [1:45:58<35:34,  1.91s/it]

 77%|███████▋  | 3840/4959 [1:45:59<34:07,  1.83s/it]

 77%|███████▋  | 3841/4959 [1:46:01<33:15,  1.79s/it]

 77%|███████▋  | 3842/4959 [1:46:03<34:33,  1.86s/it]

 77%|███████▋  | 3843/4959 [1:46:05<35:32,  1.91s/it]

 78%|███████▊  | 3844/4959 [1:46:07<36:10,  1.95s/it]

 78%|███████▊  | 3845/4959 [1:46:09<35:00,  1.89s/it]

 78%|███████▊  | 3846/4959 [1:46:11<33:37,  1.81s/it]

 78%|███████▊  | 3847/4959 [1:46:13<34:36,  1.87s/it]

 78%|███████▊  | 3848/4959 [1:46:15<35:24,  1.91s/it]

 78%|███████▊  | 3849/4959 [1:46:16<34:05,  1.84s/it]

 78%|███████▊  | 3850/4959 [1:46:18<35:05,  1.90s/it]

 78%|███████▊  | 3851/4959 [1:46:20<35:50,  1.94s/it]

 78%|███████▊  | 3852/4959 [1:46:22<36:13,  1.96s/it]

 78%|███████▊  | 3853/4959 [1:46:24<36:35,  1.99s/it]

 78%|███████▊  | 3854/4959 [1:46:26<34:39,  1.88s/it]

 78%|███████▊  | 3855/4959 [1:46:28<33:22,  1.81s/it]

 78%|███████▊  | 3856/4959 [1:46:30<34:25,  1.87s/it]

 78%|███████▊  | 3857/4959 [1:46:31<33:19,  1.81s/it]

 78%|███████▊  | 3858/4959 [1:46:33<34:23,  1.87s/it]

 78%|███████▊  | 3859/4959 [1:46:35<33:13,  1.81s/it]

 78%|███████▊  | 3860/4959 [1:46:37<34:10,  1.87s/it]

 78%|███████▊  | 3861/4959 [1:46:39<34:57,  1.91s/it]

 78%|███████▊  | 3862/4959 [1:46:41<33:29,  1.83s/it]

 78%|███████▊  | 3863/4959 [1:46:43<34:30,  1.89s/it]

 78%|███████▊  | 3864/4959 [1:46:45<35:04,  1.92s/it]

 78%|███████▊  | 3865/4959 [1:46:46<33:43,  1.85s/it]

 78%|███████▊  | 3866/4959 [1:46:48<32:39,  1.79s/it]

 78%|███████▊  | 3867/4959 [1:46:50<31:53,  1.75s/it]

 78%|███████▊  | 3868/4959 [1:46:52<33:10,  1.82s/it]

 78%|███████▊  | 3869/4959 [1:46:54<34:04,  1.88s/it]

 78%|███████▊  | 3870/4959 [1:46:55<32:54,  1.81s/it]

 78%|███████▊  | 3871/4959 [1:46:57<32:20,  1.78s/it]

 78%|███████▊  | 3872/4959 [1:46:59<31:35,  1.74s/it]

 78%|███████▊  | 3873/4959 [1:47:01<33:04,  1.83s/it]

 78%|███████▊  | 3874/4959 [1:47:02<32:14,  1.78s/it]

 78%|███████▊  | 3875/4959 [1:47:04<33:23,  1.85s/it]

 78%|███████▊  | 3876/4959 [1:47:07<34:18,  1.90s/it]

 78%|███████▊  | 3877/4959 [1:47:08<32:54,  1.82s/it]

 78%|███████▊  | 3878/4959 [1:47:10<33:49,  1.88s/it]

 78%|███████▊  | 3879/4959 [1:47:12<34:27,  1.91s/it]

 78%|███████▊  | 3880/4959 [1:47:14<34:56,  1.94s/it]

 78%|███████▊  | 3881/4959 [1:47:16<33:28,  1.86s/it]

 78%|███████▊  | 3882/4959 [1:47:18<34:08,  1.90s/it]

 78%|███████▊  | 3883/4959 [1:47:20<34:34,  1.93s/it]

 78%|███████▊  | 3884/4959 [1:47:21<33:07,  1.85s/it]

 78%|███████▊  | 3885/4959 [1:47:24<34:02,  1.90s/it]

 78%|███████▊  | 3886/4959 [1:47:25<32:44,  1.83s/it]

 78%|███████▊  | 3887/4959 [1:47:27<33:39,  1.88s/it]

 78%|███████▊  | 3888/4959 [1:47:29<34:12,  1.92s/it]

 78%|███████▊  | 3889/4959 [1:47:31<34:57,  1.96s/it]

 78%|███████▊  | 3890/4959 [1:47:33<35:05,  1.97s/it]

 78%|███████▊  | 3891/4959 [1:47:35<35:10,  1.98s/it]

 78%|███████▊  | 3892/4959 [1:47:37<33:49,  1.90s/it]

 79%|███████▊  | 3893/4959 [1:47:39<32:27,  1.83s/it]

 79%|███████▊  | 3894/4959 [1:47:40<31:43,  1.79s/it]

 79%|███████▊  | 3895/4959 [1:47:42<31:06,  1.75s/it]

 79%|███████▊  | 3896/4959 [1:47:44<32:32,  1.84s/it]

 79%|███████▊  | 3897/4959 [1:47:46<33:28,  1.89s/it]

 79%|███████▊  | 3898/4959 [1:47:48<32:06,  1.82s/it]

 79%|███████▊  | 3899/4959 [1:47:50<33:06,  1.87s/it]

 79%|███████▊  | 3900/4959 [1:47:52<33:43,  1.91s/it]

 79%|███████▊  | 3901/4959 [1:47:53<32:25,  1.84s/it]

 79%|███████▊  | 3902/4959 [1:47:55<33:13,  1.89s/it]

 79%|███████▊  | 3903/4959 [1:47:57<32:03,  1.82s/it]

 79%|███████▊  | 3904/4959 [1:47:59<31:28,  1.79s/it]

 79%|███████▊  | 3905/4959 [1:48:01<32:36,  1.86s/it]

 79%|███████▉  | 3906/4959 [1:48:03<33:21,  1.90s/it]

 79%|███████▉  | 3907/4959 [1:48:04<32:00,  1.83s/it]

 79%|███████▉  | 3908/4959 [1:48:06<31:20,  1.79s/it]

 79%|███████▉  | 3909/4959 [1:48:08<32:27,  1.86s/it]

 79%|███████▉  | 3910/4959 [1:48:10<33:15,  1.90s/it]

 79%|███████▉  | 3911/4959 [1:48:12<31:54,  1.83s/it]

 79%|███████▉  | 3912/4959 [1:48:13<30:54,  1.77s/it]

 79%|███████▉  | 3913/4959 [1:48:15<32:12,  1.85s/it]

 79%|███████▉  | 3914/4959 [1:48:17<31:27,  1.81s/it]

 79%|███████▉  | 3915/4959 [1:48:19<30:36,  1.76s/it]

 79%|███████▉  | 3916/4959 [1:48:20<30:09,  1.74s/it]

 79%|███████▉  | 3917/4959 [1:48:23<31:49,  1.83s/it]

 79%|███████▉  | 3918/4959 [1:48:24<31:05,  1.79s/it]

 79%|███████▉  | 3919/4959 [1:48:26<30:26,  1.76s/it]

 79%|███████▉  | 3920/4959 [1:48:28<31:45,  1.83s/it]

 79%|███████▉  | 3921/4959 [1:48:30<32:44,  1.89s/it]

 79%|███████▉  | 3922/4959 [1:48:32<33:23,  1.93s/it]

 79%|███████▉  | 3923/4959 [1:48:34<31:52,  1.85s/it]

 79%|███████▉  | 3924/4959 [1:48:36<32:39,  1.89s/it]

 79%|███████▉  | 3925/4959 [1:48:38<33:03,  1.92s/it]

 79%|███████▉  | 3926/4959 [1:48:39<31:36,  1.84s/it]

 79%|███████▉  | 3927/4959 [1:48:41<30:34,  1.78s/it]

 79%|███████▉  | 3928/4959 [1:48:43<29:59,  1.75s/it]

 79%|███████▉  | 3929/4959 [1:48:45<31:20,  1.83s/it]

 79%|███████▉  | 3930/4959 [1:48:46<30:20,  1.77s/it]

 79%|███████▉  | 3931/4959 [1:48:48<31:36,  1.84s/it]

 79%|███████▉  | 3932/4959 [1:48:50<30:36,  1.79s/it]

 79%|███████▉  | 3933/4959 [1:48:52<29:56,  1.75s/it]

 79%|███████▉  | 3934/4959 [1:48:54<31:06,  1.82s/it]

 79%|███████▉  | 3935/4959 [1:48:55<30:11,  1.77s/it]

 79%|███████▉  | 3936/4959 [1:48:57<29:33,  1.73s/it]

 79%|███████▉  | 3937/4959 [1:48:58<29:07,  1.71s/it]

 79%|███████▉  | 3938/4959 [1:49:01<30:56,  1.82s/it]

 79%|███████▉  | 3939/4959 [1:49:02<30:08,  1.77s/it]

 79%|███████▉  | 3940/4959 [1:49:04<31:16,  1.84s/it]

 79%|███████▉  | 3941/4959 [1:49:06<32:06,  1.89s/it]

 79%|███████▉  | 3942/4959 [1:49:08<30:50,  1.82s/it]

 80%|███████▉  | 3943/4959 [1:49:10<29:57,  1.77s/it]

 80%|███████▉  | 3944/4959 [1:49:11<29:22,  1.74s/it]

 80%|███████▉  | 3945/4959 [1:49:13<30:45,  1.82s/it]

 80%|███████▉  | 3946/4959 [1:49:15<29:53,  1.77s/it]

 80%|███████▉  | 3947/4959 [1:49:17<29:15,  1.73s/it]

 80%|███████▉  | 3948/4959 [1:49:18<28:52,  1.71s/it]

 80%|███████▉  | 3949/4959 [1:49:20<30:23,  1.81s/it]

 80%|███████▉  | 3950/4959 [1:49:22<31:16,  1.86s/it]

 80%|███████▉  | 3951/4959 [1:49:24<30:11,  1.80s/it]

 80%|███████▉  | 3952/4959 [1:49:26<31:14,  1.86s/it]

 80%|███████▉  | 3953/4959 [1:49:28<31:55,  1.90s/it]

 80%|███████▉  | 3954/4959 [1:49:30<32:23,  1.93s/it]

 80%|███████▉  | 3955/4959 [1:49:32<32:38,  1.95s/it]

 80%|███████▉  | 3956/4959 [1:49:34<32:53,  1.97s/it]

 80%|███████▉  | 3957/4959 [1:49:36<33:02,  1.98s/it]

 80%|███████▉  | 3958/4959 [1:49:38<33:07,  1.99s/it]

 80%|███████▉  | 3959/4959 [1:49:40<33:10,  1.99s/it]

 80%|███████▉  | 3960/4959 [1:49:42<31:28,  1.89s/it]

 80%|███████▉  | 3961/4959 [1:49:44<32:09,  1.93s/it]

 80%|███████▉  | 3962/4959 [1:49:46<32:42,  1.97s/it]

 80%|███████▉  | 3963/4959 [1:49:48<32:52,  1.98s/it]

 80%|███████▉  | 3964/4959 [1:49:50<33:03,  1.99s/it]

 80%|███████▉  | 3965/4959 [1:49:51<31:40,  1.91s/it]

 80%|███████▉  | 3966/4959 [1:49:53<32:12,  1.95s/it]

 80%|███████▉  | 3967/4959 [1:49:55<32:46,  1.98s/it]

 80%|████████  | 3968/4959 [1:49:57<32:52,  1.99s/it]

 80%|████████  | 3969/4959 [1:49:59<31:17,  1.90s/it]

 80%|████████  | 3970/4959 [1:50:01<30:40,  1.86s/it]

 80%|████████  | 3971/4959 [1:50:03<29:37,  1.80s/it]

 80%|████████  | 3972/4959 [1:50:04<28:51,  1.75s/it]

 80%|████████  | 3973/4959 [1:50:06<28:21,  1.73s/it]

 80%|████████  | 3974/4959 [1:50:08<29:39,  1.81s/it]

 80%|████████  | 3975/4959 [1:50:10<30:54,  1.89s/it]

 80%|████████  | 3976/4959 [1:50:12<31:35,  1.93s/it]

 80%|████████  | 3977/4959 [1:50:14<30:20,  1.85s/it]

 80%|████████  | 3978/4959 [1:50:16<31:14,  1.91s/it]

 80%|████████  | 3979/4959 [1:50:18<31:45,  1.94s/it]

 80%|████████  | 3980/4959 [1:50:19<30:27,  1.87s/it]

 80%|████████  | 3981/4959 [1:50:21<29:33,  1.81s/it]

 80%|████████  | 3982/4959 [1:50:23<28:40,  1.76s/it]

 80%|████████  | 3983/4959 [1:50:25<30:07,  1.85s/it]

 80%|████████  | 3984/4959 [1:50:26<29:17,  1.80s/it]

 80%|████████  | 3985/4959 [1:50:28<28:26,  1.75s/it]

 80%|████████  | 3986/4959 [1:50:30<29:34,  1.82s/it]

 80%|████████  | 3987/4959 [1:50:32<28:50,  1.78s/it]

 80%|████████  | 3988/4959 [1:50:34<30:03,  1.86s/it]

 80%|████████  | 3989/4959 [1:50:36<29:08,  1.80s/it]

 80%|████████  | 3990/4959 [1:50:38<30:09,  1.87s/it]

 80%|████████  | 3991/4959 [1:50:39<29:17,  1.82s/it]

 81%|████████  | 3992/4959 [1:50:41<28:40,  1.78s/it]

 81%|████████  | 3993/4959 [1:50:43<28:07,  1.75s/it]

 81%|████████  | 3994/4959 [1:50:44<27:37,  1.72s/it]

 81%|████████  | 3995/4959 [1:50:46<27:26,  1.71s/it]

 81%|████████  | 3996/4959 [1:50:48<29:02,  1.81s/it]

 81%|████████  | 3997/4959 [1:50:50<29:49,  1.86s/it]

 81%|████████  | 3998/4959 [1:50:52<29:01,  1.81s/it]

 81%|████████  | 3999/4959 [1:50:53<28:21,  1.77s/it]

 81%|████████  | 4000/4959 [1:50:55<27:53,  1.74s/it]

 81%|████████  | 4001/4959 [1:50:57<27:26,  1.72s/it]

 81%|████████  | 4002/4959 [1:50:58<27:13,  1.71s/it]

 81%|████████  | 4003/4959 [1:51:00<26:54,  1.69s/it]

 81%|████████  | 4004/4959 [1:51:02<26:52,  1.69s/it]

 81%|████████  | 4005/4959 [1:51:03<26:48,  1.69s/it]

 81%|████████  | 4006/4959 [1:51:05<28:25,  1.79s/it]

 81%|████████  | 4007/4959 [1:51:07<29:31,  1.86s/it]

 81%|████████  | 4008/4959 [1:51:09<28:43,  1.81s/it]

 81%|████████  | 4009/4959 [1:51:11<29:44,  1.88s/it]

 81%|████████  | 4010/4959 [1:51:13<28:35,  1.81s/it]

 81%|████████  | 4011/4959 [1:51:14<27:56,  1.77s/it]

 81%|████████  | 4012/4959 [1:51:16<27:29,  1.74s/it]

 81%|████████  | 4013/4959 [1:51:18<28:45,  1.82s/it]

 81%|████████  | 4014/4959 [1:51:20<28:05,  1.78s/it]

 81%|████████  | 4015/4959 [1:51:22<29:13,  1.86s/it]

 81%|████████  | 4016/4959 [1:51:24<29:56,  1.91s/it]

 81%|████████  | 4017/4959 [1:51:26<28:54,  1.84s/it]

 81%|████████  | 4018/4959 [1:51:28<30:39,  1.95s/it]

 81%|████████  | 4019/4959 [1:51:29<29:08,  1.86s/it]

 81%|████████  | 4020/4959 [1:51:31<29:54,  1.91s/it]

 81%|████████  | 4021/4959 [1:51:33<28:47,  1.84s/it]

 81%|████████  | 4022/4959 [1:51:35<29:40,  1.90s/it]

 81%|████████  | 4023/4959 [1:51:37<28:34,  1.83s/it]

 81%|████████  | 4024/4959 [1:51:39<29:30,  1.89s/it]

 81%|████████  | 4025/4959 [1:51:41<30:05,  1.93s/it]

 81%|████████  | 4026/4959 [1:51:43<30:18,  1.95s/it]

 81%|████████  | 4027/4959 [1:51:45<30:40,  1.97s/it]

 81%|████████  | 4028/4959 [1:51:47<29:11,  1.88s/it]

 81%|████████  | 4029/4959 [1:51:49<29:48,  1.92s/it]

 81%|████████▏ | 4030/4959 [1:51:50<28:59,  1.87s/it]

 81%|████████▏ | 4031/4959 [1:51:52<28:11,  1.82s/it]

 81%|████████▏ | 4032/4959 [1:51:54<27:30,  1.78s/it]

 81%|████████▏ | 4033/4959 [1:51:56<28:37,  1.85s/it]

 81%|████████▏ | 4034/4959 [1:51:58<29:27,  1.91s/it]

 81%|████████▏ | 4035/4959 [1:52:00<30:02,  1.95s/it]

 81%|████████▏ | 4036/4959 [1:52:02<28:46,  1.87s/it]

 81%|████████▏ | 4037/4959 [1:52:04<29:45,  1.94s/it]

 81%|████████▏ | 4038/4959 [1:52:06<30:09,  1.96s/it]

 81%|████████▏ | 4039/4959 [1:52:08<30:36,  2.00s/it]

 81%|████████▏ | 4040/4959 [1:52:09<29:10,  1.91s/it]

 81%|████████▏ | 4041/4959 [1:52:11<28:05,  1.84s/it]

 82%|████████▏ | 4042/4959 [1:52:13<28:59,  1.90s/it]

 82%|████████▏ | 4043/4959 [1:52:15<29:31,  1.93s/it]

 82%|████████▏ | 4044/4959 [1:52:17<28:21,  1.86s/it]

 82%|████████▏ | 4045/4959 [1:52:19<29:07,  1.91s/it]

 82%|████████▏ | 4046/4959 [1:52:21<28:03,  1.84s/it]

 82%|████████▏ | 4047/4959 [1:52:22<27:05,  1.78s/it]

 82%|████████▏ | 4048/4959 [1:52:24<26:32,  1.75s/it]

 82%|████████▏ | 4049/4959 [1:52:26<26:30,  1.75s/it]

 82%|████████▏ | 4050/4959 [1:52:28<28:22,  1.87s/it]

 82%|████████▏ | 4051/4959 [1:52:30<27:46,  1.84s/it]

 82%|████████▏ | 4052/4959 [1:52:31<27:06,  1.79s/it]

 82%|████████▏ | 4053/4959 [1:52:33<26:36,  1.76s/it]

 82%|████████▏ | 4054/4959 [1:52:35<27:49,  1.85s/it]

 82%|████████▏ | 4055/4959 [1:52:37<26:53,  1.79s/it]

 82%|████████▏ | 4056/4959 [1:52:39<27:56,  1.86s/it]

 82%|████████▏ | 4057/4959 [1:52:41<28:37,  1.90s/it]

 82%|████████▏ | 4058/4959 [1:52:43<29:08,  1.94s/it]

 82%|████████▏ | 4059/4959 [1:52:44<27:55,  1.86s/it]

 82%|████████▏ | 4060/4959 [1:52:46<28:36,  1.91s/it]

 82%|████████▏ | 4061/4959 [1:52:48<27:32,  1.84s/it]

 82%|████████▏ | 4062/4959 [1:52:50<28:14,  1.89s/it]

 82%|████████▏ | 4063/4959 [1:52:52<28:42,  1.92s/it]

 82%|████████▏ | 4064/4959 [1:52:54<27:36,  1.85s/it]

 82%|████████▏ | 4065/4959 [1:52:56<28:21,  1.90s/it]

 82%|████████▏ | 4066/4959 [1:52:58<28:59,  1.95s/it]

 82%|████████▏ | 4067/4959 [1:53:00<27:44,  1.87s/it]

 82%|████████▏ | 4068/4959 [1:53:02<28:27,  1.92s/it]

 82%|████████▏ | 4069/4959 [1:53:04<28:58,  1.95s/it]

 82%|████████▏ | 4070/4959 [1:53:05<28:00,  1.89s/it]

 82%|████████▏ | 4071/4959 [1:53:07<27:12,  1.84s/it]

 82%|████████▏ | 4072/4959 [1:53:09<27:59,  1.89s/it]

 82%|████████▏ | 4073/4959 [1:53:11<26:52,  1.82s/it]

 82%|████████▏ | 4074/4959 [1:53:13<27:43,  1.88s/it]

 82%|████████▏ | 4075/4959 [1:53:15<28:11,  1.91s/it]

 82%|████████▏ | 4076/4959 [1:53:17<28:36,  1.94s/it]

 82%|████████▏ | 4077/4959 [1:53:18<27:26,  1.87s/it]

 82%|████████▏ | 4078/4959 [1:53:20<28:14,  1.92s/it]

 82%|████████▏ | 4079/4959 [1:53:22<27:00,  1.84s/it]

 82%|████████▏ | 4080/4959 [1:53:24<27:56,  1.91s/it]

 82%|████████▏ | 4081/4959 [1:53:26<28:12,  1.93s/it]

 82%|████████▏ | 4082/4959 [1:53:28<27:05,  1.85s/it]

 82%|████████▏ | 4083/4959 [1:53:30<26:17,  1.80s/it]

 82%|████████▏ | 4084/4959 [1:53:32<27:17,  1.87s/it]

 82%|████████▏ | 4085/4959 [1:53:34<28:05,  1.93s/it]

 82%|████████▏ | 4086/4959 [1:53:36<28:30,  1.96s/it]

 82%|████████▏ | 4087/4959 [1:53:37<27:04,  1.86s/it]

 82%|████████▏ | 4088/4959 [1:53:39<26:17,  1.81s/it]

 82%|████████▏ | 4089/4959 [1:53:41<27:15,  1.88s/it]

 82%|████████▏ | 4090/4959 [1:53:43<26:14,  1.81s/it]

 82%|████████▏ | 4091/4959 [1:53:44<25:39,  1.77s/it]

 83%|████████▎ | 4092/4959 [1:53:46<26:44,  1.85s/it]

 83%|████████▎ | 4093/4959 [1:53:48<26:00,  1.80s/it]

 83%|████████▎ | 4094/4959 [1:53:50<25:22,  1.76s/it]

 83%|████████▎ | 4095/4959 [1:53:51<24:48,  1.72s/it]

 83%|████████▎ | 4096/4959 [1:53:53<24:35,  1.71s/it]

 83%|████████▎ | 4097/4959 [1:53:55<24:19,  1.69s/it]

 83%|████████▎ | 4098/4959 [1:53:56<24:15,  1.69s/it]

 83%|████████▎ | 4099/4959 [1:53:58<24:06,  1.68s/it]

 83%|████████▎ | 4100/4959 [1:54:00<25:36,  1.79s/it]

 83%|████████▎ | 4101/4959 [1:54:02<25:06,  1.76s/it]

 83%|████████▎ | 4102/4959 [1:54:03<24:46,  1.73s/it]

 83%|████████▎ | 4103/4959 [1:54:05<24:34,  1.72s/it]

 83%|████████▎ | 4104/4959 [1:54:07<25:54,  1.82s/it]

 83%|████████▎ | 4105/4959 [1:54:09<25:17,  1.78s/it]

 83%|████████▎ | 4106/4959 [1:54:11<26:20,  1.85s/it]

 83%|████████▎ | 4107/4959 [1:54:13<25:31,  1.80s/it]

 83%|████████▎ | 4108/4959 [1:54:15<26:18,  1.85s/it]

 83%|████████▎ | 4109/4959 [1:54:16<25:30,  1.80s/it]

 83%|████████▎ | 4110/4959 [1:54:18<24:57,  1.76s/it]

 83%|████████▎ | 4111/4959 [1:54:20<26:02,  1.84s/it]

 83%|████████▎ | 4112/4959 [1:54:22<26:44,  1.89s/it]

 83%|████████▎ | 4113/4959 [1:54:24<25:47,  1.83s/it]

 83%|████████▎ | 4114/4959 [1:54:26<26:41,  1.90s/it]

 83%|████████▎ | 4115/4959 [1:54:27<25:51,  1.84s/it]

 83%|████████▎ | 4116/4959 [1:54:29<25:12,  1.79s/it]

 83%|████████▎ | 4117/4959 [1:54:31<26:24,  1.88s/it]

 83%|████████▎ | 4118/4959 [1:54:33<25:22,  1.81s/it]

 83%|████████▎ | 4119/4959 [1:54:35<26:25,  1.89s/it]

 83%|████████▎ | 4120/4959 [1:54:37<25:29,  1.82s/it]

 83%|████████▎ | 4121/4959 [1:54:38<24:58,  1.79s/it]

 83%|████████▎ | 4122/4959 [1:54:40<24:32,  1.76s/it]

 83%|████████▎ | 4123/4959 [1:54:42<25:35,  1.84s/it]

 83%|████████▎ | 4124/4959 [1:54:44<26:13,  1.88s/it]

 83%|████████▎ | 4125/4959 [1:54:46<25:21,  1.82s/it]

 83%|████████▎ | 4126/4959 [1:54:47<24:44,  1.78s/it]

 83%|████████▎ | 4127/4959 [1:54:49<25:44,  1.86s/it]

 83%|████████▎ | 4128/4959 [1:54:51<26:33,  1.92s/it]

 83%|████████▎ | 4129/4959 [1:54:53<26:59,  1.95s/it]

 83%|████████▎ | 4130/4959 [1:54:55<25:53,  1.87s/it]

 83%|████████▎ | 4131/4959 [1:54:57<26:20,  1.91s/it]

 83%|████████▎ | 4132/4959 [1:54:59<26:44,  1.94s/it]

 83%|████████▎ | 4133/4959 [1:55:01<26:53,  1.95s/it]

 83%|████████▎ | 4134/4959 [1:55:03<27:14,  1.98s/it]

 83%|████████▎ | 4135/4959 [1:55:05<27:21,  1.99s/it]

 83%|████████▎ | 4136/4959 [1:55:07<27:45,  2.02s/it]

 83%|████████▎ | 4137/4959 [1:55:09<27:41,  2.02s/it]

 83%|████████▎ | 4138/4959 [1:55:11<26:16,  1.92s/it]

 83%|████████▎ | 4139/4959 [1:55:13<25:12,  1.84s/it]

 83%|████████▎ | 4140/4959 [1:55:15<25:48,  1.89s/it]

 84%|████████▎ | 4141/4959 [1:55:16<24:56,  1.83s/it]

 84%|████████▎ | 4142/4959 [1:55:18<25:46,  1.89s/it]

 84%|████████▎ | 4143/4959 [1:55:20<24:42,  1.82s/it]

 84%|████████▎ | 4144/4959 [1:55:22<25:19,  1.86s/it]

 84%|████████▎ | 4145/4959 [1:55:24<25:59,  1.92s/it]

 84%|████████▎ | 4146/4959 [1:55:26<25:01,  1.85s/it]

 84%|████████▎ | 4147/4959 [1:55:27<24:09,  1.78s/it]

 84%|████████▎ | 4148/4959 [1:55:29<25:10,  1.86s/it]

 84%|████████▎ | 4149/4959 [1:55:31<25:50,  1.91s/it]

 84%|████████▎ | 4150/4959 [1:55:33<24:52,  1.84s/it]

 84%|████████▎ | 4151/4959 [1:55:35<25:35,  1.90s/it]

 84%|████████▎ | 4152/4959 [1:55:37<26:05,  1.94s/it]

 84%|████████▎ | 4153/4959 [1:55:39<25:04,  1.87s/it]

 84%|████████▍ | 4154/4959 [1:55:41<25:41,  1.91s/it]

 84%|████████▍ | 4155/4959 [1:55:43<24:48,  1.85s/it]

 84%|████████▍ | 4156/4959 [1:55:44<24:07,  1.80s/it]

 84%|████████▍ | 4157/4959 [1:55:46<23:47,  1.78s/it]

 84%|████████▍ | 4158/4959 [1:55:48<23:21,  1.75s/it]

 84%|████████▍ | 4159/4959 [1:55:50<24:30,  1.84s/it]

 84%|████████▍ | 4160/4959 [1:55:51<23:50,  1.79s/it]

 84%|████████▍ | 4161/4959 [1:55:53<24:43,  1.86s/it]

 84%|████████▍ | 4162/4959 [1:55:55<24:01,  1.81s/it]

 84%|████████▍ | 4163/4959 [1:55:57<24:51,  1.87s/it]

 84%|████████▍ | 4164/4959 [1:55:59<25:29,  1.92s/it]

 84%|████████▍ | 4165/4959 [1:56:01<25:55,  1.96s/it]

 84%|████████▍ | 4166/4959 [1:56:03<26:09,  1.98s/it]

 84%|████████▍ | 4167/4959 [1:56:06<27:08,  2.06s/it]

 84%|████████▍ | 4168/4959 [1:56:07<25:28,  1.93s/it]

 84%|████████▍ | 4169/4959 [1:56:09<25:54,  1.97s/it]

 84%|████████▍ | 4170/4959 [1:56:11<26:01,  1.98s/it]

 84%|████████▍ | 4171/4959 [1:56:13<26:15,  2.00s/it]

 84%|████████▍ | 4172/4959 [1:56:15<24:58,  1.90s/it]

 84%|████████▍ | 4173/4959 [1:56:17<24:01,  1.83s/it]

 84%|████████▍ | 4174/4959 [1:56:19<24:41,  1.89s/it]

 84%|████████▍ | 4175/4959 [1:56:21<25:08,  1.92s/it]

 84%|████████▍ | 4176/4959 [1:56:22<24:05,  1.85s/it]

 84%|████████▍ | 4177/4959 [1:56:24<23:24,  1.80s/it]

 84%|████████▍ | 4178/4959 [1:56:26<24:18,  1.87s/it]

 84%|████████▍ | 4179/4959 [1:56:28<23:41,  1.82s/it]

 84%|████████▍ | 4180/4959 [1:56:30<24:28,  1.88s/it]

 84%|████████▍ | 4181/4959 [1:56:32<24:51,  1.92s/it]

 84%|████████▍ | 4182/4959 [1:56:33<23:54,  1.85s/it]

 84%|████████▍ | 4183/4959 [1:56:35<23:14,  1.80s/it]

 84%|████████▍ | 4184/4959 [1:56:37<24:09,  1.87s/it]

 84%|████████▍ | 4185/4959 [1:56:39<23:24,  1.81s/it]

 84%|████████▍ | 4186/4959 [1:56:41<24:05,  1.87s/it]

 84%|████████▍ | 4187/4959 [1:56:43<23:22,  1.82s/it]

 84%|████████▍ | 4188/4959 [1:56:45<24:08,  1.88s/it]

 84%|████████▍ | 4189/4959 [1:56:46<23:12,  1.81s/it]

 84%|████████▍ | 4190/4959 [1:56:48<24:05,  1.88s/it]

 85%|████████▍ | 4191/4959 [1:56:50<24:31,  1.92s/it]

 85%|████████▍ | 4192/4959 [1:56:52<23:38,  1.85s/it]

 85%|████████▍ | 4193/4959 [1:56:54<23:01,  1.80s/it]

 85%|████████▍ | 4194/4959 [1:56:55<22:32,  1.77s/it]

 85%|████████▍ | 4195/4959 [1:56:57<22:09,  1.74s/it]

 85%|████████▍ | 4196/4959 [1:56:59<21:49,  1.72s/it]

 85%|████████▍ | 4197/4959 [1:57:00<21:41,  1.71s/it]

 85%|████████▍ | 4198/4959 [1:57:02<22:48,  1.80s/it]

 85%|████████▍ | 4199/4959 [1:57:04<23:32,  1.86s/it]

 85%|████████▍ | 4200/4959 [1:57:06<24:09,  1.91s/it]

 85%|████████▍ | 4201/4959 [1:57:08<24:32,  1.94s/it]

 85%|████████▍ | 4202/4959 [1:57:10<24:49,  1.97s/it]

 85%|████████▍ | 4203/4959 [1:57:12<23:43,  1.88s/it]

 85%|████████▍ | 4204/4959 [1:57:14<23:08,  1.84s/it]

 85%|████████▍ | 4205/4959 [1:57:16<23:46,  1.89s/it]

 85%|████████▍ | 4206/4959 [1:57:18<22:57,  1.83s/it]

 85%|████████▍ | 4207/4959 [1:57:19<22:21,  1.78s/it]

 85%|████████▍ | 4208/4959 [1:57:21<22:17,  1.78s/it]

 85%|████████▍ | 4209/4959 [1:57:23<21:48,  1.75s/it]

 85%|████████▍ | 4210/4959 [1:57:25<22:42,  1.82s/it]

 85%|████████▍ | 4211/4959 [1:57:26<22:09,  1.78s/it]

 85%|████████▍ | 4212/4959 [1:57:28<23:09,  1.86s/it]

 85%|████████▍ | 4213/4959 [1:57:30<23:48,  1.91s/it]

 85%|████████▍ | 4214/4959 [1:57:33<24:50,  2.00s/it]

 85%|████████▍ | 4215/4959 [1:57:34<23:41,  1.91s/it]

 85%|████████▌ | 4216/4959 [1:57:36<24:07,  1.95s/it]

 85%|████████▌ | 4217/4959 [1:57:38<24:22,  1.97s/it]

 85%|████████▌ | 4218/4959 [1:57:40<23:17,  1.89s/it]

 85%|████████▌ | 4219/4959 [1:57:42<23:42,  1.92s/it]

 85%|████████▌ | 4220/4959 [1:57:44<22:46,  1.85s/it]

 85%|████████▌ | 4221/4959 [1:57:45<22:07,  1.80s/it]

 85%|████████▌ | 4222/4959 [1:57:47<22:56,  1.87s/it]

 85%|████████▌ | 4223/4959 [1:57:50<23:31,  1.92s/it]

 85%|████████▌ | 4224/4959 [1:57:52<23:54,  1.95s/it]

 85%|████████▌ | 4225/4959 [1:57:54<24:08,  1.97s/it]

 85%|████████▌ | 4226/4959 [1:57:55<23:02,  1.89s/it]

 85%|████████▌ | 4227/4959 [1:57:57<23:32,  1.93s/it]

 85%|████████▌ | 4228/4959 [1:57:59<23:53,  1.96s/it]

 85%|████████▌ | 4229/4959 [1:58:01<22:51,  1.88s/it]

 85%|████████▌ | 4230/4959 [1:58:03<23:27,  1.93s/it]

 85%|████████▌ | 4231/4959 [1:58:05<23:46,  1.96s/it]

 85%|████████▌ | 4232/4959 [1:58:07<24:00,  1.98s/it]

 85%|████████▌ | 4233/4959 [1:58:09<22:45,  1.88s/it]

 85%|████████▌ | 4234/4959 [1:58:11<23:21,  1.93s/it]

 85%|████████▌ | 4235/4959 [1:58:13<22:25,  1.86s/it]

 85%|████████▌ | 4236/4959 [1:58:15<22:58,  1.91s/it]

 85%|████████▌ | 4237/4959 [1:58:17<23:27,  1.95s/it]

 85%|████████▌ | 4238/4959 [1:58:19<23:45,  1.98s/it]

 85%|████████▌ | 4239/4959 [1:58:21<23:55,  1.99s/it]

 86%|████████▌ | 4240/4959 [1:58:22<22:49,  1.90s/it]

 86%|████████▌ | 4241/4959 [1:58:24<21:57,  1.84s/it]

 86%|████████▌ | 4242/4959 [1:58:26<22:39,  1.90s/it]

 86%|████████▌ | 4243/4959 [1:58:28<23:13,  1.95s/it]

 86%|████████▌ | 4244/4959 [1:58:30<22:22,  1.88s/it]

 86%|████████▌ | 4245/4959 [1:58:32<22:58,  1.93s/it]

 86%|████████▌ | 4246/4959 [1:58:34<22:36,  1.90s/it]

 86%|████████▌ | 4247/4959 [1:58:36<23:10,  1.95s/it]

 86%|████████▌ | 4248/4959 [1:58:38<23:36,  1.99s/it]

 86%|████████▌ | 4249/4959 [1:58:40<23:47,  2.01s/it]

 86%|████████▌ | 4250/4959 [1:58:42<23:53,  2.02s/it]

 86%|████████▌ | 4251/4959 [1:58:44<23:57,  2.03s/it]

 86%|████████▌ | 4252/4959 [1:58:46<22:49,  1.94s/it]

 86%|████████▌ | 4253/4959 [1:58:47<22:05,  1.88s/it]

 86%|████████▌ | 4254/4959 [1:58:49<21:28,  1.83s/it]

 86%|████████▌ | 4255/4959 [1:58:51<23:02,  1.96s/it]

 86%|████████▌ | 4256/4959 [1:58:53<22:07,  1.89s/it]

 86%|████████▌ | 4257/4959 [1:58:55<22:39,  1.94s/it]

 86%|████████▌ | 4258/4959 [1:58:57<23:06,  1.98s/it]

 86%|████████▌ | 4259/4959 [1:58:59<23:23,  2.01s/it]

 86%|████████▌ | 4260/4959 [1:59:01<23:32,  2.02s/it]

 86%|████████▌ | 4261/4959 [1:59:03<22:23,  1.93s/it]

 86%|████████▌ | 4262/4959 [1:59:05<21:28,  1.85s/it]

 86%|████████▌ | 4263/4959 [1:59:07<20:55,  1.80s/it]

 86%|████████▌ | 4264/4959 [1:59:08<20:33,  1.77s/it]

 86%|████████▌ | 4265/4959 [1:59:10<20:15,  1.75s/it]

 86%|████████▌ | 4266/4959 [1:59:12<20:13,  1.75s/it]

 86%|████████▌ | 4267/4959 [1:59:13<20:00,  1.74s/it]

 86%|████████▌ | 4268/4959 [1:59:15<19:51,  1.72s/it]

 86%|████████▌ | 4269/4959 [1:59:17<19:45,  1.72s/it]

 86%|████████▌ | 4270/4959 [1:59:19<20:52,  1.82s/it]

 86%|████████▌ | 4271/4959 [1:59:21<21:42,  1.89s/it]

 86%|████████▌ | 4272/4959 [1:59:23<22:14,  1.94s/it]

 86%|████████▌ | 4273/4959 [1:59:25<22:49,  2.00s/it]

 86%|████████▌ | 4274/4959 [1:59:27<22:01,  1.93s/it]

 86%|████████▌ | 4275/4959 [1:59:29<22:30,  1.97s/it]

 86%|████████▌ | 4276/4959 [1:59:31<21:33,  1.89s/it]

 86%|████████▌ | 4277/4959 [1:59:32<20:54,  1.84s/it]

 86%|████████▋ | 4278/4959 [1:59:34<20:23,  1.80s/it]

 86%|████████▋ | 4279/4959 [1:59:36<20:06,  1.77s/it]

 86%|████████▋ | 4280/4959 [1:59:37<19:51,  1.76s/it]

 86%|████████▋ | 4281/4959 [1:59:40<21:10,  1.87s/it]

 86%|████████▋ | 4282/4959 [1:59:41<20:38,  1.83s/it]

 86%|████████▋ | 4283/4959 [1:59:43<20:13,  1.79s/it]

 86%|████████▋ | 4284/4959 [1:59:45<19:53,  1.77s/it]

 86%|████████▋ | 4285/4959 [1:59:46<19:37,  1.75s/it]

 86%|████████▋ | 4286/4959 [1:59:48<20:00,  1.78s/it]

 86%|████████▋ | 4287/4959 [1:59:50<20:54,  1.87s/it]

 86%|████████▋ | 4288/4959 [1:59:52<21:30,  1.92s/it]

 86%|████████▋ | 4289/4959 [1:59:54<20:41,  1.85s/it]

 87%|████████▋ | 4290/4959 [1:59:56<21:17,  1.91s/it]

 87%|████████▋ | 4291/4959 [1:59:58<20:33,  1.85s/it]

 87%|████████▋ | 4292/4959 [2:00:00<21:14,  1.91s/it]

 87%|████████▋ | 4293/4959 [2:00:02<21:39,  1.95s/it]

 87%|████████▋ | 4294/4959 [2:00:04<21:57,  1.98s/it]

 87%|████████▋ | 4295/4959 [2:00:06<22:06,  2.00s/it]

 87%|████████▋ | 4296/4959 [2:00:08<21:07,  1.91s/it]

 87%|████████▋ | 4297/4959 [2:00:10<21:32,  1.95s/it]

 87%|████████▋ | 4298/4959 [2:00:12<20:41,  1.88s/it]

 87%|████████▋ | 4299/4959 [2:00:14<21:15,  1.93s/it]

 87%|████████▋ | 4300/4959 [2:00:15<20:28,  1.86s/it]

 87%|████████▋ | 4301/4959 [2:00:17<21:00,  1.92s/it]

 87%|████████▋ | 4302/4959 [2:00:19<20:44,  1.89s/it]

 87%|████████▋ | 4303/4959 [2:00:21<20:09,  1.84s/it]

 87%|████████▋ | 4304/4959 [2:00:23<20:50,  1.91s/it]

 87%|████████▋ | 4305/4959 [2:00:25<20:11,  1.85s/it]

 87%|████████▋ | 4306/4959 [2:00:26<19:37,  1.80s/it]

 87%|████████▋ | 4307/4959 [2:00:28<20:25,  1.88s/it]

 87%|████████▋ | 4308/4959 [2:00:30<19:48,  1.83s/it]

 87%|████████▋ | 4309/4959 [2:00:32<20:38,  1.91s/it]

 87%|████████▋ | 4310/4959 [2:00:34<20:02,  1.85s/it]

 87%|████████▋ | 4311/4959 [2:00:36<20:42,  1.92s/it]

 87%|████████▋ | 4312/4959 [2:00:38<21:06,  1.96s/it]

 87%|████████▋ | 4313/4959 [2:00:40<20:12,  1.88s/it]

 87%|████████▋ | 4314/4959 [2:00:41<19:30,  1.81s/it]

 87%|████████▋ | 4315/4959 [2:00:43<18:54,  1.76s/it]

 87%|████████▋ | 4316/4959 [2:00:45<19:35,  1.83s/it]

 87%|████████▋ | 4317/4959 [2:00:47<18:56,  1.77s/it]

 87%|████████▋ | 4318/4959 [2:00:49<19:37,  1.84s/it]

 87%|████████▋ | 4319/4959 [2:00:50<18:56,  1.78s/it]

 87%|████████▋ | 4320/4959 [2:00:52<19:33,  1.84s/it]

 87%|████████▋ | 4321/4959 [2:00:54<18:53,  1.78s/it]

 87%|████████▋ | 4322/4959 [2:00:56<19:31,  1.84s/it]

 87%|████████▋ | 4323/4959 [2:00:58<18:52,  1.78s/it]

 87%|████████▋ | 4324/4959 [2:00:59<18:22,  1.74s/it]

 87%|████████▋ | 4325/4959 [2:01:01<18:01,  1.71s/it]

 87%|████████▋ | 4326/4959 [2:01:03<18:52,  1.79s/it]

 87%|████████▋ | 4327/4959 [2:01:05<19:27,  1.85s/it]

 87%|████████▋ | 4328/4959 [2:01:07<19:48,  1.88s/it]

 87%|████████▋ | 4329/4959 [2:01:08<18:59,  1.81s/it]

 87%|████████▋ | 4330/4959 [2:01:10<19:34,  1.87s/it]

 87%|████████▋ | 4331/4959 [2:01:12<19:53,  1.90s/it]

 87%|████████▋ | 4332/4959 [2:01:14<20:08,  1.93s/it]

 87%|████████▋ | 4333/4959 [2:01:16<20:16,  1.94s/it]

 87%|████████▋ | 4334/4959 [2:01:18<20:21,  1.96s/it]

 87%|████████▋ | 4335/4959 [2:01:20<19:24,  1.87s/it]

 87%|████████▋ | 4336/4959 [2:01:22<18:39,  1.80s/it]

 87%|████████▋ | 4337/4959 [2:01:24<19:10,  1.85s/it]

 87%|████████▋ | 4338/4959 [2:01:25<18:29,  1.79s/it]

 87%|████████▋ | 4339/4959 [2:01:27<18:02,  1.75s/it]

 88%|████████▊ | 4340/4959 [2:01:29<17:40,  1.71s/it]

 88%|████████▊ | 4341/4959 [2:01:31<18:31,  1.80s/it]

 88%|████████▊ | 4342/4959 [2:01:32<18:00,  1.75s/it]

 88%|████████▊ | 4343/4959 [2:01:34<17:37,  1.72s/it]

 88%|████████▊ | 4344/4959 [2:01:36<18:21,  1.79s/it]

 88%|████████▊ | 4345/4959 [2:01:37<17:51,  1.74s/it]

 88%|████████▊ | 4346/4959 [2:01:39<18:48,  1.84s/it]

 88%|████████▊ | 4347/4959 [2:01:41<18:22,  1.80s/it]

 88%|████████▊ | 4348/4959 [2:01:43<18:04,  1.77s/it]

 88%|████████▊ | 4349/4959 [2:01:45<17:48,  1.75s/it]

 88%|████████▊ | 4350/4959 [2:01:46<17:39,  1.74s/it]

 88%|████████▊ | 4351/4959 [2:01:48<17:30,  1.73s/it]

 88%|████████▊ | 4352/4959 [2:01:50<17:24,  1.72s/it]

 88%|████████▊ | 4353/4959 [2:01:51<17:24,  1.72s/it]

 88%|████████▊ | 4354/4959 [2:01:53<18:20,  1.82s/it]

 88%|████████▊ | 4355/4959 [2:01:55<17:59,  1.79s/it]

 88%|████████▊ | 4356/4959 [2:01:57<17:41,  1.76s/it]

 88%|████████▊ | 4357/4959 [2:01:59<17:26,  1.74s/it]

 88%|████████▊ | 4358/4959 [2:02:00<17:17,  1.73s/it]

 88%|████████▊ | 4359/4959 [2:02:02<17:11,  1.72s/it]

 88%|████████▊ | 4360/4959 [2:02:04<17:07,  1.71s/it]

 88%|████████▊ | 4361/4959 [2:02:05<17:01,  1.71s/it]

 88%|████████▊ | 4362/4959 [2:02:07<18:10,  1.83s/it]

 88%|████████▊ | 4363/4959 [2:02:10<18:58,  1.91s/it]

 88%|████████▊ | 4364/4959 [2:02:12<19:18,  1.95s/it]

 88%|████████▊ | 4365/4959 [2:02:13<18:32,  1.87s/it]

 88%|████████▊ | 4366/4959 [2:02:15<19:01,  1.92s/it]

 88%|████████▊ | 4367/4959 [2:02:17<18:20,  1.86s/it]

 88%|████████▊ | 4368/4959 [2:02:19<18:52,  1.92s/it]

 88%|████████▊ | 4369/4959 [2:02:21<19:12,  1.95s/it]

 88%|████████▊ | 4370/4959 [2:02:23<19:29,  1.99s/it]

 88%|████████▊ | 4371/4959 [2:02:25<18:41,  1.91s/it]

 88%|████████▊ | 4372/4959 [2:02:27<19:07,  1.96s/it]

 88%|████████▊ | 4373/4959 [2:02:29<19:21,  1.98s/it]

 88%|████████▊ | 4374/4959 [2:02:31<18:38,  1.91s/it]

 88%|████████▊ | 4375/4959 [2:02:32<17:58,  1.85s/it]

 88%|████████▊ | 4376/4959 [2:02:34<17:34,  1.81s/it]

 88%|████████▊ | 4377/4959 [2:02:36<17:13,  1.78s/it]

 88%|████████▊ | 4378/4959 [2:02:38<17:00,  1.76s/it]

 88%|████████▊ | 4379/4959 [2:02:39<16:49,  1.74s/it]

 88%|████████▊ | 4380/4959 [2:02:41<17:47,  1.84s/it]

 88%|████████▊ | 4381/4959 [2:02:43<17:26,  1.81s/it]

 88%|████████▊ | 4382/4959 [2:02:45<17:10,  1.79s/it]

 88%|████████▊ | 4383/4959 [2:02:47<16:42,  1.74s/it]

 88%|████████▊ | 4384/4959 [2:02:48<16:24,  1.71s/it]

 88%|████████▊ | 4385/4959 [2:02:50<16:14,  1.70s/it]

 88%|████████▊ | 4386/4959 [2:02:51<16:02,  1.68s/it]

 88%|████████▊ | 4387/4959 [2:02:53<16:53,  1.77s/it]

 88%|████████▊ | 4388/4959 [2:02:55<17:27,  1.84s/it]

 89%|████████▊ | 4389/4959 [2:02:57<16:53,  1.78s/it]

 89%|████████▊ | 4390/4959 [2:02:59<18:06,  1.91s/it]

 89%|████████▊ | 4391/4959 [2:03:01<18:19,  1.94s/it]

 89%|████████▊ | 4392/4959 [2:03:03<18:28,  1.95s/it]

 89%|████████▊ | 4393/4959 [2:03:05<17:32,  1.86s/it]

 89%|████████▊ | 4394/4959 [2:03:07<16:53,  1.79s/it]

 89%|████████▊ | 4395/4959 [2:03:08<16:27,  1.75s/it]

 89%|████████▊ | 4396/4959 [2:03:10<16:11,  1.72s/it]

 89%|████████▊ | 4397/4959 [2:03:12<15:58,  1.71s/it]

 89%|████████▊ | 4398/4959 [2:03:13<15:46,  1.69s/it]

 89%|████████▊ | 4399/4959 [2:03:15<16:35,  1.78s/it]

 89%|████████▊ | 4400/4959 [2:03:17<16:10,  1.74s/it]

 89%|████████▊ | 4401/4959 [2:03:18<15:52,  1.71s/it]

 89%|████████▉ | 4402/4959 [2:03:20<16:35,  1.79s/it]

 89%|████████▉ | 4403/4959 [2:03:22<16:07,  1.74s/it]

 89%|████████▉ | 4404/4959 [2:03:24<15:48,  1.71s/it]

 89%|████████▉ | 4405/4959 [2:03:25<15:34,  1.69s/it]

 89%|████████▉ | 4406/4959 [2:03:27<15:26,  1.68s/it]

 89%|████████▉ | 4407/4959 [2:03:29<15:22,  1.67s/it]

 89%|████████▉ | 4408/4959 [2:03:30<15:19,  1.67s/it]

 89%|████████▉ | 4409/4959 [2:03:32<15:12,  1.66s/it]

 89%|████████▉ | 4410/4959 [2:03:34<15:07,  1.65s/it]

 89%|████████▉ | 4411/4959 [2:03:35<15:05,  1.65s/it]

 89%|████████▉ | 4412/4959 [2:03:37<15:02,  1.65s/it]

 89%|████████▉ | 4413/4959 [2:03:39<15:01,  1.65s/it]

 89%|████████▉ | 4414/4959 [2:03:40<14:57,  1.65s/it]

 89%|████████▉ | 4415/4959 [2:03:42<14:58,  1.65s/it]

 89%|████████▉ | 4416/4959 [2:03:44<15:55,  1.76s/it]

 89%|████████▉ | 4417/4959 [2:03:46<16:29,  1.83s/it]

 89%|████████▉ | 4418/4959 [2:03:48<16:53,  1.87s/it]

 89%|████████▉ | 4419/4959 [2:03:49<16:18,  1.81s/it]

 89%|████████▉ | 4420/4959 [2:03:51<16:47,  1.87s/it]

 89%|████████▉ | 4421/4959 [2:03:53<17:04,  1.90s/it]

 89%|████████▉ | 4422/4959 [2:03:55<16:19,  1.82s/it]

 89%|████████▉ | 4423/4959 [2:03:57<17:00,  1.90s/it]

 89%|████████▉ | 4424/4959 [2:03:59<16:18,  1.83s/it]

 89%|████████▉ | 4425/4959 [2:04:00<15:47,  1.77s/it]

 89%|████████▉ | 4426/4959 [2:04:02<15:25,  1.74s/it]

 89%|████████▉ | 4427/4959 [2:04:04<16:04,  1.81s/it]

 89%|████████▉ | 4428/4959 [2:04:06<15:35,  1.76s/it]

 89%|████████▉ | 4429/4959 [2:04:07<15:18,  1.73s/it]

 89%|████████▉ | 4430/4959 [2:04:09<15:57,  1.81s/it]

 89%|████████▉ | 4431/4959 [2:04:11<15:26,  1.76s/it]

 89%|████████▉ | 4432/4959 [2:04:13<16:01,  1.82s/it]

 89%|████████▉ | 4433/4959 [2:04:15<15:34,  1.78s/it]

 89%|████████▉ | 4434/4959 [2:04:16<15:15,  1.74s/it]

 89%|████████▉ | 4435/4959 [2:04:18<14:57,  1.71s/it]

 89%|████████▉ | 4436/4959 [2:04:20<15:38,  1.79s/it]

 89%|████████▉ | 4437/4959 [2:04:22<15:12,  1.75s/it]

 89%|████████▉ | 4438/4959 [2:04:23<14:58,  1.72s/it]

 90%|████████▉ | 4439/4959 [2:04:25<14:44,  1.70s/it]

 90%|████████▉ | 4440/4959 [2:04:27<14:37,  1.69s/it]

 90%|████████▉ | 4441/4959 [2:04:28<14:31,  1.68s/it]

 90%|████████▉ | 4442/4959 [2:04:30<14:23,  1.67s/it]

 90%|████████▉ | 4443/4959 [2:04:32<14:25,  1.68s/it]

 90%|████████▉ | 4444/4959 [2:04:33<14:17,  1.67s/it]

 90%|████████▉ | 4445/4959 [2:04:35<14:11,  1.66s/it]

 90%|████████▉ | 4446/4959 [2:04:37<15:01,  1.76s/it]

 90%|████████▉ | 4447/4959 [2:04:39<15:30,  1.82s/it]

 90%|████████▉ | 4448/4959 [2:04:41<15:52,  1.86s/it]

 90%|████████▉ | 4449/4959 [2:04:42<15:17,  1.80s/it]

 90%|████████▉ | 4450/4959 [2:04:44<14:56,  1.76s/it]

 90%|████████▉ | 4451/4959 [2:04:46<14:38,  1.73s/it]

 90%|████████▉ | 4452/4959 [2:04:47<14:27,  1.71s/it]

 90%|████████▉ | 4453/4959 [2:04:49<14:14,  1.69s/it]

 90%|████████▉ | 4454/4959 [2:04:51<15:02,  1.79s/it]

 90%|████████▉ | 4455/4959 [2:04:53<15:31,  1.85s/it]

 90%|████████▉ | 4456/4959 [2:04:55<15:53,  1.90s/it]

 90%|████████▉ | 4457/4959 [2:04:57<16:09,  1.93s/it]

 90%|████████▉ | 4458/4959 [2:04:59<16:16,  1.95s/it]

 90%|████████▉ | 4459/4959 [2:05:01<16:23,  1.97s/it]

 90%|████████▉ | 4460/4959 [2:05:03<16:27,  1.98s/it]

 90%|████████▉ | 4461/4959 [2:05:05<16:32,  1.99s/it]

 90%|████████▉ | 4462/4959 [2:05:07<16:31,  1.99s/it]

 90%|████████▉ | 4463/4959 [2:05:09<16:34,  2.01s/it]

 90%|█████████ | 4464/4959 [2:05:11<16:30,  2.00s/it]

 90%|█████████ | 4465/4959 [2:05:13<16:30,  2.00s/it]

 90%|█████████ | 4466/4959 [2:05:15<16:24,  2.00s/it]

 90%|█████████ | 4467/4959 [2:05:17<16:26,  2.01s/it]

 90%|█████████ | 4468/4959 [2:05:19<16:24,  2.01s/it]

 90%|█████████ | 4469/4959 [2:05:21<16:22,  2.01s/it]

 90%|█████████ | 4470/4959 [2:05:23<15:25,  1.89s/it]

 90%|█████████ | 4471/4959 [2:05:25<15:42,  1.93s/it]

 90%|█████████ | 4472/4959 [2:05:26<14:58,  1.85s/it]

 90%|█████████ | 4473/4959 [2:05:28<15:16,  1.89s/it]

 90%|█████████ | 4474/4959 [2:05:30<15:33,  1.92s/it]

 90%|█████████ | 4475/4959 [2:05:32<14:52,  1.84s/it]

 90%|█████████ | 4476/4959 [2:05:34<14:21,  1.78s/it]

 90%|█████████ | 4477/4959 [2:05:35<14:04,  1.75s/it]

 90%|█████████ | 4478/4959 [2:05:37<13:45,  1.72s/it]

 90%|█████████ | 4479/4959 [2:05:39<13:31,  1.69s/it]

 90%|█████████ | 4480/4959 [2:05:40<13:27,  1.69s/it]

 90%|█████████ | 4481/4959 [2:05:42<13:18,  1.67s/it]

 90%|█████████ | 4482/4959 [2:05:44<13:11,  1.66s/it]

 90%|█████████ | 4483/4959 [2:05:45<13:08,  1.66s/it]

 90%|█████████ | 4484/4959 [2:05:47<13:58,  1.77s/it]

 90%|█████████ | 4485/4959 [2:05:49<13:40,  1.73s/it]

 90%|█████████ | 4486/4959 [2:05:51<14:15,  1.81s/it]

 90%|█████████ | 4487/4959 [2:05:53<14:42,  1.87s/it]

 91%|█████████ | 4488/4959 [2:05:55<14:08,  1.80s/it]

 91%|█████████ | 4489/4959 [2:05:57<14:34,  1.86s/it]

 91%|█████████ | 4490/4959 [2:05:59<14:57,  1.91s/it]

 91%|█████████ | 4491/4959 [2:06:01<15:06,  1.94s/it]

 91%|█████████ | 4492/4959 [2:06:02<14:38,  1.88s/it]

 91%|█████████ | 4493/4959 [2:06:04<14:58,  1.93s/it]

 91%|█████████ | 4494/4959 [2:06:06<15:06,  1.95s/it]

 91%|█████████ | 4495/4959 [2:06:08<15:09,  1.96s/it]

 91%|█████████ | 4496/4959 [2:06:10<14:23,  1.87s/it]

 91%|█████████ | 4497/4959 [2:06:12<14:36,  1.90s/it]

 91%|█████████ | 4498/4959 [2:06:14<13:59,  1.82s/it]

 91%|█████████ | 4499/4959 [2:06:15<13:33,  1.77s/it]

 91%|█████████ | 4500/4959 [2:06:17<14:08,  1.85s/it]

 91%|█████████ | 4501/4959 [2:06:19<13:38,  1.79s/it]

 91%|█████████ | 4502/4959 [2:06:21<13:18,  1.75s/it]

 91%|█████████ | 4503/4959 [2:06:22<13:02,  1.72s/it]

 91%|█████████ | 4504/4959 [2:06:24<13:35,  1.79s/it]

 91%|█████████ | 4505/4959 [2:06:26<14:02,  1.86s/it]

 91%|█████████ | 4506/4959 [2:06:28<13:31,  1.79s/it]

 91%|█████████ | 4507/4959 [2:06:30<13:08,  1.75s/it]

 91%|█████████ | 4508/4959 [2:06:31<13:00,  1.73s/it]

 91%|█████████ | 4509/4959 [2:06:33<13:32,  1.81s/it]

 91%|█████████ | 4510/4959 [2:06:35<13:09,  1.76s/it]

 91%|█████████ | 4511/4959 [2:06:37<12:54,  1.73s/it]

 91%|█████████ | 4512/4959 [2:06:38<12:44,  1.71s/it]

 91%|█████████ | 4513/4959 [2:06:40<12:32,  1.69s/it]

 91%|█████████ | 4514/4959 [2:06:42<12:25,  1.68s/it]

 91%|█████████ | 4515/4959 [2:06:44<13:10,  1.78s/it]

 91%|█████████ | 4516/4959 [2:06:45<12:53,  1.75s/it]

 91%|█████████ | 4517/4959 [2:06:47<13:24,  1.82s/it]

 91%|█████████ | 4518/4959 [2:06:49<12:58,  1.77s/it]

 91%|█████████ | 4519/4959 [2:06:50<12:43,  1.73s/it]

 91%|█████████ | 4520/4959 [2:06:52<12:30,  1.71s/it]

 91%|█████████ | 4521/4959 [2:06:54<12:20,  1.69s/it]

 91%|█████████ | 4522/4959 [2:06:55<12:16,  1.69s/it]

 91%|█████████ | 4523/4959 [2:06:57<12:09,  1.67s/it]

 91%|█████████ | 4524/4959 [2:06:59<12:03,  1.66s/it]

 91%|█████████ | 4525/4959 [2:07:00<11:57,  1.65s/it]

 91%|█████████▏| 4526/4959 [2:07:02<12:00,  1.66s/it]

 91%|█████████▏| 4527/4959 [2:07:04<12:47,  1.78s/it]

 91%|█████████▏| 4528/4959 [2:07:06<13:13,  1.84s/it]

 91%|█████████▏| 4529/4959 [2:07:08<13:32,  1.89s/it]

 91%|█████████▏| 4530/4959 [2:07:10<13:46,  1.93s/it]

 91%|█████████▏| 4531/4959 [2:07:12<13:06,  1.84s/it]

 91%|█████████▏| 4532/4959 [2:07:14<13:24,  1.88s/it]

 91%|█████████▏| 4533/4959 [2:07:15<12:51,  1.81s/it]

 91%|█████████▏| 4534/4959 [2:07:17<13:12,  1.86s/it]

 91%|█████████▏| 4535/4959 [2:07:19<12:41,  1.80s/it]

 91%|█████████▏| 4536/4959 [2:07:21<12:21,  1.75s/it]

 91%|█████████▏| 4537/4959 [2:07:23<12:50,  1.83s/it]

 92%|█████████▏| 4538/4959 [2:07:25<13:08,  1.87s/it]

 92%|█████████▏| 4539/4959 [2:07:26<12:37,  1.80s/it]

 92%|█████████▏| 4540/4959 [2:07:28<12:14,  1.75s/it]

 92%|█████████▏| 4541/4959 [2:07:30<11:57,  1.72s/it]

 92%|█████████▏| 4542/4959 [2:07:31<11:47,  1.70s/it]

 92%|█████████▏| 4543/4959 [2:07:33<11:39,  1.68s/it]

 92%|█████████▏| 4544/4959 [2:07:34<11:33,  1.67s/it]

 92%|█████████▏| 4545/4959 [2:07:36<11:26,  1.66s/it]

 92%|█████████▏| 4546/4959 [2:07:38<12:06,  1.76s/it]

 92%|█████████▏| 4547/4959 [2:07:40<11:49,  1.72s/it]

 92%|█████████▏| 4548/4959 [2:07:42<12:18,  1.80s/it]

 92%|█████████▏| 4549/4959 [2:07:43<11:57,  1.75s/it]

 92%|█████████▏| 4550/4959 [2:07:45<11:42,  1.72s/it]

 92%|█████████▏| 4551/4959 [2:07:47<12:17,  1.81s/it]

 92%|█████████▏| 4552/4959 [2:07:49<11:55,  1.76s/it]

 92%|█████████▏| 4553/4959 [2:07:50<11:42,  1.73s/it]

 92%|█████████▏| 4554/4959 [2:07:52<12:12,  1.81s/it]

 92%|█████████▏| 4555/4959 [2:07:54<11:50,  1.76s/it]

 92%|█████████▏| 4556/4959 [2:07:56<12:15,  1.83s/it]

 92%|█████████▏| 4557/4959 [2:07:58<11:53,  1.78s/it]

 92%|█████████▏| 4558/4959 [2:07:59<11:35,  1.73s/it]

 92%|█████████▏| 4559/4959 [2:08:01<12:01,  1.80s/it]

 92%|█████████▏| 4560/4959 [2:08:03<12:20,  1.86s/it]

 92%|█████████▏| 4561/4959 [2:08:05<11:52,  1.79s/it]

 92%|█████████▏| 4562/4959 [2:08:06<11:33,  1.75s/it]

 92%|█████████▏| 4563/4959 [2:08:08<11:19,  1.72s/it]

 92%|█████████▏| 4564/4959 [2:08:10<11:50,  1.80s/it]

 92%|█████████▏| 4565/4959 [2:08:12<11:29,  1.75s/it]

 92%|█████████▏| 4566/4959 [2:08:13<11:14,  1.72s/it]

 92%|█████████▏| 4567/4959 [2:08:15<11:03,  1.69s/it]

 92%|█████████▏| 4568/4959 [2:08:17<11:38,  1.79s/it]

 92%|█████████▏| 4569/4959 [2:08:19<11:59,  1.84s/it]

 92%|█████████▏| 4570/4959 [2:08:21<12:13,  1.89s/it]

 92%|█████████▏| 4571/4959 [2:08:23<11:42,  1.81s/it]

 92%|█████████▏| 4572/4959 [2:08:24<11:21,  1.76s/it]

 92%|█████████▏| 4573/4959 [2:08:26<11:05,  1.72s/it]

 92%|█████████▏| 4574/4959 [2:08:28<11:35,  1.81s/it]

 92%|█████████▏| 4575/4959 [2:08:30<11:14,  1.76s/it]

 92%|█████████▏| 4576/4959 [2:08:31<11:05,  1.74s/it]

 92%|█████████▏| 4577/4959 [2:08:33<11:02,  1.73s/it]

 92%|█████████▏| 4578/4959 [2:08:35<10:49,  1.70s/it]

 92%|█████████▏| 4579/4959 [2:08:37<11:22,  1.80s/it]

 92%|█████████▏| 4580/4959 [2:08:39<11:42,  1.85s/it]

 92%|█████████▏| 4581/4959 [2:08:40<11:15,  1.79s/it]

 92%|█████████▏| 4582/4959 [2:08:42<10:56,  1.74s/it]

 92%|█████████▏| 4583/4959 [2:08:43<10:41,  1.71s/it]

 92%|█████████▏| 4584/4959 [2:08:45<10:31,  1.68s/it]

 92%|█████████▏| 4585/4959 [2:08:47<10:23,  1.67s/it]

 92%|█████████▏| 4586/4959 [2:08:48<10:18,  1.66s/it]

 92%|█████████▏| 4587/4959 [2:08:50<10:15,  1.65s/it]

 93%|█████████▎| 4588/4959 [2:08:52<10:51,  1.76s/it]

 93%|█████████▎| 4589/4959 [2:08:54<10:39,  1.73s/it]

 93%|█████████▎| 4590/4959 [2:08:55<10:28,  1.70s/it]

 93%|█████████▎| 4591/4959 [2:08:57<10:57,  1.79s/it]

 93%|█████████▎| 4592/4959 [2:08:59<10:39,  1.74s/it]

 93%|█████████▎| 4593/4959 [2:09:01<10:24,  1.71s/it]

 93%|█████████▎| 4594/4959 [2:09:03<10:54,  1.79s/it]

 93%|█████████▎| 4595/4959 [2:09:05<11:13,  1.85s/it]

 93%|█████████▎| 4596/4959 [2:09:07<11:26,  1.89s/it]

 93%|█████████▎| 4597/4959 [2:09:09<11:35,  1.92s/it]

 93%|█████████▎| 4598/4959 [2:09:11<11:40,  1.94s/it]

 93%|█████████▎| 4599/4959 [2:09:12<11:06,  1.85s/it]

 93%|█████████▎| 4600/4959 [2:09:14<11:19,  1.89s/it]

 93%|█████████▎| 4601/4959 [2:09:16<11:30,  1.93s/it]

 93%|█████████▎| 4602/4959 [2:09:18<11:35,  1.95s/it]

 93%|█████████▎| 4603/4959 [2:09:20<12:05,  2.04s/it]

 93%|█████████▎| 4604/4959 [2:09:22<12:01,  2.03s/it]

 93%|█████████▎| 4605/4959 [2:09:24<11:55,  2.02s/it]

 93%|█████████▎| 4606/4959 [2:09:26<11:50,  2.01s/it]

 93%|█████████▎| 4607/4959 [2:09:28<11:09,  1.90s/it]

 93%|█████████▎| 4608/4959 [2:09:30<10:39,  1.82s/it]

 93%|█████████▎| 4609/4959 [2:09:31<10:18,  1.77s/it]

 93%|█████████▎| 4610/4959 [2:09:33<10:02,  1.73s/it]

 93%|█████████▎| 4611/4959 [2:09:35<09:52,  1.70s/it]

 93%|█████████▎| 4612/4959 [2:09:36<09:43,  1.68s/it]

 93%|█████████▎| 4613/4959 [2:09:38<09:38,  1.67s/it]

 93%|█████████▎| 4614/4959 [2:09:40<09:32,  1.66s/it]

 93%|█████████▎| 4615/4959 [2:09:42<10:06,  1.76s/it]

 93%|█████████▎| 4616/4959 [2:09:43<09:50,  1.72s/it]

 93%|█████████▎| 4617/4959 [2:09:45<09:41,  1.70s/it]

 93%|█████████▎| 4618/4959 [2:09:47<10:11,  1.79s/it]

 93%|█████████▎| 4619/4959 [2:09:48<09:56,  1.75s/it]

 93%|█████████▎| 4620/4959 [2:09:50<09:43,  1.72s/it]

 93%|█████████▎| 4621/4959 [2:09:52<10:06,  1.79s/it]

 93%|█████████▎| 4622/4959 [2:09:54<09:49,  1.75s/it]

 93%|█████████▎| 4623/4959 [2:09:55<09:39,  1.72s/it]

 93%|█████████▎| 4624/4959 [2:09:57<09:29,  1.70s/it]

 93%|█████████▎| 4625/4959 [2:09:59<09:22,  1.68s/it]

 93%|█████████▎| 4626/4959 [2:10:00<09:16,  1.67s/it]

 93%|█████████▎| 4627/4959 [2:10:02<09:11,  1.66s/it]

 93%|█████████▎| 4628/4959 [2:10:04<09:11,  1.67s/it]

 93%|█████████▎| 4629/4959 [2:10:06<09:41,  1.76s/it]

 93%|█████████▎| 4630/4959 [2:10:08<10:43,  1.96s/it]

 93%|█████████▎| 4631/4959 [2:10:10<10:10,  1.86s/it]

 93%|█████████▎| 4632/4959 [2:10:12<10:21,  1.90s/it]

 93%|█████████▎| 4633/4959 [2:10:13<09:54,  1.82s/it]

 93%|█████████▎| 4634/4959 [2:10:15<09:35,  1.77s/it]

 93%|█████████▎| 4635/4959 [2:10:17<09:55,  1.84s/it]

 93%|█████████▎| 4636/4959 [2:10:19<10:11,  1.89s/it]

 94%|█████████▎| 4637/4959 [2:10:21<09:46,  1.82s/it]

 94%|█████████▎| 4638/4959 [2:10:22<09:27,  1.77s/it]

 94%|█████████▎| 4639/4959 [2:10:24<09:12,  1.73s/it]

 94%|█████████▎| 4640/4959 [2:10:26<09:02,  1.70s/it]

 94%|█████████▎| 4641/4959 [2:10:27<08:53,  1.68s/it]

 94%|█████████▎| 4642/4959 [2:10:29<08:46,  1.66s/it]

 94%|█████████▎| 4643/4959 [2:10:30<08:41,  1.65s/it]

 94%|█████████▎| 4644/4959 [2:10:32<08:38,  1.65s/it]

 94%|█████████▎| 4645/4959 [2:10:34<08:40,  1.66s/it]

 94%|█████████▎| 4646/4959 [2:10:35<08:44,  1.67s/it]

 94%|█████████▎| 4647/4959 [2:10:37<09:13,  1.77s/it]

 94%|█████████▎| 4648/4959 [2:10:39<09:01,  1.74s/it]

 94%|█████████▎| 4649/4959 [2:10:41<09:26,  1.83s/it]

 94%|█████████▍| 4650/4959 [2:10:43<09:41,  1.88s/it]

 94%|█████████▍| 4651/4959 [2:10:45<09:20,  1.82s/it]

 94%|█████████▍| 4652/4959 [2:10:47<09:09,  1.79s/it]

 94%|█████████▍| 4653/4959 [2:10:49<09:28,  1.86s/it]

 94%|█████████▍| 4654/4959 [2:10:51<09:41,  1.91s/it]

 94%|█████████▍| 4655/4959 [2:10:53<09:50,  1.94s/it]

 94%|█████████▍| 4656/4959 [2:10:54<09:23,  1.86s/it]

 94%|█████████▍| 4657/4959 [2:10:56<09:36,  1.91s/it]

 94%|█████████▍| 4658/4959 [2:10:58<09:11,  1.83s/it]

 94%|█████████▍| 4659/4959 [2:11:00<09:27,  1.89s/it]

 94%|█████████▍| 4660/4959 [2:11:02<09:05,  1.82s/it]

 94%|█████████▍| 4661/4959 [2:11:03<08:53,  1.79s/it]

 94%|█████████▍| 4662/4959 [2:11:05<08:41,  1.75s/it]

 94%|█████████▍| 4663/4959 [2:11:07<09:05,  1.84s/it]

 94%|█████████▍| 4664/4959 [2:11:09<08:50,  1.80s/it]

 94%|█████████▍| 4665/4959 [2:11:10<08:40,  1.77s/it]

 94%|█████████▍| 4666/4959 [2:11:12<08:29,  1.74s/it]

 94%|█████████▍| 4667/4959 [2:11:14<08:22,  1.72s/it]

 94%|█████████▍| 4668/4959 [2:11:16<08:16,  1.71s/it]

 94%|█████████▍| 4669/4959 [2:11:17<08:13,  1.70s/it]

 94%|█████████▍| 4670/4959 [2:11:19<08:40,  1.80s/it]

 94%|█████████▍| 4671/4959 [2:11:21<08:58,  1.87s/it]

 94%|█████████▍| 4672/4959 [2:11:23<08:43,  1.82s/it]

 94%|█████████▍| 4673/4959 [2:11:25<08:27,  1.78s/it]

 94%|█████████▍| 4674/4959 [2:11:26<08:17,  1.74s/it]

 94%|█████████▍| 4675/4959 [2:11:28<08:43,  1.84s/it]

 94%|█████████▍| 4676/4959 [2:11:30<08:27,  1.79s/it]

 94%|█████████▍| 4677/4959 [2:11:32<08:16,  1.76s/it]

 94%|█████████▍| 4678/4959 [2:11:34<08:39,  1.85s/it]

 94%|█████████▍| 4679/4959 [2:11:36<08:52,  1.90s/it]

 94%|█████████▍| 4680/4959 [2:11:37<08:31,  1.83s/it]

 94%|█████████▍| 4681/4959 [2:11:39<08:16,  1.78s/it]

 94%|█████████▍| 4682/4959 [2:11:41<08:34,  1.86s/it]

 94%|█████████▍| 4683/4959 [2:11:43<08:45,  1.90s/it]

 94%|█████████▍| 4684/4959 [2:11:45<08:26,  1.84s/it]

 94%|█████████▍| 4685/4959 [2:11:47<08:38,  1.89s/it]

 94%|█████████▍| 4686/4959 [2:11:49<08:19,  1.83s/it]

 95%|█████████▍| 4687/4959 [2:11:50<08:04,  1.78s/it]

 95%|█████████▍| 4688/4959 [2:11:52<08:25,  1.86s/it]

 95%|█████████▍| 4689/4959 [2:11:54<08:09,  1.81s/it]

 95%|█████████▍| 4690/4959 [2:11:56<07:57,  1.77s/it]

 95%|█████████▍| 4691/4959 [2:11:57<07:48,  1.75s/it]

 95%|█████████▍| 4692/4959 [2:11:59<08:09,  1.83s/it]

 95%|█████████▍| 4693/4959 [2:12:01<08:22,  1.89s/it]

 95%|█████████▍| 4694/4959 [2:12:03<08:32,  1.94s/it]

 95%|█████████▍| 4695/4959 [2:12:06<08:40,  1.97s/it]

 95%|█████████▍| 4696/4959 [2:12:08<08:42,  1.99s/it]

 95%|█████████▍| 4697/4959 [2:12:09<08:16,  1.90s/it]

 95%|█████████▍| 4698/4959 [2:12:11<08:24,  1.93s/it]

 95%|█████████▍| 4699/4959 [2:12:13<08:02,  1.86s/it]

 95%|█████████▍| 4700/4959 [2:12:15<08:14,  1.91s/it]

 95%|█████████▍| 4701/4959 [2:12:17<07:56,  1.85s/it]

 95%|█████████▍| 4702/4959 [2:12:19<08:23,  1.96s/it]

 95%|█████████▍| 4703/4959 [2:12:21<08:27,  1.98s/it]

 95%|█████████▍| 4704/4959 [2:12:23<08:02,  1.89s/it]

 95%|█████████▍| 4705/4959 [2:12:25<08:12,  1.94s/it]

 95%|█████████▍| 4706/4959 [2:12:26<07:52,  1.87s/it]

 95%|█████████▍| 4707/4959 [2:12:28<07:34,  1.80s/it]

 95%|█████████▍| 4708/4959 [2:12:30<07:22,  1.76s/it]

 95%|█████████▍| 4709/4959 [2:12:31<07:14,  1.74s/it]

 95%|█████████▍| 4710/4959 [2:12:33<07:36,  1.83s/it]

 95%|█████████▍| 4711/4959 [2:12:35<07:48,  1.89s/it]

 95%|█████████▌| 4712/4959 [2:12:37<07:30,  1.82s/it]

 95%|█████████▌| 4713/4959 [2:12:39<07:16,  1.77s/it]

 95%|█████████▌| 4714/4959 [2:12:40<07:07,  1.74s/it]

 95%|█████████▌| 4715/4959 [2:12:42<06:59,  1.72s/it]

 95%|█████████▌| 4716/4959 [2:12:44<07:22,  1.82s/it]

 95%|█████████▌| 4717/4959 [2:12:46<07:34,  1.88s/it]

 95%|█████████▌| 4718/4959 [2:12:48<07:18,  1.82s/it]

 95%|█████████▌| 4719/4959 [2:12:50<07:05,  1.77s/it]

 95%|█████████▌| 4720/4959 [2:12:52<07:21,  1.85s/it]

 95%|█████████▌| 4721/4959 [2:12:53<07:07,  1.80s/it]

 95%|█████████▌| 4722/4959 [2:12:55<06:57,  1.76s/it]

 95%|█████████▌| 4723/4959 [2:12:57<06:50,  1.74s/it]

 95%|█████████▌| 4724/4959 [2:12:58<06:44,  1.72s/it]

 95%|█████████▌| 4725/4959 [2:13:00<07:05,  1.82s/it]

 95%|█████████▌| 4726/4959 [2:13:02<06:53,  1.77s/it]

 95%|█████████▌| 4727/4959 [2:13:04<07:08,  1.85s/it]

 95%|█████████▌| 4728/4959 [2:13:06<06:53,  1.79s/it]

 95%|█████████▌| 4729/4959 [2:13:07<06:42,  1.75s/it]

 95%|█████████▌| 4730/4959 [2:13:09<06:35,  1.73s/it]

 95%|█████████▌| 4731/4959 [2:13:11<06:29,  1.71s/it]

 95%|█████████▌| 4732/4959 [2:13:12<06:25,  1.70s/it]

 95%|█████████▌| 4733/4959 [2:13:14<06:24,  1.70s/it]

 95%|█████████▌| 4734/4959 [2:13:16<06:20,  1.69s/it]

 95%|█████████▌| 4735/4959 [2:13:17<06:17,  1.68s/it]

 96%|█████████▌| 4736/4959 [2:13:19<06:13,  1.68s/it]

 96%|█████████▌| 4737/4959 [2:13:21<06:11,  1.67s/it]

 96%|█████████▌| 4738/4959 [2:13:22<06:09,  1.67s/it]

 96%|█████████▌| 4739/4959 [2:13:24<06:31,  1.78s/it]

 96%|█████████▌| 4740/4959 [2:13:26<06:44,  1.85s/it]

 96%|█████████▌| 4741/4959 [2:13:28<06:30,  1.79s/it]

 96%|█████████▌| 4742/4959 [2:13:30<06:20,  1.76s/it]

 96%|█████████▌| 4743/4959 [2:13:32<06:36,  1.84s/it]

 96%|█████████▌| 4744/4959 [2:13:34<06:47,  1.89s/it]

 96%|█████████▌| 4745/4959 [2:13:35<06:30,  1.83s/it]

 96%|█████████▌| 4746/4959 [2:13:37<06:17,  1.77s/it]

 96%|█████████▌| 4747/4959 [2:13:39<06:29,  1.84s/it]

 96%|█████████▌| 4748/4959 [2:13:41<06:37,  1.88s/it]

 96%|█████████▌| 4749/4959 [2:13:43<06:42,  1.92s/it]

 96%|█████████▌| 4750/4959 [2:13:45<06:27,  1.85s/it]

 96%|█████████▌| 4751/4959 [2:13:47<06:33,  1.89s/it]

 96%|█████████▌| 4752/4959 [2:13:48<06:15,  1.82s/it]

 96%|█████████▌| 4753/4959 [2:13:50<06:24,  1.87s/it]

 96%|█████████▌| 4754/4959 [2:13:52<06:08,  1.80s/it]

 96%|█████████▌| 4755/4959 [2:13:54<06:18,  1.85s/it]

 96%|█████████▌| 4756/4959 [2:13:56<06:02,  1.79s/it]

 96%|█████████▌| 4757/4959 [2:13:57<05:52,  1.75s/it]

 96%|█████████▌| 4758/4959 [2:13:59<06:06,  1.82s/it]

 96%|█████████▌| 4759/4959 [2:14:01<05:56,  1.78s/it]

 96%|█████████▌| 4760/4959 [2:14:03<05:46,  1.74s/it]

 96%|█████████▌| 4761/4959 [2:14:04<05:38,  1.71s/it]

 96%|█████████▌| 4762/4959 [2:14:06<05:33,  1.69s/it]

 96%|█████████▌| 4763/4959 [2:14:08<05:49,  1.78s/it]

 96%|█████████▌| 4764/4959 [2:14:10<06:10,  1.90s/it]

 96%|█████████▌| 4765/4959 [2:14:12<06:14,  1.93s/it]

 96%|█████████▌| 4766/4959 [2:14:14<06:16,  1.95s/it]

 96%|█████████▌| 4767/4959 [2:14:16<05:56,  1.86s/it]

 96%|█████████▌| 4768/4959 [2:14:17<05:42,  1.79s/it]

 96%|█████████▌| 4769/4959 [2:14:19<05:33,  1.75s/it]

 96%|█████████▌| 4770/4959 [2:14:21<05:25,  1.72s/it]

 96%|█████████▌| 4771/4959 [2:14:22<05:20,  1.70s/it]

 96%|█████████▌| 4772/4959 [2:14:24<05:34,  1.79s/it]

 96%|█████████▌| 4773/4959 [2:14:26<05:24,  1.74s/it]

 96%|█████████▋| 4774/4959 [2:14:28<05:35,  1.81s/it]

 96%|█████████▋| 4775/4959 [2:14:30<05:24,  1.76s/it]

 96%|█████████▋| 4776/4959 [2:14:32<05:35,  1.83s/it]

 96%|█████████▋| 4777/4959 [2:14:34<05:45,  1.90s/it]

 96%|█████████▋| 4778/4959 [2:14:35<05:29,  1.82s/it]

 96%|█████████▋| 4779/4959 [2:14:37<05:17,  1.77s/it]

 96%|█████████▋| 4780/4959 [2:14:39<05:08,  1.73s/it]

 96%|█████████▋| 4781/4959 [2:14:40<05:02,  1.70s/it]

 96%|█████████▋| 4782/4959 [2:14:42<04:58,  1.69s/it]

 96%|█████████▋| 4783/4959 [2:14:43<04:54,  1.67s/it]

 96%|█████████▋| 4784/4959 [2:14:45<04:50,  1.66s/it]

 96%|█████████▋| 4785/4959 [2:14:47<05:06,  1.76s/it]

 97%|█████████▋| 4786/4959 [2:14:49<05:16,  1.83s/it]

 97%|█████████▋| 4787/4959 [2:14:51<05:04,  1.77s/it]

 97%|█████████▋| 4788/4959 [2:14:52<04:55,  1.73s/it]

 97%|█████████▋| 4789/4959 [2:14:54<05:07,  1.81s/it]

 97%|█████████▋| 4790/4959 [2:14:56<05:15,  1.86s/it]

 97%|█████████▋| 4791/4959 [2:14:58<05:19,  1.90s/it]

 97%|█████████▋| 4792/4959 [2:15:00<05:04,  1.82s/it]

 97%|█████████▋| 4793/4959 [2:15:02<05:10,  1.87s/it]

 97%|█████████▋| 4794/4959 [2:15:04<04:57,  1.80s/it]

 97%|█████████▋| 4795/4959 [2:15:06<05:03,  1.85s/it]

 97%|█████████▋| 4796/4959 [2:15:08<05:08,  1.89s/it]

 97%|█████████▋| 4797/4959 [2:15:09<04:55,  1.82s/it]

 97%|█████████▋| 4798/4959 [2:15:11<05:01,  1.87s/it]

 97%|█████████▋| 4799/4959 [2:15:13<04:48,  1.80s/it]

 97%|█████████▋| 4800/4959 [2:15:14<04:38,  1.75s/it]

 97%|█████████▋| 4801/4959 [2:15:16<04:48,  1.82s/it]

 97%|█████████▋| 4802/4959 [2:15:18<04:53,  1.87s/it]

 97%|█████████▋| 4803/4959 [2:15:20<04:40,  1.80s/it]

 97%|█████████▋| 4804/4959 [2:15:22<04:31,  1.75s/it]

 97%|█████████▋| 4805/4959 [2:15:24<04:39,  1.82s/it]

 97%|█████████▋| 4806/4959 [2:15:26<04:46,  1.87s/it]

 97%|█████████▋| 4807/4959 [2:15:27<04:33,  1.80s/it]

 97%|█████████▋| 4808/4959 [2:15:29<04:24,  1.75s/it]

 97%|█████████▋| 4809/4959 [2:15:31<04:17,  1.71s/it]

 97%|█████████▋| 4810/4959 [2:15:32<04:12,  1.69s/it]

 97%|█████████▋| 4811/4959 [2:15:34<04:25,  1.79s/it]

 97%|█████████▋| 4812/4959 [2:15:36<04:16,  1.74s/it]

 97%|█████████▋| 4813/4959 [2:15:38<04:25,  1.82s/it]

 97%|█████████▋| 4814/4959 [2:15:40<04:31,  1.87s/it]

 97%|█████████▋| 4815/4959 [2:15:41<04:19,  1.80s/it]

 97%|█████████▋| 4816/4959 [2:15:43<04:25,  1.86s/it]

 97%|█████████▋| 4817/4959 [2:15:45<04:14,  1.79s/it]

 97%|█████████▋| 4818/4959 [2:15:47<04:21,  1.85s/it]

 97%|█████████▋| 4819/4959 [2:15:49<04:28,  1.92s/it]

 97%|█████████▋| 4820/4959 [2:15:51<04:14,  1.83s/it]

 97%|█████████▋| 4821/4959 [2:15:52<04:05,  1.78s/it]

 97%|█████████▋| 4822/4959 [2:15:54<03:57,  1.74s/it]

 97%|█████████▋| 4823/4959 [2:15:56<04:09,  1.84s/it]

 97%|█████████▋| 4824/4959 [2:15:58<04:00,  1.78s/it]

 97%|█████████▋| 4825/4959 [2:16:00<04:10,  1.87s/it]

 97%|█████████▋| 4826/4959 [2:16:02<04:13,  1.91s/it]

 97%|█████████▋| 4827/4959 [2:16:04<04:15,  1.94s/it]

 97%|█████████▋| 4828/4959 [2:16:06<04:16,  1.96s/it]

 97%|█████████▋| 4829/4959 [2:16:08<04:15,  1.97s/it]

 97%|█████████▋| 4830/4959 [2:16:10<04:14,  1.98s/it]

 97%|█████████▋| 4831/4959 [2:16:12<04:14,  1.99s/it]

 97%|█████████▋| 4832/4959 [2:16:14<04:12,  1.99s/it]

 97%|█████████▋| 4833/4959 [2:16:16<04:10,  1.98s/it]

 97%|█████████▋| 4834/4959 [2:16:18<04:08,  1.99s/it]

 97%|█████████▋| 4835/4959 [2:16:20<04:07,  1.99s/it]

 98%|█████████▊| 4836/4959 [2:16:22<04:06,  2.00s/it]

 98%|█████████▊| 4837/4959 [2:16:24<04:03,  1.99s/it]

 98%|█████████▊| 4838/4959 [2:16:26<04:01,  2.00s/it]

 98%|█████████▊| 4839/4959 [2:16:28<04:14,  2.12s/it]

 98%|█████████▊| 4840/4959 [2:16:30<04:07,  2.08s/it]

 98%|█████████▊| 4841/4959 [2:16:32<04:02,  2.06s/it]

 98%|█████████▊| 4842/4959 [2:16:34<03:58,  2.04s/it]

 98%|█████████▊| 4843/4959 [2:16:36<03:55,  2.03s/it]

 98%|█████████▊| 4844/4959 [2:16:38<03:52,  2.02s/it]

 98%|█████████▊| 4845/4959 [2:16:40<03:49,  2.02s/it]

 98%|█████████▊| 4846/4959 [2:16:42<03:54,  2.08s/it]

 98%|█████████▊| 4847/4959 [2:16:45<03:56,  2.11s/it]

 98%|█████████▊| 4848/4959 [2:16:47<03:58,  2.15s/it]

 98%|█████████▊| 4849/4959 [2:16:49<03:51,  2.11s/it]

 98%|█████████▊| 4850/4959 [2:16:51<03:46,  2.07s/it]

 98%|█████████▊| 4851/4959 [2:16:53<03:41,  2.05s/it]

 98%|█████████▊| 4852/4959 [2:16:55<03:38,  2.04s/it]

 98%|█████████▊| 4853/4959 [2:16:57<03:34,  2.02s/it]

 98%|█████████▊| 4854/4959 [2:16:59<03:32,  2.02s/it]

 98%|█████████▊| 4855/4959 [2:17:01<03:35,  2.07s/it]

 98%|█████████▊| 4856/4959 [2:17:03<03:31,  2.05s/it]

 98%|█████████▊| 4857/4959 [2:17:05<03:27,  2.04s/it]

 98%|█████████▊| 4858/4959 [2:17:07<03:24,  2.03s/it]

 98%|█████████▊| 4859/4959 [2:17:09<03:11,  1.92s/it]

 98%|█████████▊| 4860/4959 [2:17:11<03:12,  1.94s/it]

 98%|█████████▊| 4861/4959 [2:17:13<03:12,  1.97s/it]

 98%|█████████▊| 4862/4959 [2:17:15<03:12,  1.98s/it]

 98%|█████████▊| 4863/4959 [2:17:17<03:12,  2.00s/it]

 98%|█████████▊| 4864/4959 [2:17:19<03:16,  2.07s/it]

 98%|█████████▊| 4865/4959 [2:17:21<03:12,  2.05s/it]

 98%|█████████▊| 4866/4959 [2:17:23<03:08,  2.03s/it]

 98%|█████████▊| 4867/4959 [2:17:25<03:11,  2.08s/it]

 98%|█████████▊| 4868/4959 [2:17:28<03:12,  2.12s/it]

 98%|█████████▊| 4869/4959 [2:17:30<03:07,  2.08s/it]

 98%|█████████▊| 4870/4959 [2:17:32<03:08,  2.12s/it]

 98%|█████████▊| 4871/4959 [2:17:34<03:08,  2.15s/it]

 98%|█████████▊| 4872/4959 [2:17:36<03:03,  2.11s/it]

 98%|█████████▊| 4873/4959 [2:17:38<02:59,  2.08s/it]

 98%|█████████▊| 4874/4959 [2:17:40<02:55,  2.06s/it]

 98%|█████████▊| 4875/4959 [2:17:42<02:51,  2.05s/it]

 98%|█████████▊| 4876/4959 [2:17:44<02:48,  2.03s/it]

 98%|█████████▊| 4877/4959 [2:17:46<02:50,  2.08s/it]

 98%|█████████▊| 4878/4959 [2:17:48<02:51,  2.11s/it]

 98%|█████████▊| 4879/4959 [2:17:51<02:56,  2.20s/it]

 98%|█████████▊| 4880/4959 [2:17:53<02:49,  2.15s/it]

 98%|█████████▊| 4881/4959 [2:17:55<02:48,  2.16s/it]

 98%|█████████▊| 4882/4959 [2:17:57<02:42,  2.11s/it]

 98%|█████████▊| 4883/4959 [2:17:59<02:38,  2.08s/it]

 98%|█████████▊| 4884/4959 [2:18:01<02:34,  2.06s/it]

 99%|█████████▊| 4885/4959 [2:18:03<02:32,  2.06s/it]

 99%|█████████▊| 4886/4959 [2:18:05<02:28,  2.04s/it]

 99%|█████████▊| 4887/4959 [2:18:07<02:29,  2.08s/it]

 99%|█████████▊| 4888/4959 [2:18:09<02:25,  2.05s/it]

 99%|█████████▊| 4889/4959 [2:18:11<02:22,  2.04s/it]

 99%|█████████▊| 4890/4959 [2:18:13<02:23,  2.09s/it]

 99%|█████████▊| 4891/4959 [2:18:16<02:23,  2.12s/it]

 99%|█████████▊| 4892/4959 [2:18:18<02:23,  2.14s/it]

 99%|█████████▊| 4893/4959 [2:18:20<02:22,  2.15s/it]

 99%|█████████▊| 4894/4959 [2:18:22<02:20,  2.16s/it]

 99%|█████████▊| 4895/4959 [2:18:24<02:15,  2.11s/it]

 99%|█████████▊| 4896/4959 [2:18:26<02:11,  2.08s/it]

 99%|█████████▊| 4897/4959 [2:18:28<02:10,  2.11s/it]

 99%|█████████▉| 4898/4959 [2:18:30<02:07,  2.09s/it]

 99%|█████████▉| 4899/4959 [2:18:33<02:07,  2.12s/it]

 99%|█████████▉| 4900/4959 [2:18:35<02:02,  2.08s/it]

 99%|█████████▉| 4901/4959 [2:18:37<02:02,  2.11s/it]

 99%|█████████▉| 4902/4959 [2:18:39<01:58,  2.09s/it]

 99%|█████████▉| 4903/4959 [2:18:41<01:55,  2.06s/it]

 99%|█████████▉| 4904/4959 [2:18:43<01:56,  2.11s/it]

 99%|█████████▉| 4905/4959 [2:18:45<01:52,  2.08s/it]

 99%|█████████▉| 4906/4959 [2:18:47<01:48,  2.05s/it]

 99%|█████████▉| 4907/4959 [2:18:49<01:48,  2.09s/it]

 99%|█████████▉| 4908/4959 [2:18:52<01:50,  2.16s/it]

 99%|█████████▉| 4909/4959 [2:18:54<01:45,  2.11s/it]

 99%|█████████▉| 4910/4959 [2:18:56<01:44,  2.13s/it]

 99%|█████████▉| 4911/4959 [2:18:58<01:40,  2.09s/it]

 99%|█████████▉| 4912/4959 [2:19:00<01:39,  2.12s/it]

 99%|█████████▉| 4913/4959 [2:19:02<01:36,  2.10s/it]

 99%|█████████▉| 4914/4959 [2:19:04<01:33,  2.07s/it]

 99%|█████████▉| 4915/4959 [2:19:06<01:30,  2.06s/it]

 99%|█████████▉| 4916/4959 [2:19:08<01:27,  2.05s/it]

 99%|█████████▉| 4917/4959 [2:19:10<01:27,  2.08s/it]

 99%|█████████▉| 4918/4959 [2:19:12<01:25,  2.09s/it]

 99%|█████████▉| 4919/4959 [2:19:14<01:23,  2.08s/it]

 99%|█████████▉| 4920/4959 [2:19:16<01:20,  2.05s/it]

 99%|█████████▉| 4921/4959 [2:19:18<01:17,  2.04s/it]

 99%|█████████▉| 4922/4959 [2:19:21<01:17,  2.09s/it]

 99%|█████████▉| 4923/4959 [2:19:23<01:14,  2.06s/it]

 99%|█████████▉| 4924/4959 [2:19:25<01:11,  2.05s/it]

 99%|█████████▉| 4925/4959 [2:19:27<01:09,  2.04s/it]

 99%|█████████▉| 4926/4959 [2:19:29<01:06,  2.03s/it]

 99%|█████████▉| 4927/4959 [2:19:31<01:06,  2.08s/it]

 99%|█████████▉| 4928/4959 [2:19:33<01:03,  2.06s/it]

 99%|█████████▉| 4929/4959 [2:19:35<01:01,  2.04s/it]

 99%|█████████▉| 4930/4959 [2:19:37<00:58,  2.03s/it]

 99%|█████████▉| 4931/4959 [2:19:39<00:56,  2.02s/it]

 99%|█████████▉| 4932/4959 [2:19:41<00:56,  2.08s/it]

 99%|█████████▉| 4933/4959 [2:19:43<00:53,  2.06s/it]

 99%|█████████▉| 4934/4959 [2:19:45<00:51,  2.04s/it]

100%|█████████▉| 4935/4959 [2:19:47<00:48,  2.03s/it]

100%|█████████▉| 4936/4959 [2:19:49<00:47,  2.08s/it]

100%|█████████▉| 4937/4959 [2:19:51<00:46,  2.11s/it]

100%|█████████▉| 4938/4959 [2:19:53<00:43,  2.08s/it]

100%|█████████▉| 4939/4959 [2:19:56<00:42,  2.12s/it]

100%|█████████▉| 4940/4959 [2:19:58<00:40,  2.15s/it]

100%|█████████▉| 4941/4959 [2:20:00<00:38,  2.16s/it]

100%|█████████▉| 4942/4959 [2:20:02<00:35,  2.12s/it]

100%|█████████▉| 4943/4959 [2:20:04<00:34,  2.14s/it]

100%|█████████▉| 4944/4959 [2:20:06<00:31,  2.10s/it]

100%|█████████▉| 4945/4959 [2:20:08<00:29,  2.07s/it]

100%|█████████▉| 4946/4959 [2:20:10<00:27,  2.11s/it]

100%|█████████▉| 4947/4959 [2:20:13<00:25,  2.13s/it]

100%|█████████▉| 4948/4959 [2:20:15<00:23,  2.15s/it]

100%|█████████▉| 4949/4959 [2:20:17<00:21,  2.16s/it]

100%|█████████▉| 4950/4959 [2:20:19<00:19,  2.20s/it]

100%|█████████▉| 4951/4959 [2:20:22<00:17,  2.20s/it]

100%|█████████▉| 4952/4959 [2:20:24<00:15,  2.20s/it]

100%|█████████▉| 4953/4959 [2:20:26<00:12,  2.14s/it]

100%|█████████▉| 4954/4959 [2:20:28<00:10,  2.15s/it]

100%|█████████▉| 4955/4959 [2:20:30<00:08,  2.16s/it]

100%|█████████▉| 4956/4959 [2:20:32<00:06,  2.18s/it]

100%|█████████▉| 4957/4959 [2:20:34<00:04,  2.18s/it]

100%|█████████▉| 4958/4959 [2:20:37<00:02,  2.18s/it]

100%|██████████| 4959/4959 [2:20:39<00:00,  2.19s/it]

100%|██████████| 4959/4959 [2:20:39<00:00,  1.70s/it]

,question_id,gold,prediction,raw_output,correct,level,medical_specialty,model,stop_reason,refusal_category,refusal_type
0,1,C,C,C<eos>,1,Y2,Anatomy,google/gemma-4-12B-it+LoRA:lora_results/models...,local_lora_generate,NaN,NaN
1,2,C,C,C<eos>,1,Y1,Anatomy,google/gemma-4-12B-it+LoRA:lora_results/models...,local_lora_generate,NaN,NaN
2,3,B,A,A<eos>,0,Y2,Histology,google/gemma-4-12B-it+LoRA:lora_results/models...,local_lora_generate,NaN,NaN
3,4,B,B,B<eos>,1,Y1,Anatomy,google/gemma-4-12B-it+LoRA:lora_results/models...,local_lora_generate,NaN,NaN
4,5,C,C,C<eos>,1,Y1,Anatomy,google/gemma-4-12B-it+LoRA:lora_results/models...,local_lora_generate,NaN,NaN

In [5]:
# Quick summary: accuracy and invalid prediction rate.
VALID = set("ABCDEF")

summary = pd.DataFrame([{
    "model": results_lora["model"].iloc[0] if len(results_lora) else "Gemma 4 12B + LoRA",
    "n": len(results_lora),
    "accuracy": results_lora["correct"].mean(),
    "invalid_rate": (~results_lora["prediction"].astype(str).str.upper().isin(VALID)).mean(),
}])

summary

,model,n,accuracy,invalid_rate
0,google/gemma-4-12B-it+LoRA:lora_results/models...,4959,0.582577,0.0